### ISSUE TITLE
Sporadic NoSuchFileError in processFinishedJob

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/toil#1153]
_From @hannes-ucsc on September 13, 2016 6:13_

```
Traceback (most recent call last):
  File "/home/mesosbox/venv/bin/toil-rnaseq", line 11, in <module>
    sys.exit(main())
  File "/home/mesosbox/venv/local/lib/python2.7/site-packages/toil_scripts/rnaseq_cgl/rnaseq_cgl_pipeline.py", line 505, in main
    Job.Runner.startToil(Job.wrapJobFn(map_job, download_sample, samples, config), args)
  File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 571, in startToil
    return toil.start(job)
  File "/usr/local/lib/python2.7/dist-packages/toil/common.py", line 580, in start
    return self._runMainLoop(job)
  File "/usr/local/lib/python2.7/dist-packages/toil/common.py", line 794, in _runMainLoop
    jobCache=self._jobCache)
  File "/usr/local/lib/python2.7/dist-packages/toil/leader.py", line 692, in mainLoop
    innerLoop(jobStore, config, batchSystem, toilState, jobBatcher, serviceManager, statsAndLogging)
  File "/usr/local/lib/python2.7/dist-packages/toil/leader.py", line 935, in innerLoop
    jobBatcher.processFinishedJob(jobBatchSystemID, result, wallTime=wallTime)
  File "/usr/local/lib/python2.7/dist-packages/toil/leader.py", line 294, in processFinishedJob
    with jobWrapper.getLogFileHandle( self.jobStore ) as logFileStream:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/toil/jobStores/aws/jobStore.py", line 546, in readFileStream
    info = self.FileInfo.loadOrFail(jobStoreFileID)
  File "/usr/local/lib/python2.7/dist-packages/toil/jobStores/aws/jobStore.py", line 864, in loadOrFail
    raise NoSuchFileException(jobStoreFileID, customName=customName)
toil.jobStores.abstractJobStore.NoSuchFileException: File 'c2c91768-430b-4c96-b7ed-054753defe07' does not exist
```

_Copied from original issue: BD2KGenomics/toil-lib#24_

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-101)
┆Issue Number: TOIL-101

**Comment by DailyDreaming** [comment]
Stale.  Please reopen if still an issue.

**Comment by adamnovak** [comment]
As reported in https://github.com/DataBiosphere/toil/issues/3758#issuecomment-906310128 this issue still (or again?) exists, although it's been re-reported with the job description file itself, rather than the log file, being missing.

The underlying problem seems to be that a cluster's scheduler and its network filesystem are racing, and we go to look for the file before the filesystem is willing to show us that it is present, since we heard from the scheduler that it should be.

**Comment by adamnovak** [comment]
Maybe this is really a different bug now with a similar manifestation.
