### ISSUE TITLE
AWS jobStore imposes limit on number of child jobs

### ISSUE THREAD

**Issue by adderan** [DataBiosphere/toil#1424]
Adding too many children (in the tens of thousands range) to one job with the AWS jobStore seems to cause this assertion to fail: https://github.com/BD2KGenomics/toil/blob/bbe8ead0ea7dd74dec3decf60cf5cab3a108a1cf/src/toil/jobStores/aws/utils.py#L114

" assert len(binary) <= cls.maxBinarySize()"

The failure occurs without a log unless caching is disabled. With caching disabled I get this:

```
085be44e-b1b2-4dee-9e1a-2c7d62edc940    DEBUG:toil.jobStores.aws.jobStore:Updating job 085be44e-b1b2-4dee-9e1a-2c7d62edc940
085be44e-b1b2-4dee-9e1a-2c7d62edc940    Traceback (most recent call last):
085be44e-b1b2-4dee-9e1a-2c7d62edc940      File "/usr/local/lib/python2.7/dist-packages/toil/worker.py", line 337, in main
085be44e-b1b2-4dee-9e1a-2c7d62edc940        job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore)
085be44e-b1b2-4dee-9e1a-2c7d62edc940      File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
085be44e-b1b2-4dee-9e1a-2c7d62edc940        self.gen.next()
085be44e-b1b2-4dee-9e1a-2c7d62edc940      File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 1240, in _executor
085be44e-b1b2-4dee-9e1a-2c7d62edc940        fileStore._updateJobWhenDone()
085be44e-b1b2-4dee-9e1a-2c7d62edc940      File "/usr/local/lib/python2.7/dist-packages/toil/fileStore.py", line 1674, in _updateJobWhenDone
085be44e-b1b2-4dee-9e1a-2c7d62edc940        self.jobStore.update(self.jobGraph)
085be44e-b1b2-4dee-9e1a-2c7d62edc940      File "/usr/local/lib/python2.7/dist-packages/toil/jobStores/aws/jobStore.py", line 354, in update
085be44e-b1b2-4dee-9e1a-2c7d62edc940        assert self.jobsDomain.put_attributes(*job.toItem())
085be44e-b1b2-4dee-9e1a-2c7d62edc940      File "/usr/local/lib/python2.7/dist-packages/toil/jobStores/aws/jobStore.py", line 1355, in toItem
085be44e-b1b2-4dee-9e1a-2c7d62edc940        return self.jobStoreID, self.binaryToAttributes(cPickle.dumps(self))
085be44e-b1b2-4dee-9e1a-2c7d62edc940      File "/usr/local/lib/python2.7/dist-packages/toil/jobStores/aws/utils.py", line 111, in binaryToAttributes
085be44e-b1b2-4dee-9e1a-2c7d62edc940        assert len(binary) <= cls.maxBinarySize()
085be44e-b1b2-4dee-9e1a-2c7d62edc940    AssertionError
085be44e-b1b2-4dee-9e1a-2c7d62edc940    ERROR:toil.worker:Exiting the worker because of a failed job on host ip-172-31-18-236
085be44e-b1b2-4dee-9e1a-2c7d62edc940    DEBUG:toil.jobStores.aws.jobStore:Loaded job 085be44e-b1b2-4dee-9e1a-2c7d62edc940
085be44e-b1b2-4dee-9e1a-2c7d62edc940    WARNING:toil.jobGraph:Due to failure we are reducing the remaining retry count of job 'MakeOffDiagonalBlasts' 085be44e-b1b2-4dee-9e1a-2c7d62edc940 with ID 085be44e-b1b2-4dee-9e1a-2c7d62edc940 to 0
Added job: 'MakeOffDiagonalBlasts' 085be44e-b1b2-4dee-9e1a-2c7d62edc940 to active jobs
Built the jobs list, currently have 1 jobs to update and 0 jobs issued
```

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-128)
┆Issue Number: TOIL-128

**Comment by adderan** [comment]
Actually nevermind, I guess it isn't the number of child jobs causing this. I tried splitting the children across multiple parents in series, and the failure just occurs later.

**Comment by cket** [comment]
@adderan I think you mentioned you had a fix for this? Can you PR your changes back against Toil when you get the chance?

**Comment by cket** [comment]
@adderan any update on this? I would love to get this fix in

**Comment by DailyDreaming** [comment]
Stale. Closing, please reopen if still an issue.
