### ISSUE TITLE
Hot-deploying a user script in root directory causes AssertionError

### ISSUE THREAD

**Issue by joelarmstrong** [DataBiosphere/toil#1455]
Moving the script to a directory like "/scripts" works fine.

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/attempt_to_trigger_mesos_bug.py", line 35, in <module>
    main()
  File "/attempt_to_trigger_mesos_bug.py", line 31, in main
    job = Job.wrapJobFn(spawn_small_jobs, opts.num_jobs)
  File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 482, in wrapJobFn
    return JobFunctionWrappingJob(fn, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 1345, in __init__
    self.userFunctionModule = ModuleDescriptor.forModule(userFunction.__module__).globalize()
  File "/usr/local/lib/python2.7/dist-packages/toil/resource.py", line 393, in forModule
    assert os.path.isdir(dirPath)
AssertionError
```

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-133)
┆Issue Number: TOIL-133

**Comment by DailyDreaming** [comment]
Fixed I think by a better error message: bab3b46928d6e331ce184acc5149c1a6c11dff9a
