### ISSUE TITLE
The --cleanWorkDir never setting does not preserve downloaded files in localTempDir

### ISSUE THREAD

**Issue by adamnovak** [DataBiosphere/toil#1575]
I am running Toil 3.6.

I have a workflow where I download some files like this:

```
# Download the VCF under a .gz name
vcf_filename = os.path.join(job.fileStore.getLocalTempDir(),
    "vcf{}.vcf.gz".format(i))
job.fileStore.readGlobalFile(vcf_id, vcf_filename)
```

I ran it like this, with `--cleanWorkDir never`:

```
TMPDIR=/hive/users/anovak/tmp time build-hgvm ./tree3 test_build --base_vg_url file:`pwd`/sourceGraphs/human22.chopped.vg --vcf_contig "chr22" --vcfs_url file:`pwd`/../forward_vcfs --vcfs_url file:/cluster/home/charles/SV_HGVM_research/eighth_draft_GRCh38_bks_only_polALengths_chrs --add_chr --sample_fastq_url file:`pwd`/../mole_bams/syndip-chr22-fastq.R1.fastq --sample_fastq_url file:`pwd`/../mole_bams/syndip-chr22-fastq.R2.fastq --eval_sequences_url file:`pwd`/to_realign.seqs --logInfo --realTimeLogging --cleanWorkDir never | tee log.txt
```

It ran a `vg` process on some downloaded files, and I killed the vg process manually. Toil printed the expected error:

```
Exception: Command vg add /hive/users/anovak/tmp/toil-6d7e84cc-85b5-47d7-87ce-19868adaed02/tmpx75map/f49289a4-59f4-48fe-a59d-133023d14dc6/tmpgMmPNq.tmp -v /hive/users/anovak/tmp/toil-6d7e84cc-85b5-47d7-87ce-19868adaed02/tmpx75map/f49289a4-59f4-48fe-a59d-133023d14dc6/tsj7nSM/vcf0.vcf.gz -v /hive/users/anovak/tmp/toil-6d7e84cc-85b5-47d7-87ce-19868adaed02/tmpx75map/f49289a4-59f4-48fe-a59d-133023d14dc6/tjGyCje/vcf1.vcf.gz -n 20=chr20 -n 21=chr21 -n 22=chr22 -n 1=chr1 -n 3=chr3 -n 2=chr2 -n 5=chr5 -n 4=chr4 -n 7=chr7 -n 6=chr6 -n 9=chr9 -n 8=chr8 -n X=chrX -n 11=chr11 -n 10=chr10 -n 13=chr13 -n 12=chr12 -n 15=chr15 -n 14=chr14 -n 17=chr17 -n 16=chr16 -n 19=chr19 -n 18=chr18 returned with non-zero exit status -9
```

But, the files that my program was working on were not there:

```
ls /hive/users/anovak/tmp/toil-6d7e84cc-85b5-47d7-87ce-19868adaed02/tmpx75map/f49289a4-59f4-48fe-a59d-133023d14dc6/tsj7nSM/vcf0.vcf.gz
    
ls: cannot access /hive/users/anovak/tmp/toil-6d7e84cc-85b5-47d7-87ce-19868adaed02/tmpx75map/f49289a4-59f4-48fe-a59d-133023d14dc6/tsj7nSM/vcf0.vcf.gz: No such file or directory
```

This is what is there:

```
ls /hive/users/anovak/tmp/toil-6d7e84cc-85b5-47d7-87ce-19868adaed02

tmp2KHsNd  tmp2ZIIdJ  tmp5Vrbvg  tmpGUi_vU  tmpMFMKME  tmpTlsfr0  tmp_fYVo7  tmpqPdbEu  tmpsWKtUl  tmpvOGl9m  tmpx75map

ls /hive/users/anovak/tmp/toil-6d7e84cc-85b5-47d7-87ce-19868adaed02/tmpx75map

f49289a4-59f4-48fe-a59d-133023d14dc6  worker_log.txt

# Note that f49289a4-59f4-48fe-a59d-133023d14dc6 is chmod 777 for some reason.

ls /hive/users/anovak/tmp/toil-6d7e84cc-85b5-47d7-87ce-19868adaed02/tmpx75map/f49289a4-59f4-48fe-a59d-133023d14dc6

tjGyCje  tsj7nSM

ls /hive/users/anovak/tmp/toil-6d7e84cc-85b5-47d7-87ce-19868adaed02/tmpx75map/f49289a4-59f4-48fe-a59d-133023d14dc6/tsj7nSM

# Nothing is there
```

That `worker_log.txt` looks like this:
```
---TOIL WORKER OUTPUT LOG---
INFO:toil:Running Toil version 3.6.0-f930a841e79d1032a44670b85c319411ca539ede.
WARNING:toil.resource:Can't find resource for leader path '/hive/users/anovak/ga4gh/hgvm/hgvm-builder/src/hgvmbuilder'
WARNING:toil.resource:Can't localize module ModuleDescriptor(dirPath='/hive/users/anovak/ga4gh/hgvm/hgvm-builder/src', name='hgvmbuilder.build', fromVirtualEnv=False)
INFO:toil.fileStore:Starting job ('add_variants_job' x/2/jobcCjF7f) with ID (21b5b2c18ba9f4e029039f2ad6fa29a02db1f46d).
WARNING:toil.resource:Can't find resource for leader path '/hive/users/anovak/ga4gh/hgvm/hgvm-builder/src/hgvmbuilder'
WARNING:toil.resource:Can't localize module ModuleDescriptor(dirPath='/hive/users/anovak/ga4gh/hgvm/hgvm-builder/src', name='hgvmbuilder.build', fromVirtualEnv=False)
INFO:toil-rt:Downloaded VCF c/9/tmpi7MZ6o.tmp as /hive/users/anovak/tmp/toil-6d7e84cc-85b5-47d7-87ce-19868adaed02/tmpx75map/f49289a4-59f4-48fe-a59d-133023d14dc6/tsj7nSM/vcf0.vcf.gz
INFO:toil-rt:Downloaded VCF K/s/tmpMaPHy8.tmp as /hive/users/anovak/tmp/toil-6d7e84cc-85b5-47d7-87ce-19868adaed02/tmpx75map/f49289a4-59f4-48fe-a59d-133023d14dc6/tjGyCje/vcf1.vcf.gz
INFO:commandrunner:Run: vg validate /hive/users/anovak/tmp/toil-6d7e84cc-85b5-47d7-87ce-19868adaed02/tmpx75map/f49289a4-59f4-48fe-a59d-133023d14dc6/tmpgMmPNq.tmp
INFO:toil-rt:Adding 2 VCFs to vg graph...
INFO:commandrunner:Run: vg add /hive/users/anovak/tmp/toil-6d7e84cc-85b5-47d7-87ce-19868adaed02/tmpx75map/f49289a4-59f4-48fe-a59d-133023d14dc6/tmpgMmPNq.tmp -v /hive/users/anovak/tmp/toil-6d7e84cc-85b5-47d7-87ce-19868adaed02/tmpx75map/f49289a4-59f4-48fe-a59d-133023d14dc6/tsj7nSM/vcf0.vcf.gz -v /hive/users/anovak/tmp/toil-6d7e84cc-85b5-47d7-87ce-19868adaed02/tmpx75map/f49289a4-59f4-48fe-a59d-133023d14dc6/tjGyCje/vcf1.vcf.gz -n 20=chr20 -n 21=chr21 -n 22=chr22 -n 1=chr1 -n 3=chr3 -n 2=chr2 -n 5=chr5 -n 4=chr4 -n 7=chr7 -n 6=chr6 -n 9=chr9 -n 8=chr8 -n X=chrX -n 11=chr11 -n 10=chr10 -n 13=chr13 -n 12=chr12 -n 15=chr15 -n 14=chr14 -n 17=chr17 -n 16=chr16 -n 19=chr19 -n 18=chr18
Traceback (most recent call last):
  File "/cluster/home/anovak/python/lib/python2.7/site-packages/toil/worker.py", line 340, in main
    job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore)
  File "/cluster/home/anovak/python/lib/python2.7/site-packages/toil/job.py", line 1271, in _runner
    returnValues = self._run(jobGraph, fileStore)
  File "/cluster/home/anovak/python/lib/python2.7/site-packages/toil/job.py", line 1218, in _run
    return self.run(fileStore)
  File "/cluster/home/anovak/python/lib/python2.7/site-packages/toil/job.py", line 1384, in run
    rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
  File "/hive/users/anovak/ga4gh/hgvm/hgvm-builder/src/hgvmbuilder/build.py", line 577, in add_variants_job
    raise e
Exception: Command vg add /hive/users/anovak/tmp/toil-6d7e84cc-85b5-47d7-87ce-19868adaed02/tmpx75map/f49289a4-59f4-48fe-a59d-133023d14dc6/tmpgMmPNq.tmp -v /hive/users/anovak/tmp/toil-6d7e84cc-85b5-47d7-87ce-19868adaed02/tmpx75map/f49289a4-59f4-48fe-a59d-133023d14dc6/tsj7nSM/vcf0.vcf.gz -v /hive/users/anovak/tmp/toil-6d7e84cc-85b5-47d7-87ce-19868adaed02/tmpx75map/f49289a4-59f4-48fe-a59d-133023d14dc6/tjGyCje/vcf1.vcf.gz -n 20=chr20 -n 21=chr21 -n 22=chr22 -n 1=chr1 -n 3=chr3 -n 2=chr2 -n 5=chr5 -n 4=chr4 -n 7=chr7 -n 6=chr6 -n 9=chr9 -n 8=chr8 -n X=chrX -n 11=chr11 -n 10=chr10 -n 13=chr13 -n 12=chr12 -n 15=chr15 -n 14=chr14 -n 17=chr17 -n 16=chr16 -n 19=chr19 -n 18=chr18 returned with non-zero exit status -9
ERROR:toil.worker:Exiting the worker because of a failed job on host kolossus
WARNING:toil.jobGraph:Due to failure we are reducing the remaining retry count of job 'add_variants_job' x/2/jobcCjF7f with ID x/2/jobcCjF7f to 0
```
It looks like those files aren't supposed to be getting deleted, but they are getting deleted. Please fix it so they stay put, so that when the commands my Toil jobs run crash, I can debug them.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-144)
┆Issue Number: TOIL-144

**Comment by cket** [comment]
Caused by ``findAndHandleDeadJobs`` in both Caching and NonCaching file stores

**Comment by DailyDreaming** [comment]
Stale, please reopen if still an issue.
