### ISSUE TITLE
Toil won't create directories when exporting to a file URL

### ISSUE THREAD

**Issue by adamnovak** [DataBiosphere/toil#1577]
I'm trying to export a bunch of files that constitute a directory structure, but Toil can only export to `file` URLs if they refer to files in directories that already exist.

Trying to export under a directory that doesn't exist produces something like this:

```
Traceback (most recent call last):
  File "/cluster/home/anovak/python/bin/build-hgvm", line 11, in <module>
    load_entry_point('hgvm-builder', 'console_scripts', 'build-hgvm')()
  File "/hive/users/anovak/ga4gh/hgvm/hgvm-builder/src/hgvmbuilder/build.py", line 1126, in entrypoint
    sys.exit(main(sys.argv))
  File "/hive/users/anovak/ga4gh/hgvm/hgvm-builder/src/hgvmbuilder/build.py", line 1115, in main
    "file:{}/eval".format(options.out_dir))
  File "/hive/users/anovak/ga4gh/hgvm/hgvm-builder/src/hgvmbuilder/directory.py", line 115, in export
    file_name))
  File "/cluster/home/anovak/python/lib/python2.7/site-packages/toil/common.py", line 904, in exportFile
    self._jobStore.exportFile(jobStoreFileID, dstUrl)
  File "/cluster/home/anovak/python/lib/python2.7/site-packages/toil/jobStores/abstractJobStore.py", line 328, in exportFile
    return self._exportFile(otherCls, jobStoreFileID, dstUrl)
  File "/cluster/home/anovak/python/lib/python2.7/site-packages/toil/jobStores/fileJobStore.py", line 183, in _exportFile
    shutil.copyfile(self._getAbsPath(jobStoreFileID), self._extractPathFromUrl(url))
  File "/cluster/home/anovak/python/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: 'test_build/eval/experimental/sample.vg'
```

Toil ought to create the intermediate directories if they don't already exist.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-145)
┆Issue Number: TOIL-145

**Comment by GiriB** [comment]
Python doesn't create intermediate directories while writing to a file, if those directories do not exist already.  I'm not sure why it is this way (only thing I can think of is chance of creating unwanted directories).  However, it [does provide](https://docs.python.org/2/library/os.html#os.makedirs) `os.makedirs ` that allows recursive creation of directories. The mode for the created directories by default is `0777` (read, write and execute access to all the users) which might not be desirable.

**Comment by adamnovak** [comment]
The problem is that if you want to take an export URL from the user, you want to just feed it straight to Toil, not parse it, decide if it's a file URL, and manually make the required directories before passing it to Toil.

**Comment by DailyDreaming** [comment]
Stale, please reopen if still an issue.
