### ISSUE TITLE
Apparent cache race affecting readGlobalFile

### ISSUE THREAD

**Issue by joelarmstrong** [DataBiosphere/toil#1582]
Haven't had a chance to look into this one yet. This is the first time I've seen this after hundreds of thousands of jobs, so it must be very rare. Here's the worker log for the failed job:

```
e1f6a2b6-0632-4f49-aed4-923804828627    DEBUG:toil.job:Getting defaultdict from module collections.
e1f6a2b6-0632-4f49-aed4-923804828627    DEBUG:toil.job:Getting list from module __builtin__.
e1f6a2b6-0632-4f49-aed4-923804828627    DEBUG:toil.job:Getting CactusWorkflowArguments from module cactus.pipeline.cactus_workflow.
e1f6a2b6-0632-4f49-aed4-923804828627    DEBUG:toil.job:Getting FileID from module toil.fileStore.
e1f6a2b6-0632-4f49-aed4-923804828627    DEBUG:toil.job:Getting set from module __builtin__.
e1f6a2b6-0632-4f49-aed4-923804828627    DEBUG:toil.job:Getting ExperimentWrapper from module cactus.shared.experimentWrapper.
e1f6a2b6-0632-4f49-aed4-923804828627    DEBUG:toil.job:Getting ConfigWrapper from module cactus.shared.configWrapper.
e1f6a2b6-0632-4f49-aed4-923804828627    DEBUG:toil.job:Getting ModuleDescriptor from module toil.resource.
e1f6a2b6-0632-4f49-aed4-923804828627    DEBUG:toil.job:Getting Config from module toil.common.
e1f6a2b6-0632-4f49-aed4-923804828627    INFO:toil.fileStore:Starting job ('CactusReferenceWrapper' e1f6a2b6-0632-4f49-aed4-923804828627) with ID (6239f7200fb65c6e573a5c57a53e132d2377962f).
e1f6a2b6-0632-4f49-aed4-923804828627    DEBUG:toil.fileStore:CACHE: Obtained lock on file /var/lib/mesos/slaves/a6c0ccb3-7aff-4c92-84dc-a709b1a68f59-S1/frameworks/a6c0ccb3-7aff-4c92-84dc-a709b1a68f59-0000/executors/toil-537/runs/8c5acafe-787c-4541-a5f4-919c9d591e87/toil-43764132-2f
0d-41c5-9984-a2f78d9eb7e2/cache-43764132-2f0d-41c5-9984-a2f78d9eb7e2/.cacheLock
e1f6a2b6-0632-4f49-aed4-923804828627    DEBUG:toil.fileStore:CACHE: Released lock
e1f6a2b6-0632-4f49-aed4-923804828627    DEBUG:toil.fileStore:CACHE: Obtained lock on file /var/lib/mesos/slaves/a6c0ccb3-7aff-4c92-84dc-a709b1a68f59-S1/frameworks/a6c0ccb3-7aff-4c92-84dc-a709b1a68f59-0000/executors/toil-537/runs/8c5acafe-787c-4541-a5f4-919c9d591e87/toil-43764132-2f
0d-41c5-9984-a2f78d9eb7e2/cache-43764132-2f0d-41c5-9984-a2f78d9eb7e2/.cacheLock
e1f6a2b6-0632-4f49-aed4-923804828627    DEBUG:toil.fileStore:CACHE: Released lock
e1f6a2b6-0632-4f49-aed4-923804828627    DEBUG:toil.fileStore:CACHE: Obtained lock on file /var/lib/mesos/slaves/a6c0ccb3-7aff-4c92-84dc-a709b1a68f59-S1/frameworks/a6c0ccb3-7aff-4c92-84dc-a709b1a68f59-0000/executors/toil-537/runs/8c5acafe-787c-4541-a5f4-919c9d591e87/toil-43764132-2f
0d-41c5-9984-a2f78d9eb7e2/cache-43764132-2f0d-41c5-9984-a2f78d9eb7e2/.cacheLock
e1f6a2b6-0632-4f49-aed4-923804828627    DEBUG:toil.fileStore:CACHE: Released lock
e1f6a2b6-0632-4f49-aed4-923804828627    INFO:toil.lib.bioio:Reading database in RefWrapper: ef0ff614-224b-4abe-803d-95fb7ca241cb
e1f6a2b6-0632-4f49-aed4-923804828627    DEBUG:toil.fileStore:CACHE: Obtained lock on file /var/lib/mesos/slaves/a6c0ccb3-7aff-4c92-84dc-a709b1a68f59-S1/frameworks/a6c0ccb3-7aff-4c92-84dc-a709b1a68f59-0000/executors/toil-537/runs/8c5acafe-787c-4541-a5f4-919c9d591e87/toil-43764132-2f
0d-41c5-9984-a2f78d9eb7e2/cache-43764132-2f0d-41c5-9984-a2f78d9eb7e2/.cacheLock
e1f6a2b6-0632-4f49-aed4-923804828627    DEBUG:toil.fileStore:CACHE: Cache miss on file with ID 'ef0ff614-224b-4abe-803d-95fb7ca241cb'.
e1f6a2b6-0632-4f49-aed4-923804828627    DEBUG:toil.fileStore:LOG-TO-MASTER: CACHE: Creating a harbinger file for (ef0ff614-224b-4abe-803d-95fb7ca241cb). 
e1f6a2b6-0632-4f49-aed4-923804828627    DEBUG:toil.jobStores.aws.jobStore:Reading FileInfo(fileID='ef0ff61...7ca241cb', ownerID='None', encrypted=False, version='.bzLneK0ilNicMOMz2iaPKHL057GrX2h', previousVersion='.bzLneK0ilNicMOMz2iaPKHL057GrX2h', content=None, _numContentChunks=0
) bound to <toil.jobStores.aws.jobStore.AWSJobStore object at 0x7f97aab98a90> into '/var/lib/mesos/slaves/a6c0ccb3-7aff-4c92-84dc-a709b1a68f59-S1/frameworks/a6c0ccb3-7aff-4c92-84dc-a709b1a68f59-0000/executors/toil-537/runs/8c5acafe-787c-4541-a5f4-919c9d591e87/toil-43764132-2f0d-41c
5-9984-a2f78d9eb7e2/cache-43764132-2f0d-41c5-9984-a2f78d9eb7e2/.ZWYwZmY2MTQtMjI0Yi00YWJlLTgwM2QtOTVmYjdjYTI0MWNi'.
e1f6a2b6-0632-4f49-aed4-923804828627    DEBUG:toil.fileStore:CACHE: Obtained lock on file /var/lib/mesos/slaves/a6c0ccb3-7aff-4c92-84dc-a709b1a68f59-S1/frameworks/a6c0ccb3-7aff-4c92-84dc-a709b1a68f59-0000/executors/toil-537/runs/8c5acafe-787c-4541-a5f4-919c9d591e87/toil-43764132-2f
0d-41c5-9984-a2f78d9eb7e2/cache-43764132-2f0d-41c5-9984-a2f78d9eb7e2/.cacheLock
e1f6a2b6-0632-4f49-aed4-923804828627    CRITICAL:toil.fileStore:CACHE: Unable to acquire lock on /var/lib/mesos/slaves/a6c0ccb3-7aff-4c92-84dc-a709b1a68f59-S1/frameworks/a6c0ccb3-7aff-4c92-84dc-a709b1a68f59-0000/executors/toil-537/runs/8c5acafe-787c-4541-a5f4-919c9d591e87/toil-4376
4132-2f0d-41c5-9984-a2f78d9eb7e2/cache-43764132-2f0d-41c5-9984-a2f78d9eb7e2/.cacheLock
e1f6a2b6-0632-4f49-aed4-923804828627    DEBUG:toil.fileStore:CACHE: Released lock
e1f6a2b6-0632-4f49-aed4-923804828627    DEBUG:toil.fileStore:CACHE: Obtained lock on file /var/lib/mesos/slaves/a6c0ccb3-7aff-4c92-84dc-a709b1a68f59-S1/frameworks/a6c0ccb3-7aff-4c92-84dc-a709b1a68f59-0000/executors/toil-537/runs/8c5acafe-787c-4541-a5f4-919c9d591e87/toil-43764132-2f
0d-41c5-9984-a2f78d9eb7e2/cache-43764132-2f0d-41c5-9984-a2f78d9eb7e2/.cacheLock
e1f6a2b6-0632-4f49-aed4-923804828627    DEBUG:toil.fileStore:LOG-TO-MASTER: CACHE: Deleting the harbinger file for (ef0ff614-224b-4abe-803d-95fb7ca241cb)
e1f6a2b6-0632-4f49-aed4-923804828627    DEBUG:toil.fileStore:CACHE: Released lock
e1f6a2b6-0632-4f49-aed4-923804828627    CRITICAL:toil.fileStore:CACHE: Unable to acquire lock on /var/lib/mesos/slaves/a6c0ccb3-7aff-4c92-84dc-a709b1a68f59-S1/frameworks/a6c0ccb3-7aff-4c92-84dc-a709b1a68f59-0000/executors/toil-537/runs/8c5acafe-787c-4541-a5f4-919c9d591e87/toil-4376
4132-2f0d-41c5-9984-a2f78d9eb7e2/cache-43764132-2f0d-41c5-9984-a2f78d9eb7e2/.cacheLock
e1f6a2b6-0632-4f49-aed4-923804828627    DEBUG:toil.fileStore:CACHE: Released lock
e1f6a2b6-0632-4f49-aed4-923804828627    DEBUG:toil.fileStore:LOG-TO-MASTER: Job 'CactusReferenceWrapper' e1f6a2b6-0632-4f49-aed4-923804828627 used 0.00% (0.0 B [0B] used, 14.2 GB [15204352000B] requested) at the end of its run.
e1f6a2b6-0632-4f49-aed4-923804828627    DEBUG:toil.fileStore:CACHE: Obtained lock on file /var/lib/mesos/slaves/a6c0ccb3-7aff-4c92-84dc-a709b1a68f59-S1/frameworks/a6c0ccb3-7aff-4c92-84dc-a709b1a68f59-0000/executors/toil-537/runs/8c5acafe-787c-4541-a5f4-919c9d591e87/toil-43764132-2f
0d-41c5-9984-a2f78d9eb7e2/cache-43764132-2f0d-41c5-9984-a2f78d9eb7e2/.cacheLock
e1f6a2b6-0632-4f49-aed4-923804828627    DEBUG:toil.fileStore:CACHE: Released lock
e1f6a2b6-0632-4f49-aed4-923804828627    DEBUG:toil.fileStore:CACHE: Obtained lock on file /var/lib/mesos/slaves/a6c0ccb3-7aff-4c92-84dc-a709b1a68f59-S1/frameworks/a6c0ccb3-7aff-4c92-84dc-a709b1a68f59-0000/executors/toil-537/runs/8c5acafe-787c-4541-a5f4-919c9d591e87/toil-43764132-2f
0d-41c5-9984-a2f78d9eb7e2/cache-43764132-2f0d-41c5-9984-a2f78d9eb7e2/.cacheLock
e1f6a2b6-0632-4f49-aed4-923804828627    DEBUG:toil.fileStore:CACHE: Released lock
e1f6a2b6-0632-4f49-aed4-923804828627    Traceback (most recent call last):
e1f6a2b6-0632-4f49-aed4-923804828627      File "/usr/local/lib/python2.7/dist-packages/toil/worker.py", line 340, in main
e1f6a2b6-0632-4f49-aed4-923804828627        job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore)
e1f6a2b6-0632-4f49-aed4-923804828627      File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 1288, in _runner
e1f6a2b6-0632-4f49-aed4-923804828627        returnValues = self._run(jobGraph, fileStore)
e1f6a2b6-0632-4f49-aed4-923804828627      File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 1235, in _run
e1f6a2b6-0632-4f49-aed4-923804828627        return self.run(fileStore)
e1f6a2b6-0632-4f49-aed4-923804828627      File "/venv/lib/python2.7/site-packages/cactus/pipeline/cactus_workflow.py", line 989, in run
e1f6a2b6-0632-4f49-aed4-923804828627        permutations=self.getOptionalPhaseAttrib("permutations", int),
e1f6a2b6-0632-4f49-aed4-923804828627      File "/usr/local/lib/python2.7/dist-packages/toil/fileStore.py", line 692, in readGlobalFile
e1f6a2b6-0632-4f49-aed4-923804828627        self.addToCache(localFilePath, fileStoreID, 'read', mutable)
e1f6a2b6-0632-4f49-aed4-923804828627      File "/usr/local/lib/python2.7/dist-packages/toil/fileStore.py", line 999, in addToCache
e1f6a2b6-0632-4f49-aed4-923804828627        shutil.copyfile(cachedFile, localFilePath)
e1f6a2b6-0632-4f49-aed4-923804828627      File "/usr/lib/python2.7/shutil.py", line 82, in copyfile
e1f6a2b6-0632-4f49-aed4-923804828627        with open(src, 'rb') as fsrc:
e1f6a2b6-0632-4f49-aed4-923804828627    IOError: [Errno 2] No such file or directory: '/var/lib/mesos/slaves/a6c0ccb3-7aff-4c92-84dc-a709b1a68f59-S1/frameworks/a6c0ccb3-7aff-4c92-84dc-a709b1a68f59-0000/executors/toil-537/runs/8c5acafe-787c-4541-a5f4-919c9d591e87/toil-43764132-2f0d-41c5-9984-a2f78d9eb7e2/cache-43764132-2f0d-41c5-9984-a2f78d9eb7e2/ZWYwZmY2MTQtMjI0Yi00YWJlLTgwM2QtOTVmYjdjYTI0MWNi'
e1f6a2b6-0632-4f49-aed4-923804828627    ERROR:toil.worker:Exiting the worker because of a failed job on host ip-172-31-41-145.us-west-2.compute.internal
e1f6a2b6-0632-4f49-aed4-923804828627    DEBUG:toil.jobStores.aws.jobStore:Loaded job e1f6a2b6-0632-4f49-aed4-923804828627
e1f6a2b6-0632-4f49-aed4-923804828627    WARNING:toil.jobGraph:Due to failure we are reducing the remaining retry count of job 'CactusReferenceWrapper' e1f6a2b6-0632-4f49-aed4-923804828627 with ID e1f6a2b6-0632-4f49-aed4-923804828627 to 2
e1f6a2b6-0632-4f49-aed4-923804828627    WARNING:toil.jobGraph:We have set the failed job 'CactusReferenceWrapper' e1f6a2b6-0632-4f49-aed4-923804828627 to be non-preemptable
```

I think I can provide the logs of other jobs on the same node that were running at the same time, if it would be helpful.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-147)
┆Issue Number: TOIL-147

**Comment by DailyDreaming** [comment]
`addToCache` no longer exists as a function so this is likely no longer an issue.  If it is, it would likely be very hard to reproduce now that the code has been significantly refactored into a caching and non-caching filestore.  Hopefully this is fixed, but please reopen if it becomes an issue again.
