### ISSUE TITLE
Trying Google jobStore example and getting an error

### ISSUE THREAD

**Issue by slagelwa** [DataBiosphere/toil#1604]
```
Traceback (most recent call last):
  File "toil-sort-example.py", line 173, in <module>
    main()
  File "toil-sort-example.py", line 170, in main
    memory='1000M'), options)
  File "/home/jslagel/.local/lib/python2.7/site-packages/toil/job.py", line 738, in startToil
    with Toil(options) as toil:
  File "/home/jslagel/.local/lib/python2.7/site-packages/toil/common.py", line 605, in __enter__
    jobStore = self.getJobStore(config.jobStore)
  File "/home/jslagel/.local/lib/python2.7/site-packages/toil/common.py", line 742, in getJobStore
    return GoogleJobStore(namePrefix, projectID)
  File "/home/jslagel/.local/lib/python2.7/site-packages/toil/jobStores/googleJobStore.py", line 77, in __init__
    self._checkJobStoreCreation(create, exists, projectID+':'+namePrefix)
AttributeError: 'GoogleJobStore' object has no attribute '_checkJobStoreCreation'
```

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-149)
┆Issue Number: TOIL-149

**Comment by natanlao** [comment]
Relevant commit: 3e258b101a173aa1b7d2664f204223d14a39c3e5

**Comment by DailyDreaming** [comment]
Stale.  Closing, please reopen if still an issue.
