### ISSUE TITLE
Toil command line options can't be placed in a group

### ISSUE THREAD

**Issue by adamnovak** [DataBiosphere/toil#1632]
I want to group the Toil command line options into their own group in my script's options, because they're so numerous. (Ideally, eventually, I'd like to suppress most of them in the ordinary help output, because the help really should fit on one screen in order to not be overwhelming.)

Toil isn't happy being passed an ArgumentGroup instead of the base parser. It looks like it's trying to do un-Pythonic dispatch on the actual type of its argument:

```
Traceback (most recent call last):
  File "/cluster/home/anovak/python/bin/build-hgvm", line 11, in <module>
    load_entry_point('hgvm-builder', 'console_scripts', 'build-hgvm')()
  File "/hive/users/anovak/ga4gh/hgvm/hgvm-builder/src/hgvmbuilder/build.py", line 1618, in entrypoint
    sys.exit(main(sys.argv))
  File "/hive/users/anovak/ga4gh/hgvm/hgvm-builder/src/hgvmbuilder/build.py", line 1539, in main
    options = parse_args(args) # This holds the nicely-parsed options object
  File "/hive/users/anovak/ga4gh/hgvm/hgvm-builder/src/hgvmbuilder/build.py", line 69, in parse_args
    Job.Runner.addToilOptions(parser.add_argument_group("Toil configuration"))
  File "/cluster/home/anovak/python/lib/python2.7/site-packages/toil/job.py", line 723, in addToilOptions
    addOptions(parser)
  File "/cluster/home/anovak/python/lib/python2.7/site-packages/toil/common.py", line 552, in addOptions
    addLoggingOptions(parser) # This adds the logging stuff.
  File "/cluster/home/anovak/python/lib/python2.7/site-packages/toil/lib/bioio.py", line 116, in addLoggingOptions
    "argparse.ArgumentParser" % parser.__class__)
RuntimeError: Unanticipated class passed to addLoggingOptions(), <class 'argparse._ArgumentGroup'>. Expecting argparse.ArgumentParse
```

Toil should be changed to accept any parser that lets it call the methods it needs without throwing something.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-154)
┆Issue Number: TOIL-154

**Comment by DailyDreaming** [comment]
@adamnovak I should have checked when this was added, but is this still relevant?  If so, I think #3426 addresses this.
