### ISSUE TITLE
Spontaneous CacheUnbalancedError

### ISSUE THREAD

**Issue by adamnovak** [DataBiosphere/toil#1650]
I'm getting a CacheUnbalancedError as soon as my jobs start, before they've really used any space at all. I'm running 5 jobs that each want 1TB of disk, and I have 5 nodes each with ~5.7TB of free disk.

```
INFO:toil.leader:Issued job 'main_job' ec319e83_0222_483d_9a78_0e6a6c7ced11 with job batch system ID: 0 and cores: 1, disk: 1.0 G, and memory: 1.0 G
INFO:toil.leader:Job ended successfully: 'main_job' ec319e83_0222_483d_9a78_0e6a6c7ced11
INFO:toil.leader:Issued job 'extract_job' a6ebb053_64ac_4221_bf0d_0746bcb716c0 with job batch system ID: 1 and cores: 1, disk: 1000.0 G, and memory: 16.0 G
INFO:toil.leader:Issued job 'extract_job' 4b9f1b4c_50a2_4d58_9b00_8631c55f6320 with job batch system ID: 2 and cores: 1, disk: 1000.0 G, and memory: 16.0 G
INFO:toil.leader:Issued job 'extract_job' c43ebec8_23c0_4948_9d91_9a7bf7465cc7 with job batch system ID: 3 and cores: 1, disk: 1000.0 G, and memory: 16.0 G
INFO:toil.leader:Issued job 'extract_job' 3f9d0130_3cd7_4f96_af34_7d150d46c2e4 with job batch system ID: 4 and cores: 1, disk: 1000.0 G, and memory: 16.0 G
INFO:toil.leader:Issued job 'extract_job' 3f59876e_107b_4a81_b66b_60e298874ced with job batch system ID: 5 and cores: 1, disk: 1000.0 G, and memory: 16.0 G
INFO:toil.leader:Issued job 'extract_job' b4fc2fac_9b86_4d37_a462_f1aaa142ac3a with job batch system ID: 6 and cores: 1, disk: 1000.0 G, and memory: 16.0 G
INFO:toil.leader:Job ended successfully: 'extract_job' 3f9d0130_3cd7_4f96_af34_7d150d46c2e4
WARNING:toil.leader:The job seems to have left a log file, indicating failure: 'extract_job' 3f9d0130_3cd7_4f96_af34_7d150d46c2e4
---TOIL WORKER OUTPUT LOG---
3f9d0130_3cd7_4f96_af34_7d150d46c2e4    INFO:toil:Running Toil version 3.6.0-f930a841e79d1032a44670b85c319411ca539ede.
3f9d0130_3cd7_4f96_af34_7d150d46c2e4    INFO:toil.fileStore:Starting job ('extract_job' 3f9d0130_3cd7_4f96_af34_7d150d46c2e4) with ID (619270b49bcadd1a92869589edaeb61b855bf74d).
3f9d0130_3cd7_4f96_af34_7d150d46c2e4    Traceback (most recent call last):
3f9d0130_3cd7_4f96_af34_7d150d46c2e4      File "/usr/local/lib/python2.7/dist-packages/toil/worker.py", line 336, in main
3f9d0130_3cd7_4f96_af34_7d150d46c2e4        with fileStore.open(job):
3f9d0130_3cd7_4f96_af34_7d150d46c2e4      File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
3f9d0130_3cd7_4f96_af34_7d150d46c2e4        return self.gen.next()
3f9d0130_3cd7_4f96_af34_7d150d46c2e4      File "/usr/local/lib/python2.7/dist-packages/toil/fileStore.py", line 488, in open
3f9d0130_3cd7_4f96_af34_7d150d46c2e4        self.cleanCache(jobReqs)
3f9d0130_3cd7_4f96_af34_7d150d46c2e4      File "/usr/local/lib/python2.7/dist-packages/toil/fileStore.py", line 1160, in cleanCache
3f9d0130_3cd7_4f96_af34_7d150d46c2e4        raise CacheUnbalancedError()
3f9d0130_3cd7_4f96_af34_7d150d46c2e4    CacheUnbalancedError: Unable unable to free enough space for caching.  This error frequently arises due to jobs using more disk than they have requested.  Turn on debug logging to see more information leading up to this error through cache usage logs.
3f9d0130_3cd7_4f96_af34_7d150d46c2e4    ERROR:toil.worker:Exiting the worker because of a failed job on host hgvm1agent2
3f9d0130_3cd7_4f96_af34_7d150d46c2e4    WARNING:toil.jobGraph:Due to failure we are reducing the remaining retry count of job 'extract_job' 3f9d0130_3cd7_4f96_af34_7d150d46c2e4 with ID 3f9d0130_3cd7_4f96_af34_7d150d46c2e4 to 0
```

```
anovak@hgvm1agent1:~$ df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            221G   12K  221G   1% /dev
tmpfs            45G  428K   45G   1% /run
/dev/sda1        29G  2.6G   26G  10% /
none            4.0K     0  4.0K   0% /sys/fs/cgroup
none            5.0M     0  5.0M   0% /run/lock
none            221G     0  221G   0% /run/shm
none            100M     0  100M   0% /run/user
none             64K     0   64K   0% /etc/network/interfaces.dynamic.d
/dev/sdb1       6.0T   56M  5.7T   1% /mnt
```

This is using the Azure template, so Mesos should be putting the sandboxes in /mnt/mesos, where there is plenty of space.

What is the caching system doing to produce this issue before I have written any files?

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-157)
┆Issue Number: TOIL-157

**Comment by arkal** [comment]
Are you sure it is going to /mnt? Did you specify a --workDir? Can you check the debug logs?

**Comment by adamnovak** [comment]
I didn't manually specify a `--workDir`, but I did configure Mesos to use that directory for tasks in the template.

Sticking a `getLocalTempDir()` into one of my jobs produces a path under /mnt/:

```
INFO:toil-rt:Temp directory location: /mnt/slaves/20170421-225813-83886090-5050-36546-S4/frameworks/20170421-225813-83886090-5050-36546-0014/executors/toil-58641/runs/54301654-492b-4eec-aa87-33852f458c99/toil-9d38d881-03fd-42c6-9c55-4a53894023ce/tmpiiUBDU/21617b28-d234-438c-a4e1-c1b17169b869/tkvz1uA
```

I've attached a debug log from a case where the issue occurs.

[debug.log.txt](https://github.com/BD2KGenomics/toil/files/952680/debug.log.txt)

**Comment by arkal** [comment]
what is the response from this
`curl -i -u "toil":"loit" http://<mesos0-master-ip>:5050/master/slaves`

**Comment by adamnovak** [comment]
It looks like this:

```
anovak@hgvm1master1:~/hgvm-builder$ curl -i -u "toil":"loit" http://10.0.0.5:5050/master/slaves
HTTP/1.1 200 OK
Content-Length: 2507
Date: Mon, 24 Apr 2017 19:43:50 GMT
Content-Type: application/json

{"slaves":[{"active":true,"attributes":{"preemptable":"False"},"hostname":"hgvm1agent5","id":"20170421-225813-83886090-5050-36546-S4","offered_resources":{"cpus":0,"disk":0,"mem":0},"pid":"slave(1)@10.0.0.54:5051","registered_time":1492815498.11274,"reserved_resources":{},"resources":{"cpus":32,"disk":6236637,"mem":450468,"ports":"[1-21, 23-5050, 5052-32000]"},"unreserved_resources":{"cpus":32,"disk":6236637,"mem":450468,"ports":"[1-21, 23-5050, 5052-32000]"},"used_resources":{"cpus":0,"disk":0,"mem":0}},{"active":true,"attributes":{"preemptable":"False"},"hostname":"hgvm1agent4","id":"20170421-225813-83886090-5050-36546-S3","offered_resources":{"cpus":0,"disk":0,"mem":0},"pid":"slave(1)@10.0.0.53:5051","registered_time":1492815497.75731,"reserved_resources":{},"resources":{"cpus":32,"disk":6236637,"mem":450468,"ports":"[1-21, 23-5050, 5052-32000]"},"unreserved_resources":{"cpus":32,"disk":6236637,"mem":450468,"ports":"[1-21, 23-5050, 5052-32000]"},"used_resources":{"cpus":0,"disk":0,"mem":0}},{"active":true,"attributes":{"preemptable":"False"},"hostname":"hgvm1agent1","id":"20170421-225813-83886090-5050-36546-S2","offered_resources":{"cpus":0,"disk":0,"mem":0},"pid":"slave(1)@10.0.0.50:5051","registered_time":1492815497.69624,"reserved_resources":{},"resources":{"cpus":32,"disk":6236637,"mem":450468,"ports":"[1-21, 23-5050, 5052-32000]"},"unreserved_resources":{"cpus":32,"disk":6236637,"mem":450468,"ports":"[1-21, 23-5050, 5052-32000]"},"used_resources":{"cpus":0,"disk":0,"mem":0}},{"active":true,"attributes":{"preemptable":"False"},"hostname":"hgvm1agent2","id":"20170421-225813-83886090-5050-36546-S1","offered_resources":{"cpus":0,"disk":0,"mem":0},"pid":"slave(1)@10.0.0.51:5051","registered_time":1492815497.61819,"reserved_resources":{},"resources":{"cpus":32,"disk":6236637,"mem":450468,"ports":"[1-21, 23-5050, 5052-32000]"},"unreserved_resources":{"cpus":32,"disk":6236637,"mem":450468,"ports":"[1-21, 23-5050, 5052-32000]"},"used_resources":{"cpus":0,"disk":0,"mem":0}},{"active":true,"attributes":{"preemptable":"False"},"hostname":"hgvm1agent3","id":"20170421-225813-83886090-5050-36546-S0","offered_resources":{"cpus":0,"disk":0,"mem":0},"pid":"slave(1)@10.0.0.52:5051","registered_time":1492815497.52733,"reserved_resources":{},"resources":{"cpus":32,"disk":6236637,"mem":450468,"ports":"[1-21, 23-5050, 5052-32000]"},"unreserved_resources":{"cpus":32,"disk":6236637,"mem":450468,"ports":"[1-21, 23-5050, 5052-32000]"},"used_resources":{"cpus":0,"disk":0,"mem":0}}]}
```

**Comment by arkal** [comment]
Do you have more than 5 jobs? and you're expecting only 5 to run at one time?

**Comment by adamnovak** [comment]
I have been trying to run 6 jobs, each with a 1 TB disk requirement. I have 5 nodes, each with ~6 TB disk.

**Comment by arkal** [comment]
OK so your jobs are asking for 1000Gb, not 1024Gb. it looks like the disk has only 6210186772480 bytes free (= 5.64TB). Mesos thinks you have 6236637Mb free (=5.9TB) since your jobs are asking for 1000GB, 6* 1000Gb => 6,386,316,288 (Mesos thinks you have) > 6,291,456,000 bytes you are asking for > 6210186772480 you actually have free.

**Comment by adamnovak** [comment]
So why is Mesos wrong about how much disk is free?

Here's what I get if I ask for info down to the byte:

```
anovak@hgvm1agent1:/mnt$ df --block-size=1
Filesystem         1B-blocks        Used     Available Use% Mounted on
udev            236707127296       12288  236707115008   1% /dev
tmpfs            47342424064      610304   47341813760   1% /run
/dev/sda1        30927785984 13020581888   16610787328  44% /
none                    4096           0          4096   0% /sys/fs/cgroup
none                 5242880           0       5242880   0% /run/lock
none            236712116224      380928  236711735296   1% /run/shm
none               104857600           0     104857600   0% /run/user
none                   65536           0         65536   0% /etc/network/interfaces.dynamic.d
/dev/sdb1      6544957526016    57995264 6215029321728   1% /mnt
```

Note that used and available don't add up to the total size of the disk, because 5% of every filesystem by default is reserved for root's use (and so 5% of space is not used but also isn't "available").

`tune2fs` on /dev/sdb1 shows 80530623/1610612475 blocks, or 5%, reserved for UID 0.

I think what's going on here is that Mesos is handing out allocations up to the actual unused space on the disk, ignoring the reservation of 5% for root. The Mesos agents run as root, so they see all the free space. Toil then starts up under a normal user, and complains that the disk is oversubscribed by about 5%.

Somehow this disagreement on the meaning of the disk resource needs to be resolved. Mesos thinks it's disk available when sudo'd to root, and when running stuff through Docker we probably would be able to use it all, but Toil thinks it's just disk accessible to the current user directly.

I can change the Azure template to not reserve any of the dedicated Mesos disk for root, but in some Mesos configurations the sandboxes will be on the main OS disk, which does need to have space reserved for root.

Toil needs to have some kind of chat with Mesos (perhaps at https://issues.apache.org/jira/browse/MESOS-7420 where I have complained about this). Either Mesos has to account for disk reservation for root, or Toil has to account for disk reservation for root, or the code/docs we use to spin up clusters has to account for disk reservation for root.

**Comment by DailyDreaming** [comment]
Stale.  Please reopen if still an issue.  Caching was reworked so I'm assuming this issue no longer exists in (at least not in this current form).
