### ISSUE TITLE
CWL+Toil+Restarts produces "Got workflow error"

### ISSUE THREAD

**Issue by evan-wehi** [DataBiosphere/toil#1872]
I have large workflow, 10x human genomes, ~15 steps about a week of runtime. I've had to restart it because our cluster failed and initially the restart seemed to work well, it ran for several more days. It then failed with the following:

Got workflow error
Traceback (most recent call last):
  File "/stornext/HPCScratch/PapenfussLab/projects/ovary-work/toil-env/lib/python2.7/site-packages/cwltool/main.py", line 281, in single_job_executor
    r.run(**kwargs)
  File "/stornext/HPCScratch/PapenfussLab/projects/ovary-work/toil-env/lib/python2.7/site-packages/cwltool/job.py", line 307, in run
    stageFiles(self.generatemapper, ignoreWritable=self.inplace_update, symLink=True)
  File "/stornext/HPCScratch/PapenfussLab/projects/ovary-work/toil-env/lib/python2.7/site-packages/cwltool/process.py", line 227, in stageFiles
    os.symlink(p.resolved, p.target)
OSError: [Errno 17] File exists
ERROR:cwltool:Got workflow error
Traceback (most recent call last):
  File "/stornext/HPCScratch/PapenfussLab/projects/ovary-work/toil-env/lib/python2.7/site-packages/cwltool/main.py", line 281, in single_job_executor
    r.run(**kwargs)
  File "/stornext/HPCScratch/PapenfussLab/projects/ovary-work/toil-env/lib/python2.7/site-packages/cwltool/job.py", line 307, in run
    stageFiles(self.generatemapper, ignoreWritable=self.inplace_update, symLink=True)
  File "/stornext/HPCScratch/PapenfussLab/projects/ovary-work/toil-env/lib/python2.7/site-packages/cwltool/process.py", line 227, in stageFiles
    os.symlink(p.resolved, p.target)
OSError: [Errno 17] File exists
DEBUG:toil.fileStore:LOG-TO-MASTER: Job 'file:///stornext/HPCScratch/PapenfussLab/projects/ovary-work/pdx-genome/tools/src/tools/samtools-index.cwl' samtools index s/k/jobRYYJes used 4002.83% (80.1 GB [85960163328B] used, 2.0 GB [2147483648B] requested) at the end of its run.
WARNING:toil.fileStore:LOG-TO-MASTER: Job used more disk than requested. Please reconsider modifying the user script to avoid the chance  of failure due to incorrectly requested resources. Job 'file:///stornext/HPCScratch/PapenfussLab/projects/ovary-work/pdx-genome/tools/src/tools/samtools-index.cwl' samtools index s/k/jobRYYJes used 4002.83% (80.1 GB [85960163328B] used, 2.0 GB [2147483648B] requested) at the end of its run.
DEBUG:toil.fileStore:CACHE: Obtained lock on file /home/thomas.e/tmp/toil-8f27be6d-d41a-4567-bf63-6b298c5302fe-e0b198a6-1d82-4bc3-9fd8-97741b77688b/cache-8f27be6d-d41a-4567-bf63-6b298c5302fe/.cacheLock
DEBUG:toil.fileStore:LOG-TO-MASTER: Successfully deleted local copies of file with ID 'g/C/tmpRxqHOu.tmp'.
DEBUG:toil.fileStore:CACHE: Released lock
DEBUG:toil.fileStore:CACHE: Obtained lock on file /home/thomas.e/tmp/toil-8f27be6d-d41a-4567-bf63-6b298c5302fe-e0b198a6-1d82-4bc3-9fd8-97741b77688b/cache-8f27be6d-d41a-4567-bf63-6b298c5302fe/.cacheLock
DEBUG:toil.fileStore:CACHE: Released lock
DEBUG:toil.fileStore:CACHE: Obtained lock on file /home/thomas.e/tmp/toil-8f27be6d-d41a-4567-bf63-6b298c5302fe-e0b198a6-1d82-4bc3-9fd8-97741b77688b/cache-8f27be6d-d41a-4567-bf63-6b298c5302fe/.cacheLock
DEBUG:toil.fileStore:CACHE: Released lock
Traceback (most recent call last):
  File "/stornext/HPCScratch/PapenfussLab/projects/ovary-work/toil-env/lib/python2.7/site-packages/toil/worker.py", line 340, in main
    job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore)
  File "/stornext/HPCScratch/PapenfussLab/projects/ovary-work/toil-env/lib/python2.7/site-packages/toil/job.py", line 1289, in _runner
    returnValues = self._run(jobGraph, fileStore)
  File "/stornext/HPCScratch/PapenfussLab/projects/ovary-work/toil-env/lib/python2.7/site-packages/toil/job.py", line 1234, in _run
    return self.run(fileStore)
  File "/stornext/HPCScratch/PapenfussLab/projects/ovary-work/toil-env/lib/python2.7/site-packages/toil/cwl/cwltoil.py", line 306, in run
    **opts)
  File "/stornext/HPCScratch/PapenfussLab/projects/ovary-work/toil-env/lib/python2.7/site-packages/cwltool/main.py", line 289, in single_job_executor
    raise WorkflowException(Text(e))
WorkflowException: [Errno 17] File exists
ERROR:toil.worker:Exiting the worker because of a failed job on host trqn-n51538.hpc.wehi.edu.au
WARNING:toil.jobGraph:Due to failure we are reducing the remaining retry count of job 'file:///stornext/HPCScratch/PapenfussLab/projects/ovary-work/pdx-genome/tools/src/tools/samtools-index.cwl' samtools index s/k/jobRYYJes with ID s/k/jobRYYJes to 0
<=========
If I restart it just produces the same error. Not sure what other information I should provide.

Here is some version info:

(toil-env) [thomas.e@torquelord ovary]$ cwltoil --version
3.9.1
(toil-env) [thomas.e@torquelord ovary]$ cwltool --version
/stornext/HPCScratch/PapenfussLab/projects/ovary-work/toil-env/bin/cwltool 1.0.20170822192924

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-201)
┆Issue Number: TOIL-201

**Comment by evan-wehi** [comment]
This is a crosspost: https://github.com/common-workflow-language/cwltool/issues/541

**Comment by tetron** [comment]
Hi @evan-wehi 

I'm a little confused.  You are reporting cwltoil 3.9.1 (which was released July 19) but cwltool from August 22?  Are you using a version from git?

I suggest trying the current master branch of Toil.

**Comment by evan-wehi** [comment]
Yes, this is a large job which I started a month ago which is why I want to restart the failed workflow if possible. I would have just done `pip install toil cwltool etc` into the virtualenv to get stable releases. Also the job store is very large so it is not practical to copy it. I'm not really in a position to experiment unless there is a compelling reason to.

**Comment by evan-wehi** [comment]
I made copy of the jobstore, which took 5 days (I won't be doing that again). I've restarted the workflow with the current master branch. It also fails:
```
Traceback (most recent call last):
  File "/stornext/HPCScratch/PapenfussLab/projects/ovary-work/toil-env-3.11/lib/python2.7/site-packages/toil/worker.py", line 315, in main
    job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore)
  File "/stornext/HPCScratch/PapenfussLab/projects/ovary-work/toil-env-3.11/lib/python2.7/site-packages/toil/job.py", line 1299, in _runner
    returnValues = self._run(jobGraph, fileStore)
  File "/stornext/HPCScratch/PapenfussLab/projects/ovary-work/toil-env-3.11/lib/python2.7/site-packages/toil/job.py", line 1244, in _run
    return self.run(fileStore)
  File "/stornext/HPCScratch/PapenfussLab/projects/ovary-work/toil-env-3.11/lib/python2.7/site-packages/toil/cwl/cwltoil.py", line 428, in run
    fillInDefaults(self.step_inputs, cwljob)
AttributeError: 'CWLJob' object has no attribute 'step_inputs'
ERROR:toil.worker:Exiting the worker because of a failed job on host trqn-n51538.hpc.wehi.edu.au
WARNING:toil.jobGraph:Due to failure we are reducing the remaining retry count of job 'file:///stornext/HPCScratch/PapenfussLab/projects/ovary-work/pdx-genome/tools/src/tools/samtools-index.cwl' samtools index s/k/jobRYYJes with ID s/k/jobRYYJes to 0
```

**Comment by DailyDreaming** [comment]
Stale, and my guess is, difficult to reproduce.  Please reopen if this is still an issue.  If reopened, we would need the CWL script and some parsed down input files with which to run it at the least otherwise I don't know how we'd reproduce this to debug.
