### ISSUE TITLE
Sort Example Options Not Working As Expected.

### ISSUE THREAD

**Issue by bencvdb** [DataBiosphere/toil#1928]
This is just a place for me to log my documentation suggestions as I go through the toil tutorials.

Edited by @DailyDreaming .  Most of the issues here have been addressed, except for the last one about the `sort.py` function.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/TOIL-40)
┆Issue Number: TOIL-40

**Comment by bencvdb** [comment]
**Suggestions for Quickstart Example - helloWorld.py:**
1. It took me a couple read throughs of the paragraphs explaining job stores and batch systems to understand it.
2. some thoughts regarding --help option
    a. under "toil core options":
	"...turn on stats collation about the performance of jobs." do you mean collection?
    b. under "toil options for restarting an existing workflow"
	does restart mean pick up from where it left off or from the beginning?

**Comment by bencvdb** [comment]
***Suggestions for Quickstart Example - Running a basic CWL tutorial***
1. I could not complete the tutorial based off the tasks given.
    
commands: 
    $ pip install toil[cwl]
    $ ls
             example-job.yaml	example.cwl
    $ toil-cwl-runner example.cwl example-job.yaml
    eduroam-169-233-201-205.ucsc.edu 2017-10-26 11:24:05,707 MainThread INFO toil.lib.bioio: Root logger is at level 'INFO', 'toil' logger at level 'INFO'.
eduroam-169-233-201-205.ucsc.edu 2017-10-26 11:24:05,713 MainThread INFO toil.jobStores.abstractJobStore: The workflow ID is: '319fe247-391f-4e23-9ef9-369d899e3e07'
Resolved 'example.cwl' to 'file:///Users/ben/Desktop/Toil/Toil-CWL%20tutorial/example.cwl'
eduroam-169-233-201-205.ucsc.edu 2017-10-26 11:24:05,715 MainThread INFO cwltool: Resolved 'example.cwl' to 'file:///Users/ben/Desktop/Toil/Toil-CWL%20tutorial/example.cwl'
Traceback (most recent call last):
  File "/Users/ben/venv/bin/toil-cwl-runner", line 11, in <module>
    sys.exit(main())
  File "/Users/ben/venv/lib/python2.7/site-packages/toil/cwl/cwltoil.py", line 873, in main
    strict=useStrict)
  File "/Users/ben/venv/lib/python2.7/site-packages/cwltool/load_tool.py", line 285, in load_tool
    strict=strict, fetcher_constructor=fetcher_constructor)
  File "/Users/ben/venv/lib/python2.7/site-packages/cwltool/load_tool.py", line 151, in validate_document
    raise ValueError("workflowjobj must be a dict, got '%s': %s" % (type(workflowobj), workflowobj))
ValueError: workflowjobj must be a dict, got '<type 'str'>': example.cwl
(venv) eduroam-169-233-201-205:Toil-CWL tutorial ben$ ls
example-job.yaml	example.cwl

No file was in the directory as the tutorial described.
**SOLVED:** Needed to copy and paste example.cwl again. Perhaps an issue with newline differences between Windows and others.

**Comment by bencvdb** [comment]
**Suggestions for "Real World" Example**
1. Regarding running it with options:
     Some of the options (ie: --lineLength = 10) did not seem to have an effect. There were more than 
     10 characters per line in sortedFile.txt.
2. Tutorial claims that "The first two options determine the number of lines and how many characters are in each line." Does this mean that we can change the number of lines to be read with this option? Is it just letting toil know beforehand what to expect? Clarify what the options being referred to do.
