### ISSUE TITLE
First case of eventual consistency with versioned bucket

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/toil#200]
Determine if the trace below is a symptom of eventual consistency. If so come up with a plan to handle it.

http://jenkins.cgcloud.info/job/toil/111/console

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/mnt/ephemeral/workspace/toil/src/toil/jobStores/awsJobStore.py", line 516, in writer
    key.get_contents_to_file( writable, version_id=version )
  File "/mnt/ephemeral/workspace/toil/venv/local/lib/python2.7/site-packages/boto/s3/key.py", line 1650, in get_contents_to_file
    response_headers=response_headers)
  File "/mnt/ephemeral/workspace/toil/venv/local/lib/python2.7/site-packages/boto/s3/key.py", line 1482, in get_file
    query_args=None)
  File "/mnt/ephemeral/workspace/toil/venv/local/lib/python2.7/site-packages/boto/s3/key.py", line 1514, in _get_file_internal
    override_num_retries=override_num_retries)
  File "/mnt/ephemeral/workspace/toil/venv/local/lib/python2.7/site-packages/boto/s3/key.py", line 343, in open
    override_num_retries=override_num_retries)
  File "/mnt/ephemeral/workspace/toil/venv/local/lib/python2.7/site-packages/boto/s3/key.py", line 303, in open_read
    self.resp.reason, body)
S3ResponseError: S3ResponseError: 404 Not Found
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchVersion</Code><Message>The specified version does not exist.</Message><Key>a7173eaf-b774-4fc2-87d3-ace6e7b3a7de</Key><VersionId>6KNHtJLQQb9cDoGL4W.MiEXDeQfKq.i2</VersionId><RequestId>2723C04EB4469358</RequestId><HostId>z+oIOiyrJuJkUJNjwJO1p2U7jFhooVkqNXd09l0mzgdmuNRZRDcEOcoM7yR+zEuZBjDyLh+VFUM=</HostId></Error>
```

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-222)
┆Issue Number: TOIL-222

**Comment by cricketsloan** [comment]
➤ Adam Novak commented:

I don’t think S3’s merely-eventual consistency has actually ever been a problem for us since this was reported.
