### ISSUE TITLE
error: can't start new thread

### ISSUE THREAD

**Issue by screx** [DataBiosphere/toil#2023]
Hi my team is trying to get the toil cwl implementation running on our cluster but for some reason when run I get an error when I'm just running it on the tutorial workflow.

```
[codyr@qlogin5 echo]$ toil-cwl-runner --preserve-environment PATH PYTHONPATH --disableCaching --workDir /tmp --jobStore ${PWD}/jobstore echo.cwl message.yml 
qlogin5.hpf.new 2018-01-17 09:29:38,401 MainThread INFO toil.lib.bioio: Root logger is at level 'INFO', 'toil' logger at level 'INFO'.
qlogin5.hpf.new 2018-01-17 09:29:38,402 MainThread INFO toil.lib.bioio: Root logger is at level 'INFO', 'toil' logger at level 'INFO'.
qlogin5.hpf.new 2018-01-17 09:29:38,435 MainThread INFO toil.jobStores.abstractJobStore: The workflow ID is: '93226b07-3424-4473-8de6-79cb66b997ab'
Resolved 'echo.cwl' to 'file:///home/codyr/cwl-tutorial/cl-tools/echo/echo.cwl'
qlogin5.hpf.new 2018-01-17 09:29:38,502 MainThread INFO cwltool: Resolved 'echo.cwl' to 'file:///home/codyr/cwl-tutorial/cl-tools/echo/echo.cwl'
qlogin5.hpf.new 2018-01-17 09:29:41,363 MainThread INFO toil.common: Using the single machine batch system
qlogin5.hpf.new 2018-01-17 09:29:41,363 MainThread WARNING toil.batchSystems.singleMachine: Limiting maxCores to CPU count of system (32).
qlogin5.hpf.new 2018-01-17 09:29:41,363 MainThread WARNING toil.batchSystems.singleMachine: Limiting maxMemory to physically available memory (135365353472).
qlogin5.hpf.new 2018-01-17 09:29:41,377 MainThread INFO toil.common: Created the workflow directory at /tmp/toil-93226b07-3424-4473-8de6-79cb66b997ab-f8e5eb59cd9b009ff8a84fc600000018
qlogin5.hpf.new 2018-01-17 09:29:41,377 MainThread WARNING toil.batchSystems.singleMachine: Limiting maxDisk to physically available disk (854637912064).
Traceback (most recent call last):
  File "/home/codyr/.local/bin/toil-cwl-runner", line 11, in <module>
    sys.exit(main())
  File "/home/codyr/.local/lib/python2.7/site-packages/toil/cwl/cwltoil.py", line 951, in main
    outobj = toil.start(wf1)
  File "/home/codyr/.local/lib/python2.7/site-packages/toil/common.py", line 722, in start
    self._batchSystem = self.createBatchSystem(self.config)
  File "/home/codyr/.local/lib/python2.7/site-packages/toil/common.py", line 872, in createBatchSystem
    return batchSystemClass(**kwargs)
  File "/home/codyr/.local/lib/python2.7/site-packages/toil/batchSystems/singleMachine.py", line 133, in __init__
    worker.start()
  File "/hpf/tools/centos6/python/2.7.13/lib/python2.7/threading.py", line 736, in start
    _start_new_thread(self.__bootstrap, ())
thread.error: can't start new thread
=>> PBS: job killed: vmem 2270076928 exceeded limit 2147483648

```
Also this seems to also be affecting it when I run with no additional parameters to `toil-cwl-runner`
Any help is appreciated, thanks!

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-224)
┆Issue Number: TOIL-224

**Comment by adamnovak** [comment]
Toil is running out of virtual memory, because it has been limited by your scheduler to a virtual memory size of ~2 GB. The single machine batch system will create 10 threads per core, so it requires a lot of virtual memory for all their stacks and so forth, especially on a machine with a lot of cores.

The solution here I think is to raise the virtual memory limit, or else limit the number of cores with `--maxCores`.

I am going to close this, considering how old it is. Please re-open it if your problem is still unsolved.

**Comment by jsmedmar** [comment]
I added a comment on this topic here: https://github.com/DataBiosphere/toil/issues/2308#issuecomment-588353477
