### ISSUE TITLE
Toil tries to zip up the entire directory your script is in, and does not handle the presence of other people's files

### ISSUE THREAD

**Issue by DailyDreaming** [DataBiosphere/toil#2088]
Running toil on aws from '/tmp' can trigger race conditions with hot-deployment and should not be run with autoscaling.  Toil should check to make sure the user is not running autoscaling from '/tmp'.

Error message will look like:

```
Traceback (most recent call last):
  File "toiltest_make_many_small_files.py", line 38, in <module>
    toil.start(job0)
  File "/usr/local/lib/python2.7/dist-packages/toil/common.py", line 715, in start
    self._setupHotDeployment(rootJob.getUserScript())
  File "/usr/local/lib/python2.7/dist-packages/toil/common.py", line 908, in _setupHotDeployment
    userScriptResource = userScript.saveAsResourceTo(self._jobStore)
  File "/usr/local/lib/python2.7/dist-packages/toil/resource.py", line 459, in saveAsResourceTo
    return self._getResourceClass().create(jobStore, self._resourcePath)
  File "/usr/local/lib/python2.7/dist-packages/toil/resource.py", line 88, in create
    with cls._load(leaderPath) as src:
  File "/usr/local/lib/python2.7/dist-packages/toil/resource.py", line 294, in _load
    zipFile.write(fullPath, os.path.relpath(fullPath, rootDir))
  File "/usr/lib/python2.7/zipfile.py", line 1153, in write
    with open(filename, "rb") as fp:
IOError: [Errno 6] No such device or address: '/tmp/ssh-Cy2sW44CRPyF/agent.3172'
```

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-230)
┆Issue Number: TOIL-230

**Comment by DailyDreaming** [comment]
Also, running from `/var` is even worse.

**Comment by DailyDreaming** [comment]
Running in `/var` gives this error:

```
Traceback (most recent call last):
  File "toiltest_make_many_small_files.py", line 38, in <module>
    toil.start(job0)
  File "/usr/local/lib/python2.7/dist-packages/toil/common.py", line 715, in start
    self._setupHotDeployment(rootJob.getUserScript())
  File "/usr/local/lib/python2.7/dist-packages/toil/common.py", line 908, in _setupHotDeployment
    userScriptResource = userScript.saveAsResourceTo(self._jobStore)
  File "/usr/local/lib/python2.7/dist-packages/toil/resource.py", line 459, in saveAsResourceTo
    return self._getResourceClass().create(jobStore, self._resourcePath)
  File "/usr/local/lib/python2.7/dist-packages/toil/resource.py", line 88, in create
    with cls._load(leaderPath) as src:
  File "/usr/local/lib/python2.7/dist-packages/toil/resource.py", line 294, in _load
    zipFile.write(fullPath, os.path.relpath(fullPath, rootDir))
  File "/usr/lib/python2.7/zipfile.py", line 1153, in write
    with open(filename, "rb") as fp:
IOError: [Errno 6] No such device or address: '/var/lib/docker/overlay2/2b2b46c70e0de04a2a88380cba77e84c106ee7f1f0c5fb5f71c2d21bab46a2f9/diff/usr/bin/easy_install'
```

**Comment by diekhans** [comment]
@joelarmstrong figured out that this is because of the script was in /tmp, so toil aggressively tried to 
zip up /tmp, which is a shared directory (even on a single user system).

So it started to zip up a file that then was removed during the zip process.
A related issue is it could be easy to zip up a large directory.

Toils attempt to implicitly find what to send seems fragile and dangerous. It would be much better to be explicit.

**Comment by diekhans** [comment]
The list of where not to run isn't easy to define; it's a bit of
AI problem and yes, we should address this independently of toil
deployment.

I am a bit nervous about catch and ignore.  There are maybe
cases where that would cause an erroneous deployment, such as a
file not being readable.  Instead, I would suggest a try/catch
that outputs a detailed and useful error and aborts


BTW, I would really like to have a nice bike shed

**Comment by jeffrey856** [comment]
Created a PR to fix this issue. PR#2728
