### ISSUE TITLE
Placing Azure storage account key in AZURE_ACCOUNT_KEY environment variable breaks

### ISSUE THREAD

**Issue by bencvdb** [DataBiosphere/toil#2185]
Traceback (most recent call last):
  File "/home/ben/venv/bin/toil", line 11, in <module>
    sys.exit(main())
  File "/home/ben/venv/local/lib/python2.7/site-packages/toil/utils/toilMain.py", line 34, in main
    module.main()
  File "/home/ben/venv/local/lib/python2.7/site-packages/toil/utils/toilSshCluster.py", line 35, in main
    cluster.sshCluster(args=config.args, strict=not config.insecure)
  File "/home/ben/venv/local/lib/python2.7/site-packages/toil/provisioners/__init__.py", line 83, in sshCluster
    self.provisioner.sshLeader(self.clusterName, args, self.zone, **kwargs)
  File "/home/ben/venv/local/lib/python2.7/site-packages/toil/provisioners/azure/azureProvisioner.py", line 364, in sshLeader
    cls._sshAppliance(cls._getLeaderPublicIP(clusterName), *command, **kwargs)
  File "/home/ben/venv/local/lib/python2.7/site-packages/toil/provisioners/abstractProvisioner.py", line 217, in _sshAppliance
    return cls._coreSSH(leaderIP, *args, **kwargs)
  File "/home/ben/venv/local/lib/python2.7/site-packages/toil/provisioners/abstractProvisioner.py", line 275, in _coreSSH
    'exit code %s with stdout %s and stderr %s' % (' '.join(args), resultValue, stdout, stderr))

Per documentation, my Azure credentials are in AZURE_ACCOUNT_KEY but, when running sort.py on an Standard_A2 instance, I get the above error.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-250)
┆Issue Number: TOIL-250

**Comment by DailyDreaming** [comment]
Azure support has been deprecated.
