### ISSUE TITLE
No OFF logLevel

### ISSUE THREAD

**Issue by david4096** [DataBiosphere/toil#2186]
The help message suggests a loglevel `OFF` but it is not present and throws this error:

```
Traceback (most recent call last):
  File "/home/david/git/workflow-service/env/bin/cwltoil", line 11, in <module>
    sys.exit(main())
  File "/home/david/git/workflow-service/env/local/lib/python2.7/site-packages/toil/cwl/cwltoil.py", line 916, in main
    cwllogger.setLevel(options.logLevel)
  File "/usr/lib/python2.7/logging/__init__.py", line 1143, in setLevel
    self.level = _checkLevel(level)
  File "/usr/lib/python2.7/logging/__init__.py", line 182, in _checkLevel
    raise ValueError("Unknown level: %r" % level)
ValueError: Unknown level: 'OFF'
```

From @DailyDreaming it is synonymous with critical and should either be removed from the help message or added.

python 2.7.12+, toil 3.15.0

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/TOIL-84)
┆Issue Number: TOIL-84

**Comment by bencvdb** [comment]
I have been unable to reproduce this error and have no issue setting the logLevel to OFF.
