### ISSUE TITLE
Azure provisioner launch-cluster fails unclearly when `--zone` is not specified

### ISSUE THREAD

**Issue by natanlao** [DataBiosphere/toil#2191]
When the `--zone` argument isn't provided to `toil launch-cluster`, Toil exits with an unclear traceback:

```
$ toil launch-cluster -p azure --leaderNodeType Standard_A0 --keyPairName natanlao@users.noreply.github.com natanlao-test-cluster
...
Traceback (most recent call last):
  File "/home/natan/toil/toil/bin/toil", line 11, in <module>
    load_entry_point('toil', 'console_scripts', 'toil')()
  File "/home/natan/toil/src/toil/utils/toilMain.py", line 34, in main
    module.main()
  File "/home/natan/toil/src/toil/utils/toilLaunchCluster.py", line 133, in main
    azureStorageCredentials=config.azureStorageCredentials)
  File "/home/natan/toil/src/toil/provisioners/azure/azureProvisioner.py", line 139, in launchCluster
    self.callPlaybook(self.playbook['create-cluster'], ansibleArgs, wait=True)
  File "/home/natan/toil/src/toil/provisioners/ansibleDriver.py", line 43, in callPlaybook
    command.append(" ".join(["=".join(i) for i in ansibleArgs.items()]))  # Arguments being passed to playbook
TypeError: sequence item 1: expected string, NoneType found
```

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/TOIL-14)
┆Issue Number: TOIL-14

**Comment by bencvdb** [comment]
This was resolved by PR #2320
