### ISSUE TITLE
LSF possible memory issue/leak

### ISSUE THREAD

**Issue by jsmedmar** [DataBiosphere/toil#2231]
Best regards, LSF is reporting 17GB of SWAP memory usage for the simplest toil pipeline. This phenomena happens at random with toil versions  `3.14.0`, `3.15.0` and `3.16.0`. 

Here is how to reproduce:

## pipeline

```python
# test.py

from toil.job import Job
from toil.common import Toil


if __name__ == "__main__":
    parser = Job.Runner.getDefaultArgumentParser()
    options = parser.parse_args()
    with Toil(options) as pipe:
        if not pipe.options.restart:
            pipe.start(Job())
        else:
            pipe.restart()
```

## run multiple times

This takes some time.

```bash
for i in `seq 10`; do 
    ID=`rm -rf jobstore && bsub -K python test.py --batchSystem LSF jobstore | grep -P '[0-9]+(?=\>)' -o`
    bacct -l $ID;
done
```

## report example

Please note the `SWAP` section.

```
Accounting information about jobs that are: 
  - submitted by all users.
  - accounted on all projects.
  - completed normally or exited
  - executed on all hosts.
  - submitted to all queues.
  - accounted on all service classes.
------------------------------------------------------------------------------

Job <20941857>, User <medinaj>, Project <default>, Status <DONE>, Queue <sol>, 
                     Synchronous Execution, Command <python test.py --batchSyst
                     em LSF jobstore>, Share group charged </medinaj>
Fri Jun  1 15:34:21: Submitted from host <selene>, CWD </ifs/work/leukgen/home/
                     s/repos/deleteme2>;
Fri Jun  1 15:34:33: Dispatched 1 Task(s) on Host(s) <s22>, Allocated 1 Slot(s)
                      on Host(s) <s22>, Effective RES_REQ <select[type == any] 
                     order[iounits] rusage[mem=8.00,iounits=0.10] span[hosts=1]
                      affinity[thread(1)*1] >;
Fri Jun  1 15:35:05: Completed <done>.

Accounting information about this job:
     Share group charged </medinaj>
     CPU_T     WAIT     TURNAROUND   STATUS     HOG_FACTOR    MEM    SWAP
      1.90       12             44     done         0.0432     0G     17G
------------------------------------------------------------------------------

SUMMARY:      ( time unit: second ) 
 Total number of done jobs:       1      Total number of exited jobs:     0
 Total CPU time consumed:       1.9      Average CPU time consumed:     1.9
 Maximum CPU time of a job:     1.9      Minimum CPU time of a job:     1.9
 Total wait time in queues:    12.0
 Average wait time in queue:   12.0
 Maximum wait time in queue:   12.0      Minimum wait time in queue:   12.0
 Average turnaround time:        44 (seconds/job)
 Maximum turnaround time:        44      Minimum turnaround time:        44
 Average hog factor of a job:  0.04 ( cpu time / turnaround time )
 Maximum hog factor of a job:  0.04      Minimum hog factor of a job:  0.04
```

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/TOIL-101)
┆Issue Number: TOIL-101

**Comment by joelarmstrong** [comment]
This is interesting. I can't really track down what SWAP memory usage means in LSF. Is this just the virtual memory usage, rather than the true resident set size?

**Comment by jsmedmar** [comment]
Im confused also, I asked sys admin and she told me its virtual memory. I was wondering if someonelse could reproduce in other LSF system. I thought it was a LSF reporting problem but I tried with other commands and couldn’t reproduce swap phenomena...

**Comment by DailyDreaming** [comment]
That's really odd.  As far as I can tell, SWAP looks like virtual memory, so resources set aside for the task, rather than those actually used.  I don't have an LSF cluster to test this on however.

**Comment by jsmedmar** [comment]
I dont think its that important to figure this out, we can just close this issue and leave the message for the record

**Comment by zhouyangyu** [comment]
I have the same problem with large SWAP memory in LSF:
### Logs
```
Resource usage summary:
    CPU time :                                   346.42 sec.
    Total Requested Memory :                     -
    Delta Memory :                               -
    Max Swap :                                   21 GB
    Max Processes :                              7
    Max Threads :                                412
    Run time :                                   708 sec.
    Turnaround time :                            115897 sec.
```
This unexpected behavior are failing a lot of my jobs. The error log looks like this:
```Traceback (most recent call last):
  File "/ifs/work/leukgen/bin/python/.virtualenvs/users/leukbot/prod__toil_strelka__v0.2.2/bin/toil_strelka", line 11, in <module>
    sys.exit(main())
  File "/ifs/work/leukgen/bin/python/.virtualenvs/users/leukbot/prod__toil_strelka__v0.2.2/lib/python2.7/site-packages/toil_strelka/cli.py", line 23, in main
    commands.main()
  File "/ifs/work/leukgen/bin/python/.virtualenvs/users/leukbot/prod__toil_strelka__v0.2.2/lib/python2.7/site-packages/toil_strelka/commands.py", line 294, in main
    run_toil(options=options)
  File "/ifs/work/leukgen/bin/python/.virtualenvs/users/leukbot/prod__toil_strelka__v0.2.2/lib/python2.7/site-packages/toil_strelka/commands.py", line 202, in run_toil
    ContainerJob.Runner.startToil(manta_config_node, options)
  File "/ifs/work/leukgen/bin/python/.virtualenvs/users/leukbot/prod__toil_strelka__v0.2.2/lib/python2.7/site-packages/toil/job.py", line 785, in startToil
    return toil.start(job)
  File "/ifs/work/leukgen/bin/python/.virtualenvs/users/leukbot/prod__toil_strelka__v0.2.2/lib/python2.7/site-packages/toil/common.py", line 783, in start
    return self._runMainLoop(rootJobGraph)
  File "/ifs/work/leukgen/bin/python/.virtualenvs/users/leukbot/prod__toil_strelka__v0.2.2/lib/python2.7/site-packages/toil/common.py", line 1057, in _runMainLoop
    jobCache=self._jobCache).run()
  File "/ifs/work/leukgen/bin/python/.virtualenvs/users/leukbot/prod__toil_strelka__v0.2.2/lib/python2.7/site-packages/toil/leader.py", line 212, in run
    self.innerLoop()
  File "/ifs/work/leukgen/bin/python/.virtualenvs/users/leukbot/prod__toil_strelka__v0.2.2/lib/python2.7/site-packages/toil/leader.py", line 539, in innerLoop
    self.checkForDeadlocks()
  File "/ifs/work/leukgen/bin/python/.virtualenvs/users/leukbot/prod__toil_strelka__v0.2.2/lib/python2.7/site-packages/toil/leader.py", line 556, in checkForDeadlocks
    totalRunningJobs = len(self.batchSystem.getRunningBatchJobIDs())
  File "/ifs/work/leukgen/bin/python/.virtualenvs/users/leukbot/prod__toil_strelka__v0.2.2/lib/python2.7/site-packages/toil/batchSystems/abstractGridEngineBatchSystem.py", line 361, in getRunningBatchJobIDs
    batchIds = self.worker.getRunningJobIDs()
  File "/ifs/work/leukgen/bin/python/.virtualenvs/users/leukbot/prod__toil_strelka__v0.2.2/lib/python2.7/site-packages/toil/batchSystems/lsf.py", line 56, in getRunningJobIDs
    stdout=subprocess.PIPE)
  File "/ifs/work/leukgen/bin/python/.virtualenvs/users/leukbot/prod__toil_strelka__v0.2.2/lib/python2.7/site-packages/subprocess32.py", line 614, in __init__
    restore_signals, start_new_session)
  File "/ifs/work/leukgen/bin/python/.virtualenvs/users/leukbot/prod__toil_strelka__v0.2.2/lib/python2.7/site-packages/subprocess32.py", line 1211, in _execute_child
    restore_signals, start_new_session, preexec_fn)
OSError: [Errno 12] Cannot allocate memory
```
It seems like because of the large memory SWAP, toil cannot allocate memory to worker jobs when there are many other toil jobs running on the same node. 

I am using toil 3.12.0. Any help would be greatly appreciated.

**Comment by jsmedmar** [comment]
Will close this for now, we'll see if we need to revisit in the future.
