### ISSUE TITLE
cwltoil fails when @ symbol is in the directory name

### ISSUE THREAD

**Issue by cmball1** [DataBiosphere/toil#2274]
When running a CWL workflow with `toilcwl`, the job fails when the `@` symbol is in the file name. The below steps are ran on my Mac. However, we have experienced the same issue on CentOS 7.

Steps to reproduce:
```
$ virtualenv venv
$ source venv/bin/activate
$ pip install toil[all]

$ cwltoil --version
DEBUG:rdflib:RDFLib Version: 4.2.2
3.16.0

$ mkdir example
$ mkdir example@gmail.com
```

`touch.cwl`:
```
cwlVersion: v1.0
class: CommandLineTool
baseCommand: ["touch"]
inputs:
  - id: filename
    type: string
    inputBinding:
      position: 1
outputs:
  - id: file_out
    type: File
    outputBinding:
      glob: $(inputs.filename)
  - id: standard_out
    type: stdout
stdout: $(inputs.filename+".touch.cwl.stdout")
requirements:
  - class: InlineJavascriptRequirement
```

`touch-works.yml`:
```
filename: example/anewfile
```

`touch-broken.yml`:
```
filename: example@gmail.com/anewfile
```

Run:
```
$ cd example
$ cwltoil ../touch.cwl ../touch-works.yml
```

Output:
```
2018-07-03 12:44:39,977 - toil.leader - INFO - Finished toil run successfully
{
    "standard_out": {
        "checksum": "sha1$da39a3ee5e6b4b0d3255bfef95601890afd80709", 
        "basename": "anewfile.touch.cwl.stdout", 
        "nameext": ".stdout", 
        "nameroot": "anewfile.touch.cwl", 
        "http://commonwl.org/cwltool#generation": 0, 
        "location": "file:///<base-path>/example/anewfile.touch.cwl.stdout", 
        "class": "File", 
        "size": 0
    }, 
    "file_out": {
        "checksum": "sha1$da39a3ee5e6b4b0d3255bfef95601890afd80709", 
        "basename": "anewfile", 
        "nameext": "", 
        "nameroot": "anewfile", 
        "http://commonwl.org/cwltool#generation": 0, 
        "location": "file:///<base-path>/example/anewfile", 
        "class": "File", 
        "size": 0
    }
```

Run: 
```
$ cd example@gmail.com
$ cwltoil ../touch.cwl ../touch-broken.yml
```

Output:
```
DEBUG:rdflib:RDFLib Version: 4.2.2
INFO:toil.lib.bioio:Root logger is at level 'INFO', 'toil' logger at level 'INFO'.
INFO:toil.jobStores.abstractJobStore:The workflow ID is: '8a33a8f2-f230-4338-a5b5-7b0e74bbcbd8'
Resolved '../touch.cwl' to 'file:///<base-path>/touch.cwl'
INFO:cwltool:Resolved '../touch.cwl' to 'file:///<base-path>/touch.cwl'
INFO:toil.common:Using the single machine batch system
WARNING:toil.batchSystems.singleMachine:Limiting maxCores to CPU count of system (8).
WARNING:toil.batchSystems.singleMachine:Limiting maxMemory to physically available memory (17179869184).
INFO:toil.common:Created the workflow directory at /var/folders/fp/01yx8fgx1yb79yy0ydkmt231tr07vn/T/toil-8a33a8f2-f230-4338-a5b5-7b0e74bbcbd8-132281832502514
WARNING:toil.batchSystems.singleMachine:Limiting maxDisk to physically available disk (166046789632).
INFO:toil.common:User script ModuleDescriptor(dirPath='/<base-path>/venv/lib/python2.7/site-packages', name='toil.cwl.cwltoil', fromVirtualEnv=True) belongs to Toil. No need to auto-deploy it.
INFO:toil.common:No user script to auto-deploy.
INFO:toil.common:Written the environment for the jobs to the environment file
INFO:toil.common:Caching all jobs in job store
INFO:toil.common:0 jobs downloaded.
INFO:toil:Running Toil version 3.16.0-5988d51822310572dee1aa1e3cb8c81e39ba376c.
INFO:toil.realtimeLogger:Real-time logging disabled
INFO:toil.toilState:(Re)building internal scheduler state
2018-07-03 12:46:53,718 - toil.toilState - INFO - (Re)building internal scheduler state
INFO:toil.leader:Found 1 jobs to start and 0 jobs with successors to run
2018-07-03 12:46:53,718 - toil.leader - INFO - Found 1 jobs to start and 0 jobs with successors to run
INFO:toil.leader:Checked batch system has no running jobs and no updated jobs
2018-07-03 12:46:53,718 - toil.leader - INFO - Checked batch system has no running jobs and no updated jobs
INFO:toil.leader:Starting the main loop
2018-07-03 12:46:53,719 - toil.leader - INFO - Starting the main loop
INFO:toil.leader:Issued job 'file:///<base-path>/touch.cwl' touch y/T/jobPTqCjV with job batch system ID: 0 and cores: 1, disk: 3.0 G, and memory: 2.0 G
2018-07-03 12:46:53,720 - toil.leader - INFO - Issued job 'file:///<base-path>/touch.cwl' touch y/T/jobPTqCjV with job batch system ID: 0 and cores: 1, disk: 3.0 G, and memory: 2.0 G
DEBUG:toil.jobStores.fileJobStore:Path to job store directory is '/var/folders/fp/01yx8fgx1yb79yy0ydkmt231tr07vn/T/tmpOMGmwu'.
INFO:toil.leader:Job ended successfully: 'file:///<base-path>/touch.cwl' touch y/T/jobPTqCjV
2018-07-03 12:46:55,043 - toil.leader - INFO - Job ended successfully: 'file:///<base-path>/touch.cwl' touch y/T/jobPTqCjV
WARNING:toil.leader:The job seems to have left a log file, indicating failure: 'file:///<base-path>/touch.cwl' touch y/T/jobPTqCjV
2018-07-03 12:46:55,050 - toil.leader - WARNING - The job seems to have left a log file, indicating failure: 'file:///<base-path>/touch.cwl' touch y/T/jobPTqCjV
WARNING:toil.leader:y/T/jobPTqCjV    INFO:toil.worker:---TOIL WORKER OUTPUT LOG---
2018-07-03 12:46:55,050 - toil.leader - WARNING - y/T/jobPTqCjV    INFO:toil.worker:---TOIL WORKER OUTPUT LOG---
WARNING:toil.leader:y/T/jobPTqCjV    INFO:toil:Running Toil version 3.16.0-5988d51822310572dee1aa1e3cb8c81e39ba376c.
2018-07-03 12:46:55,050 - toil.leader - WARNING - y/T/jobPTqCjV    INFO:toil:Running Toil version 3.16.0-5988d51822310572dee1aa1e3cb8c81e39ba376c.
WARNING:toil.leader:y/T/jobPTqCjV    [job touch.cwl] /<base-path>/example@gmail.com/out_tmpdirX5vwz0$ touch \
2018-07-03 12:46:55,051 - toil.leader - WARNING - y/T/jobPTqCjV    [job touch.cwl] /<base-path>/example@gmail.com/out_tmpdirX5vwz0$ touch \
WARNING:toil.leader:y/T/jobPTqCjV        'example@gmail.com/anewfile' > /<base-path>/example@gmail.com/out_tmpdirX5vwz0/example@gmail.com/anewfile.touch.cwl.stdout
2018-07-03 12:46:55,051 - toil.leader - WARNING - y/T/jobPTqCjV        'example@gmail.com/anewfile' > /<base-path>/example@gmail.com/out_tmpdirX5vwz0/example@gmail.com/anewfile.touch.cwl.stdout
WARNING:toil.leader:y/T/jobPTqCjV    INFO:cwltool:[job touch.cwl] /<base-path>/example@gmail.com/out_tmpdirX5vwz0$ touch \
2018-07-03 12:46:55,051 - toil.leader - WARNING - y/T/jobPTqCjV    INFO:cwltool:[job touch.cwl] /<base-path>/example@gmail.com/out_tmpdirX5vwz0$ touch \
WARNING:toil.leader:y/T/jobPTqCjV        'example@gmail.com/anewfile' > /<base-path>/example@gmail.com/out_tmpdirX5vwz0/example@gmail.com/anewfile.touch.cwl.stdout
2018-07-03 12:46:55,051 - toil.leader - WARNING - y/T/jobPTqCjV        'example@gmail.com/anewfile' > /<base-path>/example@gmail.com/out_tmpdirX5vwz0/example@gmail.com/anewfile.touch.cwl.stdout
WARNING:toil.leader:y/T/jobPTqCjV    [job touch.cwl] Job error:
2018-07-03 12:46:55,051 - toil.leader - WARNING - y/T/jobPTqCjV    [job touch.cwl] Job error:
WARNING:toil.leader:y/T/jobPTqCjV    Error collecting output for parameter 'file_out':
2018-07-03 12:46:55,051 - toil.leader - WARNING - y/T/jobPTqCjV    Error collecting output for parameter 'file_out':
WARNING:toil.leader:y/T/jobPTqCjV    ../touch.cwl:10:5: [Errno 2] No such file or directory: '/<base-path>/example@gmail.com/out_tmpdirX5vwz0/example%40gmail.com/anewfile'
2018-07-03 12:46:55,051 - toil.leader - WARNING - y/T/jobPTqCjV    ../touch.cwl:10:5: [Errno 2] No such file or directory: '/<base-path>/example@gmail.com/out_tmpdirX5vwz0/example%40gmail.com/anewfile'
WARNING:toil.leader:y/T/jobPTqCjV    ERROR:cwltool:[job touch.cwl] Job error:
2018-07-03 12:46:55,051 - toil.leader - WARNING - y/T/jobPTqCjV    ERROR:cwltool:[job touch.cwl] Job error:
WARNING:toil.leader:y/T/jobPTqCjV    Error collecting output for parameter 'file_out':
2018-07-03 12:46:55,051 - toil.leader - WARNING - y/T/jobPTqCjV    Error collecting output for parameter 'file_out':
WARNING:toil.leader:y/T/jobPTqCjV    ../touch.cwl:10:5: [Errno 2] No such file or directory: '/<base-path>/example@gmail.com/out_tmpdirX5vwz0/example%40gmail.com/anewfile'
2018-07-03 12:46:55,051 - toil.leader - WARNING - y/T/jobPTqCjV    ../touch.cwl:10:5: [Errno 2] No such file or directory: '/<base-path>/example@gmail.com/out_tmpdirX5vwz0/example%40gmail.com/anewfile'
WARNING:toil.leader:y/T/jobPTqCjV    [job touch.cwl] completed permanentFail
2018-07-03 12:46:55,051 - toil.leader - WARNING - y/T/jobPTqCjV    [job touch.cwl] completed permanentFail
WARNING:toil.leader:y/T/jobPTqCjV    WARNING:cwltool:[job touch.cwl] completed permanentFail
2018-07-03 12:46:55,051 - toil.leader - WARNING - y/T/jobPTqCjV    WARNING:cwltool:[job touch.cwl] completed permanentFail
WARNING:toil.leader:y/T/jobPTqCjV    Traceback (most recent call last):
2018-07-03 12:46:55,051 - toil.leader - WARNING - y/T/jobPTqCjV    Traceback (most recent call last):
WARNING:toil.leader:y/T/jobPTqCjV      File "/<base-path>/venv/lib/python2.7/site-packages/toil/worker.py", line 313, in workerScript
2018-07-03 12:46:55,051 - toil.leader - WARNING - y/T/jobPTqCjV      File "/<base-path>/venv/lib/python2.7/site-packages/toil/worker.py", line 313, in workerScript
WARNING:toil.leader:y/T/jobPTqCjV        job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore)
2018-07-03 12:46:55,052 - toil.leader - WARNING - y/T/jobPTqCjV        job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore)
WARNING:toil.leader:y/T/jobPTqCjV      File "/<base-path>/venv/lib/python2.7/site-packages/toil/job.py", line 1337, in _runner
2018-07-03 12:46:55,052 - toil.leader - WARNING - y/T/jobPTqCjV      File "/<base-path>/venv/lib/python2.7/site-packages/toil/job.py", line 1337, in _runner
WARNING:toil.leader:y/T/jobPTqCjV        returnValues = self._run(jobGraph, fileStore)
2018-07-03 12:46:55,052 - toil.leader - WARNING - y/T/jobPTqCjV        returnValues = self._run(jobGraph, fileStore)
WARNING:toil.leader:y/T/jobPTqCjV      File "/<base-path>/venv/lib/python2.7/site-packages/toil/job.py", line 1282, in _run
2018-07-03 12:46:55,052 - toil.leader - WARNING - y/T/jobPTqCjV      File "/<base-path>/venv/lib/python2.7/site-packages/toil/job.py", line 1282, in _run
WARNING:toil.leader:y/T/jobPTqCjV        return self.run(fileStore)
2018-07-03 12:46:55,052 - toil.leader - WARNING - y/T/jobPTqCjV        return self.run(fileStore)
WARNING:toil.leader:y/T/jobPTqCjV      File "/<base-path>/venv/lib/python2.7/site-packages/toil/cwl/cwltoil.py", line 472, in run
2018-07-03 12:46:55,052 - toil.leader - WARNING - y/T/jobPTqCjV      File "/<base-path>/venv/lib/python2.7/site-packages/toil/cwl/cwltoil.py", line 472, in run
WARNING:toil.leader:y/T/jobPTqCjV        raise cwltool.errors.WorkflowException(status)
2018-07-03 12:46:55,052 - toil.leader - WARNING - y/T/jobPTqCjV        raise cwltool.errors.WorkflowException(status)
WARNING:toil.leader:y/T/jobPTqCjV    WorkflowException: permanentFail
2018-07-03 12:46:55,052 - toil.leader - WARNING - y/T/jobPTqCjV    WorkflowException: permanentFail
WARNING:toil.leader:y/T/jobPTqCjV    ERROR:toil.worker:Exiting the worker because of a failed job on host RTI-102919.rti.ns
2018-07-03 12:46:55,052 - toil.leader - WARNING - y/T/jobPTqCjV    ERROR:toil.worker:Exiting the worker because of a failed job on host RTI-102919.rti.ns
WARNING:toil.leader:y/T/jobPTqCjV    WARNING:toil.jobGraph:Due to failure we are reducing the remaining retry count of job 'file:///<base-path>/touch.cwl' touch y/T/jobPTqCjV with ID y/T/jobPTqCjV to 1
2018-07-03 12:46:55,052 - toil.leader - WARNING - y/T/jobPTqCjV    WARNING:toil.jobGraph:Due to failure we are reducing the remaining retry count of job 'file:///<base-path>/touch.cwl' touch y/T/jobPTqCjV with ID y/T/jobPTqCjV to 1
INFO:toil.leader:Issued job 'file:///<base-path>/touch.cwl' touch y/T/jobPTqCjV with job batch system ID: 1 and cores: 1, disk: 3.0 G, and memory: 2.0 G
2018-07-03 12:46:55,053 - toil.leader - INFO - Issued job 'file:///<base-path>/touch.cwl' touch y/T/jobPTqCjV with job batch system ID: 1 and cores: 1, disk: 3.0 G, and memory: 2.0 G
DEBUG:toil.jobStores.fileJobStore:Path to job store directory is '/var/folders/fp/01yx8fgx1yb79yy0ydkmt231tr07vn/T/tmpOMGmwu'.
INFO:toil.leader:Job ended successfully: 'file:///<base-path>/touch.cwl' touch y/T/jobPTqCjV
2018-07-03 12:46:56,364 - toil.leader - INFO - Job ended successfully: 'file:///<base-path>/touch.cwl' touch y/T/jobPTqCjV
WARNING:toil.leader:The job seems to have left a log file, indicating failure: 'file:///<base-path>/touch.cwl' touch y/T/jobPTqCjV
2018-07-03 12:46:56,373 - toil.leader - WARNING - The job seems to have left a log file, indicating failure: 'file:///<base-path>/touch.cwl' touch y/T/jobPTqCjV
WARNING:toil.leader:y/T/jobPTqCjV    INFO:toil.worker:---TOIL WORKER OUTPUT LOG---
2018-07-03 12:46:56,373 - toil.leader - WARNING - y/T/jobPTqCjV    INFO:toil.worker:---TOIL WORKER OUTPUT LOG---
WARNING:toil.leader:y/T/jobPTqCjV    INFO:toil:Running Toil version 3.16.0-5988d51822310572dee1aa1e3cb8c81e39ba376c.
2018-07-03 12:46:56,373 - toil.leader - WARNING - y/T/jobPTqCjV    INFO:toil:Running Toil version 3.16.0-5988d51822310572dee1aa1e3cb8c81e39ba376c.
WARNING:toil.leader:y/T/jobPTqCjV    [job touch.cwl] /<base-path>/example@gmail.com/out_tmpdirLgFwMg$ touch \
2018-07-03 12:46:56,373 - toil.leader - WARNING - y/T/jobPTqCjV    [job touch.cwl] /<base-path>/example@gmail.com/out_tmpdirLgFwMg$ touch \
WARNING:toil.leader:y/T/jobPTqCjV        'example@gmail.com/anewfile' > /<base-path>/example@gmail.com/out_tmpdirLgFwMg/example@gmail.com/anewfile.touch.cwl.stdout
2018-07-03 12:46:56,373 - toil.leader - WARNING - y/T/jobPTqCjV        'example@gmail.com/anewfile' > /<base-path>/example@gmail.com/out_tmpdirLgFwMg/example@gmail.com/anewfile.touch.cwl.stdout
WARNING:toil.leader:y/T/jobPTqCjV    INFO:cwltool:[job touch.cwl] /<base-path>/example@gmail.com/out_tmpdirLgFwMg$ touch \
2018-07-03 12:46:56,373 - toil.leader - WARNING - y/T/jobPTqCjV    INFO:cwltool:[job touch.cwl] /<base-path>/example@gmail.com/out_tmpdirLgFwMg$ touch \
WARNING:toil.leader:y/T/jobPTqCjV        'example@gmail.com/anewfile' > /<base-path>/example@gmail.com/out_tmpdirLgFwMg/example@gmail.com/anewfile.touch.cwl.stdout
2018-07-03 12:46:56,373 - toil.leader - WARNING - y/T/jobPTqCjV        'example@gmail.com/anewfile' > /<base-path>/example@gmail.com/out_tmpdirLgFwMg/example@gmail.com/anewfile.touch.cwl.stdout
WARNING:toil.leader:y/T/jobPTqCjV    [job touch.cwl] Job error:
2018-07-03 12:46:56,373 - toil.leader - WARNING - y/T/jobPTqCjV    [job touch.cwl] Job error:
WARNING:toil.leader:y/T/jobPTqCjV    Error collecting output for parameter 'file_out':
2018-07-03 12:46:56,374 - toil.leader - WARNING - y/T/jobPTqCjV    Error collecting output for parameter 'file_out':
WARNING:toil.leader:y/T/jobPTqCjV    ../touch.cwl:10:5: [Errno 2] No such file or directory: '/<base-path>/example@gmail.com/out_tmpdirLgFwMg/example%40gmail.com/anewfile'
2018-07-03 12:46:56,374 - toil.leader - WARNING - y/T/jobPTqCjV    ../touch.cwl:10:5: [Errno 2] No such file or directory: '/<base-path>/example@gmail.com/out_tmpdirLgFwMg/example%40gmail.com/anewfile'
WARNING:toil.leader:y/T/jobPTqCjV    ERROR:cwltool:[job touch.cwl] Job error:
2018-07-03 12:46:56,374 - toil.leader - WARNING - y/T/jobPTqCjV    ERROR:cwltool:[job touch.cwl] Job error:
WARNING:toil.leader:y/T/jobPTqCjV    Error collecting output for parameter 'file_out':
2018-07-03 12:46:56,374 - toil.leader - WARNING - y/T/jobPTqCjV    Error collecting output for parameter 'file_out':
WARNING:toil.leader:y/T/jobPTqCjV    ../touch.cwl:10:5: [Errno 2] No such file or directory: '/<base-path>/example@gmail.com/out_tmpdirLgFwMg/example%40gmail.com/anewfile'
2018-07-03 12:46:56,374 - toil.leader - WARNING - y/T/jobPTqCjV    ../touch.cwl:10:5: [Errno 2] No such file or directory: '/<base-path>/example@gmail.com/out_tmpdirLgFwMg/example%40gmail.com/anewfile'
WARNING:toil.leader:y/T/jobPTqCjV    [job touch.cwl] completed permanentFail
2018-07-03 12:46:56,374 - toil.leader - WARNING - y/T/jobPTqCjV    [job touch.cwl] completed permanentFail
WARNING:toil.leader:y/T/jobPTqCjV    WARNING:cwltool:[job touch.cwl] completed permanentFail
2018-07-03 12:46:56,374 - toil.leader - WARNING - y/T/jobPTqCjV    WARNING:cwltool:[job touch.cwl] completed permanentFail
WARNING:toil.leader:y/T/jobPTqCjV    Traceback (most recent call last):
2018-07-03 12:46:56,374 - toil.leader - WARNING - y/T/jobPTqCjV    Traceback (most recent call last):
WARNING:toil.leader:y/T/jobPTqCjV      File "/<base-path>/venv/lib/python2.7/site-packages/toil/worker.py", line 313, in workerScript
2018-07-03 12:46:56,374 - toil.leader - WARNING - y/T/jobPTqCjV      File "/<base-path>/venv/lib/python2.7/site-packages/toil/worker.py", line 313, in workerScript
WARNING:toil.leader:y/T/jobPTqCjV        job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore)
2018-07-03 12:46:56,374 - toil.leader - WARNING - y/T/jobPTqCjV        job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore)
WARNING:toil.leader:y/T/jobPTqCjV      File "/<base-path>/venv/lib/python2.7/site-packages/toil/job.py", line 1337, in _runner
2018-07-03 12:46:56,374 - toil.leader - WARNING - y/T/jobPTqCjV      File "/<base-path>/venv/lib/python2.7/site-packages/toil/job.py", line 1337, in _runner
WARNING:toil.leader:y/T/jobPTqCjV        returnValues = self._run(jobGraph, fileStore)
2018-07-03 12:46:56,374 - toil.leader - WARNING - y/T/jobPTqCjV        returnValues = self._run(jobGraph, fileStore)
WARNING:toil.leader:y/T/jobPTqCjV      File "/<base-path>/venv/lib/python2.7/site-packages/toil/job.py", line 1282, in _run
2018-07-03 12:46:56,375 - toil.leader - WARNING - y/T/jobPTqCjV      File "/<base-path>/venv/lib/python2.7/site-packages/toil/job.py", line 1282, in _run
WARNING:toil.leader:y/T/jobPTqCjV        return self.run(fileStore)
2018-07-03 12:46:56,375 - toil.leader - WARNING - y/T/jobPTqCjV        return self.run(fileStore)
WARNING:toil.leader:y/T/jobPTqCjV      File "/<base-path>/venv/lib/python2.7/site-packages/toil/cwl/cwltoil.py", line 472, in run
2018-07-03 12:46:56,375 - toil.leader - WARNING - y/T/jobPTqCjV      File "/<base-path>/venv/lib/python2.7/site-packages/toil/cwl/cwltoil.py", line 472, in run
WARNING:toil.leader:y/T/jobPTqCjV        raise cwltool.errors.WorkflowException(status)
2018-07-03 12:46:56,375 - toil.leader - WARNING - y/T/jobPTqCjV        raise cwltool.errors.WorkflowException(status)
WARNING:toil.leader:y/T/jobPTqCjV    WorkflowException: permanentFail
2018-07-03 12:46:56,375 - toil.leader - WARNING - y/T/jobPTqCjV    WorkflowException: permanentFail
WARNING:toil.leader:y/T/jobPTqCjV    ERROR:toil.worker:Exiting the worker because of a failed job on host RTI-102919.rti.ns
2018-07-03 12:46:56,375 - toil.leader - WARNING - y/T/jobPTqCjV    ERROR:toil.worker:Exiting the worker because of a failed job on host RTI-102919.rti.ns
WARNING:toil.leader:y/T/jobPTqCjV    WARNING:toil.jobGraph:Due to failure we are reducing the remaining retry count of job 'file:///<base-path>/touch.cwl' touch y/T/jobPTqCjV with ID y/T/jobPTqCjV to 0
2018-07-03 12:46:56,375 - toil.leader - WARNING - y/T/jobPTqCjV    WARNING:toil.jobGraph:Due to failure we are reducing the remaining retry count of job 'file:///<base-path>/touch.cwl' touch y/T/jobPTqCjV with ID y/T/jobPTqCjV to 0
WARNING:toil.leader:Job 'file:///<base-path>/touch.cwl' touch y/T/jobPTqCjV with ID y/T/jobPTqCjV is completely failed
2018-07-03 12:46:56,375 - toil.leader - WARNING - Job 'file:///<base-path>/touch.cwl' touch y/T/jobPTqCjV with ID y/T/jobPTqCjV is completely failed
INFO:toil.leader:Finished the main loop: no jobs left to run
2018-07-03 12:46:58,379 - toil.leader - INFO - Finished the main loop: no jobs left to run
INFO:toil.serviceManager:Waiting for service manager thread to finish ...
2018-07-03 12:46:58,379 - toil.serviceManager - INFO - Waiting for service manager thread to finish ...
INFO:toil.serviceManager:... finished shutting down the service manager. Took 0.348975896835 seconds
2018-07-03 12:46:58,728 - toil.serviceManager - INFO - ... finished shutting down the service manager. Took 0.348975896835 seconds
INFO:toil.statsAndLogging:Waiting for stats and logging collator thread to finish ...
2018-07-03 12:46:58,729 - toil.statsAndLogging - INFO - Waiting for stats and logging collator thread to finish ...
INFO:toil.statsAndLogging:... finished collating stats and logs. Took 0.025799036026 seconds
2018-07-03 12:46:58,755 - toil.statsAndLogging - INFO - ... finished collating stats and logs. Took 0.025799036026 seconds
INFO:toil.leader:Finished toil run with 1 failed jobs
2018-07-03 12:46:58,756 - toil.leader - INFO - Finished toil run with 1 failed jobs
INFO:toil.leader:Failed jobs at end of the run: 'file:///<base-path>/touch.cwl' touch y/T/jobPTqCjV
2018-07-03 12:46:58,756 - toil.leader - INFO - Failed jobs at end of the run: 'file:///<base-path>/touch.cwl' touch y/T/jobPTqCjV
Traceback (most recent call last):
  File "/<base-path>/venv/bin/cwltoil", line 11, in <module>
    sys.exit(main())
  File "/<base-path>/venv/lib/python2.7/site-packages/toil/cwl/cwltoil.py", line 1048, in main
    outobj = toil.start(wf1)
  File "/<base-path>/venv/lib/python2.7/site-packages/toil/common.py", line 783, in start
    return self._runMainLoop(rootJobGraph)
  File "/<base-path>/venv/lib/python2.7/site-packages/toil/common.py", line 1057, in _runMainLoop
    jobCache=self._jobCache).run()
  File "/<base-path>/venv/lib/python2.7/site-packages/toil/leader.py", line 241, in run
    raise FailedJobsException(self.config.jobStore, self.toilState.totalFailedJobs, self.jobStore)
toil.leader.FailedJobsException: The job store 'file:/var/folders/fp/01yx8fgx1yb79yy0ydkmt231tr07vn/T/tmpOMGmwu' contains 1 failed jobs: 'file:///<base-path>/touch.cwl' touch y/T/jobPTqCjV
=========> Failed job 'file:///<base-path>/touch.cwl' touch y/T/jobPTqCjV 
INFO:toil.worker:---TOIL WORKER OUTPUT LOG---
INFO:toil:Running Toil version 3.16.0-5988d51822310572dee1aa1e3cb8c81e39ba376c.
[job touch.cwl] /<base-path>/example@gmail.com/out_tmpdirLgFwMg$ touch \
    'example@gmail.com/anewfile' > /<base-path>/example@gmail.com/out_tmpdirLgFwMg/example@gmail.com/anewfile.touch.cwl.stdout
INFO:cwltool:[job touch.cwl] /<base-path>/example@gmail.com/out_tmpdirLgFwMg$ touch \
    'example@gmail.com/anewfile' > /<base-path>/example@gmail.com/out_tmpdirLgFwMg/example@gmail.com/anewfile.touch.cwl.stdout
[job touch.cwl] Job error:
Error collecting output for parameter 'file_out':
../touch.cwl:10:5: [Errno 2] No such file or directory: '/<base-path>/example@gmail.com/out_tmpdirLgFwMg/example%40gmail.com/anewfile'
ERROR:cwltool:[job touch.cwl] Job error:
Error collecting output for parameter 'file_out':
../touch.cwl:10:5: [Errno 2] No such file or directory: '/<base-path>/example@gmail.com/out_tmpdirLgFwMg/example%40gmail.com/anewfile'
[job touch.cwl] completed permanentFail
WARNING:cwltool:[job touch.cwl] completed permanentFail
Traceback (most recent call last):
  File "/<base-path>/venv/lib/python2.7/site-packages/toil/worker.py", line 313, in workerScript
    job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore)
  File "/<base-path>/venv/lib/python2.7/site-packages/toil/job.py", line 1337, in _runner
    returnValues = self._run(jobGraph, fileStore)
  File "/<base-path>/venv/lib/python2.7/site-packages/toil/job.py", line 1282, in _run
    return self.run(fileStore)
  File "/<base-path>/venv/lib/python2.7/site-packages/toil/cwl/cwltoil.py", line 472, in run
    raise cwltool.errors.WorkflowException(status)
WorkflowException: permanentFail
ERROR:toil.worker:Exiting the worker because of a failed job on host RTI-102919.rti.ns
WARNING:toil.jobGraph:Due to failure we are reducing the remaining retry count of job 'file:///<base-path>/touch.cwl' touch y/T/jobPTqCjV with ID y/T/jobPTqCjV to 0
<=========
```

Please let me know if there is anything else I can provide to be helpful. Thanks in advance!

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/TOIL-293)
┆Issue Number: TOIL-293

**Comment by cmball1** [comment]
It looks like `/<base-path>/out_tmpdirJUvyiG/example@gmail.com/` is converted to `/<base-path>/out_tmpdirJUvyiG/example%40gmail.com/`.

When toil looks for `/<base-path>/out_tmpdirJUvyiG/example%40gmail.com/anewfile` it doesn't exist. However, `/<base-path>/out_tmpdirJUvyiG/example@gmail.com/anewfile` does exist. 

Any idea where/what is converting `@` to `%40`?

**Comment by pkp124** [comment]
I would like to point to this similar issue: https://github.com/DataBiosphere/toil/issues/2280
There is a issue for the same in cwltool repo as well : https://github.com/common-workflow-language/cwltool/issues/817

**Comment by cmball1** [comment]
@pkp124 Thanks, it does look like the same parsing function is changing both the space and `@` symbol.

**Comment by cmball1** [comment]
This is a CWLTool issue, and Toil uses CWLTool to run CWL workflows.

From @pkp124's (comment)[https://github.com/common-workflow-language/cwltool/issues/817#issue-340166587]:
```
The output file is created. When collecting the output file, the space character is replaced with "%20", which i assume is because of the call to file_uri() in StdFsAccess class, glob() method. I am not sure if this is expected behaviour or a bug.
```

Looking into that, this snippet is where the file path is converted to URL (lines 28-36)[https://github.com/common-workflow-language/cwltool/blob/886a6ac41c685f20d39e352f9c657e59f3312265/cwltool/stdfsaccess.py#L36]:
```
class StdFsAccess(object):
    def __init__(self, basedir):  # type: (Text) -> None
        self.basedir = basedir

    def _abs(self, p):  # type: (Text) -> Text
        return abspath(p, self.basedir)

    def glob(self, pattern):  # type: (Text) -> List[Text]
        return [file_uri(str(self._abs(l))) for l in glob.glob(self._abs(pattern))]
```

`file_uri` is imported from `schema_salad.ref_resolver`

In `ref_resolver.py`, (file_uri)[https://github.com/common-workflow-language/schema_salad/blob/master/schema_salad/ref_resolver.py#L53] calls (urllib.request.pathname2url)[https://docs.python.org/3/library/urllib.request.html#urllib.request.pathname2url].

The call to `pathname2url` is causing `@` to be converted to `%40`. 

@pkp124 It also converts spaces to `%20`.

This issue doesn't belong in the Toil repo anymore. I'll move to using https://github.com/common-workflow-language/cwltool/issues/817 as it's the same code causing both things.
