### ISSUE TITLE
'File is missing' error accessing a file in a Directory, Toil expects a file:// IRI prefix which failed to be added

### ISSUE THREAD

**Issue by whlavina** [DataBiosphere/toil#2310]
We are experiencing failures using Toil to run our CWL workflow, and suspect a bug in Toil's handling of Directory inputs. The symptom is an error message, "File is missing: /the/path/to/some/file" (note that this is a file path, without an IRI schema prefix).

On code inspection of `uploadFile()` in `src/toil/cwl/cwltoil.py`, it is clear the logic expects an IRI with `file://` schema prefix within the contents of `uf["location"]`. trimming the first 7 characters in the check `if not os.path.isfile(uf["location"][7:]):`. That prefix should have been added when resolving the IRI relative to the CWL on the filesystem, and clearly the error message shows it was not. Since the first 7 characters of the file path get stripped regardless of the schema prefix, the path fails to represent a valid file in the filesystem.

The code paths for resolving IRIs for File vs Directory are different, and I suspect a bug in the latter. In particular, File IRIs have logic to resolve schema-relative locations, via a call to `schema_salad.ref_resolver.file_uri()`; suspiciously, such call isn't present in the code path for resolving Directory objects.

To reproduce this failure, you may try to run the NCBI PGAP workflow. Please note that this pipeline is still a work in progress, and has not yet been formally announced or released; the URL is subject to move:
https://github.com/ncbi-gpipe/pgap

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-276)
┆Issue Number: TOIL-276

**Comment by jessebrennan** [comment]
@whlavina it would be helpful if you had a stack trace. Also could you make a minimal example to reproduce the failure? I'd rather not download the 30GBs of files, etc necessary to run your pipline to figure out exactly what's going on.

I have some ideas for a fix, but I want to be sure that I'm coming at this from the right angle. Thanks!

**Comment by DailyDreaming** [comment]
@jessebrennan If you did manage to get the space to test locally, I have a script that parses gs files from a json, downloads the files locally, and rewrites a new json with the new local file locations: https://github.com/DailyDreaming/fetch_gs_frm_json

One thing, you need to have the Google sdk installed for it to work.

**Comment by whlavina** [comment]
I'll try to come up with a minimalist example that reproduces the failure. If there's any specific debugging/logging you'd like me to add, feel free to ask. Here's the Python stack trace at the point of failure; if you want full logs, I can attach those too.

```
WARNING:toil.leader:D/u/job_ugwte    Traceback (most recent call last):
2018-07-25 23:06:29,871 - toil.leader - WARNING - D/u/job_ugwte    Traceback (most recent call last):
WARNING:toil.leader:D/u/job_ugwte      File "/Users/whlavina/pgap/venv2.7-pristine/lib/python2.7/site-packages/toil/worker.py", line 313, in workerScript
2018-07-25 23:06:29,871 - toil.leader - WARNING - D/u/job_ugwte      File "/Users/whlavina/pgap/venv2.7-pristine/lib/python2.7/site-packages/toil/worker.py", line 313, in workerScript
WARNING:toil.leader:D/u/job_ugwte        job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore)
2018-07-25 23:06:29,871 - toil.leader - WARNING - D/u/job_ugwte        job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore)
WARNING:toil.leader:D/u/job_ugwte      File "/Users/whlavina/pgap/venv2.7-pristine/lib/python2.7/site-packages/toil/job.py", line 1337, in _runner
2018-07-25 23:06:29,871 - toil.leader - WARNING - D/u/job_ugwte      File "/Users/whlavina/pgap/venv2.7-pristine/lib/python2.7/site-packages/toil/job.py", line 1337, in _runner
WARNING:toil.leader:D/u/job_ugwte        returnValues = self._run(jobGraph, fileStore)
2018-07-25 23:06:29,871 - toil.leader - WARNING - D/u/job_ugwte        returnValues = self._run(jobGraph, fileStore)
WARNING:toil.leader:D/u/job_ugwte      File "/Users/whlavina/pgap/venv2.7-pristine/lib/python2.7/site-packages/toil/job.py", line 1282, in _run
2018-07-25 23:06:29,871 - toil.leader - WARNING - D/u/job_ugwte      File "/Users/whlavina/pgap/venv2.7-pristine/lib/python2.7/site-packages/toil/job.py", line 1282, in _run
WARNING:toil.leader:D/u/job_ugwte        return self.run(fileStore)
2018-07-25 23:06:29,871 - toil.leader - WARNING - D/u/job_ugwte        return self.run(fileStore)
WARNING:toil.leader:D/u/job_ugwte      File "/Users/whlavina/pgap/venv2.7-pristine/lib/python2.7/site-packages/toil/cwl/cwltoil.py", line 480, in run
2018-07-25 23:06:29,871 - toil.leader - WARNING - D/u/job_ugwte      File "/Users/whlavina/pgap/venv2.7-pristine/lib/python2.7/site-packages/toil/cwl/cwltoil.py", line 480, in run
WARNING:toil.leader:D/u/job_ugwte        index, existing))
2018-07-25 23:06:29,871 - toil.leader - WARNING - D/u/job_ugwte        index, existing))
WARNING:toil.leader:D/u/job_ugwte      File "/Users/whlavina/pgap/venv2.7-pristine/lib/python2.7/site-packages/cwltool/pathmapper.py", line 55, in adjustFileObjs
2018-07-25 23:06:29,871 - toil.leader - WARNING - D/u/job_ugwte      File "/Users/whlavina/pgap/venv2.7-pristine/lib/python2.7/site-packages/cwltool/pathmapper.py", line 55, in adjustFileObjs
WARNING:toil.leader:D/u/job_ugwte        visit_class(rec, ("File",), op)
2018-07-25 23:06:29,871 - toil.leader - WARNING - D/u/job_ugwte        visit_class(rec, ("File",), op)
WARNING:toil.leader:D/u/job_ugwte      File "/Users/whlavina/pgap/venv2.7-pristine/lib/python2.7/site-packages/cwltool/pathmapper.py", line 48, in visit_class
2018-07-25 23:06:29,871 - toil.leader - WARNING - D/u/job_ugwte      File "/Users/whlavina/pgap/venv2.7-pristine/lib/python2.7/site-packages/cwltool/pathmapper.py", line 48, in visit_class
WARNING:toil.leader:D/u/job_ugwte        visit_class(rec[d], cls, op)
2018-07-25 23:06:29,872 - toil.leader - WARNING - D/u/job_ugwte        visit_class(rec[d], cls, op)
WARNING:toil.leader:D/u/job_ugwte      File "/Users/whlavina/pgap/venv2.7-pristine/lib/python2.7/site-packages/cwltool/pathmapper.py", line 48, in visit_class
2018-07-25 23:06:29,872 - toil.leader - WARNING - D/u/job_ugwte      File "/Users/whlavina/pgap/venv2.7-pristine/lib/python2.7/site-packages/cwltool/pathmapper.py", line 48, in visit_class
WARNING:toil.leader:D/u/job_ugwte        visit_class(rec[d], cls, op)
2018-07-25 23:06:29,872 - toil.leader - WARNING - D/u/job_ugwte        visit_class(rec[d], cls, op)
WARNING:toil.leader:D/u/job_ugwte      File "/Users/whlavina/pgap/venv2.7-pristine/lib/python2.7/site-packages/cwltool/pathmapper.py", line 51, in visit_class
2018-07-25 23:06:29,872 - toil.leader - WARNING - D/u/job_ugwte      File "/Users/whlavina/pgap/venv2.7-pristine/lib/python2.7/site-packages/cwltool/pathmapper.py", line 51, in visit_class
WARNING:toil.leader:D/u/job_ugwte        visit_class(d, cls, op)
2018-07-25 23:06:29,872 - toil.leader - WARNING - D/u/job_ugwte        visit_class(d, cls, op)
WARNING:toil.leader:D/u/job_ugwte      File "/Users/whlavina/pgap/venv2.7-pristine/lib/python2.7/site-packages/cwltool/pathmapper.py", line 46, in visit_class
2018-07-25 23:06:29,872 - toil.leader - WARNING - D/u/job_ugwte      File "/Users/whlavina/pgap/venv2.7-pristine/lib/python2.7/site-packages/cwltool/pathmapper.py", line 46, in visit_class
WARNING:toil.leader:D/u/job_ugwte        op(rec)
2018-07-25 23:06:29,872 - toil.leader - WARNING - D/u/job_ugwte        op(rec)
WARNING:toil.leader:D/u/job_ugwte      File "/Users/whlavina/pgap/venv2.7-pristine/lib/python2.7/site-packages/toil/cwl/cwltoil.py", line 334, in uploadFile
2018-07-25 23:06:29,872 - toil.leader - WARNING - D/u/job_ugwte      File "/Users/whlavina/pgap/venv2.7-pristine/lib/python2.7/site-packages/toil/cwl/cwltoil.py", line 334, in uploadFile
WARNING:toil.leader:D/u/job_ugwte        raise cwltool.errors.WorkflowException("File is missing: %s" % uf["location"])
2018-07-25 23:06:29,872 - toil.leader - WARNING - D/u/job_ugwte        raise cwltool.errors.WorkflowException("File is missing: %s" % uf["location"])
WARNING:toil.leader:D/u/job_ugwte    WorkflowException: File is missing: /Users/whlavina/pgap/pgap-2018-07-05.build2884/out_tmpdirInEt_Q/sequence_cache/asn_cache.idx
2018-07-25 23:06:29,872 - toil.leader - WARNING - D/u/job_ugwte    WorkflowException: File is missing: /Users/whlavina/pgap/pgap-2018-07-05.build2884/out_tmpdirInEt_Q/sequence_cache/asn_cache.idx
WARNING:toil.leader:D/u/job_ugwte    ERROR:toil.worker:Exiting the worker because of a failed job on host Wratkos-Mac-Pro.home
2018-07-25 23:06:29,872 - toil.leader - WARNING - D/u/job_ugwte    ERROR:toil.worker:Exiting the worker because of a failed job on host Wratkos-Mac-Pro.home
```

**Comment by jessebrennan** [comment]
@whlavina sure I'll take the logs! Thanks.

**Comment by whlavina** [comment]
The problem may lie in support for the `InitialWorkDirRequirement` feature. Here is a simple demo set of CWL files (no need for data or Docker) that is likely to be the same problem we are seeing:

# test.cwl
```
#!/usr/bin/env cwl-runner

cwlVersion: v1.0
class: Workflow

requirements:
  - class: SubworkflowFeatureRequirement

inputs: []

steps:
  directory_output_step:
    run: mkdir.cwl
    in: []
    out: [my_output]

  initial_work_dir_step:
    run: initial_work_dir.cwl
    in:
        my_input: directory_output_step/my_output
    out: [my_output]
 
outputs:
  my_final_output:
    type: Directory
    outputSource: initial_work_dir_step/my_output
```

# test.yaml
```
{}
```

# mkdir.cwl
```
cwlVersion: v1.0 
class: CommandLineTool

baseCommand: [bash, '-c', 'mkdir "$1" && touch "$1/my_file"', '-']

inputs:
  my_input:
    type: string
    default: my_dir
    inputBinding:
      position: 1

outputs:
  my_output:
    type: Directory
    outputBinding:
        glob: $(inputs.my_input)
```

# initial_work_dir.cwl
```
cwlVersion: v1.0
class: CommandLineTool

requirements:
  - class: InitialWorkDirRequirement
    listing:
      - entry: $(inputs.my_input)
        writable: False

baseCommand: 'true'

inputs:
  my_input:
    type: Directory
    inputBinding:
      prefix: -asn-cache

outputs:
  my_output:
    type: Directory
    outputBinding:
      glob: $(inputs.my_input.basename)  
```

**Comment by jessebrennan** [comment]
@whlavina thank you, this will be a big help.

**Comment by whlavina** [comment]
While the error message says `File is missing` and this is because the code expects a `file://`prefix (stripping 7 characters off the file path), there might be another underlying issue here regarding the handling of read vs read-write output. The synthetic example succeeds if you change the CWL to specify `writable: True`.

**Comment by mr-c** [comment]
This bug is no longer present in toil-cwl-runner 5.5.0 (but probably sooner)
