### ISSUE TITLE
`toilwdl.py` fails with AttributeError: 'Ast' object has no attribute 'source_string'

### ISSUE THREAD

**Issue by kghosesbg** [DataBiosphere/toil#2312]
Hi Folks!

I was trying to run `toilwdl.py` on [this workflow](https://dockstore.org/workflows/github.com/gatk-workflows/somatic-snvs-indels/gatk4-somatic-snvs-indels-discovery:master?tab=files) from dockstore. I get the following error:

```
python ~/Code/toil/src/toil/wdl/toilwdl.py mutect2.wdl mutect2.exome.inputs.json --dev_mode 2
```
[mutect2.wdl.txt](https://github.com/DataBiosphere/toil/files/2203488/mutect2.wdl.txt)
[mutect2.exome.inputs.json.txt](https://github.com/DataBiosphere/toil/files/2203489/mutect2.exome.inputs.json.txt)

```
Traceback (most recent call last):
  File "/Users/kghose/Code/toil/src/toil/wdl/toilwdl.py", line 145, in <module>
    main()
  File "/Users/kghose/Code/toil/src/toil/wdl/toilwdl.py", line 113, in main
    aWDL.create_tasks_dict(ast)
  File "/Users/kghose/Code/toil/src/toil/wdl/wdl_analysis.py", line 141, in create_tasks_dict
    self.parse_task(task)
  File "/Users/kghose/Code/toil/src/toil/wdl/wdl_analysis.py", line 164, in parse_task
    declaration_array.append(self.parse_task_declaration(declaration_subAST))
  File "/Users/kghose/Code/toil/src/toil/wdl/wdl_analysis.py", line 202, in parse_task_declaration
    var_type = self.parse_declaration_type(declaration_subAST.attr("type"))
  File "/Users/kghose/Code/toil/src/toil/wdl/wdl_analysis.py", line 637, in parse_declaration_type
    return typeAST.attr('innerType').source_string
AttributeError: 'Ast' object has no attribute 'source_string'
```

```
toil --version
3.17.0a1
```

This is  commit f6bb9fbcf82e23ef78c2f75999c63def16734062 from source.

Thanks!
-Kaushik

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/TOIL-322)
┆Issue Number: TOIL-322

**Comment by DailyDreaming** [comment]
You may be the first person to have run our wdl support and posted an issue.  Thanks for catching the bug!

I've made a fix at  #2315, plus a couple of others that should run the `GATK4 Mutect 2` workflow in the dockstore link provided.  It finished successfully on my machine at least.

Thanks for posting the issue!
