### ISSUE TITLE
`toil-cwl-runner` fails with TypeError: unhashable type: 'JobGraph'

### ISSUE THREAD

**Issue by kghosesbg** [DataBiosphere/toil#2313]
This CWL file (and simple input) 

`multi-out.cwl`
```
class: CommandLineTool
cwlVersion: v1.0
id: multi_out
baseCommand:
  - /bin/sh
inputs:
  - id: input
    type: int
    label: Number of files needed
outputs:
  - id: output
    type: 'File[]'
    outputBinding:
      glob: abc*
label: Create multiple files
arguments:
  - position: 0
    prefix: ''
    separate: false
    shellQuote: false
    valueFrom: script.sh
requirements:
  - class: ShellCommandRequirement
  - class: ResourceRequirement
    ramMin: 100
    coresMin: 1
  - class: DockerRequirement
    dockerPull: alpine
  - class: InitialWorkDirRequirement
    listing:
      - entryname: script.sh
        entry: |-
          $(
          "for V in $(seq 1 " + inputs.input + ")\n" +
          "do\n" +
          "  echo ${V} > abc.${V}.txt\n" +
          "done"
          )
  - class: InlineJavascriptRequirement
```

`input.yaml`
```
input: 4
```

runs fine on Rabix Executor and cwltool but fails on `toil-cwl-runner`.

```
(cwl) MacBook-Pro:001 kghose$ toil-cwl-runner multi-out.cwl inputs.yaml
DEBUG:past.translation:Running find_module: avro...
DEBUG:past.translation:Running load_module for avro...
DEBUG:past.translation:Autoconverting avro ...
DEBUG:past.translation:Running find_module: avro.schema...
DEBUG:past.translation:Running load_module for avro.schema...
DEBUG:past.translation:Autoconverting avro.schema ...
DEBUG:rdflib:RDFLib Version: 4.2.2
Resolved 'multi-out.cwl' to 'file:///Users/kghose/Work/cwl-examples/001/multi-out.cwl'
INFO:cwltool:Resolved 'multi-out.cwl' to 'file:///Users/kghose/Work/cwl-examples/001/multi-out.cwl'
WARNING:toil.batchSystems.singleMachine:Limiting maxCores to CPU count of system (4).
WARNING:toil.batchSystems.singleMachine:Limiting maxMemory to physically available memory (17179869184).
WARNING:toil.batchSystems.singleMachine:Limiting maxDisk to physically available disk (13166436352).
INFO:toil:Running Toil version 3.17.0a1-b'9f46ffc7442e56d9689579801fd9c3c151de40ff'.
INFO:toil.realtimeLogger:Real-time logging disabled
Traceback (most recent call last):
  File "/Users/kghose/miniconda2/envs/cwl/bin/toil-cwl-runner", line 11, in <module>
    load_entry_point('toil', 'console_scripts', 'toil-cwl-runner')()
  File "/Users/kghose/Code/toil/src/toil/cwl/cwltoil.py", line 1065, in main
    outobj = toil.start(wf1)
  File "/Users/kghose/Code/toil/src/toil/common.py", line 783, in start
    return self._runMainLoop(rootJobGraph)
  File "/Users/kghose/Code/toil/src/toil/common.py", line 1057, in _runMainLoop
    jobCache=self._jobCache).run()
  File "/Users/kghose/Code/toil/src/toil/leader.py", line 128, in __init__
    self.toilState = ToilState(jobStore, rootJob, jobCache=jobCache)
  File "/Users/kghose/Code/toil/src/toil/toilState.py", line 72, in __init__
    self._buildToilState(rootJob, jobStore, jobCache)
  File "/Users/kghose/Code/toil/src/toil/toilState.py", line 102, in _buildToilState
    self.updatedJobs.add((jobGraph, 0))
TypeError: unhashable type: 'JobGraph'
```

```
toil --version
3.17.0a1
```
 
Also fails on master (9f46ffc7442e56d9689579801fd9c3c151de40ff)

Thanks!
-Kaushik

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/TOIL-323)
┆Issue Number: TOIL-323

**Comment by DailyDreaming** [comment]
Interesting.  I just ran this and it seemed to complete successfully: 
[output.txt](https://github.com/DataBiosphere/toil/files/2217618/output.txt)

I'm running on `Ubuntu 18.04`, and building toil from source with this one-liner (to ensure we have the same dependencies with a fresh virtualenv):
`git clone https://github.com/DataBiosphere/toil.git && cd toil && virtualenv -p python2.7 venv && . venv/bin/activate && make prepare && make develop extras=[all]`

One other thought comes to mind, are you using `python 2.7`?

**Comment by kghosesbg** [comment]
@DailyDreaming - I think you caught me! I installed this on my Py3 environment. Toil doesn't run on Py3, right?

**Comment by DailyDreaming** [comment]
Nope, only python 2.7 currently. Though it should be python 3 soon!
