### ISSUE TITLE
CWL: --workdir should default to --tmpdir-prefix, if present

### ISSUE THREAD

**Issue by FarahZKhan** [DataBiosphere/toil#2354]
Hi, 
I am trying to run this [workflow](https://github.com/DataBiosphere/topmed-workflows/blob/develop/aligner/sbg-alignment-cwl/topmed-alignment.cwl) using cwltoil on a cloud instance as following: 
```
cwltoil --no-match-user --tmp-outdir-prefix=/CWLProv_workflow_testing/intermediate_temp/temp --tmpdir-prefix=/CWLProv_workflow_testing/intermediate_temp/temp topmed-workflows/aligner/sbg-alignment-cwl/topmed-alignment.cwl topmed-workflows/aligner/sbg-alignment-cwl/topmed-alignment.sample.json.new
```
Here is the error that I get: 

```
Traceback (most recent call last):
  File "/CWLProv_workflow_testing/toiltesting/bin/cwltoil", line 11, in <module>
    sys.exit(main())
  File "/CWLProv_workflow_testing/toiltesting/local/lib/python2.7/site-packages/toil/cwl/cwltoil.py", line 1204, in main
    outobj = toil.start(wf1)
  File "/CWLProv_workflow_testing/toiltesting/local/lib/python2.7/site-packages/toil/common.py", line 784, in start
    return self._runMainLoop(rootJobGraph)
  File "/CWLProv_workflow_testing/toiltesting/local/lib/python2.7/site-packages/toil/common.py", line 1059, in _runMainLoop
    jobCache=self._jobCache).run()
  File "/CWLProv_workflow_testing/toiltesting/local/lib/python2.7/site-packages/toil/leader.py", line 208, in run
    self.innerLoop()
  File "/CWLProv_workflow_testing/toiltesting/local/lib/python2.7/site-packages/toil/leader.py", line 539, in innerLoop
    self._gatherUpdatedJobs(updatedJobTuple)
  File "/CWLProv_workflow_testing/toiltesting/local/lib/python2.7/site-packages/toil/leader.py", line 496, in _gatherUpdatedJobs
    self.processFinishedJob(jobID, result, wallTime=wallTime)
  File "/CWLProv_workflow_testing/toiltesting/local/lib/python2.7/site-packages/toil/leader.py", line 807, in processFinishedJob
    self.jobStore.update(jobGraph)
  File "/CWLProv_workflow_testing/toiltesting/local/lib/python2.7/site-packages/toil/jobStores/fileJobStore.py", line 214, in update
    pickle.dump(job, f)
IOError: [Errno 28] No space left on device
```
I have an attached volume with ample disk space and have an XXlarge instance which has enough cores and memory. The issue is, despite using tmpdir prefixes cwltoil is not using these resources but is limited to the default 10G. 
I have read the documentations and could not find any way to redirect this computation to use these resources. 
cwltool on itself works fine when tmpdirs are assigned a location. 

I am not sure what's the solution of this issue. 
Any help will be much appreciated.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/TOIL-336)
┆Issue Number: TOIL-336

**Comment by FarahZKhan** [comment]
@mr-c Yes setting --workDir worked fine and I was able to run this workflow. 
Thanks a lot.

**Comment by DailyDreaming** [comment]
@mr-c Are there any problems left to address?  I'm inclined to close this.
