### ISSUE TITLE
KeyError: 'c3.4xlarge:0.45'

### ISSUE THREAD

**Issue by gzhang1986** [DataBiosphere/toil#2384]
Hi, I was trying to start a cluster with spot instances
`toil launch-cluster mytestcluster1 --leaderNodeType c3.4xlarge:0.45 --leaderStorage 200 --zone us-west-2a --keyPairName id_rsa.pub`
And I got this error:
`Traceback (most recent call last):
  File "/Users/xxx/xxx/venv/bin/toil", line 11, in <module>
    sys.exit(main())
  File "/Users/xxx/xxx/venv/lib/python2.7/site-packages/toil/utils/toilMain.py", line 35, in main
    module.main()
  File "/Users/xxx/xxx/venv/lib/python2.7/site-packages/toil/utils/toilLaunchCluster.py", line 157, in main
    azureStorageCredentials=config.azureStorageCredentials)
  File "/Users/xxx/xxx/venv/lib/python2.7/site-packages/toil/provisioners/aws/awsProvisioner.py", line 138, in launchCluster
    bdm = self._getBlockDeviceMapping(E2Instances[leaderNodeType], rootVolSize=leaderStorage)
KeyError: 'c3.4xlarge:0.45'
`
I am using 3.17.0. Thank you.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/TOIL-350)
┆Issue Number: TOIL-350

**Comment by DailyDreaming** [comment]
The leader node doesn't support spot instance pricing since if it goes down when the spot bid ends, you lose the entire cluster of instances.  Also, I'd explicitly specify the provisioner with `-p aws`.
