### ISSUE TITLE
This job was passed a promise that wasn't yet resolved when it ran.

### ISSUE THREAD

**Issue by Juke34** [DataBiosphere/toil#2499]
Hi,

I have experienced the same problem as described here #2212.
I'm using toil 3.18.0 (released on October 2nd) for launching a tool call `cactus`. I have open an issue in their repo (https://github.com/ComparativeGenomicsToolkit/cactus/issues/51) but I guess the problem is in fact linked to `toil`.

The error message I get is the following:

```
INFO:toil.leader:Job ended successfully: 'RunCactusPreprocessorThenProgressiveDown' w/A/job7Y0wzz
INFO:toil.leader:Finished toil run successfully.
Traceback (most recent call last):
  File "/sw/bioinfo/cactus/latest/bin/cactus", line 11, in <module>
    sys.exit(main())
  File "/sw/bioinfo/cactus/d2cae96/lib/python2.7/site-packages/cactus/progressive/cactus_progressive.py", line 500, in main
    halID = toil.start(RunCactusPreprocessorThenProgressiveDown(options, project, memory=configWrapper.getDefaultMemory()))
  File "/sw/bioinfo/cactus/d2cae96/lib/python2.7/site-packages/toil/common.py", line 784, in start
    return self._runMainLoop(rootJobGraph)
  File "/sw/bioinfo/cactus/d2cae96/lib/python2.7/site-packages/toil/common.py", line 1059, in _runMainLoop
    jobCache=self._jobCache).run()
  File "/sw/bioinfo/cactus/d2cae96/lib/python2.7/site-packages/toil/leader.py", line 239, in run
    return self.jobStore.getRootJobReturnValue()
  File "/sw/bioinfo/cactus/d2cae96/lib/python2.7/site-packages/toil/jobStores/abstractJobStore.py", line 218, in getRootJobReturnValue
    return safeUnpickleFromStream(fH)
  File "/sw/bioinfo/cactus/d2cae96/lib/python2.7/site-packages/toil/common.py", line 1360, in safeUnpickleFromStream
    return pickle.loads(string)
  File "/sw/bioinfo/cactus/d2cae96/lib/python2.7/site-packages/toil/job.py", line 1763, in __new__
    return cls._resolve(*args)
  File "/sw/bioinfo/cactus/d2cae96/lib/python2.7/site-packages/toil/job.py", line 1775, in _resolve
    value = safeUnpickleFromStream(fileHandle)
  File "/sw/bioinfo/cactus/d2cae96/lib/python2.7/site-packages/toil/common.py", line 1360, in safeUnpickleFromStream
    return pickle.loads(string)
  File "/sw/bioinfo/cactus/d2cae96/lib/python2.7/site-packages/toil/job.py", line 1763, in __new__
    return cls._resolve(*args)
  File "/sw/bioinfo/cactus/d2cae96/lib/python2.7/site-packages/toil/job.py", line 1775, in _resolve
    value = safeUnpickleFromStream(fileHandle)
  File "/sw/bioinfo/cactus/d2cae96/lib/python2.7/site-packages/toil/common.py", line 1360, in safeUnpickleFromStream
    return pickle.loads(string)
  File "/sw/bioinfo/cactus/d2cae96/lib/python2.7/site-packages/toil/job.py", line 1853, in __setstate__
    "this job as a child/follow-on of {jobName}.".format(jobName=jobName))
RuntimeError: This job was passed a promise that wasn't yet resolved when it ran. The job 'RunCactusPreprocessorThenProgressiveDown2' that fulfills this promise hasn't yet finished. This means that there aren't enough constraints to ensure the current job always runs after 'RunCactusPreprocessorThenProgressiveDown2'. Consider adding a follow-on indirection between this job and its parent, or adding this job as a child/follow-on of 'RunCactusPreprocessorThenProgressiveDown2'.
```

I have relaunched the command many times, and never succeeded to go through.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-62)
┆Issue Number: TOIL-62

**Comment by joelarmstrong** [comment]
I mentioned this on the other issue, but for the toil maintainers -- this may be an issue with either Cactus or Toil, not 100% sure yet. The error usually indicates that the job DAG doesn't correctly represent the data dependencies, and that a job has been run "too soon", before its input is ready. But note that in this case this is happening when getting the root job's return value, which implies all jobs have already completed. This is just a guess, but I think this might mean that toil's BatchSystem interface (GridEngine in this case) is marking a job as complete before it's been run. That or I've done something stupid in the Cactus job wiring, but this example seems to run fine elsewhere.

Has anyone running on GridEngine run into this before?

**Comment by DailyDreaming** [comment]
Is there a minimal working example of this?

**Comment by Juke34** [comment]
I have used the example provided by [cactus](https://github.com/ComparativeGenomicsToolkit/cactus) . I haven't seen anyone else with the same problem so I'm wondering if it could be hardware related. I use SGE 8.1.9 and I have tried with openmpi 1.10.7 and 2.1.2.

**Comment by phanikishore2** [comment]
@Juke34 Did you try running with --disableCaching . I also encountered similar issue on GridEngine.  --disableCaching seems to solved the issue.

**Comment by Juke34** [comment]
Thx @phanikishore2, I tried `--disableCaching` without success for me.

**Comment by ionox0** [comment]
Just fyi we are running into this issue on LSF 10.1 using Toil 3.19:

```
DEBUG:toil.jobStores.fileJobStore:Path to job store directory is '/work/bergerm1/MSK-ACCESS/ACCESS-Projects/07889_F/TDM1-1-1.1.13/tmp/jobstore-10e655d8-a4f0-11e9-95cf-ec0d9a7e8c22'.
Traceback (most recent call last):
  File "/home/johnsoni/virtualenvs/pipeline_1.1.13/lib/python2.7/site-packages/toil/worker.py", line 309, in workerScript
    job = Job._loadJob(jobGraph.command, jobStore)
  File "/home/johnsoni/virtualenvs/pipeline_1.1.13/lib/python2.7/site-packages/toil/job.py", line 918, in _loadJob
    return cls._unpickle(userModule, fileHandle, jobStore.config)
  File "/home/johnsoni/virtualenvs/pipeline_1.1.13/lib/python2.7/site-packages/toil/job.py", line 959, in _unpickle
    runnable = unpickler.load()
  File "/home/johnsoni/virtualenvs/pipeline_1.1.13/lib/python2.7/site-packages/toil/job.py", line 1763, in __new__
    return cls._resolve(*args)
  File "/home/johnsoni/virtualenvs/pipeline_1.1.13/lib/python2.7/site-packages/toil/job.py", line 1775, in _resolve
    value = safeUnpickleFromStream(fileHandle)
  File "/home/johnsoni/virtualenvs/pipeline_1.1.13/lib/python2.7/site-packages/toil/common.py", line 1351, in safeUnpickleFromStream
    return pickle.loads(string)
  File "/home/johnsoni/virtualenvs/pipeline_1.1.13/lib/python2.7/site-packages/toil/job.py", line 1763, in __new__
    return cls._resolve(*args)
  File "/home/johnsoni/virtualenvs/pipeline_1.1.13/lib/python2.7/site-packages/toil/job.py", line 1775, in _resolve
    value = safeUnpickleFromStream(fileHandle)
  File "/home/johnsoni/virtualenvs/pipeline_1.1.13/lib/python2.7/site-packages/toil/common.py", line 1351, in safeUnpickleFromStream
    return pickle.loads(string)
  File "/home/johnsoni/virtualenvs/pipeline_1.1.13/lib/python2.7/site-packages/toil/job.py", line 1853, in __setstate__
    "this job as a child/follow-on of {jobName}.".format(jobName=jobName))
RuntimeError: (RuntimeError(RuntimeError("This job was passed a promise that wasn't yet resolved when it ran. The job 'ResolveIndirect' that fulfills this promise hasn't yet finished. This means that there aren't enough constraints to ensure the current job always runs after 'ResolveIndirect'. Consider adding a follow-on indirection between this job and its parent, or adding this job as a child/follow-on of 'ResolveIndirect'.",), <class 'toil.job.Promise'>, ('file:/work/bergerm1/MSK-ACCESS/ACCESS-Projects/07889_F/TDM1-1-1.1.13/tmp/jobstore-10e655d8-a4f0-11e9-95cf-ec0d9a7e8c22', 'A/v/tmpPyllhR-registerPromise-stream')), <class 'toil.job.Promise'>, ('file:/work/bergerm1/MSK-ACCESS/ACCESS-Projects/07889_F/TDM1-1-1.1.13/tmp/jobstore-10e655d8-a4f0-11e9-95cf-ec0d9a7e8c22', 'S/M/tmpOnqVms-registerPromise-stream'))
ERROR:toil.worker:Exiting the worker because of a failed job on host jx02
WARNING:toil.jobGraph:Due to failure we are reducing the remaining retry count of job 'ResolveIndirect' 0/y/jobmIssd9 with ID 0/y/jobmIssd9 to 2
Traceback (most recent call last):
  File "/home/johnsoni/virtualenvs/pipeline_1.1.13/bin/_toil_worker", line 10, in <module>
    sys.exit(main())
  File "/home/johnsoni/virtualenvs/pipeline_1.1.13/lib/python2.7/site-packages/toil/worker.py", line 520, in main
    workerScript(jobStore, config, jobName, jobStoreID)
  File "/home/johnsoni/virtualenvs/pipeline_1.1.13/lib/python2.7/site-packages/toil/worker.py", line 432, in workerScript
    if job and jobGraph.remainingRetryCount == 0:
UnboundLocalError: local variable 'job' referenced before assignment
```

**Comment by ionox0** [comment]
My best guess is that polling for job exit status using `bsub` is not as reliable as using the `bwait` command, which is used by cwlexec:

https://github.com/IBMSpectrumComputing/cwlexec/blob/4409597e9a4e5a5cd5d9fe29073d48f83af2dc39/src/main/java/com/ibm/spectrumcomputing/cwl/exec/executor/lsf/LSFBwaitExecutorTask.java#L197

In this implementation, all CWL commands are prefixed with a `bwait` command which is used to monitor job status.

**Comment by adamnovak** [comment]
@ionox0 It could be that the CWL interpreter is not correctly marking the dependencies between the jobs it runs. If that's the case, simplifying the workflow might work around the problem.

I don't see why we should be taking the batch system's word for it that jobs complete successfully. In fact, @joelarmstrong, I don't think we are. A nonzero error code from the Toil command we dispatch to run the job doesn't translate into the job or even the job and all its chained successors having completed without throwing any exceptions, right? It just means Toil itself didn't crash.

The authoritative place to look for whether the job ran correctly is in the job store, right? If the job does succeed, the worker records that fact in the job store before returning. If it doesn't, it attaches a log to the job, which is how we get that "ended successfully/left a log file indicating failure" pair of messages when jobs fail, which we just fixed up in https://github.com/DataBiosphere/toil/pull/2729.

It looks like in both these cases, the file job store is being used. **Does the shared filesystem that the job store is on guarantee perfect, global, read-everyone's-previous-writes consistency?** This is a requirement for Toil to work correctly, but some shared filesystems used in cluster environments (specifically, any shared filesystems that allow reads to be fulfilled from a local cache without blocking to check for updates from other nodes first) don't promise it. If the worker writes a job's completion to the job store, and the leader can see it but the worker that runs the subsequent job can't, I think we could get into a situation like the one we see here. We would also expect it to be tough to replicate, because we'd have the cluster scheduler racing against the filesystem.

If we're sure the filesystem does guarantee real consistency, like a local filesystem would, we can try and dig into the scheduling logic, or look for problems in Cactus's or the CWL runner's dependency graphs.

**Comment by joelarmstrong** [comment]
Good point about the batch system not being the source of truth -- I looked and I don't see a path where a job specifically getting marked as completed early could cause a promise not to be fulfilled. NB that ResolveIndirect will probably be run by the leader's "local" batch system anyway, since it's part of `CWL_INTERNAL_JOBS`, assuming that functionality still works.

This specific issue seems like a CWL issue. Does it work if you restart the workflow from where you left off? If it doesn't work, then it seems a more likely (though not guaranteed) that it's a filesystem issue rather than a cwltoil wiring issue.

**Comment by ionox0** [comment]
We were previously using an Islion filesystem that may not have been consisten, however I believe that our current GPFS filesystem is indeed consistent. 

We also see this same issue after using `--restart`, which is confusing because we would expect that all nodes have been made consistent by this point.

**Comment by ionox0** [comment]
@DailyDreaming 

Given your initial fix for https://github.com/DataBiosphere/toil/issues/2212

And given that the error message in this case says:
```
RuntimeError: (RuntimeError(RuntimeError("This job was passed a promise that wasn't yet resolved when it ran. The job 'ResolveIndirect' that fulfills this promise hasn't yet finished. 
```

I have a hunch that the fix for this would be to add the `ResolveIndirect` job to the same array here:

https://github.com/DataBiosphere/toil/pull/2053/files#diff-ee480085fcce06066f78f98d1188e663R773

Which was what you did for the `CWLGather` job when the error message said:
```
RuntimeError: This job was passed a promise that wasn't yet resolved when it ran. The job 'CWLGather' that fulfills this promise hasn't yet finished.
```

Just a guess, will try this out on our end to try to confirm

**Comment by ionox0** [comment]
Upon returning to this, I placed a breakpoint in the code to see the state of the workflow, and came up with this representation of the rootJobGraph, in case that has a clue:

```
/home/johnsoni/virtualenvs/pipeline_1.1.13/lib/python2.7/site-packages/toil/common.py(803)restart()

-> return self._runMainLoop(rootJobGraph)

['JobException', 'rootJobGraph', 'self']

-> rootJobGraph

JobGraph( **{  
   'predecessorNumber':0,
   'startJobStoreID':None,
   '_preemptable':False,
   'errorJobStoreID':None,
   'remainingRetryCount':3,
   'filesToDelete':[  

   ],
   'checkpointFilesToDelete':None,
   'checkpoint':None,
   '_cores':1,
   'logJobStoreFileID':None,
   'jobStoreID':'n/Z/jobZ_Y8gA',
   'unitName':None,
   'chainedJobs':None,
   'services':[  

   ],
   'predecessorsFinished':set(   [  

   ]   ),
   'stack':[  
      [  
         JobNode( **         {  
            'jobStoreID':'K/S/job796XQW',
            '_config':None,
            'displayName':'JobGraph',
            'predecessorNumber':1,
            'unitName':None,
            '_preemptable':False,
            'jobName':'ResolveIndirect',
            '_disk':10737418240,
            '_cores':1,
            'command':None,
            '_memory':10737418240
         }         )
      ]
   ],
   '_config':None,
   'displayName':'JobGraph',
   'jobName':'CWLWorkflow',
   '_disk':10737418240,
   'command':None,
   '_memory':10737418240,
   'terminateJobStoreID':None
})
```

**Comment by DailyDreaming** [comment]
Should be fixed by: https://github.com/ionox0/toil/commit/09f248844fc360ead06bec79c40fa955ba14bf3b .  If this is still an issue, please reopen.

**Comment by stevekm** [comment]
I am getting what seems to be the same error message using Toil 5.5.0;

```
        [2021-09-30T12:33:31-0400] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---
        [2021-09-30T12:33:31-0400] [MainThread] [I] [toil] Running Toil version 5.5.0-b0ff5be051f2fd55352e00450b7848dcf8354a3b on host silo.
        [2021-09-30T12:33:31-0400] [MainThread] [I] [toil.worker] Working on job 'ResolveIndirect' kind-ResolveIndirect/instance-zwepivvi v4
        Traceback (most recent call last):
          File "/home/kellys5/projects/pluto-dev/test-toil-runs/conda/lib/python3.7/site-packages/toil/worker.py", line 376, in workerScript
            job = Job.loadJob(jobStore, jobDesc)
          File "/home/kellys5/projects/pluto-dev/test-toil-runs/conda/lib/python3.7/site-packages/toil/job.py", line 2251, in loadJob
            job = cls._unpickle(userModule, fileHandle, requireInstanceOf=Job)
          File "/home/kellys5/projects/pluto-dev/test-toil-runs/conda/lib/python3.7/site-packages/toil/job.py", line 1876, in _unpickle
            runnable = unpickler.load()
          File "/home/kellys5/projects/pluto-dev/test-toil-runs/conda/lib/python3.7/site-packages/toil/job.py", line 2857, in __new__
            return cls._resolve(*args)
          File "/home/kellys5/projects/pluto-dev/test-toil-runs/conda/lib/python3.7/site-packages/toil/job.py", line 2869, in _resolve
            value = safeUnpickleFromStream(fileHandle)
          File "/home/kellys5/projects/pluto-dev/test-toil-runs/conda/lib/python3.7/site-packages/toil/common.py", line 1468, in safeUnpickleFromStream
            return pickle.loads(string)
          File "/home/kellys5/projects/pluto-dev/test-toil-runs/conda/lib/python3.7/site-packages/toil/job.py", line 2857, in __new__
            return cls._resolve(*args)
          File "/home/kellys5/projects/pluto-dev/test-toil-runs/conda/lib/python3.7/site-packages/toil/job.py", line 2869, in _resolve
            value = safeUnpickleFromStream(fileHandle)
          File "/home/kellys5/projects/pluto-dev/test-toil-runs/conda/lib/python3.7/site-packages/toil/common.py", line 1468, in safeUnpickleFromStream
            return pickle.loads(string)
          File "/home/kellys5/projects/pluto-dev/test-toil-runs/conda/lib/python3.7/site-packages/toil/job.py", line 2944, in __setstate__
            raise RuntimeError(f"This job was passed promise {file_id} that wasn't yet resolved when it "
        RuntimeError: This job was passed promise files/no-job/file-cd8001b186194fd2a11cfdf50b9e51ad/stream that wasn't yet resolved when it ran. The job 'ResolveIndirect' kind-ResolveIndirect/instance-0mx6i51k v0 that fulfills this promise hasn't yet finished. This means that there aren't enough constraints to ensure the current job always runs after 'ResolveIndirect' kind-ResolveIndirect/instance-0mx6i51k v0. Consider adding a follow-on indirection between this job and its parent, or adding this job as a child/follow-on of 'ResolveIndirect' kind-ResolveIndirect/instance-0mx6i51k v0.
        [2021-09-30T12:33:31-0400] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host silo
```

This workflow runs just fine under `cwltool`. On Toil using LSF, it breaks.

**Comment by stevekm** [comment]
Also when I re-run the same exact pipeline instance (completely fresh run, no `--restart` or resumed job store or anything), it finished correctly. So, this error seems to be randomly occurring.

**Comment by EtiennePer** [comment]
Hello guys, I experienced the same issue  :

```SHELL
Traceback (most recent call last):
      File "/usr/local/lib/python3.9/site-packages/toil/worker.py", line 376, in workerScript
        job = Job.loadJob(jobStore, jobDesc)
      File "/usr/local/lib/python3.9/site-packages/toil/job.py", line 2251, in loadJob
        job = cls._unpickle(userModule, fileHandle, requireInstanceOf=Job)
      File "/usr/local/lib/python3.9/site-packages/toil/job.py", line 1876, in _unpickle
        runnable = unpickler.load()
      File "/usr/local/lib/python3.9/site-packages/toil/job.py", line 2857, in __new__
        return cls._resolve(*args)
      File "/usr/local/lib/python3.9/site-packages/toil/job.py", line 2869, in _resolve
        value = safeUnpickleFromStream(fileHandle)
      File "/usr/local/lib/python3.9/site-packages/toil/common.py", line 1468, in safeUnpickleFromStream
        return pickle.loads(string)
      File "/usr/local/lib/python3.9/site-packages/toil/job.py", line 2857, in __new__
        return cls._resolve(*args)
      File "/usr/local/lib/python3.9/site-packages/toil/job.py", line 2869, in _resolve
        value = safeUnpickleFromStream(fileHandle)
      File "/usr/local/lib/python3.9/site-packages/toil/common.py", line 1468, in safeUnpickleFromStream
        return pickle.loads(string)
      File "/usr/local/lib/python3.9/site-packages/toil/job.py", line 2944, in __setstate__
        raise RuntimeError(f"This job was passed promise {file_id} that wasn't yet resolved when it "
    RuntimeError: This job was passed promise files/no-job/file-c1c33b6b16e541c1b114eae1c161eaeb/stream that wasn't yet resolved when it ran. The job 'CWLGather' kind-CWLGather/instance-tzic00ra v0 that fulfills this promise hasn't yet finished. This means that there aren't enough constraints to ensure the current job always runs after 'CWLGather' kind-CWLGather/instance-tzic00ra v0. Consider adding a follow-on indirection between this job and its parent, or adding this job as a child/follow-on of 'CWLGather' kind-CWLGather/instance-tzic00ra v0.
    [2022-01-04T13:17:56+0000] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host 441781310d9a
```

I experienced this **only** while running through an NFS server, on both master node and worker nodes ... 

I feel like it happens only when there are a lot of I/O, I would say that the NFS caching may be the issue ... but I'm not so sure. 

- I'm running **toil 5.5.0** 

Thanks in advance for any help. 
Etienne
