### ISSUE TITLE
AttributeError: 'Expando' object has no attribute 'workers'

### ISSUE THREAD

**Issue by gijzelaerr** [DataBiosphere/toil#2532]
Both with  current master 044970558318d28654d2f79d1c9ccf31c4dfab81 and 3.18.0:
```
$ toil stats scratch/workflow/22/job
DEBUG:past.translation:Running find_module: avro...
DEBUG:past.translation:Running load_module for avro...
DEBUG:past.translation:Autoconverting avro ...
DEBUG:past.translation:Running find_module: avro.schema...
DEBUG:past.translation:Running load_module for avro.schema...
DEBUG:past.translation:Autoconverting avro.schema ...
Traceback (most recent call last):
  File "/home/gijs/Work/buis/.venv/bin/toil", line 11, in <module>
    load_entry_point('toil', 'console_scripts', 'toil')()
  File "/home/gijs/Work/toil/src/toil/utils/toilMain.py", line 35, in main
    module.main()
  File "/home/gijs/Work/toil/src/toil/utils/toilStats.py", line 604, in main
    collatedStatsTag = processData(jobStore.config, stats)
  File "/home/gijs/Work/toil/src/toil/utils/toilStats.py", line 554, in processData
    worker = [_f for _f in stats.workers if _f]
AttributeError: 'Expando' object has no attribute 'workers'
```

**Comment by gijzelaerr** [comment]
starting the workflow with 
`$ toil-cwl-runner --jobStore=scratch/workflow/22/job --workDir=scratch/workflow/22/work workflow.cwl job.yaml`

and workflow looks like:
```
cwlVersion: v1.0
class: CommandLineTool
baseCommand: sleep

inputs:
  seconds:
    type: int
    inputBinding:
      position: 1

outputs: {}
```

**Comment by gijzelaerr** [comment]
looks related to https://github.com/DataBiosphere/toil/issues/2188

i don't get it, I thought I had this working. Maybe the `workers` en `jobs` fields are not writting to the config with such a simple workflow.

**Comment by gijzelaerr** [comment]
ah wait, this CWL file only has one step, that seems to be the problem.
