### ISSUE TITLE
Toil 3.18.0, Python 3 and --stats

### ISSUE THREAD

**Issue by gijzelaerr** [DataBiosphere/toil#2564]
If I run `python3 toil-cwl-runner --stats sleep_workflow.cwl job.json` i get:
```
Traceback (most recent call last):
  File "/Users/gijs/Work/buis/.venv/bin/toil-cwl-runner", line 10, in <module>
    sys.exit(main())
  File "/Users/gijs/Work/buis/.venv/lib/python3.7/site-packages/toil/cwl/cwltoil.py", line 1220, in main
    outobj = toil.start(wf1)
  File "/Users/gijs/Work/buis/.venv/lib/python3.7/site-packages/toil/common.py", line 758, in start
    self.writePIDFile()
  File "/Users/gijs/Work/buis/.venv/lib/python3.7/site-packages/toil/common.py", line 1086, in writePIDFile
    f.write(str(os.getpid()))
TypeError: a bytes-like object is required, not 'str'
```
If I change the `str()` to a `bytes()`: I get:
```
Traceback (most recent call last):
  File "/Users/gijs/Work/buis/.venv/bin/toil-cwl-runner", line 10, in <module>
    sys.exit(main())
  File "/Users/gijs/Work/buis/.venv/lib/python3.7/site-packages/toil/cwl/cwltoil.py", line 1220, in main
    outobj = toil.start(wf1)
  File "/Users/gijs/Work/buis/.venv/lib/python3.7/site-packages/toil/common.py", line 784, in start
    return self._runMainLoop(rootJobGraph)
  File "/Users/gijs/Work/buis/.venv/lib/python3.7/site-packages/toil/common.py", line 1059, in _runMainLoop
    jobCache=self._jobCache).run()
  File "/Users/gijs/Work/buis/.venv/lib/python3.7/site-packages/toil/leader.py", line 124, in __init__
    self.toilState = ToilState(jobStore, rootJob, jobCache=jobCache)
  File "/Users/gijs/Work/buis/.venv/lib/python3.7/site-packages/toil/toilState.py", line 72, in __init__
    self._buildToilState(rootJob, jobStore, jobCache)
  File "/Users/gijs/Work/buis/.venv/lib/python3.7/site-packages/toil/toilState.py", line 102, in _buildToilState
    self.updatedJobs.add((jobGraph, 0))
TypeError: unhashable type: 'JobGraph'
```

**Comment by gijzelaerr** [comment]
This is on OS X with Python 3.7, can't reproduce this on Ubuntu 18.04 with Python 3.6

**Comment by gijzelaerr** [comment]
Yes, it is a python 3.7 issue.

**Comment by gijzelaerr** [comment]
This issue seems to be solved in the current master
