### ISSUE TITLE
toil.batchSystems.singleMachine:Got exit code 1 (indicating failure) 

### ISSUE THREAD

**Issue by dreamrororo20** [DataBiosphere/toil#2588]
exmaple:

```
from toil.common import Toil
from toil.job import Job

class HelloWorld(Job):
    def __init__(self, message):
        Job.__init__(self,  memory="2G", cores=2, disk="3G")
        self.message = message

    def run(self, fileStore):
        return "Hello, world!, here's a message: %s" % self.message

if __name__=="__main__":
    options = Job.Runner.getDefaultOptions("./toilWorkflowRun")
    options.logLevel = "OFF"
    options.clean = "always"

    hello_job = HelloWorld("Woot")

    with Toil(options) as toil:
        print(toil.start(hello_job))
```

Log:

```
DEBUG:toil.resource:Discovering real name of module
DEBUG:toil.resource:Module dir is /home/frank/test
WARNING:toil.batchSystems.singleMachine:Limiting maxCores to CPU count of system (32).
WARNING:toil.batchSystems.singleMachine:Limiting maxMemory to physically available memory (236100448256).
WARNING:toil.batchSystems.singleMachine:Limiting maxDisk to physically available disk (18252824576).
INFO:toil:Running Toil version 3.19.0-0feb1d4d1b4fc66062fc4dbc5d8f7fb046df39e6.
INFO:toil.leader:Issued job 'HelloWorld' k/m/job1BT60S with job batch system ID: 0 and cores: 2, disk: 3.0 G, and memory: 2.0 G
DEBUG:toil.jobStores.fileJobStore:Path to job store directory is '/home/frank/test/toilWorkflowRun'.
ERROR:toil.batchSystems.singleMachine:Got exit code 1 (indicating failure) from job _toil_worker HelloWorld file:/home/frank/test/toilWorkflowRun k/m/job1BT60S.
WARNING:toil.leader:Job failed with exit value 1: 'HelloWorld' k/m/job1BT60S
WARNING:toil.leader:No log file is present, despite job failing: 'HelloWorld' k/m/job1BT60S
WARNING:toil.jobGraph:Due to failure we are reducing the remaining retry count of job 'HelloWorld' k/m/job1BT60S with ID k/m/job1BT60S to 1
INFO:toil.leader:Issued job 'HelloWorld' k/m/job1BT60S with job batch system ID: 1 and cores: 2, disk: 3.0 G, and memory: 2.0 G
DEBUG:toil.jobStores.fileJobStore:Path to job store directory is '/home/frank/test/toilWorkflowRun'.
ERROR:toil.batchSystems.singleMachine:Got exit code 1 (indicating failure) from job _toil_worker HelloWorld file:/home/frank/test/toilWorkflowRun k/m/job1BT60S.
WARNING:toil.leader:Job failed with exit value 1: 'HelloWorld' k/m/job1BT60S
WARNING:toil.leader:No log file is present, despite job failing: 'HelloWorld' k/m/job1BT60S
WARNING:toil.jobGraph:Due to failure we are reducing the remaining retry count of job 'HelloWorld' k/m/job1BT60S with ID k/m/job1BT60S to 0
WARNING:toil.leader:Job 'HelloWorld' k/m/job1BT60S with ID k/m/job1BT60S is completely failed
INFO:toil.leader:Finished toil run with 1 failed jobs.
INFO:toil.leader:Failed jobs at end of the run: 'HelloWorld' k/m/job1BT60S
INFO:toil.common:Successfully deleted the job store: FileJobStore(/home/frank/test/toilWorkflowRun)
Traceback (most recent call last):
  File "test_toil.py", line 21, in <module>
    toil.start(hello_job)
  File "/usr/lib/python2.7/site-packages/toil/common.py", line 771, in start
    return self._runMainLoop(rootJobGraph)
  File "/usr/lib/python2.7/site-packages/toil/common.py", line 1044, in _runMainLoop
    jobCache=self._jobCache).run()
  File "/usr/lib/python2.7/site-packages/toil/leader.py", line 245, in run
    raise FailedJobsException(self.config.jobStore, self.toilState.totalFailedJobs, self.jobStore)
toil.leader.FailedJobsException
```

**Comment by dreamrororo20** [comment]
i found remove /home/frank/test/__init__.py , it's ok

**Comment by adamnovak** [comment]
OK, if removing `__init__.py` fixed it, I will go ahead and close this.

**Comment by luisacusick** [comment]
Hi! I am having a similar error; can you explain what the solution is? Is it really just removing the file called __init__.py?

**Comment by adamnovak** [comment]
I don't think this issue has a general solution for its previous title of `toil.batchSystems.singleMachine:Got exit code 1 (indicating failure)`. I've renamed it to something more specific.

If your problem is that your workflow script is in a directory with an __init__.py, and it isn't working, then getting rid of the __init__.py (i.e. making the workflow script not part of any module) might fix it. Especially if that directory that is the module is also where you are trying to put your job store directory, and also your working directory when trying to run the workflow.

I know that you *can* have workflows be part of modules ([toil-vg](https://github.com/vgteam/toil-vg) is one example), but in that case we generally want the module to be installed into a virtualenv in order for Toil to be able to pack it up and send it to the workers.
