### ISSUE TITLE
StorageDataError: BotoClientError while running cactus with toil on AWS

### ISSUE THREAD

**Issue by xieduo7** [DataBiosphere/toil#2640]
Hi, When I ran cactus on aws with toli I got this error.
```
b98811ab-e0da-4f05-96eb-c73f2b7a6029    Running command catchsegv 'halAppendCactusSubtree' 'tmppV4nPw.tmp' 'tmpnLyLBU.tmp' '(gorilla_chimp_human:0.009693,Pongo_abelii:0.01894)great_ape;' 'tmp_alignment.hal' '--outgroups' 'Macaca_mulatta'
b98811ab-e0da-4f05-96eb-c73f2b7a6029    WARNING:toil.fileStore:LOG-TO-MASTER: Job used more disk than requested. Consider modifying the user script to avoid the chance of failure due to incorrectly requested resources. Job 80f184e6-cd91-44d7-bd6c-1579e4534a22 used 2294.54% (42.7 GB [45890854912B] used, 1.9 GB [2000000000B] requested) at the end of its run.
b98811ab-e0da-4f05-96eb-c73f2b7a6029    Traceback (most recent call last):
b98811ab-e0da-4f05-96eb-c73f2b7a6029      File "/usr/local/lib/python2.7/dist-packages/toil/worker.py", line 314, in workerScript
b98811ab-e0da-4f05-96eb-c73f2b7a6029        job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore)
b98811ab-e0da-4f05-96eb-c73f2b7a6029      File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 1351, in _runner
b98811ab-e0da-4f05-96eb-c73f2b7a6029        returnValues = self._run(jobGraph, fileStore)
b98811ab-e0da-4f05-96eb-c73f2b7a6029      File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 1296, in _run
b98811ab-e0da-4f05-96eb-c73f2b7a6029        return self.run(fileStore)
b98811ab-e0da-4f05-96eb-c73f2b7a6029      File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 1480, in run
b98811ab-e0da-4f05-96eb-c73f2b7a6029        rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
b98811ab-e0da-4f05-96eb-c73f2b7a6029      File "/tmp/tmplTXg25/1cd9814280973785960266b6bfe38b8a/cactus/progressive/cactus_progressive.py", line 302, in exportHal
b98811ab-e0da-4f05-96eb-c73f2b7a6029        halFastaPath = job.fileStore.readGlobalFile(experiment.getHalFastaID())
b98811ab-e0da-4f05-96eb-c73f2b7a6029      File "/usr/local/lib/python2.7/dist-packages/toil/fileStore.py", line 1661, in readGlobalFile
b98811ab-e0da-4f05-96eb-c73f2b7a6029        self.jobStore.readFile(fileStoreID, localFilePath, symlink=symlink)
b98811ab-e0da-4f05-96eb-c73f2b7a6029      File "/usr/local/lib/python2.7/dist-packages/toil/jobStores/aws/jobStore.py", line 563, in readFile
b98811ab-e0da-4f05-96eb-c73f2b7a6029        info.download(localFilePath)
b98811ab-e0da-4f05-96eb-c73f2b7a6029      File "/usr/local/lib/python2.7/dist-packages/toil/jobStores/aws/jobStore.py", line 1152, in download
b98811ab-e0da-4f05-96eb-c73f2b7a6029        headers=headers)
b98811ab-e0da-4f05-96eb-c73f2b7a6029      File "/usr/local/lib/python2.7/dist-packages/boto/s3/key.py", line 1724, in get_contents_to_filename
b98811ab-e0da-4f05-96eb-c73f2b7a6029        response_headers=response_headers)
b98811ab-e0da-4f05-96eb-c73f2b7a6029      File "/usr/local/lib/python2.7/dist-packages/boto/s3/key.py", line 1662, in get_contents_to_file
b98811ab-e0da-4f05-96eb-c73f2b7a6029        response_headers=response_headers)
b98811ab-e0da-4f05-96eb-c73f2b7a6029      File "/usr/local/lib/python2.7/dist-packages/boto/s3/key.py", line 1494, in get_file
b98811ab-e0da-4f05-96eb-c73f2b7a6029        query_args=None)
b98811ab-e0da-4f05-96eb-c73f2b7a6029      File "/usr/local/lib/python2.7/dist-packages/boto/s3/key.py", line 1562, in _get_file_internal
b98811ab-e0da-4f05-96eb-c73f2b7a6029        '%s' % fp.name)
b98811ab-e0da-4f05-96eb-c73f2b7a6029    StorageDataError: BotoClientError: Out of space for destination file /var/lib/toil/toil-e7178a87-50ae-43c0-8566-220a6258b0d6-8bd426d6-2a4b-445d-98c7-16e9bb4ab5c8/tmpFahPVx/09352ccc-2f54-4ad6-af6a-2c6657f046d5/tmpRR17mN.tmp
b98811ab-e0da-4f05-96eb-c73f2b7a6029    ERROR:toil.worker:Exiting the worker because of a failed job on host ip-10-0-51-94.ec2.internal
```
Was the leader machine out of space? or Was the worker  out of space?
What's more, how can I modify the defaultdisk  when I restart a job?

Thank you!

**Comment by adamnovak** [comment]
To me that looks like your worker machine ran out of disk, not the leader. Unless you are running on just a single machine which happens to be in AWS, in which case the worker machine is the leader machine.

You can set the default disk space requirement with the `--defaultDisk` option.

```
  --defaultDisk INT     The default amount of disk space to dedicate a job.
                        Only applicable to jobs that do not specify an
                        explicit value for this requirement. Standard suffixes
                        like K, Ki, M, Mi, G or Gi are supported. Default is
                        2.0 Gi
```

It definitely does look like it is running this job with the default, which happens to be very inadequate. It's probably a Cactus bug that it can't figure out a sufficient disk requirement value on its own.

**Comment by xieduo7** [comment]
@adamnovak 
Thank you, Adam ! 
I restarted this job and added `--defaultDisk` to the command.
```
TOIL_AWS_AMI=ami-aff944d5 nohup cactus --configFile primate_progressive_config.xml --stats --nodeTypes c4.8xlarge:1.0,r4.8xlarge --minNodes 0,0 --maxNodes 70,4 --defaultDisk 50G --provisioner aws --batchSystem mesos --metrics aws:us-east-1:primate-jobstore-xiaoyu seqFile_ensembl20190410.txt s3://primate-out/cactus-xiaoyu.hal --logFile primate_20190421.log --restart >cactus0421.log 2>&1 &
```
But the requested `disk` didn't change:
```
INFO:toil.leader:Issued job 'exportHal' b98811ab-e0da-4f05-96eb-c73f2b7a6029 with job batch system ID: 0 and cores: 1, disk: 1.9 G, and memory: 32.0 G
```
How can I change the requested disk when I restart the job?
Thank you!
Best,
Duo

**Comment by xieduo7** [comment]
@adamnovak 
Hi Adam,
I have sloved this problem by adding `--nodeStorage 100 ` to command. And this indeed the worker machine was out of desk.
```
TOIL_AWS_AMI=ami-aff944d5 nohup cactus --configFile primate_progressive_config.xml --stats --nodeTypes c4.8xlarge:0.6,r4.8xlarge --minNodes 0,0 --maxNodes 70,4 --nodeStorage 100 --defaultDisk 50G --provisioner aws --batchSystem mesos --metrics aws:us-east-1:primate-jobstore-xiaoyu seqFile_ensembl20190410.txt s3://primate-out/cactus-xiaoyu.hal --logFile primate_20190423.log --restart >cactus0423.log 2>&1 &
```
Thank you!

**Comment by adamnovak** [comment]
I don't believe that you can change the disk allocation of a failed job when you `--restart` by adjusting the `--defaultDisk`. It is only going to apply to newly created jobs, not jobs that are already in the job store waiting to run. You would have to start over.

Upping the storage space on the nodes is going to help because jobs are allowed to opportunistically exceed their requirements, if resources are available. So even though the job uses more than the 2 GB it claims to, there's no failure if the machine has the space available. But you still will want to set `--defaultDisk` to how much disk the jobs will actually use, to avoid over-scheduling the node if enough jobs become available to fill it up.

Since you say you've solved your problem, I am going to close this issue.
