### ISSUE TITLE
Error in Mesos batch system when killing tasks

### ISSUE THREAD

**Issue by arostamianfar** [DataBiosphere/toil#2655]
Mesos throws an error when trying to kill tasks (when setting `maxJobDuration`). [stack trace below]. It appears that pymesos does not [take the `value` from the dict](https://github.com/douban/pymesos/blob/master/pymesos/executor.py#L158) like it does with other methods ([example](https://github.com/douban/pymesos/blob/master/pymesos/executor.py#L150)).

@adamnovak can you confirm if this is indeed a bug on the pymesos side? If so, I can file a bug and/or send a PR on their end.

In any case, I think we can add a workaround on our end to extract the `value` until/if pymesos fixes the issue. Something like this in [here](https://github.com/DataBiosphere/toil/blob/master/src/toil/batchSystems/mesos/executor.py#L101) will work for now: `if isinstance(taskId, dict): taskId = taskId['value']`

Stack trace:
```
[10.0.129.75] out: WARNING:toil.batchSystems.mesos.batchSystem:Executor: DEBUG:toil.batchSystems.mesos.executor:Event: {u'type': u'KILL', u'kill': {u'task_id': {u'value': u'10'}}}
[10.0.129.75] out: WARNING:toil.batchSystems.mesos.batchSystem:Executor: ERROR:pymesos.process:Failed to process event
[10.0.129.75] out: WARNING:toil.batchSystems.mesos.batchSystem:Executor: Traceback (most recent call last):
[10.0.129.75] out: WARNING:toil.batchSystems.mesos.batchSystem:Executor:   File "/usr/local/lib/python2.7/dist-packages/pymesos/process.py", line 194, in read
[10.0.129.75] out: WARNING:toil.batchSystems.mesos.batchSystem:Executor:     self._callback.process_event(event)
[10.0.129.75] out: WARNING:toil.batchSystems.mesos.batchSystem:Executor:   File "/usr/local/lib/python2.7/dist-packages/pymesos/process.py", line 274, in process_event
[10.0.129.75] out: WARNING:toil.batchSystems.mesos.batchSystem:Executor:     self.on_event(event)
[10.0.129.75] out: WARNING:toil.batchSystems.mesos.batchSystem:Executor:   File "/usr/local/lib/python2.7/dist-packages/toil/batchSystems/mesos/executor.py", line 296, in patched_on_event
[10.0.129.75] out: WARNING:toil.batchSystems.mesos.batchSystem:Executor:     old_on_event(event)
[10.0.129.75] out: WARNING:toil.batchSystems.mesos.batchSystem:Executor:   File "/usr/local/lib/python2.7/dist-packages/pymesos/executor.py", line 116, in on_event
[10.0.129.75] out: WARNING:toil.batchSystems.mesos.batchSystem:Executor:     func(event)
[10.0.129.75] out: WARNING:toil.batchSystems.mesos.batchSystem:Executor:   File "/usr/local/lib/python2.7/dist-packages/pymesos/executor.py", line 159, in on_kill
[10.0.129.75] out: WARNING:toil.batchSystems.mesos.batchSystem:Executor:     self.executor.killTask(self, self._dict_cls(task_id))
[10.0.129.75] out: WARNING:toil.batchSystems.mesos.batchSystem:Executor:   File "/usr/local/lib/python2.7/dist-packages/toil/batchSystems/mesos/executor.py", line 101, in killTask
[10.0.129.75] out: WARNING:toil.batchSystems.mesos.batchSystem:Executor:     pid = self.runningTasks[taskId]
[10.0.129.75] out: WARNING:toil.batchSystems.mesos.batchSystem:Executor: TypeError: unhashable type: 'Dict'
```

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-353)
┆Issue Number: TOIL-353

**Comment by adamnovak** [comment]
I think this is our bug. In other places where we handle task IDs like [here](https://github.com/DataBiosphere/toil/blob/a8252277ff814e7bee0971139c2344f88e44b644/src/toil/batchSystems/mesos/executor.py#L175) we are responsible for pulling out the value ourselves. We neglected to do that here.

We need to fix this, and probably to add a test for maxJobDuration with Mesos.

**Comment by DailyDreaming** [comment]
Looks like this was fixed by: https://github.com/DataBiosphere/toil/pull/2661  Please reopen if this is not the case.
