### ISSUE TITLE
DeadlockException incorrectly thrown using SLURM

### ISSUE THREAD

**Issue by lparsons** [DataBiosphere/toil#2663]
I seem to have problems with a Deadlock Exception being thrown when running cactus workflows on our shared SLURM cluster (see https://github.com/ComparativeGenomicsToolkit/cactus/issues/78).

I believe that somehow toil isn't capturing the list of running and issued jobs. In the most recent case, I could see that cactus had issued up to job number `514`. Toil had submitted jobs to SLURM up to job number `444` (meaning jobs `445` - `514` were *issued* by cactus, but not yet in the SLURM queue for some reason. Also, there were a number of jobs (`427` - `444`) in the SLURM queue, but waiting to be exectued at the time the `DeadlockException` was thrown. See logs and SLURM queue below.

Any help in tracking this down would be appreciated. I'm happy to work on a PR, but I don't quite have a full understanding of how toil manages the jobs and detects the Deadlocks just yet.

This is using `toil==3.19.0`, btw. Happy to try out other versions (or unreleased patches) if that will help.

Most recent log message from cactus regarding submitted jobs:
```
INFO:toil.leader:Issued job 'CactusReferenceRecursion2' V/G/jobkNS6oh with job batch system ID: 514 and cores: 1, disk: 2.0 G, and memory: 9.4 G
```

Slurm queue shortly after Deadlock Exception:
```
             JOBID PARTITION                           NAME     USER ST  NODES  CPUS MIN_MEMORY       TIME     NODELIST(REASON)         PRIORITY          SUBMIT_TIME           START_TIME  TIME_LEFT        QOS
          23526506       all                   toil_job_427 lparsons PD      1     1       700M       0:00           (Priority)             4229  2019-05-06T16:28:19                  N/A 1-00:00:00      short
          23526507       all                   toil_job_428 lparsons PD      1     1       700M       0:00           (Priority)             4229  2019-05-06T16:28:19                  N/A 1-00:00:00      short
          23526509       all                   toil_job_429 lparsons PD      1     1       700M       0:00           (Priority)             4229  2019-05-06T16:28:20                  N/A 1-00:00:00      short
          23526510       all                   toil_job_430 lparsons PD      1     1       700M       0:00           (Priority)             4229  2019-05-06T16:28:48                  N/A 1-00:00:00      short
          23526511       all                   toil_job_431 lparsons PD      1     1       700M       0:00           (Priority)             4229  2019-05-06T16:28:48                  N/A 1-00:00:00      short
          23526512       all                   toil_job_432 lparsons PD      1     1       700M       0:00           (Priority)             4229  2019-05-06T16:28:50                  N/A 1-00:00:00      short
          23526514       all                   toil_job_433 lparsons PD      1     1       700M       0:00           (Priority)             4229  2019-05-06T16:29:19                  N/A 1-00:00:00      short
          23526515       all                   toil_job_434 lparsons PD      1     1       700M       0:00           (Priority)             4229  2019-05-06T16:29:19                  N/A 1-00:00:00      short
          23526517       all                   toil_job_435 lparsons PD      1     1       700M       0:00           (Priority)             4229  2019-05-06T16:29:26                  N/A 1-00:00:00      short
          23526519       all                   toil_job_436 lparsons PD      1     1       700M       0:00           (Priority)             4229  2019-05-06T16:29:49                  N/A 1-00:00:00      short
          23526520       all                   toil_job_437 lparsons PD      1     1       700M       0:00           (Priority)             4229  2019-05-06T16:29:49                  N/A 1-00:00:00      short
          23526521       all                   toil_job_438 lparsons PD      1     1       700M       0:00           (Priority)             4229  2019-05-06T16:29:50                  N/A 1-00:00:00      short
          23526523       all                   toil_job_439 lparsons PD      1     1       700M       0:00           (Priority)             4229  2019-05-06T16:30:20                  N/A 1-00:00:00      short
          23526524       all                   toil_job_440 lparsons PD      1     1       700M       0:00           (Priority)             4229  2019-05-06T16:30:20                  N/A 1-00:00:00      short
          23526525       all                   toil_job_441 lparsons PD      1     1       700M       0:00           (Priority)             4229  2019-05-06T16:30:25                  N/A 1-00:00:00      short
          23526528       all                   toil_job_442 lparsons PD      1     1       700M       0:00           (Priority)             4229  2019-05-06T16:30:50                  N/A 1-00:00:00      short
          23526529       all                   toil_job_443 lparsons PD      1     1       700M       0:00           (Priority)             4229  2019-05-06T16:30:50                  N/A 1-00:00:00      short
          23526530       all                   toil_job_444 lparsons PD      1     1       700M       0:00           (Priority)             4229  2019-05-06T16:30:50                  N/A 1-00:00:00      short
          23525316       all                     toil_job_5 lparsons  R      1     1     95367M    1:12:42        della-r2c4n14             4230  2019-05-06T14:54:09  2019-05-06T15:19:23   22:47:18      short
          23525179       all                     toil_job_2 lparsons  R      1     1     95367M    1:39:06         della-r2c3n5             4230  2019-05-06T14:31:17  2019-05-06T14:52:59   22:20:54      short
```

Exception:
```
INFO:toil.leader:Issued job 'CactusReferenceRecursion2' V/G/jobkNS6oh with job batch system ID: 514 and cores: 1, disk: 2.0 G, and memory: 9.4 G
INFO:toil.leader:Job ended successfully: 'CactusReferenceWrapper' k/k/job7kXNgW
INFO:toil.leader:Job ended successfully: 'CactusReferenceWrapper' 8/f/job0ScWfo
INFO:toil.leader:Job ended successfully: 'CactusReferenceWrapper' n/w/job5abkek
INFO:toil.leader:Job ended successfully: 'CactusReferenceWrapper' K/y/job6UnpLD
INFO:toil.leader:Job ended successfully: 'CactusReferenceWrapper' Y/H/jobZ4XAwC
INFO:toil.leader:Job ended successfully: 'CactusReferenceWrapper' Z/7/jobQcgqkx
INFO:toil.leader:Job ended successfully: 'CactusReferenceWrapper' I/m/jobgYDdUI
INFO:toil.leader:Job ended successfully: 'CactusReferenceWrapper' C/H/job55r7qn
INFO:toil.leader:Job ended successfully: 'CactusReferenceWrapper' u/x/job5wHD7o
INFO:toil.leader:Job ended successfully: 'CactusReferenceWrapper' V/l/jobiv4R6L
INFO:toil.leader:Job ended successfully: 'CactusReferenceWrapper' G/h/jobHCKiQ4
INFO:toil.leader:Job ended successfully: 'CactusReferenceWrapper' h/X/joboXcjfg
INFO:toil.leader:Reissued any over long jobs
Traceback (most recent call last):
  File "/home/lparsons/miniconda3/envs/cactus/bin/cactus", line 11, in <module>
    load_entry_point('progressiveCactus', 'console_scripts', 'cactus')()
  File "/tigress/lparsons/kocher_lab/cactus/src/cactus/progressive/cactus_progressive.py", line 477, in main
    halID = toil.restart()
  File "/home/lparsons/miniconda3/envs/cactus/lib/python2.7/site-packages/toil/common.py", line 803, in restart
    return self._runMainLoop(rootJobGraph)
  File "/home/lparsons/miniconda3/envs/cactus/lib/python2.7/site-packages/toil/common.py", line 1044, in _runMainLoop
    jobCache=self._jobCache).run()
  File "/home/lparsons/miniconda3/envs/cactus/lib/python2.7/site-packages/toil/leader.py", line 211, in run
    self.innerLoop()
  File "/home/lparsons/miniconda3/envs/cactus/lib/python2.7/site-packages/toil/leader.py", line 556, in innerLoop
    self.checkForDeadlocks()
  File "/home/lparsons/miniconda3/envs/cactus/lib/python2.7/site-packages/toil/leader.py", line 588, in checkForDeadlocks
    raise DeadlockException("The system is service deadlocked - all %d running jobs are active services" % totalRunningJobs)
toil.leader.DeadlockException
```

**Comment by adamnovak** [comment]
It looks like the problem is that the service jobs are running but the work that uses them is stuck in the Slurm queue, maybe behind other people's jobs or maybe behind the service jobs themselves.

Toil looks and sees that none of the jobs that use the services are actually starting, assumes it is because they are all actually waiting on the services to finish (which will never happen), and that your cluster is too small for your workload, and bails out to avoid a possible deadlock.

The workaround is to know your cluster is genuinely big enough, and then set `--deadlockWait` to a high enough number of seconds that the check never happens.

I'm not sure how we fix this properly if we can't tell the difference between jobs being stuck in queue behind other people's jobs and the cluster actually being permanently too small.
