### ISSUE TITLE
OSError: [Errno 24] Too many open files

### ISSUE THREAD

**Issue by lac2208** [DataBiosphere/toil#2687]
Hello, 

I'm using toil v. 3.14 while attempting to align 6 bird genomes(~1.1 Gb each) with cactus on a PBS cluster (using --batchsystem Torque and --binariesMode local). 

After many successful steps in my own run, the run end up with  an error related to the subprocess.py function detecting to many open files. Is there a way to adapt part of the toil/batchSystems/torque.py script to force closing used files? Or should I attempt a force --restart without using the --batchSystem option? 

Thank you! 

```
2019-05-23 08:05:58,116 - toil.leader - INFO - Job ended successfully: 'RunBlast' x/g/jobLxDVb3
Issued job 'RunBlast' x/g/jobLxDVb3 with job batch system ID: 22693 and cores: 1, disk: 100.0 M, and memory: 100.0 M
2019-05-23 08:05:58,120 - toil.leader - INFO - Issued job 'RunBlast' x/g/jobLxDVb3 with job batch system ID: 22693 and cores: 1, disk: 100.0 M, and memory: 100.0 M
Exception in thread Thread-1281:
Traceback (most recent call last):
  File "/home/lcoelho/array1/miniconda2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/lcoelho/array1/miniconda2/lib/python2.7/site-packages/toil/batchSystems/abstractGridEngineBatchSystem.py", line 219, in run
    activity |= self.createJobs(newJob)
  File "/home/lcoelho/array1/miniconda2/lib/python2.7/site-packages/toil/batchSystems/abstractGridEngineBatchSystem.py", line 121, in createJobs
    batchJobID = self.submitJob(subLine)
  File "/home/lcoelho/array1/miniconda2/lib/python2.7/site-packages/toil/batchSystems/torque.py", line 129, in submitJob
    process = subprocess.Popen(subLine, stdout=subprocess.PIPE)
  File "/home/lcoelho/array1/miniconda2/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/home/lcoelho/array1/miniconda2/lib/python2.7/subprocess.py", line 928, in _execute_child
    errpipe_read, errpipe_write = self.pipe_cloexec()
  File "/home/lcoelho/array1/miniconda2/lib/python2.7/subprocess.py", line 865, in pipe_cloexec
    r, w = os.pipe()
OSError: [Errno 24] Too many open files

Waiting for service manager thread to finish ...
2019-05-23 08:06:02,524 - toil.serviceManager - INFO - Waiting for service manager thread to finish ...
... finished shutting down the service manager. Took 0.0857980251312 seconds
2019-05-23 08:06:02,610 - toil.serviceManager - INFO - ... finished shutting down the service manager. Took 0.0857980251312 seconds
Waiting for stats and logging collator thread to finish ...
2019-05-23 08:06:02,613 - toil.statsAndLogging - INFO - Waiting for stats and logging collator thread to finish ...
... finished collating stats and logs. Took 0.403775930405 seconds
2019-05-23 08:06:03,017 - toil.statsAndLogging - INFO - ... finished collating stats and logs. Took 0.403775930405 seconds
Traceback (most recent call last):
  File "/home/lcoelho/array1/miniconda2/bin/cactus", line 11, in <module>
    load_entry_point('progressiveCactus==1.0', 'console_scripts', 'cactus')()
  File "/home/lcoelho/array1/miniconda2/lib/python2.7/site-packages/cactus/progressive/cactus_progressive.py", line 520, in main
    halID = toil.start(RunCactusPreprocessorThenProgressiveDown(options, project, memory=configWrapper.getDefaultMemory()))
  File "/home/lcoelho/array1/miniconda2/lib/python2.7/site-packages/toil/common.py", line 743, in start
    return self._runMainLoop(rootJobGraph)
  File "/home/lcoelho/array1/miniconda2/lib/python2.7/site-packages/toil/common.py", line 1018, in _runMainLoop
    jobCache=self._jobCache).run()
  File "/home/lcoelho/array1/miniconda2/lib/python2.7/site-packages/toil/leader.py", line 197, in run
    self.innerLoop()
  File "/home/lcoelho/array1/miniconda2/lib/python2.7/site-packages/toil/leader.py", line 501, in innerLoop
    self.checkForDeadlocks()
  File "/home/lcoelho/array1/miniconda2/lib/python2.7/site-packages/toil/leader.py", line 518, in checkForDeadlocks
    totalRunningJobs = len(self.batchSystem.getRunningBatchJobIDs())
  File "/home/lcoelho/array1/miniconda2/lib/python2.7/site-packages/toil/batchSystems/abstractGridEngineBatchSystem.py", line 370, in getRunningBatchJobIDs
    batchIds = self.worker.getRunningJobIDs()
  File "/home/lcoelho/array1/miniconda2/lib/python2.7/site-packages/toil/batchSystems/torque.py", line 82, in getRunningJobIDs
    process = subprocess.Popen(['qstat'] + jobids, stdout=subprocess.PIPE)
  File "/home/lcoelho/array1/miniconda2/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/home/lcoelho/array1/miniconda2/lib/python2.7/subprocess.py", line 928, in _execute_child
    errpipe_read, errpipe_write = self.pipe_cloexec()
  File "/home/lcoelho/array1/miniconda2/lib/python2.7/subprocess.py", line 865, in pipe_cloexec
    r, w = os.pipe()
OSError: [Errno 24] Too many open files
```

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-367)
┆Issue Number: TOIL-367

**Comment by adamnovak** [comment]
It sounds like something (maybe the code that is actually throwing here) is leaking file descriptors.

The offending code is here:

https://github.com/DataBiosphere/toil/blob/b3d132ba9f6475751cc2fa4e634a0c1ccd2cbb07/src/toil/batchSystems/torque.py#L79-L85

What version of Python 2.7 are you running with, specifically? There have apparently historically been some bugs with subprocess Popen that could leak file descriptors in some situations.

I would just replace the Popen usages with `check_output` and a catch for `CalledProcessError`, unless we specifically need to process partial output from failed qstat commands.

It might be worth checking your file descriptor limit (`ulimit -n`), because it might not be a leak; maybe you just need a lot of FDs. On Mac I'm getting 256, which is plausible to reach in normal operation.

**Comment by lac2208** [comment]
Thanks for the help, Adam. 

I'm running Python 2.7.15. The ulimit in our system is 500k.
From that little that I understand from this, you mean I should do these edits (below) to torque.py? 

       if self._version == "pro":
                process = **subprocess.check_output**(['qstat', '-x'] + jobids, stdout=subprocess.PIPE)
            elif self._version == "oss":
                process = **subprocess.CalledProcessError**(['qstat'] + jobids, stdout=subprocess.PIPE)


            stdout, stderr = process.communicate()

What I'm trying to do now is forcing --restart the run and seeing if it can pick up where it left off "fresh", with no open files. Not an ideal solution.

**Comment by adamnovak** [comment]
That's not quite the change I was thinking of; check_output just returns the output text, so you would store it in a variable and then split that on '\n' later for the loop. And you'd have to have a try/except to catch CalledProcessError in case qsub crashes for some reason.

Just restarting the workflow with --restart ought to be a workaround.

**Comment by DailyDreaming** [comment]
Stale, closing.  Please reopen if still an issue.
