### ISSUE TITLE
toil-cwl-runner input parameters

### ISSUE THREAD

**Issue by ryanjeon0423** [DataBiosphere/toil#2696]
I ran toil-cwl-runner on HPC and gave input parameters, --tmpdir-prefix, --defaultCores, --defaultDisk, and --defaultMem but it seemed it didn't work.
the temporary directory didn't changed and the computing resources values were still the default values which I think are supposed to be overwritten.
@kaushik-work

**Comment by kaushik-work** [comment]
This is likely an issue with the `cwltoil.py` component. It looks like the CWL `resourceRequirements` are honored but are not overridden by the Toil command line parameters. So, if no CWL `resourceRequirements` are present, Toil's command line parameters do not get propagated. A fix should be reasonably straightforward.

**Comment by adamnovak** [comment]
Hello, @ryanjeon0423 

Just yesterday we merged https://github.com/DataBiosphere/toil/pull/2587 which has a fix for --tmpdir-prefix not being honored. This should be available in Toil 3.20.0.

The --defaultCores and similar options not being applied is a new bug; I will set this issue to track that.

**Comment by kaushik-work** [comment]
@adamnovak nice! @ryanjeon0423 will be worth while to try out this new version of Toil.

**Comment by lac2208** [comment]
I am encountering an error while running cactus that I think is related to this problem as well. 

I'm using toil v. 3.14 while attempting to align 6 bird genomes(~1.1 Gb each) with cactus on a PBS cluster (using --batchsystem Torque and --binariesMode local). I have more than 2T of space available, and the run never uses more than 30GB at any given time while running. Increasing disk space with --defaultDisk does not work. Is this issue related?

> cat: write error: No space left on device
Traceback (most recent call last):
  File "/home/lcoelho/array1/miniconda2/lib/python2.7/site-packages/toil/worker.py", line 309, in workerScript
    job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore)
  File "/home/lcoelho/array1/miniconda2/lib/python2.7/site-packages/cactus/shared/common.py", line 1096, in _runner
    super(RoundedJob, self)._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore)
  File "/home/lcoelho/array1/miniconda2/lib/python2.7/site-packages/toil/job.py", line 1328, in _runner
    returnValues = self._run(jobGraph, fileStore)
  File "/home/lcoelho/array1/miniconda2/lib/python2.7/site-packages/toil/job.py", line 1273, in _run
    return self.run(fileStore)
  File "/home/lcoelho/array1/miniconda2/lib/python2.7/site-packages/cactus/blast/blast.py", line 481, in run
    catFiles(resultsFiles, collatedResultsFile)
  File "/home/lcoelho/array1/miniconda2/lib/python2.7/site-packages/sonLib/bioio.py", line 662, in catFiles
    system("cat %s >> %s" % (" ".join(filesToCat[:maxCat]), catFile))
  File "/home/lcoelho/array1/miniconda2/lib/python2.7/site-packages/sonLib/bioio.py", line 185, in system
    raise RuntimeError("Command: %s exited with non-zero status %i" % (command, sts))
RuntimeError: Command: cat /var/tmp/pbs.400001.amnh-gen-001/toil-8e1ff5c2-a865-4fbc-98f5-99a7c5812889-901745c3-81f2-471d-91a5-515b0 (...)-d23e-4bfc-8acb-80f210e1e233/tmplaKl9Z.tmp exited with non-zero status 1
ERROR:toil.worker:Exiting the worker because of a failed job on host amnh-gen-001.internal.amnh.org
WARNING:toil.jobGraph:Due to failure we are reducing the remaining retry count of job 'CollateBlasts2' 4/R/jobF2JeHl with ID 4/R/jobF2JeHl to 0

**Comment by adamnovak** [comment]
@lac2208 I think you have a different issue. For one thing, you aren't working in CWL.

It's hard to get "no space left on device" unless you are actually filling up a real disk somewhere, and not hitting a Torque-imposed quota. If you have 2 TB and you can only actually use 30 GB, part of your problem I think is that you aren't actually putting your files on the 2 TB disk.

It looks like your workflow is working under /var/tmp; is that the directory hierarchy where you have your 2 TB of space?

If you don't want the individual jobs to be doing their work in that directory, you probably need to pass `--workDir` with a path to the place where you want the individual nodes to do their work. Usually we use per-node non-shared directories for this, and account for the available space when scheduling jobs, but you can also just pass a sufficiently big shared directory.

Now, it could be the case that part of your problem is also that --defaultDisk isn't working in your environment. I suspect it is because [Toil's Torque batch system doesn't seem to pass along disk space requirements](https://github.com/DataBiosphere/toil/blob/7da75ea784e515dba08451eeef6ed03527b19a5c/src/toil/batchSystems/torque.py#L161) to Torque. I did a little looking around and it seems uncommon to use Torque to allocate disk space on local scratch disks. If your cluster does support scheduling jobs based on free disk space, you might be able to add a disk space requirement to the jobs Toil sends to Torque with [`TOIL_TORQUE_REQS`](https://github.com/DataBiosphere/toil/blob/65ebba3c41623ea429e2193c4ffde756250698a3/docs/appendices/environment_vars.rst).

But given that `/var/tmp` seems unlikely to have th 2 TB of space you mentioned, I suspect you really want to run all the jobs working against a big shared filesystem, and just let Torque assume that you will never have jobs ready to run that need more disk space in total than you actually have available.

**Comment by lac2208** [comment]
Thank you, Adam. 

I do think that Torque is failing to pass along disk space and memory requirements to PBS. 
I've been trying to run directly on the threads with no --batchSystem and using --workDir. Although now I get a toil folder in the 2TB disk, the software keeps writing something to /var/tmp (30GB limit) and failing. 

The job crashes every 2 hs. It seems like the initial steps of 'mappingQualityRescoring' goes to the right folder (array1), but crashes when 'sort' command attempts to save to /var/tmp/. 

> 2019-06-06 09:33:05,704 - toil.leader - INFO - Starting the main loop
Issued job 'mappingQualityRescoring' K/G/jobWNHZCV with job batch system ID: 0 and cores: 1, disk: 2.0 G, and memory: 2.0 G
2019-06-06 09:33:05,705 - toil.leader - INFO - Issued job 'mappingQualityRescoring' K/G/jobWNHZCV with job batch system ID: 0 and cores: 1, disk: 2.0 G, and memory: 2.0 G
Job ended successfully: 'mappingQualityRescoring' K/G/jobWNHZCV
2019-06-06 09:49:23,475 - toil.leader - INFO - Job ended successfully: 'mappingQualityRescoring' K/G/jobWNHZCV
The job seems to have left a log file, indicating failure: 'mappingQualityRescoring' K/G/jobWNHZCV
2019-06-06 09:49:23,480 - toil.leader - WARNING - The job seems to have left a log file, indicating failure: 'mappingQualityRescoring' K/G/jobWNHZCV
K/G/jobWNHZCV    INFO:toil.worker:---TOIL WORKER OUTPUT LOG---
2019-06-06 09:49:23,481 - toil.leader - WARNING - K/G/jobWNHZCV    INFO:toil.worker:---TOIL WORKER OUTPUT LOG---
K/G/jobWNHZCV    INFO:toil:Running Toil version 3.14.0-b91dbf9bf6116879952f0a70f9a2fbbcae7e51b6.
2019-06-06 09:49:23,481 - toil.leader - WARNING - K/G/jobWNHZCV    INFO:toil:Running Toil version 3.14.0-b91dbf9bf6116879952f0a70f9a2fbbcae7e51b6.
K/G/jobWNHZCV    WARNING:toil.resource:'JTRES_3f16598175194404dc255f8ff30578ce' may exist, but is not yet referenced by the worker (KeyError from os.environ[]).
2019-06-06 09:49:23,481 - toil.leader - WARNING - K/G/jobWNHZCV    WARNING:toil.resource:'JTRES_3f16598175194404dc255f8ff30578ce' may exist, but is not yet referenced by the worker (KeyError from os.environ[]).
K/G/jobWNHZCV    WARNING:toil.resource:'JTRES_3f16598175194404dc255f8ff30578ce' may exist, but is not yet referenced by the worker (KeyError from os.environ[]).
2019-06-06 09:49:23,481 - toil.leader - WARNING - K/G/jobWNHZCV    WARNING:toil.resource:'JTRES_3f16598175194404dc255f8ff30578ce' may exist, but is not yet referenced by the worker (KeyError from os.environ[]).
K/G/jobWNHZCV    INFO:toil.fileStore:LOG-TO-MASTER: Input cigar file has 9501473 lines
2019-06-06 09:49:23,481 - toil.leader - WARNING - K/G/jobWNHZCV    INFO:toil.fileStore:LOG-TO-MASTER: Input cigar file has 9501473 lines
K/G/jobWNHZCV    INFO:cactus.shared.common:Running the command ['bash', '-c', u'set -eo pipefail && cat /home/lcoelho/array1/toil-8e1ff5c2-a865-4fbc-98f5-99a7c5812889-901745c3-81f2-471d-91a5-515b0cd7d7fd/tmphJXhCV/5fc058bd-3abc-4d34-ac7c-45712e28d935/tmppbRE3Y.tmp | cactus_mirrorAndOrientAlignments CRITICAL | sort -k6,6 -k7,7n -k8,8n | uniq | cactus_splitAlignmentOverlaps CRITICAL | cactus_calculateMappingQualities CRITICAL 5 0.0 0.001 /home/lcoelho/array1/toil-8e1ff5c2-a865-4fbc-98f5-99a7c5812889-901745c3-81f2-471d-91a5-515b0cd7d7fd/tmphJXhCV/5fc058bd-3abc-4d34-ac7c-45712e28d935/tmpYZ5lWP.tmp /home/lcoelho/array1/toil-8e1ff5c2-a865-4fbc-98f5-99a7c5812889-901745c3-81f2-471d-91a5-515b0cd7d7fd/tmphJXhCV/5fc058bd-3abc-4d34-ac7c-45712e28d935/tmpTJtJeN.tmp /home/lcoelho/array1/toil-8e1ff5c2-a865-4fbc-98f5-99a7c5812889-901745c3-81f2-471d-91a5-515b0cd7d7fd/tmphJXhCV/5fc058bd-3abc-4d34-ac7c-45712e28d935/tmp0yeEMo.tmp /home/lcoelho/array1/toil-8e1ff5c2-a865-4fbc-98f5-99a7c5812889-901745c3-81f2-471d-91a5-515b0cd7d7fd/tmphJXhCV/5fc058bd-3abc-4d34-ac7c-45712e28d935/tmpoJJExb.tmp /home/lcoelho/array1/toil-8e1ff5c2-a865-4fbc-98f5-99a7c5812889-901745c3-81f2-471d-91a5-515b0cd7d7fd/tmphJXhCV/5fc058bd-3abc-4d34-ac7c-45712e28d935/tmpZLCjlz.tmp']
2019-06-06 09:49:23,482 - toil.leader - WARNING - K/G/jobWNHZCV    INFO:cactus.shared.common:Running the command ['bash', '-c', u'set -eo pipefail && cat /home/lcoelho/array1/toil-8e1ff5c2-a865-4fbc-98f5-99a7c5812889-901745c3-81f2-471d-91a5-515b0cd7d7fd/tmphJXhCV/5fc058bd-3abc-4d34-ac7c-45712e28d935/tmppbRE3Y.tmp | cactus_mirrorAndOrientAlignments CRITICAL | sort -k6,6 -k7,7n -k8,8n | uniq | cactus_splitAlignmentOverlaps CRITICAL | cactus_calculateMappingQualities CRITICAL 5 0.0 0.001 /home/lcoelho/array1/toil-8e1ff5c2-a865-4fbc-98f5-99a7c5812889-901745c3-81f2-471d-91a5-515b0cd7d7fd/tmphJXhCV/5fc058bd-3abc-4d34-ac7c-45712e28d935/tmpYZ5lWP.tmp /home/lcoelho/array1/toil-8e1ff5c2-a865-4fbc-98f5-99a7c5812889-901745c3-81f2-471d-91a5-515b0cd7d7fd/tmphJXhCV/5fc058bd-3abc-4d34-ac7c-45712e28d935/tmpTJtJeN.tmp /home/lcoelho/array1/toil-8e1ff5c2-a865-4fbc-98f5-99a7c5812889-901745c3-81f2-471d-91a5-515b0cd7d7fd/tmphJXhCV/5fc058bd-3abc-4d34-ac7c-45712e28d935/tmp0yeEMo.tmp /home/lcoelho/array1/toil-8e1ff5c2-a865-4fbc-98f5-99a7c5812889-901745c3-81f2-471d-91a5-515b0cd7d7fd/tmphJXhCV/5fc058bd-3abc-4d34-ac7c-45712e28d935/tmpoJJExb.tmp /home/lcoelho/array1/toil-8e1ff5c2-a865-4fbc-98f5-99a7c5812889-901745c3-81f2-471d-91a5-515b0cd7d7fd/tmphJXhCV/5fc058bd-3abc-4d34-ac7c-45712e28d935/tmpZLCjlz.tmp']
K/G/jobWNHZCV    sort: write failed: /var/tmp/pbs.400207.amnh-gen-001/sortG776z8: No space left on device
2019-06-06 09:49:23,482 - toil.leader - WARNING - K/G/jobWNHZCV    sort: write failed: /var/tmp/pbs.400207.amnh-gen-001/sortG776z8: No space left on device

Do you know why --workDir isn't going through? Thank you!

**Comment by adamnovak** [comment]
@lac2208 I think the problem you are having is that Cactus is invoking the `sort` Unix command, which is creating temporary files in whatever it perceives to be the system temp directory, and not in the Toil working directory.

You can try working around the problem by overriding the temp directory seen by the workers. Something like `TMPDIR=/home/lcoelho/array1 cactus ...`. Toil should take care of shipping the environment out to the workers, and the sort command should respect it.

Really, either Cactus needs to tell sort to work in the Toil work directory, or Toil just needs to override `TMPDIR` as seen by jobs, so that when they run Unix commands, those commands keep their temporary files in a directory for that job.

**Comment by mr-c** [comment]
👍 for setting `TMPDIR`

**Comment by dicknetherlands** [comment]
> This is likely an issue with the `cwltoil.py` component. It looks like the CWL `resourceRequirements` are honored but are not overridden by the Toil command line parameters. So, if no CWL `resourceRequirements` are present, Toil's command line parameters do not get propagated. A fix should be reasonably straightforward.

I thought that defaultCores/Memory/Disk were there only to provide values for when there were no ResourceRequirements in the CWL, and that the CWL settings should take priority if present? Particularly since the CWL is fine-grained with different resources per job within a workflow, but the default* params are global. If default* takes precedence then the CWL settings become redundant - there should be a way to turn this off if it gets changed.
