### ISSUE TITLE
Update EC2 instances

### ISSUE THREAD

**Issue by arostamianfar** [DataBiosphere/toil#2702]
New c5n instances have been introduced in Nov 2018: https://aws.amazon.com/about-aws/whats-new/2018/11/introducing-amazon-ec2-c5n-instances/

Running `src/toil/utils/toilUpdateEC2Instances.py` currently gives the exception:
```
Traceback (most recent call last):
  File "src/toil/utils/toilUpdateEC2Instances.py", line 45, in <module>
    main()
  File "src/toil/utils/toilUpdateEC2Instances.py", line 42, in main
    updateStaticEC2Instances()
  File "/Users/asha/venvtoil/lib/python2.7/site-packages/toil/lib/ec2nodes.py", line 256, in updateStaticEC2Instances
    currentEC2Dict = fetchEC2InstanceDict(regionNickname=regionNickname)
  File "/Users/asha/venvtoil/lib/python2.7/site-packages/toil/lib/ec2nodes.py", line 162, in fetchEC2InstanceDict
    ec2InstanceList = parseEC2Json2List(jsontext=response.text, region=region)
  File "/Users/asha/venvtoil/lib/python2.7/site-packages/toil/lib/ec2nodes.py", line 206, in parseEC2Json2List
    'Duplicate instance {} found.'.format(instance))
RuntimeError: EC2 JSON format has likely changed.  Duplicate instance Type: r5d.large
Cores: 2
Disks: 1.0
Memory: 16.0
Disk Capacity: 75.0
 found.
```

Not yet sure what has changed since the last update.

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-377)
┆Issue Number: TOIL-377

**Comment by DailyDreaming** [comment]
@arostamianfar I'll look into this.

**Comment by DailyDreaming** [comment]
@arostamianfar I flagged you to review #2709 if you get some time.
