### ISSUE TITLE
Decode lshosts output in lsf.py

### ISSUE THREAD

**Issue by adamnovak** [DataBiosphere/toil#2724]
@drkennetz suggests that we add some decoding logic to `lsf.py`, because apparently it doesn't work in Pythion 3.

```
        for line in p.stdout:
                split_items = line.strip().split()
#logic          items = [item.decode() for item in split_items if isinstance(item, bytes)]
                for value in items:
                    if isinstance(value, bytes):
                        value = value.decode()
                if len(items) < num_columns:
                        RuntimeError("lshosts output has a varying number of "
                                     "columns")
#logic      if items[cpu_index] != '-' and int(items[cpu_index]) > int(maxCPU):
                        maxCPU = items[cpu_index]
                if (items[mem_index] != '-' and
                        MemoryString(items[mem_index]) > maxMEM):
                    maxMEM = MemoryString(items[mem_index])
```

See [this comment](https://github.com/DataBiosphere/toil/issues/2523#issuecomment-506395221).

As suggested, we can also explore if there's some way to wrap or set a default encoding on all our text streams with one bit of code.

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-388)
┆Issue Number: TOIL-388

**Comment by drkennetz** [comment]
I am going to continue to look into what is going on here. I am tracking the issues as I work through them. I want to make sure this is reproducible for different versions of python from a pip install. I am seeing some other downstream errors as well like:
```
Traceback (most recent call last):
  File "/hpcf/apps/python/install/3.5.2/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/users/dkennetz/toil_test/lib/python3.5/site-packages/toil/batchSystems/abstractGridEngineBatchSystem.py", line 235, in run
    activity = self.checkOnJobs()
  File "/users/dkennetz/toil_test/lib/python3.5/site-packages/toil/batchSystems/abstractGridEngineBatchSystem.py", line 210, in checkOnJobs
    status = with_retries(self.getJobExitCode, batchJobID)
  File "/users/dkennetz/toil_test/lib/python3.5/site-packages/toil/batchSystems/abstractGridEngineBatchSystem.py", line 42, in with_retries
    return operation(*args, **kwargs)
  File "/users/dkennetz/toil_test/lib/python3.5/site-packages/toil/batchSystems/lsf.py", line 98, in getJobExitCode
    if "Done successfully" in line:
TypeError: a bytes-like object is required, not 'str'
```

**Comment by drkennetz** [comment]
Last comment was unrelated to this issue. This is related:

```
Exception in thread Thread-281:
Traceback (most recent call last):
  File "/hpcf/apps/python/install/3.5.2/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/users/dkennetz/toil_test/lib/python3.5/site-packages/toil/batchSystems/abstractGridEngineBatchSystem.py", line 235, in run
    activity |= self.checkOnJobs()
  File "/users/dkennetz/toil_test/lib/python3.5/site-packages/toil/batchSystems/abstractGridEngineBatchSystem.py", line 210, in checkOnJobs
    status = with_retries(self.getJobExitCode, batchJobID)
  File "/users/dkennetz/toil_test/lib/python3.5/site-packages/toil/batchSystems/abstractGridEngineBatchSystem.py", line 42, in with_retries
    return operation(*args, **kwargs)
  File "/users/dkennetz/toil_test/lib/python3.5/site-packages/toil/batchSystems/lsf.py", line 98, in getJobExitCode
    if "Done successfully" in line:
TypeError: a bytes-like object is required, not 'str'
```
Opposite effect from lsf job checker.

**Comment by drkennetz** [comment]
My plan is to keep track of these and then fork and make changes and PR when I have a working copy.

**Comment by drkennetz** [comment]
d2daf98

**Comment by mr-c** [comment]
Fixed in https://github.com/DataBiosphere/toil/commit/dc282404e031aa3ba9683fff7f06716934d12749
