### ISSUE TITLE
Toil-Job on Slurm failed

### ISSUE THREAD

**Issue by JSquar** [DataBiosphere/toil#2756]
I try to execute a simple code example from [toil documentation](https://toil.readthedocs.io/en/releases-3.7.x/running/running.html#quickstart-a-simple-workflow). Without the batchSystem flag everything works fine and produces output on the login node. But as soon as I try to use slurm to execute the job on a compute node, the execution fails. I see that a job is spawned, so I assume that the error occurs during the execution.

```shell
(virtualenv_python3_toil_cwl) $ TOIL_SLURM_ARGS="-p west -N 1" python3 helloWorld.py --batchSystem Slurm file:bla
WARNING:toil.batchSystems.singleMachine:Limiting maxMemory to physically available memory (10226737152).
WARNING:toil.batchSystems.singleMachine:Limiting maxDisk to physically available disk (10655739904).
WARNING:toil.common:Batch system does not support auto-deployment. The user script ModuleDescriptor(dirPath='/home/squar/Git/Testprogramme/Workflows/Toil/01_HelloWorld', name='helloWorld', fromVirtualEnv=False) will have to be present at the same location on every worker.
INFO:toil:Running Toil version 3.20.0-cf34ca3416697f2abc816b2538f20ee29ba16932.
INFO:toil.leader:Issued job 'helloWorld' O/G/jobcdqc4ot2 with job batch system ID: 0 and cores: 1, disk: 1.0 G, and memory: 1.0 G
WARNING:toil.leader:Job failed with exit value 1: 'helloWorld' O/G/jobcdqc4ot2
WARNING:toil.leader:No log file is present, despite job failing: 'helloWorld' O/G/jobcdqc4ot2
WARNING:toil.jobGraph:Due to failure we are reducing the remaining retry count of job 'helloWorld' O/G/jobcdqc4ot2 with ID O/G/jobcdqc4ot2 to 1
WARNING:toil.jobGraph:We have increased the default memory of the failed job 'helloWorld' O/G/jobcdqc4ot2 to 2147483648 bytes
INFO:toil.leader:Issued job 'helloWorld' O/G/jobcdqc4ot2 with job batch system ID: 1 and cores: 1, disk: 1.0 G, and memory: 2.0 G
WARNING:toil.leader:Job failed with exit value 1: 'helloWorld' O/G/jobcdqc4ot2
WARNING:toil.leader:No log file is present, despite job failing: 'helloWorld' O/G/jobcdqc4ot2
WARNING:toil.jobGraph:Due to failure we are reducing the remaining retry count of job 'helloWorld' O/G/jobcdqc4ot2 with ID O/G/jobcdqc4ot2 to 0
WARNING:toil.leader:Job 'helloWorld' O/G/jobcdqc4ot2 with ID O/G/jobcdqc4ot2 is completely failed
INFO:toil.leader:Finished toil run with 1 failed jobs.
INFO:toil.leader:Failed jobs at end of the run: 'helloWorld' O/G/jobcdqc4ot2
Traceback (most recent call last):
  File "helloWorld.py", line 12, in <module>
    output = toil.start(Job.wrapFn(helloWorld, "You did it!"))
  File "/home/squar/virtualenv_python3_toil_cwl/lib/python3.7/site-packages/toil/common.py", line 781, in start
    return self._runMainLoop(rootJobGraph)
  File "/home/squar/virtualenv_python3_toil_cwl/lib/python3.7/site-packages/toil/common.py", line 1054, in _runMainLoop
    jobCache=self._jobCache).run()
  File "/home/squar/virtualenv_python3_toil_cwl/lib/python3.7/site-packages/toil/leader.py", line 246, in run
    raise FailedJobsException(self.config.jobStore, self.toilState.totalFailedJobs, self.jobStore)
toil.leader.FailedJobsException
```
Nodes of the west partition are available, each compute node mounts the home directories via nfs so the script is available. I don't see any significant error message or logs, nor any slurm log files. Any idea what the problem might be or where I should start to debug?

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-403)
┆Issue Number: TOIL-403

**Comment by mr-c** [comment]
@jsquar I saw CWL in the title, but it looks like this is a plain "toil" workflow example, not a `toil-cwl-runner` example.

Maybe try installing toil from this Git repository? There is an unreleased feature that explicitly asks SLURM to save logs for each job run, so that might help

**Comment by JSquar** [comment]
You're right, I posted the output of a regular toil workflow, I took the wrong output. But the error message is the same. I'll try an installation from repo and I'll update my post then.

**Comment by JSquar** [comment]
I installed toil 3.21.0a1 from repository and launched the toil-job via `export TOIL_SLURM_ARGS="-p west -N 1"; python helloWorld.py file:output --logDebug --batchSystem Slurm --disableAutoDeployment --disableCaching --writeLogs`

This resulted in the following output:
```shell
cluster 2019-08-04 23:01:06,266 MainThread DEBUG toil.lib.bioio: Root logger is at level 'DEBUG', 'toil' logger at level 'DEBUG'.
cluster 2019-08-04 23:01:06,749 MainThread DEBUG rdflib: RDFLib Version: 4.2.2
cluster 2019-08-04 23:01:07,243 MainThread DEBUG toil.jobStores.fileJobStore: Path to job store directory is '/home/squar/Git/Testprogramme/Workflows/Toil/01_HelloWorld/output'.
cluster 2019-08-04 23:01:07,252 MainThread DEBUG toil.jobStores.abstractJobStore: The workflow ID is: 'fcb02852-aa15-4a4f-95d1-ff3521f3075a'
cluster 2019-08-04 23:01:07,256 MainThread DEBUG toil.resource: Module dir is /home/squar/Git/toil/src
cluster 2019-08-04 23:01:07,257 MainThread DEBUG toil.resource: Discovering real name of module
cluster 2019-08-04 23:01:07,261 MainThread DEBUG toil.resource: Module dir is /home/squar/Git/Testprogramme/Workflows/Toil/01_HelloWorld
cluster 2019-08-04 23:01:07,264 MainThread DEBUG toil.common: Using the slurm batch system
cluster 2019-08-04 23:01:07,268 MainThread WARNING toil.batchSystems.singleMachine: Limiting maxMemory to physically available memory (10226737152).
cluster 2019-08-04 23:01:07,268 MainThread DEBUG toil.common: Obtained node ID 63aee6c2a4398fec1f1244040000011b from file /var/lib/dbus/machine-id
cluster 2019-08-04 23:01:07,269 MainThread DEBUG toil.common: Created the workflow directory at /tmp/toil-fcb02852-aa15-4a4f-95d1-ff3521f3075a-63aee6c2a4398fec1f1244040000011b
cluster 2019-08-04 23:01:07,269 MainThread WARNING toil.batchSystems.singleMachine: Limiting maxDisk to physically available disk (10642518016).
cluster 2019-08-04 23:01:07,269 MainThread DEBUG toil.batchSystems.singleMachine: Setting up the thread pool with 120 workers, given a minimum CPU fraction of 0.100000 and a maximum CPU value of 12.
cluster 2019-08-04 23:01:07,336 MainThread WARNING toil.common: Batch system does not support auto-deployment. The user script ModuleDescriptor(dirPath='/home/squar/Git/Testprogramme/Workflows/Toil/01_HelloWorld', name='helloWorld', fromVirtualEnv=False) will have to be present at the same location on every worker.
cluster 2019-08-04 23:01:07,338 MainThread DEBUG toil.common: No user script to auto-deploy.
cluster 2019-08-04 23:01:07,341 MainThread DEBUG toil.common: Written the environment for the jobs to the environment file
cluster 2019-08-04 23:01:07,341 MainThread DEBUG toil.common: Caching all jobs in job store
cluster 2019-08-04 23:01:07,344 MainThread DEBUG toil.common: 0 jobs downloaded.
cluster 2019-08-04 23:01:07,384 MainThread INFO toil: Running Toil version 3.21.0a1-0905ea20868da02f3978ccc53be4f7b1c530e42d.
cluster 2019-08-04 23:01:07,384 MainThread DEBUG toil: Configuration: {'maxLocalJobs': 12, 'rescueJobsFrequency': 3600, 'logLevel': 'DEBUG', 'minNodes': None, 'targetTime': 1800, 'jobStore': 'file:/home/squar/Git/Testprogramme/Workflows/Toil/01_HelloWorld/output', 'linkImports': False, 'manualMemArgs': False, 'forceDockerAppliance': False, 'nodeOptions': None, 'nodeTypes': [], 'servicePollingInterval': 60, 'workDir': None, 'stats': False, 'disableCaching': True, 'noStdOutErr': False, 'maxPreemptableServiceJobs': 9223372036854775807, 'environment': {}, 'parasolMaxBatches': 10000, 'cleanWorkDir': 'always', 'disableChaining': False, 'maxCores': 9223372036854775807, 'sseKey': None, 'maxMemory': 9223372036854775807, 'maxDisk': 9223372036854775807, 'cwl': False, 'scaleInterval': 60, 'deadlockWait': 60, 'defaultPreemptable': False, 'clusterStats': None, 'defaultCores': 1, 'cseKey': None, 'betaInertia': 0.1, 'metrics': False, 'maxNodes': [10], 'scale': 1, 'writeLogs': '/home/squar/Git/Testprogramme/Workflows/Toil/01_HelloWorld', 'runCwlInternalJobsOnWorkers': False, 'disableAutoDeployment': True, 'badWorker': 0.0, 'defaultDisk': 2147483648, 'mesosMasterAddress': '136.172.61.247:5050', 'restart': False, 'useAsync': True, 'preemptableCompensation': 0.0, 'parasolCommand': 'parasol', 'workflowID': 'fcb02852-aa15-4a4f-95d1-ff3521f3075a', 'maxServiceJobs': 9223372036854775807, 'readGlobalFileMutableByDefault': False, 'badWorkerFailInterval': 0.01, 'statePollingWait': 1, 'debugWorker': False, 'maxLogFileSize': 64000, 'defaultMemory': 2147483648, 'workflowAttemptNumber': 0, 'maxJobDuration': 9223372036854775807, 'clean': 'onSuccess', 'provisioner': None, 'batchSystem': 'Slurm', 'retryCount': 1, 'writeLogsGzip': None, 'nodeStorage': 50}
cluster 2019-08-04 23:01:07,385 MainThread DEBUG toil.realtimeLogger: Real-time logging disabled
cluster 2019-08-04 23:01:07,399 MainThread DEBUG toil.toilState: Found job to run: kind-helloWorld/instance5bzjRf, with command: True, with checkpoint: False, with  services: False, with stack: False
cluster 2019-08-04 23:01:07,400 MainThread DEBUG toil.leader: Found 1 jobs to start and 0 jobs with successors to run
cluster 2019-08-04 23:01:07,400 MainThread DEBUG toil.leader: Checked batch system has no running jobs and no updated jobs
cluster 2019-08-04 23:01:07,400 MainThread DEBUG toil.serviceManager: Initializing service manager
cluster 2019-08-04 23:01:07,401 MainThread DEBUG toil.leader: Built the jobs list, currently have 1 jobs to update and 0 jobs issued
cluster 2019-08-04 23:01:07,401 MainThread DEBUG toil.leader: Updating status of job 'helloWorld' kind-helloWorld/instance5bzjRf with ID kind-helloWorld/instance5bzjRf: with result status: 0
cluster 2019-08-04 23:01:07,403 MainThread DEBUG toil.batchSystems.abstractGridEngineBatchSystem: Issued the job command: /home/squar/virtualenv_workflow_python2/bin/_toil_worker helloWorld file:/home/squar/Git/Testprogramme/Workflows/Toil/01_HelloWorld/output kind-helloWorld/instance5bzjRf with job id: 0 
cluster 2019-08-04 23:01:07,404 MainThread INFO toil.leader: Issued job 'helloWorld' kind-helloWorld/instance5bzjRf with job batch system ID: 0 and cores: 1, disk: 1.0 G, and memory: 1.0 G
cluster 2019-08-04 23:01:08,337 Thread-121 DEBUG toil.batchSystems.abstractGridEngineBatchSystem: No activity, sleeping for 1s
cluster 2019-08-04 23:01:08,338 Thread-121 DEBUG toil.common: Obtained node ID 63aee6c2a4398fec1f1244040000011b from file /var/lib/dbus/machine-id
cluster 2019-08-04 23:01:08,338 Thread-121 DEBUG toil.common: Obtained node ID 63aee6c2a4398fec1f1244040000011b from file /var/lib/dbus/machine-id
cluster 2019-08-04 23:01:08,339 Thread-121 DEBUG toil.batchSystems.slurm: Native SLURM options appended to sbatch from TOIL_SLURM_ARGS env. variable: -p west -N 1
cluster 2019-08-04 23:01:08,339 Thread-121 DEBUG toil.batchSystems.abstractGridEngineBatchSystem: Running ['sbatch', '-Q', '-J', 'toil_job_0', '--mem=1024', '--cpus-per-task=1', '-o', u'/tmp/toil-fcb02852-aa15-4a4f-95d1-ff3521f3075a-63aee6c2a4398fec1f1244040000011b/toil_job_0_batch_slurm_%j_std_output.log', '-e', u'/tmp/toil-fcb02852-aa15-4a4f-95d1-ff3521f3075a-63aee6c2a4398fec1f1244040000011b/toil_job_0_batch_slurm_%j_std_error.log', '-p', 'west', '-N', '1', '--wrap=/home/squar/virtualenv_workflow_python2/bin/_toil_worker helloWorld file:/home/squar/Git/Testprogramme/Workflows/Toil/01_HelloWorld/output kind-helloWorld/instance5bzjRf']
cluster 2019-08-04 23:01:08,381 Thread-121 DEBUG toil.batchSystems.slurm: sbatch submitted job 11264
cluster 2019-08-04 23:01:08,381 Thread-121 DEBUG toil.batchSystems.abstractGridEngineBatchSystem: Submitted job 11264
cluster 2019-08-04 23:01:08,383 Thread-121 DEBUG toil.batchSystems.slurm: Getting exit code for slurm job 11264
cluster 2019-08-04 23:01:08,430 Thread-121 DEBUG toil.batchSystems.slurm: scontrol exit code is 0:0, returning status 0
cluster 2019-08-04 23:01:08,430 Thread-121 DEBUG toil.batchSystems.slurm: s job state is PENDING
cluster 2019-08-04 23:01:09,432 Thread-121 DEBUG toil.batchSystems.abstractGridEngineBatchSystem: No activity, sleeping for 1s
cluster 2019-08-04 23:01:09,433 Thread-121 DEBUG toil.batchSystems.slurm: Getting exit code for slurm job 11264
cluster 2019-08-04 23:01:09,477 Thread-121 DEBUG toil.batchSystems.slurm: scontrol exit code is 1:0, returning status 1
cluster 2019-08-04 23:01:09,477 Thread-121 DEBUG toil.batchSystems.slurm: s job state is FAILED
cluster 2019-08-04 23:01:09,493 MainThread DEBUG toil.batchSystems.abstractGridEngineBatchSystem: UpdatedJobsQueue Item: (0, 1)
cluster 2019-08-04 23:01:09,497 MainThread WARNING toil.leader: Job failed with exit value 1: 'helloWorld' kind-helloWorld/instance5bzjRf
cluster 2019-08-04 23:01:09,501 MainThread DEBUG toil.leader: Job 'helloWorld' kind-helloWorld/instance5bzjRf continues to exist (i.e. has more to do)
cluster 2019-08-04 23:01:09,521 MainThread WARNING toil.leader: No log file is present, despite job failing: 'helloWorld' kind-helloWorld/instance5bzjRf
cluster 2019-08-04 23:01:09,522 MainThread DEBUG toil.common: Obtained node ID 63aee6c2a4398fec1f1244040000011b from file /var/lib/dbus/machine-id
cluster 2019-08-04 23:01:09,525 MainThread WARNING toil.jobGraph: Due to failure we are reducing the remaining retry count of job 'helloWorld' kind-helloWorld/instance5bzjRf with ID kind-helloWorld/instance5bzjRf to 1
cluster 2019-08-04 23:01:09,525 MainThread WARNING toil.jobGraph: We have increased the default memory of the failed job 'helloWorld' kind-helloWorld/instance5bzjRf to 2147483648 bytes
cluster 2019-08-04 23:01:09,539 MainThread DEBUG toil.leader: Added job: 'helloWorld' kind-helloWorld/instance5bzjRf to active jobs
cluster 2019-08-04 23:01:09,540 MainThread DEBUG toil.leader: Built the jobs list, currently have 1 jobs to update and 0 jobs issued
cluster 2019-08-04 23:01:09,541 MainThread DEBUG toil.leader: Updating status of job 'helloWorld' kind-helloWorld/instance5bzjRf with ID kind-helloWorld/instance5bzjRf: with result status: 1
cluster 2019-08-04 23:01:09,542 MainThread DEBUG toil.batchSystems.abstractGridEngineBatchSystem: Issued the job command: /home/squar/virtualenv_workflow_python2/bin/_toil_worker helloWorld file:/home/squar/Git/Testprogramme/Workflows/Toil/01_HelloWorld/output kind-helloWorld/instance5bzjRf with job id: 1 
cluster 2019-08-04 23:01:09,543 MainThread INFO toil.leader: Issued job 'helloWorld' kind-helloWorld/instance5bzjRf with job batch system ID: 1 and cores: 1, disk: 1.0 G, and memory: 2.0 G
cluster 2019-08-04 23:01:09,543 Thread-121 DEBUG toil.common: Obtained node ID 63aee6c2a4398fec1f1244040000011b from file /var/lib/dbus/machine-id
cluster 2019-08-04 23:01:09,544 Thread-121 DEBUG toil.common: Obtained node ID 63aee6c2a4398fec1f1244040000011b from file /var/lib/dbus/machine-id
cluster 2019-08-04 23:01:09,544 Thread-121 DEBUG toil.batchSystems.slurm: Native SLURM options appended to sbatch from TOIL_SLURM_ARGS env. variable: -p west -N 1
cluster 2019-08-04 23:01:09,544 Thread-121 DEBUG toil.batchSystems.abstractGridEngineBatchSystem: Running ['sbatch', '-Q', '-J', 'toil_job_1', '--mem=2048', '--cpus-per-task=1', '-o', u'/tmp/toil-fcb02852-aa15-4a4f-95d1-ff3521f3075a-63aee6c2a4398fec1f1244040000011b/toil_job_1_batch_slurm_%j_std_output.log', '-e', u'/tmp/toil-fcb02852-aa15-4a4f-95d1-ff3521f3075a-63aee6c2a4398fec1f1244040000011b/toil_job_1_batch_slurm_%j_std_error.log', '-p', 'west', '-N', '1', '--wrap=/home/squar/virtualenv_workflow_python2/bin/_toil_worker helloWorld file:/home/squar/Git/Testprogramme/Workflows/Toil/01_HelloWorld/output kind-helloWorld/instance5bzjRf']
cluster 2019-08-04 23:01:09,581 Thread-121 DEBUG toil.batchSystems.slurm: sbatch submitted job 11265
cluster 2019-08-04 23:01:09,581 Thread-121 DEBUG toil.batchSystems.abstractGridEngineBatchSystem: Submitted job 11265
cluster 2019-08-04 23:01:10,478 Thread-121 DEBUG toil.batchSystems.slurm: Getting exit code for slurm job 11265
cluster 2019-08-04 23:01:10,522 Thread-121 DEBUG toil.batchSystems.slurm: scontrol exit code is 0:0, returning status 0
cluster 2019-08-04 23:01:10,522 Thread-121 DEBUG toil.batchSystems.slurm: s job state is PENDING
cluster 2019-08-04 23:01:11,524 Thread-121 DEBUG toil.batchSystems.abstractGridEngineBatchSystem: No activity, sleeping for 1s
cluster 2019-08-04 23:01:11,524 Thread-121 DEBUG toil.batchSystems.slurm: Getting exit code for slurm job 11265
cluster 2019-08-04 23:01:11,588 Thread-121 DEBUG toil.batchSystems.slurm: scontrol exit code is 1:0, returning status 1
cluster 2019-08-04 23:01:11,589 Thread-121 DEBUG toil.batchSystems.slurm: s job state is FAILED
cluster 2019-08-04 23:01:11,610 MainThread DEBUG toil.batchSystems.abstractGridEngineBatchSystem: UpdatedJobsQueue Item: (1, 1)
cluster 2019-08-04 23:01:11,610 MainThread WARNING toil.leader: Job failed with exit value 1: 'helloWorld' kind-helloWorld/instance5bzjRf
cluster 2019-08-04 23:01:11,612 MainThread DEBUG toil.leader: Job 'helloWorld' kind-helloWorld/instance5bzjRf continues to exist (i.e. has more to do)
cluster 2019-08-04 23:01:11,624 MainThread WARNING toil.leader: No log file is present, despite job failing: 'helloWorld' kind-helloWorld/instance5bzjRf
cluster 2019-08-04 23:01:11,626 MainThread DEBUG toil.common: Obtained node ID 63aee6c2a4398fec1f1244040000011b from file /var/lib/dbus/machine-id
cluster 2019-08-04 23:01:11,629 MainThread WARNING toil.jobGraph: Due to failure we are reducing the remaining retry count of job 'helloWorld' kind-helloWorld/instance5bzjRf with ID kind-helloWorld/instance5bzjRf to 0
cluster 2019-08-04 23:01:11,642 MainThread DEBUG toil.leader: Added job: 'helloWorld' kind-helloWorld/instance5bzjRf to active jobs
cluster 2019-08-04 23:01:11,643 MainThread DEBUG toil.leader: Built the jobs list, currently have 1 jobs to update and 0 jobs issued
cluster 2019-08-04 23:01:11,644 MainThread DEBUG toil.leader: Updating status of job 'helloWorld' kind-helloWorld/instance5bzjRf with ID kind-helloWorld/instance5bzjRf: with result status: 1
cluster 2019-08-04 23:01:11,645 MainThread DEBUG toil.leader: Found new failed successors:  of job: 'helloWorld' kind-helloWorld/instance5bzjRf
cluster 2019-08-04 23:01:11,645 MainThread WARNING toil.leader: Job 'helloWorld' kind-helloWorld/instance5bzjRf with ID kind-helloWorld/instance5bzjRf is completely failed
cluster 2019-08-04 23:01:13,591 Thread-121 DEBUG toil.batchSystems.abstractGridEngineBatchSystem: No activity, sleeping for 1s
cluster 2019-08-04 23:01:13,647 MainThread DEBUG toil.leader: Finished the main loop: no jobs left to run.
cluster 2019-08-04 23:01:13,647 MainThread DEBUG toil.serviceManager: Waiting for service manager thread to finish ...
cluster 2019-08-04 23:01:14,410 Thread-122 DEBUG toil.serviceManager: Received signal to quit starting services.
cluster 2019-08-04 23:01:14,592 Thread-121 DEBUG toil.batchSystems.abstractGridEngineBatchSystem: No activity, sleeping for 1s
cluster 2019-08-04 23:01:15,411 MainThread DEBUG toil.serviceManager: ... finished shutting down the service manager. Took 1.76382708549 seconds
cluster 2019-08-04 23:01:15,413 MainThread DEBUG toil.statsAndLogging: Waiting for stats and logging collator thread to finish ...
cluster 2019-08-04 23:01:15,453 MainThread DEBUG toil.statsAndLogging: ... finished collating stats and logs. Took 0.0396230220795 seconds
cluster 2019-08-04 23:01:15,459 MainThread DEBUG toil.jobStores.abstractJobStore: Unable to import 'toil.jobStores.azureJobStore' as is expected if the corresponding extra was omitted at installation time.
cluster 2019-08-04 23:01:15,462 MainThread DEBUG toil.jobStores.abstractJobStore: Unable to import 'toil.jobStores.googleJobStore' as is expected if the corresponding extra was omitted at installation time.
cluster 2019-08-04 23:01:15,584 MainThread INFO toil.leader: Finished toil run with 1 failed jobs.
cluster 2019-08-04 23:01:15,584 MainThread INFO toil.leader: Failed jobs at end of the run: 'helloWorld' kind-helloWorld/instance5bzjRf
cluster 2019-08-04 23:01:15,587 MainThread DEBUG toil.common: Shutting down batch system ...
cluster 2019-08-04 23:01:15,594 Thread-121 DEBUG toil.batchSystems.abstractGridEngineBatchSystem: No activity, sleeping for 1s
cluster 2019-08-04 23:01:15,614 MainThread DEBUG toil.common: Obtained node ID 63aee6c2a4398fec1f1244040000011b from file /var/lib/dbus/machine-id
cluster 2019-08-04 23:01:15,614 MainThread DEBUG toil.deferred: Cleaning up deferred functions system
cluster 2019-08-04 23:01:15,615 MainThread DEBUG toil.deferred: Running for file /tmp/toil-fcb02852-aa15-4a4f-95d1-ff3521f3075a-63aee6c2a4398fec1f1244040000011b/deferred/tmpS2kkN3
cluster 2019-08-04 23:01:15,615 MainThread DEBUG toil.deferred: Running orphaned deferred functions
cluster 2019-08-04 23:01:15,616 MainThread DEBUG toil.deferred: Deleting /tmp/toil-fcb02852-aa15-4a4f-95d1-ff3521f3075a-63aee6c2a4398fec1f1244040000011b/deferred/tmpS2kkN3
cluster 2019-08-04 23:01:16,596 Thread-121 DEBUG toil.batchSystems.abstractGridEngineBatchSystem: No activity, sleeping for 1s
cluster 2019-08-04 23:01:16,596 Thread-121 DEBUG toil.batchSystems.abstractGridEngineBatchSystem: Received queue sentinel.
cluster 2019-08-04 23:01:16,596 MainThread DEBUG toil.common: ... finished shutting down the batch system in 1.00929284096 seconds.
Traceback (most recent call last):
  File "helloWorld.py", line 12, in <module>
    output = toil.start(Job.wrapFn(helloWorld, "You did it!"))
  File "/home/squar/Git/toil/src/toil/common.py", line 781, in start
    return self._runMainLoop(rootJobGraph)
  File "/home/squar/Git/toil/src/toil/common.py", line 1054, in _runMainLoop
    jobCache=self._jobCache).run()
  File "/home/squar/Git/toil/src/toil/leader.py", line 246, in run
    raise FailedJobsException(self.config.jobStore, self.toilState.totalFailedJobs, self.jobStore)
toil.leader.FailedJobsException
```

I think the "interesting" part is 
```
cluster 2019-08-04 23:01:10,522 Thread-121 DEBUG toil.batchSystems.slurm: s job state is PENDING
cluster 2019-08-04 23:01:11,524 Thread-121 DEBUG toil.batchSystems.abstractGridEngineBatchSystem: No activity, sleeping for 1s
cluster 2019-08-04 23:01:11,524 Thread-121 DEBUG toil.batchSystems.slurm: Getting exit code for slurm job 11265
cluster 2019-08-04 23:01:11,588 Thread-121 DEBUG toil.batchSystems.slurm: scontrol exit code is 1:0, returning status 1
cluster 2019-08-04 23:01:11,589 Thread-121 DEBUG toil.batchSystems.slurm: s job state is FAILED
```
According to the describtion of `--writeLogs` I expected slurm output to be written into the local directory but I found no logs.

**Comment by JSquar** [comment]
A new morning, a new try. This time I call the workflow with `TOIL_SLURM_ARGS="-p west -N 1" python helloWorld.py --logDebug --workDir=tmp --batchSystem=slurm --disableAutoDeployment --disableCaching --writeLogs=workerLogs file:output` and this time it worked just fine. Not quite sure yet, what caused the problem, I'll investigate. 
But since the problem is solved, this issue has become obsolete.

**Comment by edraizen** [comment]
I keep getting the same error, any other ideas what could be causing this?

**Comment by adamnovak** [comment]
@edraizen Do you have a `TMPDIR` set in the output of `env`? Have you tried the `--workDir=tmp` workaround?

Is Toil not reporting the error output from the failing job that Slurm is supposed to deliver back?

**Comment by edraizen** [comment]
Thanks! It finally worked when I made new tmp directory in the cwd. 

`TMPDIR` had already been set to `/tmp` so didn't think that was my issue. I guess the default is not accessible on all of the workers.
