### ISSUE TITLE
failed job --> lsf job not terminated

### ISSUE THREAD

**Issue by ionox0** [DataBiosphere/toil#2800]
After 3 failures of a job using `toil-cwl-runner` due to the job exceeding the `-W` lsf walltime limit, and using a retryCount of 2, the job is not cleaned up from the `bjobs` output. Looks like there is a PID that doesn't belong to the toil leader somehow?

Can help debug this, just looking for some additional information.

```
DEBUG:toil.serviceManager:Waiting for service manager thread to finish ...
DEBUG:toil.serviceManager:Received signal to quit starting services.
DEBUG:toil.batchSystems.abstractGridEngineBatchSystem:No activity, sleeping for 1s
DEBUG:toil.serviceManager:... finished shutting down the service manager. Took 1.06528997421 seconds
DEBUG:toil.statsAndLogging:Waiting for stats and logging collator thread to finish ...
DEBUG:toil.statsAndLogging:... finished collating stats and logs. Took 0.317795991898 seconds
INFO:toil.leader:Finished toil run with 13 failed jobs.
INFO:toil.leader:Failed jobs at end of the run: 'CWLWorkflow' X/b/jobpr3C7T 'CWLScatter' P/y/job4RCcHx 'CWLScatter' B/2/job41V4zQ 'file:///home/johnsoni/pipeline_1.1.14/ACCESS-Pipeline/cwl_tools/python/list2bed.cwl' list2bed l/W/jobCCCy2N 'file:///home/johnsoni/pipeline_1.1.14/ACCESS-Pipeline/cwl_tools/expression_tools/group_bams.cwl' c/S/jobK20nfM 'CWLGather' s/7/jobcis2Dh 'CWLScatter' n/t/job6RttLc 'CWLWorkflow' 8/B/job9W7rzu 'file:///home/johnsoni/pipeline_1.1.14/ACCESS-Pipeline/cwl_tools/python/make_directory.cwl' Q/r/jobw6jqCz 'CWLWorkflow' j/9/jobimhTqP 'CWLGather' Y/Y/jobyJZUSE 'file:///home/johnsoni/pipeline_1.1.14/ACCESS-Pipeline/cwl_tools/abra/abra.cwl' R/H/job1pyH6x 'CWLWorkflow' I/6/jobfH6x1A
DEBUG:toil.common:Shutting down batch system ...
DEBUG:toil.common:Obtained node ID 8f60711f-e47f-4141-be7d-4b082f041fca from file /proc/sys/kernel/random/boot_id
Traceback (most recent call last):
  File "/home/johnsoni/virtualenvs/pipeline_1.1.14/bin/toil-cwl-runner", line 10, in <module>
    sys.exit(main())
  File "/home/johnsoni/virtualenvs/pipeline_1.1.14/lib/python2.7/site-packages/toil/cwl/cwltoil.py", line 1274, in main
    outobj = toil.start(wf1)
  File "/home/johnsoni/virtualenvs/pipeline_1.1.14/lib/python2.7/site-packages/toil/common.py", line 773, in start
    self._shutdownBatchSystem()
  File "/home/johnsoni/virtualenvs/pipeline_1.1.14/lib/python2.7/site-packages/toil/common.py", line 1054, in _shutdownBatchSystem
    self._batchSystem.shutdown()
  File "/home/johnsoni/virtualenvs/pipeline_1.1.14/lib/python2.7/site-packages/toil/batchSystems/abstractGridEngineBatchSystem.py", line 405, in shutdown
    self.shutdownLocal()
  File "/home/johnsoni/virtualenvs/pipeline_1.1.14/lib/python2.7/site-packages/toil/batchSystems/abstractBatchSystem.py", line 356, in shutdownLocal
DEBUG:toil.batchSystems.abstractGridEngineBatchSystem:No activity, sleeping for 1s
    self.localBatch.shutdown()
  File "/home/johnsoni/virtualenvs/pipeline_1.1.14/lib/python2.7/site-packages/toil/batchSystems/singleMachine.py", line 281, in shutdown
    BatchSystemSupport.workerCleanup(self.workerCleanupInfo)
  File "/home/johnsoni/virtualenvs/pipeline_1.1.14/lib/python2.7/site-packages/toil/batchSystems/abstractBatchSystem.py", line 293, in workerCleanup
    shutdownFileStore(workflowDir, info.workflowID)
  File "/home/johnsoni/virtualenvs/pipeline_1.1.14/lib/python2.7/site-packages/toil/fileStore.py", line 1953, in shutdownFileStore
    NonCachingFileStore.shutdown(workflowDir)
  File "/home/johnsoni/virtualenvs/pipeline_1.1.14/lib/python2.7/site-packages/toil/fileStore.py", line 1848, in shutdown
    cls.findAndHandleDeadJobs(dir_, batchSystemShutdown=True)
  File "/home/johnsoni/virtualenvs/pipeline_1.1.14/lib/python2.7/site-packages/toil/fileStore.py", line 1749, in findAndHandleDeadJobs
    if not cls._pidExists(jobState['jobPID']):
  File "/home/johnsoni/virtualenvs/pipeline_1.1.14/lib/python2.7/site-packages/toil/fileStore.py", line 420, in _pidExists
    os.kill(pid, 0)
OSError: [Errno 1] Operation not permitted
```

The toil leader job is not terminated on lsf cluster:
```
 $ bjobs
           JOBID         USER     JOB_NAME   STAT      QUEUE  FROM_HOST    EXEC_HOST   SUBMIT_TIME    START_TIME  TIME_LEFT
        19178412    accessbot *run-lane-3    RUN    general       juno         jx19  Sep 10 13:31  Sep 10 13:32    73:32 L
```

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-423)
┆Issue Number: TOIL-423

**Comment by adamnovak** [comment]
OK, the batch system has two components: a "local" one for running housekeeping work on the head node, and a real one that talks to LSF. The local one is crashing during shutdown, and the LSF shutdown isn't running.

The local one is crashing during shutdown because it is trying to poll a PID for existence (with kill with signal 0) and getting a permission denied error. It's possible that that PID was re-used between when Toil used it to (fail to) run a job and when it went to poll it for existence.

We should wrap that kill in a try/except and treating various OSErrors as the absence of the job.

The harder case is PID re-use when we *can* see that the other process exists, but it isn't actually the Toil worker we think it is. But we don't necessarily have to fix that here, since that's not the problem we're seeing.

**Comment by diekhans** [comment]
If Toil is probing for the existing of a process it didn't create, that seems very dangerous, as really has no way of knowing what process that is.

If Toil did create the process, it has had to do a waitpid for the PID to be recycled.  In this case, Toil has lost track of it own state and doing a try will just mask a bug.

**Comment by adamnovak** [comment]
What Toil is attempting to do is to coordinate between different Toil worker processes on the machine that may not share a Toil-controlled parent process. The file store wants to be able to have one Toil job on the machine, scheduled by one cluster job, journal its work in a file, and then have another Toil job on the machine, scheduled by a *different* cluster job, clean up after the first job if the first job happened to crash and the second job noticed. So it's not a case of a parent waiting on a child, and indeed we don't actually want to wait for the other process; we just want to know that it is alive and still responsible for what it says it is responsible for.

It can't ever be 100% reliable: you can be the final job on the machine, and fail, and not get your cleanup done. You can also be running at the same time as another job, and fail after it polls you. It's also, as currently implemented, foolable by PID re-use.

I think some of the relevant code might be being changed in https://github.com/DataBiosphere/toil/pull/2770 to use fcntl-based file locking instead of polling on PIDs, but that PR still uses a bunch of polling of PIDs in other places, which is still fundamentally unreliable.

**Comment by diekhans** [comment]
sigh ;-)

It would be a good to take a hard look at the design of the Toil process management and communication.  This seems like a serious flaw the will only happen on very large batches.

**Comment by melainalegaspi** [comment]
@ionox0 we think this was fixed, please re-open if this is still an issue.
