### ISSUE TITLE
toil-cwl-runner cannot parse default if parent workflow does not provide input

### ISSUE THREAD

**Issue by ionox0** [DataBiosphere/toil#2802]
Error log:
```
WARNING:toil.leader:9/C/job6PDNtG    WARNING:toil.resource:Can't globalize module ModuleDescriptor(dirPath='/home/johnsoni/virtualenvs/pipeline_1.2.6/lib/python2.7/site-packages', name='toil.cwl.cwltoil', fromVirtualEnv=True).
WARNING:toil.leader:9/C/job6PDNtG    DEBUG:toil.resource:Module dir is /home/johnsoni/virtualenvs/pipeline_1.2.6/lib/python2.7/site-packages
WARNING:toil.leader:9/C/job6PDNtG    WARNING:toil.resource:Can't globalize module ModuleDescriptor(dirPath='/home/johnsoni/virtualenvs/pipeline_1.2.6/lib/python2.7/site-packages', name='toil.cwl.cwltoil', fromVirtualEnv=True).
WARNING:toil.leader:9/C/job6PDNtG    DEBUG:toil.fileStore:LOG-TO-MASTER: Job 4/O/jobqSOorG/g/tmpQUrbBM-_serialiseJob-stream used 0.00% (1.5 KB [1536B] used, 10.0 GB [10737418240B] requested) at the end of its run.
WARNING:toil.leader:9/C/job6PDNtG    Traceback (most recent call last):
WARNING:toil.leader:9/C/job6PDNtG      File "/home/johnsoni/virtualenvs/pipeline_1.2.6/lib/python2.7/site-packages/toil/worker.py", line 324, in workerScript
WARNING:toil.leader:9/C/job6PDNtG        job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore)
WARNING:toil.leader:9/C/job6PDNtG      File "/home/johnsoni/virtualenvs/pipeline_1.2.6/lib/python2.7/site-packages/toil/job.py", line 1351, in _runner
WARNING:toil.leader:9/C/job6PDNtG        returnValues = self._run(jobGraph, fileStore)
WARNING:toil.leader:9/C/job6PDNtG      File "/home/johnsoni/virtualenvs/pipeline_1.2.6/lib/python2.7/site-packages/toil/job.py", line 1296, in _run
WARNING:toil.leader:9/C/job6PDNtG        return self.run(fileStore)
WARNING:toil.leader:9/C/job6PDNtG      File "/home/johnsoni/virtualenvs/pipeline_1.2.6/lib/python2.7/site-packages/toil/cwl/cwltoil.py", line 917, in run
WARNING:toil.leader:9/C/job6PDNtG        jobobj[key][0]] is None:
WARNING:toil.leader:9/C/job6PDNtG    KeyError: u'bam_compression_level'
WARNING:toil.leader:9/C/job6PDNtG    ERROR:toil.worker:Exiting the worker because of a failed job on host jx21
WARNING:toil.leader:9/C/job6PDNtG    WARNING:toil.jobGraph:Due to failure we are reducing the remaining retry count of job 'CWLWorkflow' 9/C/job6PDNtG with ID 9/C/job6PDNtG to 0
DEBUG:toil.leader:Added job: 'CWLWorkflow' 9/C/job6PDNtG to active jobs
DEBUG:toil.leader:Built the jobs list, currently have 1 jobs to update and 0 jobs issued
```

I believe that these lines from `cwltoil.py`:
```
                            if "default" in inp:
                                if key in jobobj:
                                    if isinstance(jobobj[key][1], Promise):
                                        d = copy.copy(inp["default"])
                                        jobobj[key] = DefaultWithSource(
                                            d, jobobj[key])
                                    else:
                                        if jobobj[key][1][
                                                jobobj[key][0]] is None:
                                            d = copy.copy(inp["default"])
                                            jobobj[key] = (
                                                "default", {"default": d})
                                else:
                                    d = copy.copy(inp["default"])
                                    jobobj[key] = ("default", {"default": d})
```

Should be change to:
```
                                        if hasattr(jobobj[key][1], jobobj[key][0]) and \
                                            and jobobj[key][1][jobobj[key][0]] is None:
                                                ...
```

but it's a bit hard to understand the difference between `jobobj[key][0]` and `jobobj[key][1]`

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-425)
┆Issue Number: TOIL-425

**Comment by ionox0** [comment]
I edited the title of this issue as I've found a minimally-reproducible example:

`tool.cwl`:
```
cwlVersion: v1.0

class: CommandLineTool

baseCommand: echo

inputs:

  input_one:
    type: int?
    inputBinding:
      position: 2

outputs: []
```

`subworkflow.cwl`:
```
cwlVersion: v1.0

class: Workflow

inputs:

  one: int?

outputs: []

steps:

  step_one:
    run: ./tool.cwl
    in:
      input_one:
        source: one
        default: 2
    out: []
```

`parent_workflow.cwl`:
```
cwlVersion: v1.0

class: Workflow

requirements:
  SubworkflowFeatureRequirement: {}

inputs:

  one: int?

outputs: []

steps:

  step_one:
    run: ./child.cwl
    in: []
#      one:
#        source: one
#        default: 1
    out: []
```

The difference between this workflow passing and failing is based on the presence of the input `one` in the parent workflow, and without it the following error occurs:

```
WARNING:toil.leader:c/r/jobqzOvP3    Traceback (most recent call last):
WARNING:toil.leader:c/r/jobqzOvP3      File "/Users/johnsoni/.virtualenvs/toil/lib/python2.7/site-packages/toil/worker.py", line 324, in workerScript
WARNING:toil.leader:c/r/jobqzOvP3        job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore)
WARNING:toil.leader:c/r/jobqzOvP3      File "/Users/johnsoni/.virtualenvs/toil/lib/python2.7/site-packages/toil/job.py", line 1351, in _runner
WARNING:toil.leader:c/r/jobqzOvP3        returnValues = self._run(jobGraph, fileStore)
WARNING:toil.leader:c/r/jobqzOvP3      File "/Users/johnsoni/.virtualenvs/toil/lib/python2.7/site-packages/toil/job.py", line 1296, in _run
WARNING:toil.leader:c/r/jobqzOvP3        return self.run(fileStore)
WARNING:toil.leader:c/r/jobqzOvP3      File "/Users/johnsoni/.virtualenvs/toil/lib/python2.7/site-packages/toil/cwl/cwltoil.py", line 917, in run
WARNING:toil.leader:c/r/jobqzOvP3        jobobj[key][0]] is None:
WARNING:toil.leader:c/r/jobqzOvP3    KeyError: u'one'
WARNING:toil.leader:c/r/jobqzOvP3    ERROR:toil.worker:Exiting the worker because of a failed job on host lski2427
WARNING:toil.leader:c/r/jobqzOvP3    WARNING:toil.jobGraph:Due to failure we are reducing the remaining retry count of job 'CWLWorkflow' c/r/jobqzOvP3 with ID c/r/jobqzOvP3 to 0
```

It is not present with cwltool, which runs successfully

**Comment by ionox0** [comment]
I'm not sure what the expected behavior should be, but it might be an improvement from a usability perspective if missing inputs from parent workflows still had defaults applied

**Comment by mr-c** [comment]
Reviewing the standard, I believe `cwltool`'s behaviour here is correct, and this is a bug in the toil-cwl-runner. We should make a conformance test out of this!

@ionox0  Do the rest of the CWL conformance tests still pass with your proposed changes?

**Comment by ionox0** [comment]
Yes I'll submit a PR, I believe it should prevent the error but I'll need to make sure about the conformance tests!

**Comment by DailyDreaming** [comment]
I'm assuming that this was included in the cwl conformance tests and thus is a test that we run now.  Closing, please reopen if this is still an issue.

**Comment by adamnovak** [comment]
I guess this never did make it into the conformance tests, @mr-c?

**Comment by mr-c** [comment]
assigned to myself

**Comment by ionox0** [comment]
This appears to have been fixed since we've upgraded to toil 5

**Comment by adamnovak** [comment]
If this is fixed in Toil 5 then I am going to close this.
