### ISSUE TITLE
ReadTheDocs example failing

### ISSUE THREAD

**Issue by azzaea** [DataBiosphere/toil#2803]
┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-426)
┆Issue Number: TOIL-426

**Comment by azzaea** [comment]
The class-based hello world example (not wrapping python functions) seems to be failing unexpectedly [here](https://toil.readthedocs.io/en/latest/developingWorkflows/developing.html#invoking-a-workflow)

```
(toil) 1 azza:learning-toil⟫ python hello.class.py 
DEBUG:toil.resource:Discovering real name of module
DEBUG:toil.resource:Module dir is /home/azza/github_repos/learning-toil
DEBUG:toil.jobStores.fileJobStore:Path to job store directory is '/home/azza/github_repos/learning-toil/toilWorkflowRun'.
DEBUG:toil.jobStores.fileJobStore:Path to job store directory is '/home/azza/github_repos/learning-toil/toilWorkflowRun'.
Traceback (most recent call last):
  File "hello.class.py", line 20, in <module>
    print(toil.start(hello_job))
  File "/home/azza/pythonenvs/toil/lib/python2.7/site-packages/toil/common.py", line 781, in start
    return self._runMainLoop(rootJobGraph)
  File "/home/azza/pythonenvs/toil/lib/python2.7/site-packages/toil/common.py", line 1054, in _runMainLoop
    jobCache=self._jobCache).run()
  File "/home/azza/pythonenvs/toil/lib/python2.7/site-packages/toil/leader.py", line 246, in run
    raise FailedJobsException(self.config.jobStore, self.toilState.totalFailedJobs, self.jobStore)
toil.leader.FailedJobsException
```

**Comment by adamnovak** [comment]
It's complaining that a job failed at the end, but not saying anything
about why.

Can you drop the options.logLevel = "OFF" line and run it again?

**Comment by azzaea** [comment]
Thank you @adamnovak ! Yes, kindly find the log below:
```
DEBUG:toil.resource:Discovering real name of module
DEBUG:toil.resource:Module dir is /home/azza/github_repos/learning-toil
WARNING:toil.batchSystems.singleMachine:Limiting maxCores to CPU count of system (4).
WARNING:toil.batchSystems.singleMachine:Limiting maxMemory to physically available memory (6141358080).
WARNING:toil.batchSystems.singleMachine:Limiting maxDisk to physically available disk (7654871040).
INFO:toil:Running Toil version 3.20.0-cf34ca3416697f2abc816b2538f20ee29ba16932.
INFO:toil.leader:Issued job 'HelloWorld' o/i/job6NO_kl with job batch system ID: 0 and cores: 2, disk: 3.0 G, and memory: 2.0 G
DEBUG:toil.jobStores.fileJobStore:Path to job store directory is '/home/azza/github_repos/learning-toil/toilWorkflowRun'.
INFO:toil.worker:Redirecting logging to /tmp/toil-604e5a93-4682-4464-a7db-81ba7421dcda-2a77c9e44cbe4a17b74b11479a5c5836/tmpZwVv1c/worker_log.txt
INFO:toil.leader:Job ended successfully: 'HelloWorld' o/i/job6NO_kl
WARNING:toil.leader:The job seems to have left a log file, indicating failure: 'HelloWorld' o/i/job6NO_kl
WARNING:toil.leader:o/i/job6NO_kl    INFO:toil.worker:---TOIL WORKER OUTPUT LOG---
WARNING:toil.leader:o/i/job6NO_kl    INFO:toil:Running Toil version 3.20.0-cf34ca3416697f2abc816b2538f20ee29ba16932.
WARNING:toil.leader:o/i/job6NO_kl    WARNING:toil.resource:'JTRES_7cd590743af63a63e2c782b719102240' may exist, but is not yet referenced by the worker (KeyError from os.environ[]).
WARNING:toil.leader:o/i/job6NO_kl    ERROR:toil.resource:Failed to import user module ModuleDescriptor(dirPath=u'/home/azza/github_repos/learning-toil', name=u'hello.class', fromVirtualEnv=False) from sys.path (['/home/azza/pythonenvs/toil/bin', '/home/azza/pythonenvs/toil/lib/python2.7', '/home/azza/pythonenvs/toil/lib/python2.7/plat-x86_64-linux-gnu', '/home/azza/pythonenvs/toil/lib/python2.7/lib-tk', '/home/azza/pythonenvs/toil/lib/python2.7/lib-old', '/home/azza/pythonenvs/toil/lib/python2.7/lib-dynload', '/home/azza/anaconda2/lib/python2.7', '/home/azza/anaconda2/lib/python2.7/lib-tk', '/home/azza/pythonenvs/toil/lib/python2.7/site-packages', u'/home/azza/github_repos/learning-toil']).
WARNING:toil.leader:o/i/job6NO_kl    Traceback (most recent call last):
WARNING:toil.leader:o/i/job6NO_kl      File "/home/azza/pythonenvs/toil/lib/python2.7/site-packages/toil/worker.py", line 316, in workerScript
WARNING:toil.leader:o/i/job6NO_kl        job = Job._loadJob(jobGraph.command, jobStore)
WARNING:toil.leader:o/i/job6NO_kl      File "/home/azza/pythonenvs/toil/lib/python2.7/site-packages/toil/job.py", line 910, in _loadJob
WARNING:toil.leader:o/i/job6NO_kl        userModule = cls._loadUserModule(userModule)
WARNING:toil.leader:o/i/job6NO_kl      File "/home/azza/pythonenvs/toil/lib/python2.7/site-packages/toil/job.py", line 887, in _loadUserModule
WARNING:toil.leader:o/i/job6NO_kl        return userModule.load()
WARNING:toil.leader:o/i/job6NO_kl      File "/home/azza/pythonenvs/toil/lib/python2.7/site-packages/toil/resource.py", line 597, in load
WARNING:toil.leader:o/i/job6NO_kl        return importlib.import_module(module.name)
WARNING:toil.leader:o/i/job6NO_kl      File "/home/azza/anaconda2/lib/python2.7/importlib/__init__.py", line 37, in import_module
WARNING:toil.leader:o/i/job6NO_kl        __import__(name)
WARNING:toil.leader:o/i/job6NO_kl    ImportError: No module named class
WARNING:toil.leader:o/i/job6NO_kl    ERROR:toil.worker:Exiting the worker because of a failed job on host azza-Satellite-P845
WARNING:toil.leader:o/i/job6NO_kl    WARNING:toil.jobGraph:Due to failure we are reducing the remaining retry count of job 'HelloWorld' o/i/job6NO_kl with ID o/i/job6NO_kl to 1
INFO:toil.leader:Issued job 'HelloWorld' o/i/job6NO_kl with job batch system ID: 1 and cores: 2, disk: 3.0 G, and memory: 2.0 G
DEBUG:toil.jobStores.fileJobStore:Path to job store directory is '/home/azza/github_repos/learning-toil/toilWorkflowRun'.
INFO:toil.worker:Redirecting logging to /tmp/toil-604e5a93-4682-4464-a7db-81ba7421dcda-2a77c9e44cbe4a17b74b11479a5c5836/tmpWJDar_/worker_log.txt
INFO:toil.leader:Job ended successfully: 'HelloWorld' o/i/job6NO_kl
WARNING:toil.leader:The job seems to have left a log file, indicating failure: 'HelloWorld' o/i/job6NO_kl
WARNING:toil.leader:o/i/job6NO_kl    INFO:toil.worker:---TOIL WORKER OUTPUT LOG---
WARNING:toil.leader:o/i/job6NO_kl    INFO:toil:Running Toil version 3.20.0-cf34ca3416697f2abc816b2538f20ee29ba16932.
WARNING:toil.leader:o/i/job6NO_kl    WARNING:toil.resource:'JTRES_7cd590743af63a63e2c782b719102240' may exist, but is not yet referenced by the worker (KeyError from os.environ[]).
WARNING:toil.leader:o/i/job6NO_kl    ERROR:toil.resource:Failed to import user module ModuleDescriptor(dirPath=u'/home/azza/github_repos/learning-toil', name=u'hello.class', fromVirtualEnv=False) from sys.path (['/home/azza/pythonenvs/toil/bin', '/home/azza/pythonenvs/toil/lib/python2.7', '/home/azza/pythonenvs/toil/lib/python2.7/plat-x86_64-linux-gnu', '/home/azza/pythonenvs/toil/lib/python2.7/lib-tk', '/home/azza/pythonenvs/toil/lib/python2.7/lib-old', '/home/azza/pythonenvs/toil/lib/python2.7/lib-dynload', '/home/azza/anaconda2/lib/python2.7', '/home/azza/anaconda2/lib/python2.7/lib-tk', '/home/azza/pythonenvs/toil/lib/python2.7/site-packages', u'/home/azza/github_repos/learning-toil']).
WARNING:toil.leader:o/i/job6NO_kl    Traceback (most recent call last):
WARNING:toil.leader:o/i/job6NO_kl      File "/home/azza/pythonenvs/toil/lib/python2.7/site-packages/toil/worker.py", line 316, in workerScript
WARNING:toil.leader:o/i/job6NO_kl        job = Job._loadJob(jobGraph.command, jobStore)
WARNING:toil.leader:o/i/job6NO_kl      File "/home/azza/pythonenvs/toil/lib/python2.7/site-packages/toil/job.py", line 910, in _loadJob
WARNING:toil.leader:o/i/job6NO_kl        userModule = cls._loadUserModule(userModule)
WARNING:toil.leader:o/i/job6NO_kl      File "/home/azza/pythonenvs/toil/lib/python2.7/site-packages/toil/job.py", line 887, in _loadUserModule
WARNING:toil.leader:o/i/job6NO_kl        return userModule.load()
WARNING:toil.leader:o/i/job6NO_kl      File "/home/azza/pythonenvs/toil/lib/python2.7/site-packages/toil/resource.py", line 597, in load
WARNING:toil.leader:o/i/job6NO_kl        return importlib.import_module(module.name)
WARNING:toil.leader:o/i/job6NO_kl      File "/home/azza/anaconda2/lib/python2.7/importlib/__init__.py", line 37, in import_module
WARNING:toil.leader:o/i/job6NO_kl        __import__(name)
WARNING:toil.leader:o/i/job6NO_kl    ImportError: No module named class
WARNING:toil.leader:o/i/job6NO_kl    ERROR:toil.worker:Exiting the worker because of a failed job on host azza-Satellite-P845
WARNING:toil.leader:o/i/job6NO_kl    WARNING:toil.jobGraph:Due to failure we are reducing the remaining retry count of job 'HelloWorld' o/i/job6NO_kl with ID o/i/job6NO_kl to 0
WARNING:toil.leader:Job 'HelloWorld' o/i/job6NO_kl with ID o/i/job6NO_kl is completely failed
INFO:toil.leader:Finished toil run with 1 failed jobs.
INFO:toil.leader:Failed jobs at end of the run: 'HelloWorld' o/i/job6NO_kl
INFO:toil.common:Successfully deleted the job store: FileJobStore(/home/azza/github_repos/learning-toil/toilWorkflowRun)
Traceback (most recent call last):
  File "hello.class.py", line 20, in <module>
    print(toil.start(hello_job))
  File "/home/azza/pythonenvs/toil/lib/python2.7/site-packages/toil/common.py", line 781, in start
    return self._runMainLoop(rootJobGraph)
  File "/home/azza/pythonenvs/toil/lib/python2.7/site-packages/toil/common.py", line 1054, in _runMainLoop
    jobCache=self._jobCache).run()
  File "/home/azza/pythonenvs/toil/lib/python2.7/site-packages/toil/leader.py", line 246, in run
    raise FailedJobsException(self.config.jobStore, self.toilState.totalFailedJobs, self.jobStore)
toil.leader.FailedJobsException
```

**Comment by adamnovak** [comment]
I think your problem is that you have dots in your filename that you
have saved the example under. Your Python file needs to be named such
that another python file sitting next to it could import stuff from
it. If you did that here you would end up trying to say something like
"import hello.class", which to Python means it should look for
"hello.py" or "hello/__init__.py", neither of which exist.

We have this requirement because Toil needs to start up a new Python
process but then get access to types and functions defined in your
file (in this case, the class that represents the job). So Toil has to
import your code in the new process, and it does this by grabbing the
module name and then running import on it. But import tries to parse
the dots and goes looking for a module that doesn't exist.

I think we need to make Toil throw an error when the user script file
name has dots in it, and complain that it won't be able to import the
user code when it needs it.

The workaround is to remove all dots from the user script filename
except the one in ".py".

**Comment by azzaea** [comment]
This makes sense, thank you much- it did work!

But yes, an error message to the command (or even a warning box in the python-based toil scripts [documentation page](https://github.com/DataBiosphere/toil/blob/master/docs/developingWorkflows/developing.rst)) would make it clearer to users.

Again, thank you for your help, and most importantly, for explaining the rationale of the design. 

I'm happy to close this ticket, or maybe leave it open till documentation is updated at least? Just created a pull request as such
