### ISSUE TITLE
[kubernetes] Could not obtain AWS credentials from Boto3. 

### ISSUE THREAD

**Issue by jeffrey856** [DataBiosphere/toil#2818]
@adamnovak 
For Kubernetes PR #2786  
This is the full error:

```
(venv) eduroam-169-233-194-195:toil mymac$ TOIL_APPLIANCE_SELF=quay.io/adamnovak/toil:3.21.0a1-f2557fdc404a7267c3801faa0849d476f3674793 python examples/hello.py --logInfo --realTimeLogging --batchSystem kubernetes aws:us-west-2:jwu157-toiltest2 || toil clean aws:us-west-2:jwu157-toiltest2
/Users/mymac/venv/lib/python2.7/site-packages/cwltool/__init__.py:17: CWLToolDeprecationWarning: 
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020.
Please upgrade your Python as the Python 2.7 version of cwltool won't be
maintained after that date.

  """,  category=CWLToolDeprecationWarning)
eduroam-169-233-194-195.ucsc.edu 2019-10-17 15:54:05,301 MainThread INFO botocore.credentials: Found credentials in shared credentials file: ~/.aws/credentials
eduroam-169-233-194-195.ucsc.edu 2019-10-17 15:54:11,019 MainThread WARNING toil.batchSystems.singleMachine: Limiting maxMemory to physically available memory (17179869184).
eduroam-169-233-194-195.ucsc.edu 2019-10-17 15:54:11,027 MainThread WARNING toil.batchSystems.singleMachine: Limiting maxDisk to physically available disk (905322430464).
eduroam-169-233-194-195.ucsc.edu 2019-10-17 15:54:11,053 MainThread INFO toil: Using default docker registry of quay.io/jeffrey856 as TOIL_DOCKER_REGISTRY is not set.
eduroam-169-233-194-195.ucsc.edu 2019-10-17 15:54:11,053 MainThread INFO toil: Using default docker name of toil as TOIL_DOCKER_NAME is not set.
eduroam-169-233-194-195.ucsc.edu 2019-10-17 15:54:11,053 MainThread INFO toil: Overriding docker appliance of quay.io/jeffrey856/toil:3.21.0a1-f2557fdc404a7267c3801faa0849d476f3674793-dirty with quay.io/adamnovak/toil:3.21.0a1-f2557fdc404a7267c3801faa0849d476f3674793 from TOIL_APPLIANCE_SELF.
eduroam-169-233-194-195.ucsc.edu 2019-10-17 15:54:13,539 MainThread INFO toil: Running Toil version 3.21.0a1-f2557fdc404a7267c3801faa0849d476f3674793-dirty.
eduroam-169-233-194-195.ucsc.edu 2019-10-17 15:54:13,539 MainThread INFO toil.realtimeLogger: Starting real-time logging.
eduroam-169-233-194-195.ucsc.edu 2019-10-17 15:54:13,773 MainThread INFO toil.leader: Issued job 'HelloWorld' 75dd65fc-473e-40dd-84d7-e24d9a81622c with job batch system ID: 0 and cores: 2, disk: 2.0 G, and memory: 1.0 G
eduroam-169-233-194-195.ucsc.edu 2019-10-17 15:54:22,921 MainThread WARNING toil.batchSystems.kubernetes: Log from failed pod: /usr/local/lib/python2.7/dist-packages/cwltool/__init__.py:17: CWLToolDeprecationWarning: 
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020.
Please upgrade your Python as the Python 2.7 version of cwltool won't be
maintained after that date.

  """,  category=CWLToolDeprecationWarning)
DEBUG:toil.batchSystems.kubernetes:Starting executor
DEBUG:toil.batchSystems.kubernetes:Preparing system for resource download
DEBUG:toil.batchSystems.kubernetes:Invoking command: '_toil_worker HelloWorld aws:us-west-2:jwu157-toiltest2 75dd65fc-473e-40dd-84d7-e24d9a81622c'
DEBUG:toil.batchSystems.kubernetes:Using environment variables: ['KUBERNETES_SERVICE_PORT', 'TOIL_RT_LOGGING_ADDRESS', 'TERM', 'HOSTNAME', 'KUBERNETES_PORT_443_TCP_ADDR', 'KUBERNETES_SERVICE_HOST', 'KUBERNETES_PORT_443_TCP', 'KUBERNETES_PORT_443_TCP_PROTO', 'JTRES_49c85cd6c4258954d4c5d71e813c7d3f', 'PATH', 'SHELL', 'TOIL_RT_LOGGING_LEVEL', 'JTRES_ROOT', 'TOIL_APPLIANCE_SELF', 'HOME', 'KUBERNETES_PORT', 'KUBERNETES_PORT_443_TCP_PORT', 'MESOS_LAUNCHER', 'KUBERNETES_SERVICE_PORT_HTTPS', 'TOIL_WORKDIR']
/usr/local/lib/python2.7/dist-packages/cwltool/__init__.py:17: CWLToolDeprecationWarning: 
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020.
Please upgrade your Python as the Python 2.7 version of cwltool won't be
maintained after that date.

  """,  category=CWLToolDeprecationWarning)
Traceback (most recent call last):
  File "/usr/local/bin/_toil_worker", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/toil/worker.py", line 565, in main
    jobStore = Toil.resumeJobStore(jobStoreLocator)
  File "/usr/local/lib/python2.7/dist-packages/toil/common.py", line 890, in resumeJobStore
    jobStore = cls.getJobStore(locator)
  File "/usr/local/lib/python2.7/dist-packages/toil/common.py", line 861, in getJobStore
    return AWSJobStore(rest)
  File "/usr/local/lib/python2.7/dist-packages/toil/jobStores/aws/jobStore.py", line 135, in __init__
    self.db = self._connectSimpleDB()
  File "/usr/local/lib/python2.7/dist-packages/toil/jobStores/aws/jobStore.py", line 669, in _connectSimpleDB
    db = boto.sdb.connect_to_region(self.region)
  File "/usr/local/lib/python2.7/dist-packages/boto/sdb/__init__.py", line 53, in connect_to_region
    return connect('sdb', region_name, region_cls=SDBRegionInfo, **kw_params)
  File "/usr/local/lib/python2.7/dist-packages/boto/regioninfo.py", line 220, in connect
    return region.connect(**kw_params)
  File "/usr/local/lib/python2.7/dist-packages/boto/regioninfo.py", line 290, in connect
    return self.connection_cls(region=self, **kw_params)
  File "/usr/local/lib/python2.7/dist-packages/boto/sdb/connection.py", line 122, in __init__
    profile_name=profile_name)
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1100, in __init__
    provider=provider)
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 555, in __init__
    profile_name)
  File "/usr/local/lib/python2.7/dist-packages/toil/__init__.py", line 491, in __init__
    profile_name=profile_name, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/boto/provider.py", line 201, in __init__
    self.get_credentials(access_key, secret_key, security_token, profile_name)
  File "/usr/local/lib/python2.7/dist-packages/toil/__init__.py", line 503, in get_credentials
    self._obtain_credentials_from_cache_or_boto3()
  File "/usr/local/lib/python2.7/dist-packages/toil/__init__.py", line 630, in _obtain_credentials_from_cache_or_boto3
    self._obtain_credentials_from_boto3()
  File "/usr/local/lib/python2.7/dist-packages/toil/__init__.py", line 552, in _obtain_credentials_from_boto3
    raise RuntimeError("Could not obtain AWS credentials from Boto3. Resolvers tried: " + resolvers)
RuntimeError: Could not obtain AWS credentials from Boto3. Resolvers tried: [<botocore.credentials.EnvProvider object at 0x7f960ca8ce90>, <botocore.credentials.AssumeRoleProvider object at 0x7f960ca90310>, <botocore.credentials.AssumeRoleWithWebIdentityProvider object at 0x7f960ca90350>, <botocore.credentials.SharedCredentialProvider object at 0x7f960ca90390>, <botocore.credentials.ProcessProvider object at 0x7f960ca903d0>, <botocore.credentials.ConfigProvider object at 0x7f960ca90410>, <botocore.credentials.OriginalEC2Provider object at 0x7f960ca90450>, <botocore.credentials.BotoProvider object at 0x7f960ca90490>, <botocore.credentials.ContainerProvider object at 0x7f960ca8ced0>, <botocore.credentials.InstanceMetadataProvider object at 0x7f960ca90250>]

eduroam-169-233-194-195.ucsc.edu 2019-10-17 15:54:22,964 MainThread WARNING toil.leader: Job failed with exit value 1: 'HelloWorld' 75dd65fc-473e-40dd-84d7-e24d9a81622c
eduroam-169-233-194-195.ucsc.edu 2019-10-17 15:54:23,071 MainThread WARNING toil.leader: No log file is present, despite job failing: 'HelloWorld' 75dd65fc-473e-40dd-84d7-e24d9a81622c
eduroam-169-233-194-195.ucsc.edu 2019-10-17 15:54:23,072 MainThread WARNING toil.jobGraph: Due to failure we are reducing the remaining retry count of job 'HelloWorld' 75dd65fc-473e-40dd-84d7-e24d9a81622c with ID 75dd65fc-473e-40dd-84d7-e24d9a81622c to 1
eduroam-169-233-194-195.ucsc.edu 2019-10-17 15:54:23,072 MainThread WARNING toil.jobGraph: We have increased the default memory of the failed job 'HelloWorld' 75dd65fc-473e-40dd-84d7-e24d9a81622c to 2147483648 bytes
eduroam-169-233-194-195.ucsc.edu 2019-10-17 15:54:23,196 MainThread INFO toil.leader: Issued job 'HelloWorld' 75dd65fc-473e-40dd-84d7-e24d9a81622c with job batch system ID: 1 and cores: 2, disk: 2.0 G, and memory: 2.0 G
eduroam-169-233-194-195.ucsc.edu 2019-10-17 15:54:31,870 MainThread WARNING toil.batchSystems.kubernetes: Log from failed pod: /usr/local/lib/python2.7/dist-packages/cwltool/__init__.py:17: CWLToolDeprecationWarning: 
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020.
Please upgrade your Python as the Python 2.7 version of cwltool won't be
maintained after that date.

  """,  category=CWLToolDeprecationWarning)
DEBUG:toil.batchSystems.kubernetes:Starting executor
DEBUG:toil.batchSystems.kubernetes:Preparing system for resource download
DEBUG:toil.batchSystems.kubernetes:Invoking command: '_toil_worker HelloWorld aws:us-west-2:jwu157-toiltest2 75dd65fc-473e-40dd-84d7-e24d9a81622c'
DEBUG:toil.batchSystems.kubernetes:Using environment variables: ['KUBERNETES_SERVICE_PORT', 'TOIL_RT_LOGGING_ADDRESS', 'TERM', 'HOSTNAME', 'KUBERNETES_PORT_443_TCP_ADDR', 'KUBERNETES_SERVICE_HOST', 'KUBERNETES_PORT_443_TCP', 'KUBERNETES_PORT_443_TCP_PROTO', 'JTRES_49c85cd6c4258954d4c5d71e813c7d3f', 'PATH', 'SHELL', 'TOIL_RT_LOGGING_LEVEL', 'JTRES_ROOT', 'TOIL_APPLIANCE_SELF', 'HOME', 'KUBERNETES_PORT', 'KUBERNETES_PORT_443_TCP_PORT', 'MESOS_LAUNCHER', 'KUBERNETES_SERVICE_PORT_HTTPS', 'TOIL_WORKDIR']
/usr/local/lib/python2.7/dist-packages/cwltool/__init__.py:17: CWLToolDeprecationWarning: 
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020.
Please upgrade your Python as the Python 2.7 version of cwltool won't be
maintained after that date.

  """,  category=CWLToolDeprecationWarning)
Traceback (most recent call last):
  File "/usr/local/bin/_toil_worker", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/toil/worker.py", line 565, in main
    jobStore = Toil.resumeJobStore(jobStoreLocator)
  File "/usr/local/lib/python2.7/dist-packages/toil/common.py", line 890, in resumeJobStore
    jobStore = cls.getJobStore(locator)
  File "/usr/local/lib/python2.7/dist-packages/toil/common.py", line 861, in getJobStore
    return AWSJobStore(rest)
  File "/usr/local/lib/python2.7/dist-packages/toil/jobStores/aws/jobStore.py", line 135, in __init__
    self.db = self._connectSimpleDB()
  File "/usr/local/lib/python2.7/dist-packages/toil/jobStores/aws/jobStore.py", line 669, in _connectSimpleDB
    db = boto.sdb.connect_to_region(self.region)
  File "/usr/local/lib/python2.7/dist-packages/boto/sdb/__init__.py", line 53, in connect_to_region
    return connect('sdb', region_name, region_cls=SDBRegionInfo, **kw_params)
  File "/usr/local/lib/python2.7/dist-packages/boto/regioninfo.py", line 220, in connect
    return region.connect(**kw_params)
  File "/usr/local/lib/python2.7/dist-packages/boto/regioninfo.py", line 290, in connect
    return self.connection_cls(region=self, **kw_params)
  File "/usr/local/lib/python2.7/dist-packages/boto/sdb/connection.py", line 122, in __init__
    profile_name=profile_name)
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1100, in __init__
    provider=provider)
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 555, in __init__
    profile_name)
  File "/usr/local/lib/python2.7/dist-packages/toil/__init__.py", line 491, in __init__
    profile_name=profile_name, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/boto/provider.py", line 201, in __init__
    self.get_credentials(access_key, secret_key, security_token, profile_name)
  File "/usr/local/lib/python2.7/dist-packages/toil/__init__.py", line 503, in get_credentials
    self._obtain_credentials_from_cache_or_boto3()
  File "/usr/local/lib/python2.7/dist-packages/toil/__init__.py", line 630, in _obtain_credentials_from_cache_or_boto3
    self._obtain_credentials_from_boto3()
  File "/usr/local/lib/python2.7/dist-packages/toil/__init__.py", line 552, in _obtain_credentials_from_boto3
    raise RuntimeError("Could not obtain AWS credentials from Boto3. Resolvers tried: " + resolvers)
RuntimeError: Could not obtain AWS credentials from Boto3. Resolvers tried: [<botocore.credentials.EnvProvider object at 0x7f007c78de90>, <botocore.credentials.AssumeRoleProvider object at 0x7f007c791310>, <botocore.credentials.AssumeRoleWithWebIdentityProvider object at 0x7f007c791350>, <botocore.credentials.SharedCredentialProvider object at 0x7f007c791390>, <botocore.credentials.ProcessProvider object at 0x7f007c7913d0>, <botocore.credentials.ConfigProvider object at 0x7f007c791410>, <botocore.credentials.OriginalEC2Provider object at 0x7f007c791450>, <botocore.credentials.BotoProvider object at 0x7f007c791490>, <botocore.credentials.ContainerProvider object at 0x7f007c78ded0>, <botocore.credentials.InstanceMetadataProvider object at 0x7f007c791250>]

eduroam-169-233-194-195.ucsc.edu 2019-10-17 15:54:31,912 MainThread WARNING toil.leader: Job failed with exit value 1: 'HelloWorld' 75dd65fc-473e-40dd-84d7-e24d9a81622c
eduroam-169-233-194-195.ucsc.edu 2019-10-17 15:54:32,012 MainThread WARNING toil.leader: No log file is present, despite job failing: 'HelloWorld' 75dd65fc-473e-40dd-84d7-e24d9a81622c
eduroam-169-233-194-195.ucsc.edu 2019-10-17 15:54:32,013 MainThread WARNING toil.jobGraph: Due to failure we are reducing the remaining retry count of job 'HelloWorld' 75dd65fc-473e-40dd-84d7-e24d9a81622c with ID 75dd65fc-473e-40dd-84d7-e24d9a81622c to 0
eduroam-169-233-194-195.ucsc.edu 2019-10-17 15:54:32,083 MainThread WARNING toil.leader: Job 'HelloWorld' 75dd65fc-473e-40dd-84d7-e24d9a81622c with ID 75dd65fc-473e-40dd-84d7-e24d9a81622c is completely failed
eduroam-169-233-194-195.ucsc.edu 2019-10-17 15:54:34,660 MainThread INFO toil.leader: Finished toil run with 1 failed jobs.
eduroam-169-233-194-195.ucsc.edu 2019-10-17 15:54:34,660 MainThread INFO toil.leader: Failed jobs at end of the run: 'HelloWorld' 75dd65fc-473e-40dd-84d7-e24d9a81622c
eduroam-169-233-194-195.ucsc.edu 2019-10-17 15:54:34,709 MainThread INFO toil.realtimeLogger: Stopping real-time logging server.
eduroam-169-233-194-195.ucsc.edu 2019-10-17 15:54:35,164 MainThread INFO toil.realtimeLogger: Joining real-time logging server thread.
Traceback (most recent call last):
  File "examples/hello.py", line 19, in <module>
    print(toil.start(hello_job))
  File "/Users/mymac/UCSC/toil/src/toil/common.py", line 798, in start
    return self._runMainLoop(rootJobGraph)
  File "/Users/mymac/UCSC/toil/src/toil/common.py", line 1071, in _runMainLoop
    jobCache=self._jobCache).run()
  File "/Users/mymac/UCSC/toil/src/toil/leader.py", line 246, in run
    raise FailedJobsException(self.config.jobStore, self.toilState.totalFailedJobs, self.jobStore)
toil.leader.FailedJobsException
/Users/mymac/venv/lib/python2.7/site-packages/cwltool/__init__.py:17: CWLToolDeprecationWarning: 
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020.
Please upgrade your Python as the Python 2.7 version of cwltool won't be
maintained after that date.

  """,  category=CWLToolDeprecationWarning)
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:toil.utils.toilClean:Successfully deleted the job store: aws:us-west-2:jwu157-toiltest2
```

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-435)
┆Issue Number: TOIL-435

**Comment by adamnovak** [comment]
OK, this does look exactly like the problem I was having, except you are getting it from Toil itself.

The underlying problem is that it is looking in `$HOME` for `.aws/credentials`, and it is using the `$HOME` that yiu have set on your machine rather than the right one to use on the workers.

I fixed this in https://github.com/DataBiosphere/toil/commit/0d1f0a0f835dbaef8a78b1db2ff58995a200b33e and if you use `TOIL_APPLIANCE_SELF=quay.io/adamnovak/toil:3.21.0a1-9f59f70d3424b6c7944a9ff9dc4cbdb96ba91e0b-dirty` or build your own Docker containers with the current code, you should not have this problem anymore.

Please reopen if the issue persists!
