### ISSUE TITLE
toil launch-cluster --provisioner gce fails with "The referenced image resource cannot be found"

### ISSUE THREAD

**Issue by dleehr** [DataBiosphere/toil#2827]
With a pip-installed toil 3.2.0, attempting to launch a Google Cloud cluster fails due to referencing a CoreOS boot image (coreos-stable-1576-4-0-v20171206) that is no longer available:

```
$ toil --version
3.20.0

$ toil launch-cluster gce-demo --provisioner gce --leaderNodeType n1-standard-1 --keyPairName dcl9 --zone us-central1-b
INFO:toil:Using default docker registry of quay.io/ucsc_cgl as TOIL_DOCKER_REGISTRY is not set.
INFO:toil:Using default docker name of toil as TOIL_DOCKER_NAME is not set.
INFO:toil:Overriding docker appliance of quay.io/ucsc_cgl/toil:3.20.0-cf34ca3416697f2abc816b2538f20ee29ba16932 with quay.io/ucsc_cgl/toil:latest from TOIL_APPLIANCE_SELF.
INFO:toil:Using default user-defined custom docker init command of  as TOIL_CUSTOM_DOCKER_INIT_COMMAND is not set.
INFO:toil:Using default docker registry of quay.io/ucsc_cgl as TOIL_DOCKER_REGISTRY is not set.
INFO:toil:Using default docker name of toil as TOIL_DOCKER_NAME is not set.
INFO:toil:Overriding docker appliance of quay.io/ucsc_cgl/toil:3.20.0-cf34ca3416697f2abc816b2538f20ee29ba16932 with quay.io/ucsc_cgl/toil:latest from TOIL_APPLIANCE_SELF.
Traceback (most recent call last):
  File "/Users/dcl9/Code/toil/env/bin/toil", line 8, in <module>
    sys.exit(main())
  File "/Users/dcl9/Code/toil/env/lib/python2.7/site-packages/toil/utils/toilMain.py", line 35, in main
    module.main()
  File "/Users/dcl9/Code/toil/env/lib/python2.7/site-packages/toil/utils/toilLaunchCluster.py", line 162, in main
    awsEc2ProfileArn=config.awsEc2ProfileArn)
  File "/Users/dcl9/Code/toil/env/lib/python2.7/site-packages/toil/provisioners/gceProvisioner.py", line 157, in launchCluster
    ex_preemptible=False)
  File "/Users/dcl9/Code/toil/env/lib/python2.7/site-packages/libcloud/compute/drivers/gce.py", line 3883, in create_node
    self.connection.async_request(request, method='POST', data=node_data)
  File "/Users/dcl9/Code/toil/env/lib/python2.7/site-packages/libcloud/common/base.py", line 772, in async_request
    response = request(**kwargs)
  File "/Users/dcl9/Code/toil/env/lib/python2.7/site-packages/libcloud/compute/drivers/gce.py", line 121, in request
    response = super(GCEConnection, self).request(*args, **kwargs)
  File "/Users/dcl9/Code/toil/env/lib/python2.7/site-packages/libcloud/common/google.py", line 808, in request
    *args, **kwargs)
  File "/Users/dcl9/Code/toil/env/lib/python2.7/site-packages/libcloud/common/base.py", line 637, in request
    response = responseCls(**kwargs)
  File "/Users/dcl9/Code/toil/env/lib/python2.7/site-packages/libcloud/common/base.py", line 159, in __init__
    self.object = self.parse_body()
  File "/Users/dcl9/Code/toil/env/lib/python2.7/site-packages/libcloud/common/google.py", line 288, in parse_body
    raise InvalidRequestError(message, self.status, code)
libcloud.common.google.InvalidRequestError: {u'domain': u'global', u'message': u"Invalid value for field 'resource.disks[0].initializeParams.sourceImage': 'https://www.googleapis.com/compute/v1/projects/coreos-cloud/global/images/coreos-stable-1576-4-0-v20171206'. The referenced image resource cannot be found.", u'reason': u'invalid'}
$ 
```

Relevant code:

https://github.com/DataBiosphere/toil/blob/79c553f7c0f7bb698db09966cf4bad2b52b5c345/src/toil/provisioners/gceProvisioner.py#L42-L43

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-440)
┆Issue Number: TOIL-440

**Comment by dleehr** [comment]
I fixed in a [fork](https://github.com/dleehr/toil/commit/b87082e4aba5d62f795319038c8531fd72314108), but held off pull-requesting since it seemed likely to break again soon 😄

**Comment by adamnovak** [comment]
How did you get the correct image? Maybe it's something we can automate/scrape?

**Comment by dleehr** [comment]
I did a `gcloud compute image list | grep coreos`, but it looks like `gcloud compute images list --filter="family=('coreos-stable')"` is a little more precise

**Comment by dleehr** [comment]
As noted in the PR, it's sufficient to specify the image family instead of a specific version for launching the instance.
