### ISSUE TITLE
Pickling error when running Cactus on larger input

### ISSUE THREAD

**Issue by glennhickey** [DataBiosphere/toil#2881]
I'm trying to run Cactus on a larger dataset on kubernetes, and this is the latest error `PicklingError: Can't pickle <class 'toil.BotoCredentialAdapter'>: it's not found as toil.BotoCredentialAdapter`

Is this a Toil problem? 

```
86359de7-b94e-47bb-99e2-016fc4314469    Running command catchsegv 'cactus_blast_chunkSequences' 'INFO' '25000000' '10000' 'tsJ4ChA/tmp_DsPa0hrmcW' 'tmp4bFJbY.tmp'
86359de7-b94e-47bb-99e2-016fc4314469    Set log level to INFO
86359de7-b94e-47bb-99e2-016fc4314469    INFO:toil-rt:2019-12-05 23:45:54.502858: Successfully ran the command: "singularity --silent run -B /var/lib/toil/toil-632aa838-c670-4e9f-97b3-b45f546568f0-dc95beedd0eeec54a13d84c25de81dc2/tmpdvB9f_/9f512bca-9683-4b6d-962a-dd060f2d5983:/mnt --pwd /mnt -u /var/lib/toil/toil-632aa838-c670-4e9f-97b3-b45f546568f0-dc95beedd0eeec54a13d84c25de81dc2/tmpdvB9f_/9f512bca-9683-4b6d-962a-dd060f2d5983/tjMQD3l/cactus.img.sb cactus_blast_chunkSequences INFO 25000000 10000 tsJ4ChA/tmp_DsPa0hrmcW tmp4bFJbY.tmp" in 49.5165989399 seconds
86359de7-b94e-47bb-99e2-016fc4314469    INFO:toil.lib.bioio:Made the list of blasts
86359de7-b94e-47bb-99e2-016fc4314469    WARNING:toil.resource:Can't globalize module ModuleDescriptor(dirPath='/venv2/local/lib/python2.7/site-packages', name='cactus.blast.blast', fromVirtualEnv=True).
86359de7-b94e-47bb-99e2-016fc4314469    Traceback (most recent call last):
86359de7-b94e-47bb-99e2-016fc4314469      File "/usr/local/lib/python2.7/dist-packages/toil/worker.py", line 367, in workerScript
86359de7-b94e-47bb-99e2-016fc4314469        job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore, defer=defer)
86359de7-b94e-47bb-99e2-016fc4314469      File "/tmp/tmpgbMfBk/3a536290e528005ce049de97a4aca1e6/cactus/shared/common.py", line 1201, in _runner
86359de7-b94e-47bb-99e2-016fc4314469        super(RoundedJob, self)._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore, defer=defer)
86359de7-b94e-47bb-99e2-016fc4314469      File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 1399, in _runner
86359de7-b94e-47bb-99e2-016fc4314469        self._serialiseExistingJob(jobGraph, jobStore, returnValues)
86359de7-b94e-47bb-99e2-016fc4314469      File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 1308, in _serialiseExistingJob
86359de7-b94e-47bb-99e2-016fc4314469        self._serialiseJobGraph(jobGraph, jobStore, returnValues, False)
86359de7-b94e-47bb-99e2-016fc4314469      File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 1277, in _serialiseJobGraph
86359de7-b94e-47bb-99e2-016fc4314469        job._serialiseJob(jobStore, jobsToJobGraphs, jobGraph)
86359de7-b94e-47bb-99e2-016fc4314469      File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 1155, in _serialiseJob
86359de7-b94e-47bb-99e2-016fc4314469        pickle.dump(self, fileHandle, pickle.HIGHEST_PROTOCOL)
86359de7-b94e-47bb-99e2-016fc4314469      File "/usr/lib/python2.7/pickle.py", line 1376, in dump
86359de7-b94e-47bb-99e2-016fc4314469        Pickler(file, protocol).dump(obj)
86359de7-b94e-47bb-99e2-016fc4314469      File "/usr/lib/python2.7/pickle.py", line 224, in dump
86359de7-b94e-47bb-99e2-016fc4314469        self.save(obj)
86359de7-b94e-47bb-99e2-016fc4314469      File "/usr/lib/python2.7/pickle.py", line 331, in save
86359de7-b94e-47bb-99e2-016fc4314469        self.save_reduce(obj=obj, *rv)
86359de7-b94e-47bb-99e2-016fc4314469      File "/usr/lib/python2.7/pickle.py", line 425, in save_reduce
86359de7-b94e-47bb-99e2-016fc4314469        save(state)
86359de7-b94e-47bb-99e2-016fc4314469      File "/usr/lib/python2.7/pickle.py", line 286, in save
86359de7-b94e-47bb-99e2-016fc4314469        f(self, obj) # Call unbound method with explicit self
86359de7-b94e-47bb-99e2-016fc4314469      File "/usr/local/lib/python2.7/dist-packages/dill/dill.py", line 871, in save_module_dict
86359de7-b94e-47bb-99e2-016fc4314469        StockPickler.save_dict(pickler, obj)
86359de7-b94e-47bb-99e2-016fc4314469      File "/usr/lib/python2.7/pickle.py", line 655, in save_dict
86359de7-b94e-47bb-99e2-016fc4314469        self._batch_setitems(obj.iteritems())
86359de7-b94e-47bb-99e2-016fc4314469      File "/usr/lib/python2.7/pickle.py", line 687, in _batch_setitems
86359de7-b94e-47bb-99e2-016fc4314469        save(v)
86359de7-b94e-47bb-99e2-016fc4314469      File "/usr/lib/python2.7/pickle.py", line 286, in save
86359de7-b94e-47bb-99e2-016fc4314469        f(self, obj) # Call unbound method with explicit self
86359de7-b94e-47bb-99e2-016fc4314469      File "/usr/lib/python2.7/pickle.py", line 606, in save_list
86359de7-b94e-47bb-99e2-016fc4314469        self._batch_appends(iter(obj))
86359de7-b94e-47bb-99e2-016fc4314469      File "/usr/lib/python2.7/pickle.py", line 639, in _batch_appends
86359de7-b94e-47bb-99e2-016fc4314469        save(x)
86359de7-b94e-47bb-99e2-016fc4314469      File "/usr/lib/python2.7/pickle.py", line 286, in save
86359de7-b94e-47bb-99e2-016fc4314469        f(self, obj) # Call unbound method with explicit self
86359de7-b94e-47bb-99e2-016fc4314469      File "/usr/lib/python2.7/pickle.py", line 606, in save_list
86359de7-b94e-47bb-99e2-016fc4314469        self._batch_appends(iter(obj))
86359de7-b94e-47bb-99e2-016fc4314469      File "/usr/lib/python2.7/pickle.py", line 639, in _batch_appends
86359de7-b94e-47bb-99e2-016fc4314469        save(x)
86359de7-b94e-47bb-99e2-016fc4314469      File "/usr/lib/python2.7/pickle.py", line 286, in save
86359de7-b94e-47bb-99e2-016fc4314469        f(self, obj) # Call unbound method with explicit self
86359de7-b94e-47bb-99e2-016fc4314469      File "/usr/lib/python2.7/pickle.py", line 606, in save_list
86359de7-b94e-47bb-99e2-016fc4314469        self._batch_appends(iter(obj))
86359de7-b94e-47bb-99e2-016fc4314469      File "/usr/lib/python2.7/pickle.py", line 639, in _batch_appends
86359de7-b94e-47bb-99e2-016fc4314469        save(x)
86359de7-b94e-47bb-99e2-016fc4314469      File "/usr/lib/python2.7/pickle.py", line 331, in save
86359de7-b94e-47bb-99e2-016fc4314469        self.save_reduce(obj=obj, *rv)
86359de7-b94e-47bb-99e2-016fc4314469      File "/usr/lib/python2.7/pickle.py", line 425, in save_reduce
86359de7-b94e-47bb-99e2-016fc4314469        save(state)
86359de7-b94e-47bb-99e2-016fc4314469      File "/usr/lib/python2.7/pickle.py", line 286, in save
86359de7-b94e-47bb-99e2-016fc4314469        f(self, obj) # Call unbound method with explicit self
86359de7-b94e-47bb-99e2-016fc4314469      File "/usr/local/lib/python2.7/dist-packages/dill/dill.py", line 871, in save_module_dict
86359de7-b94e-47bb-99e2-016fc4314469        StockPickler.save_dict(pickler, obj)
86359de7-b94e-47bb-99e2-016fc4314469      File "/usr/lib/python2.7/pickle.py", line 655, in save_dict
86359de7-b94e-47bb-99e2-016fc4314469        self._batch_setitems(obj.iteritems())
86359de7-b94e-47bb-99e2-016fc4314469      File "/usr/lib/python2.7/pickle.py", line 687, in _batch_setitems
86359de7-b94e-47bb-99e2-016fc4314469        save(v)
86359de7-b94e-47bb-99e2-016fc4314469      File "/usr/lib/python2.7/pickle.py", line 331, in save
86359de7-b94e-47bb-99e2-016fc4314469        self.save_reduce(obj=obj, *rv)
86359de7-b94e-47bb-99e2-016fc4314469      File "/usr/lib/python2.7/pickle.py", line 425, in save_reduce
86359de7-b94e-47bb-99e2-016fc4314469        save(state)
86359de7-b94e-47bb-99e2-016fc4314469      File "/usr/lib/python2.7/pickle.py", line 286, in save
86359de7-b94e-47bb-99e2-016fc4314469        f(self, obj) # Call unbound method with explicit self
86359de7-b94e-47bb-99e2-016fc4314469      File "/usr/local/lib/python2.7/dist-packages/dill/dill.py", line 871, in save_module_dict
86359de7-b94e-47bb-99e2-016fc4314469        StockPickler.save_dict(pickler, obj)
86359de7-b94e-47bb-99e2-016fc4314469      File "/usr/lib/python2.7/pickle.py", line 655, in save_dict
86359de7-b94e-47bb-99e2-016fc4314469        self._batch_setitems(obj.iteritems())
86359de7-b94e-47bb-99e2-016fc4314469      File "/usr/lib/python2.7/pickle.py", line 687, in _batch_setitems
86359de7-b94e-47bb-99e2-016fc4314469        save(v)
86359de7-b94e-47bb-99e2-016fc4314469      File "/usr/lib/python2.7/pickle.py", line 331, in save
86359de7-b94e-47bb-99e2-016fc4314469        self.save_reduce(obj=obj, *rv)
86359de7-b94e-47bb-99e2-016fc4314469      File "/usr/lib/python2.7/pickle.py", line 425, in save_reduce
86359de7-b94e-47bb-99e2-016fc4314469        save(state)
86359de7-b94e-47bb-99e2-016fc4314469      File "/usr/lib/python2.7/pickle.py", line 286, in save
86359de7-b94e-47bb-99e2-016fc4314469        f(self, obj) # Call unbound method with explicit self
86359de7-b94e-47bb-99e2-016fc4314469      File "/usr/local/lib/python2.7/dist-packages/dill/dill.py", line 871, in save_module_dict
86359de7-b94e-47bb-99e2-016fc4314469        StockPickler.save_dict(pickler, obj)
86359de7-b94e-47bb-99e2-016fc4314469      File "/usr/lib/python2.7/pickle.py", line 655, in save_dict
86359de7-b94e-47bb-99e2-016fc4314469        self._batch_setitems(obj.iteritems())
86359de7-b94e-47bb-99e2-016fc4314469      File "/usr/lib/python2.7/pickle.py", line 687, in _batch_setitems
86359de7-b94e-47bb-99e2-016fc4314469        save(v)
86359de7-b94e-47bb-99e2-016fc4314469      File "/usr/lib/python2.7/pickle.py", line 331, in save
86359de7-b94e-47bb-99e2-016fc4314469        self.save_reduce(obj=obj, *rv)
86359de7-b94e-47bb-99e2-016fc4314469      File "/usr/lib/python2.7/pickle.py", line 425, in save_reduce
86359de7-b94e-47bb-99e2-016fc4314469        save(state)
86359de7-b94e-47bb-99e2-016fc4314469      File "/usr/lib/python2.7/pickle.py", line 286, in save
86359de7-b94e-47bb-99e2-016fc4314469        f(self, obj) # Call unbound method with explicit self
86359de7-b94e-47bb-99e2-016fc4314469      File "/usr/local/lib/python2.7/dist-packages/dill/dill.py", line 871, in save_module_dict
86359de7-b94e-47bb-99e2-016fc4314469        StockPickler.save_dict(pickler, obj)
86359de7-b94e-47bb-99e2-016fc4314469      File "/usr/lib/python2.7/pickle.py", line 655, in save_dict
86359de7-b94e-47bb-99e2-016fc4314469        self._batch_setitems(obj.iteritems())
86359de7-b94e-47bb-99e2-016fc4314469      File "/usr/lib/python2.7/pickle.py", line 687, in _batch_setitems
86359de7-b94e-47bb-99e2-016fc4314469        save(v)
86359de7-b94e-47bb-99e2-016fc4314469      File "/usr/lib/python2.7/pickle.py", line 331, in save
86359de7-b94e-47bb-99e2-016fc4314469        self.save_reduce(obj=obj, *rv)
86359de7-b94e-47bb-99e2-016fc4314469      File "/usr/lib/python2.7/pickle.py", line 396, in save_reduce
86359de7-b94e-47bb-99e2-016fc4314469        save(cls)
86359de7-b94e-47bb-99e2-016fc4314469      File "/usr/lib/python2.7/pickle.py", line 286, in save
86359de7-b94e-47bb-99e2-016fc4314469        f(self, obj) # Call unbound method with explicit self
86359de7-b94e-47bb-99e2-016fc4314469      File "/usr/local/lib/python2.7/dist-packages/dill/dill.py", line 1299, in save_type
86359de7-b94e-47bb-99e2-016fc4314469        StockPickler.save_global(pickler, obj)
86359de7-b94e-47bb-99e2-016fc4314469      File "/usr/lib/python2.7/pickle.py", line 754, in save_global
86359de7-b94e-47bb-99e2-016fc4314469        (obj, module, name))
86359de7-b94e-47bb-99e2-016fc4314469    PicklingError: Can't pickle <class 'toil.BotoCredentialAdapter'>: it's not found as toil.BotoCredentialAdapter
86359de7-b94e-47bb-99e2-016fc4314469    ERROR:toil.worker:Exiting the worker because of a failed job on host root-toil-d12ffe0b-ef0d-42cf-90f5-c2b0060670de-3188-s6m95
86359de7-b94e-47bb-99e2-016fc4314469    WARNING:toil.jobGraph:Due to failure we are reducing the remaining retry count of job 'BlastSequencesAgainstEachOther' 86359de7-b94e-47bb-99e2-016fc4314469 with ID 86359de7-b94e-47bb-99e2-016fc4314469 to 2
Issued job 'BlastSequencesAgainstEachOther' 86359de7-b94e-47bb-99e2-016fc4314469 with job batch system ID: 3190 and cores: 1, disk: 85.8 G, and memory: 16.0 G
2019-12-06 00:07:33.322926: Running the command: "singularity --silent run -B /var/lib/toil/toil-632aa838-c670-4e9f-97b3-b45f546568f0-dc95beedd0eeec54a13d84c25de81dc2/tmpqyLu7Z/ee90be22-885b-449b-a269-3457163d1217:/mnt --pwd /mnt -u /var/lib/toil/toil-632aa838-c670-4e9f-97b3-b45f546568f0-dc95beedd0eeec54a13d84c25de81dc2/tmpqyLu7Z/ee90be22-885b-449b-a269-3457163d1217/tqINIfd/cactus.img.sb cactus_blast_chunkSequences INFO 25000000 10000 tGGRcR4/tmp_b58alVaJnN tmpdrqoB4.tmp tmpFXOVtZ.tmp"
2019-12-06 00:09:06.558278: Successfully ran the command: "singularity --silent run -B /var/lib/toil/toil-632aa838-c670-4e9f-97b3-b45f546568f0-dc95beedd0eeec54a13d84c25de81dc2/tmpqyLu7Z/ee90be22-885b-449b-a269-3457163d1217:/mnt --pwd /mnt -u /var/lib/toil/toil-632aa838-c670-4e9f-97b3-b45f546568f0-dc95beedd0eeec54a13d84c25de81dc2/tmpqyLu7Z/ee90be22-885b-449b-a269-3457163d1217/tqINIfd/cactus.img.sb cactus_blast_chunkSequences INFO 25000000 10000 tGGRcR4/tmp_b58alVaJnN tmpdrqoB4.tmp tmpFXOVtZ.tmp" in 92.7297759056 seconds
2019-12-06 00:09:06.559814: Running the command: "singularity --silent run -B /var/lib/toil/toil-632aa838-c670-4e9f-97b3-b45f546568f0-dc95beedd0eeec54a13d84c25de81dc2/tmpqyLu7Z/ee90be22-885b-449b-a269-3457163d1217:/mnt --pwd /mnt -u /var/lib/toil/toil-632aa838-c670-4e9f-97b3-b45f546568f0-dc95beedd0eeec54a13d84c25de81dc2/tmpqyLu7Z/ee90be22-885b-449b-a269-3457163d1217/tqINIfd/cactus.img.sb cactus_blast_chunkSequences INFO 25000000 10000 txNK42h/tmp_Z4yHYyAACP tmpvqeGbA.tmp"
2019-12-06 00:09:54.259745: Successfully ran the command: "singularity --silent run -B /var/lib/toil/toil-632aa838-c670-4e9f-97b3-b45f546568f0-dc95beedd0eeec54a13d84c25de81dc2/tmpqyLu7Z/ee90be22-885b-449b-a269-3457163d1217:/mnt --pwd /mnt -u /var/lib/toil/toil-632aa838-c670-4e9f-97b3-b45f546568f0-dc95beedd0eeec54a13d84c25de81dc2/tmpqyLu7Z/ee90be22-885b-449b-a269-3457163d1217/tqINIfd/cactus.img.sb cactus_blast_chunkSequences INFO 25000000 10000 txNK42h/tmp_Z4yHYyAACP tmpvqeGbA.tmp" in 47.1937949657 seconds
Reissued any over long jobs
```

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-466)
┆Issue Number: TOIL-466

**Comment by glennhickey** [comment]
Just noticed this issue has already been raised here:
https://github.com/ComparativeGenomicsToolkit/cactus/issues/100

Not sure what the way forward is.  Is this a Toil problem or a Cactus problem?

**Comment by glennhickey** [comment]
If I understand correctly, Cactus is using the `ChildTreeJob` to span child jobs.  It does this because serializing a great big list of child jobs is two slow, so this class spreads adding alist of child jobs into a set of child jobs.  The problem is maybe that something changed within Toil to give Cactus problems pickling the list of child jobs?   

I'll try disabling this logic.  But if this is the issue, perhaps there's a way to speed up adding large child job lists within Toil?

**Comment by adamnovak** [comment]
@jeffrey856 has a PR that should address this here, by making that object actually picklable, even though we still don't see why it ought to want to come along in the pickle: https://github.com/DataBiosphere/toil/pull/2871

Unfortunately it still needs some work; I fixed CI on master, but this PR doesn't pass tests because some variable references broke during the refactor.

**Comment by adamnovak** [comment]
@glennhickey Did you manage to work around this issue? I'm not sure we'll be able to get Jeffrey's fix polished off until the new year.

**Comment by glennhickey** [comment]
You can disable pickling in cactus by setting maxChildrenPerJob=sys.maxint
(instead of 20) on this line:

https://github.com/ComparativeGenomicsToolkit/cactus/blob/master/src/cactus/shared/common.py#L1268

I'll try to get this into master soon, but it does work around this issue.

**Comment by brantfaircloth** [comment]
In Python 3, shouldn't this be `sys.maxsize` rather than `sys.maxint` (which no longer exists)?

**Comment by glennhickey** [comment]
Cactus still only runs with Python 2.7.  That should be changing soon though.

**Comment by brantfaircloth** [comment]
Gotcha - i made the assumption it was also at Python 3 to track Toil.  Thanks again 💯

**Comment by adamnovak** [comment]
Post-https://github.com/DataBiosphere/toil/pull/2904, BotoCredentialAdapter ought to be picklable, because it is defined at module scope. Is this still showing up with Toil from master as of the ~17 days ago when that was merged? If not we can close this issue...

**Comment by adamnovak** [comment]
There's still the issue of why Cactus's large child count workarounds want to pickle internal parts of Boto, but that is a Cactus issue, and a low priority one if it works in practice.

**Comment by brantfaircloth** [comment]
I was testing this on `3.23.0`, which appears to incorporate the PR above... that said, there seems to be a `socket.timeout` error that is an uncaught exception and keeps toil from launching a new cluster on AWS (checked this in Python 3.8, then 3.6 to make sure 3.8 wasn't the problem).  Seems like https://github.com/DataBiosphere/toil/blob/master/src/toil/provisioners/aws/__init__.py#L40-L44 should be (after also importing `timeout` from `socket`):

```
    try:
        urlopen('http://169.254.169.254/latest/dynamic/instance-identity/document', timeout=1)
        return True
    except (URLError, timeout):
        return False

```

**Comment by brantfaircloth** [comment]
When testing the updated code, I seem to be able to get past the original pickling error, but I hit what may be a related error:

```
62f78797-abc1-43ca-b588-182567a4856b    INFO:toil.worker:---TOIL WORKER OUTPUT LOG---
62f78797-abc1-43ca-b588-182567a4856b    INFO:toil:Running Toil version 3.23.1-56ad62624e7d659a7b0fbd7f1e097b880a7833e9.
62f78797-abc1-43ca-b588-182567a4856b    Traceback (most recent call last):
62f78797-abc1-43ca-b588-182567a4856b      File "/usr/local/lib/python2.7/dist-packages/toil/worker.py", line 350, in workerScript
62f78797-abc1-43ca-b588-182567a4856b        job = Job._loadJob(jobGraph.command, jobStore)
62f78797-abc1-43ca-b588-182567a4856b      File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 939, in _loadJob
62f78797-abc1-43ca-b588-182567a4856b        return cls._unpickle(userModule, fileHandle, jobStore.config)
62f78797-abc1-43ca-b588-182567a4856b      File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 990, in _unpickle
62f78797-abc1-43ca-b588-182567a4856b        runnable = unpickler.load()
62f78797-abc1-43ca-b588-182567a4856b    TypeError: __new__() takes at least 2 arguments (1 given)
62f78797-abc1-43ca-b588-182567a4856b    ERROR:toil.worker:Exiting the worker because of a failed job on host ip-172-31-0-83.ec2.internal
62f78797-abc1-43ca-b588-182567a4856b    WARNING:toil.jobGraph:Due to failure we are reducing the remaining retry count of job 'SpawnChildren' 62f78797-abc1-43ca-b588-182567a4856b with ID 62f78797-abc1-43ca-b588-182567a4856b to 0
Job 'SpawnChildren' 62f78797-abc1-43ca-b588-182567a4856b with ID 62f78797-abc1-43ca-b588-182567a4856b is completely failed
```

**Comment by adamnovak** [comment]
Hm. Maybe we'll have to solve the underlying issue of why Cactus wants to pickle global stuff after all. It looks like we managed to pickle something that can't be un-pickled because it defines a `__new__`.

**Comment by adamnovak** [comment]
@glennhickey @joelarmstrong @diekhans Does one of you want to address the problem in Cactus once and for all? Or should I try and dive in and do it?

**Comment by diekhans** [comment]
So this isn't fixed by the latest toil?  It always seemed like
cactus was doing something is shouldn't do.

I will not be able to get to it for at least a week, so if you want to
dive in, that would be great.  Happy to advise and assist.

I would really like to do this on top of moving to py3.

**Comment by glennhickey** [comment]
@adamnovak The offending code is the `ChildTreeJob` class here: https://github.com/ComparativeGenomicsToolkit/cactus/blob/master/src/cactus/shared/common.py#L1256-L1331

It is @joelarmstrong's hack to speed up running long lists of child jobs which is very slow in Toil.  It involves making a tree of jobs, where jobs contain lists of child jobs.  Pickling lists of jobs in this way seems to have caused trouble in the past (see his monkey patch replace cpickle with pickle), and is probably what's the matter here.

Cactus will still run fine if we disable this (it can be turned off by not using `ChildTreeJob` or by hacking `ChildTreeJob` it to never use `SpanChildren`.  But it will be slower on large inputs.  If I remember @joelarmstrong said somethign to the tune of a few hours, which may not be that big of a deal?

@diekhans I think this is what you need to do in the `py3` branch, otherwise it will not be mergable anytime soon.  

@adamnovak Ideally, the root issue would then be entirely fixed in Toil by making it scale better with larger numbers of child jobs, or by providing some kind of similar pattern to cactus's current hack.

**Comment by glennhickey** [comment]
I'm going to spend more time on Cactus this week.  I will take a shot at re-writing this logic without sending jobs as arguments to jobs.  Unless I'm missing something (I probably am), I think it should be fairly doable.  If somehow Toil gets fixed up and this is the only issue preventing a merge, I think disabling temporarily in Cactus is fine.  It can be re-activated in a future PR.  Also, it may become less of an issue if we can refactor Cactus a bit to do fewer blast jobs.

**Comment by adamnovak** [comment]
Lon and I closed this because Jeffrey solved this actual error. We've created a new un-pickling error instead, but it sounds like we're going to fix that on the Cactus side.
