### ISSUE TITLE
Avoid using non-default ports for Mesos maybe?

### ISSUE THREAD

**Issue by jasonsydes** [DataBiosphere/toil#2905]
Hi Toil Community!

I kept running into a bug that I could not figure out how to fix (I ended up using a colleague's copy of cactus).  Today I finally determined that the bug was due to a funky conda install of psutil (it was linked to the Intel Math Library (libimf.so) which wasn't available in my environment).

But toil/cactus was presenting a completely different error:
```
Limiting maxMemory to physically available memory (270370213888).
Limiting maxDisk to physically available disk (791423064473600).
Running Toil version 3.20.0-cf34ca3416697f2abc816b2538f20ee29ba16932.
Issued job 'RunCactusPreprocessorThenProgressiveDown' X/y/jobRfF6db with job batch system ID: 0 and cores: 1, disk: 2.0 G, and memory: 3.3 G
Executor 'toil-14220' reported lost with status '256'.
Handling failure of executor 'toil-14220' on agent 'a7513970-ea64-470a-aadf-575530a58dac-S3'.
Could not retrieve logs due to: '<urlopen error [Errno 111] Connection refused>'.
Traceback (most recent call last):
  File "/home/sydes/miniconda3/envs/cactus_20200103/lib/python2.7/site-packages/toil/batchSystems/mesos/batchSystem.py", line 755, in _handleFailedExecutor
    filesDict = json.loads(urlopen(filesQueryURL).read())
  File "/home/sydes/miniconda3/envs/cactus_20200103/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/home/sydes/miniconda3/envs/cactus_20200103/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/home/sydes/miniconda3/envs/cactus_20200103/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/home/sydes/miniconda3/envs/cactus_20200103/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/home/sydes/miniconda3/envs/cactus_20200103/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/home/sydes/miniconda3/envs/cactus_20200103/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 111] Connection refused>
```
I think what is happening is that Toil is trying to retrieve the error from Mesos Agent, which by default appears to be running on port 5051.  And that's what this code is hardcoded to:

https://github.com/DataBiosphere/toil/blob/master/src/toil/batchSystems/mesos/batchSystem.py#L748

Unfortunately, we had our leader and workers all wired up on different (non-default) ports, so I ended up with the cryptic error message above.

Anyway, I hadn't found anything on the Toil or Cactus Issues page, so I figured I'd make a public note about it, in case anyone else runs into this problem.

For now, I think I'll try to update my leader and workers to use 5050/5051.

Thanks!
Jason

**Comment by jasonsydes** [comment]
Ok good, looks like switching to default ports (5050 for the leader and 5051 for the workers) no longer gives the urlopen red herring above (and now gives the error message that I actually needed to fix the problem).
```
Attempting to retrieve executor error log: http://172.20.8.136:5051/files/download?path=worker-work-dir-6%2Fslaves%2F6e7d14e2-fc26-4535-8de5-4b316009f60e-S4%2Fframeworks%2F6e7d14e2-fc26-4535-8de5-4b316009f60e-0000%2Fexecutors%2Ftoil-37918%2Fruns%2Fbfda5b0a-578e-464c-a412-ed482334651d%2Fstderr
Executor: /home/sydes/miniconda3/envs/cactus_20200103_mike_20191009/lib/python2.7/site-packages/subprocess32.py:146: RuntimeWarning: The _posixsubprocess module is not being used. Child process reliability may suffer if your program uses threads.
Executor:   "program uses threads.", RuntimeWarning)
Executor: Traceback (most recent call last):
Executor:   File "/home/sydes/miniconda3/envs/cactus_20200103_mike_20191009/bin/_toil_mesos_executor", line 6, in <module>
Executor:     from toil.batchSystems.mesos.executor import main
Executor:   File "/home/sydes/miniconda3/envs/cactus_20200103_mike_20191009/lib/python2.7/site-packages/toil/batchSystems/mesos/executor.py", line 27, in <module>
Executor:     import psutil
Executor:   File "/home/sydes/miniconda3/envs/cactus_20200103_mike_20191009/lib/python2.7/site-packages/psutil/__init__.py", line 63, in <module>
Executor:     from . import _pslinux as _psplatform
Executor:   File "/home/sydes/miniconda3/envs/cactus_20200103_mike_20191009/lib/python2.7/site-packages/psutil/_pslinux.py", line 24, in <module>
Executor:     from . import _psutil_linux as cext
Executor: ImportError: libimf.so: cannot open shared object file: No such file or directory
```
I personally don't need a fix for this particular issue because switching to default ports is a simple workaround.

Thanks!
Jason

**Comment by michaelkarlcoleman** [comment]
+1 for at least documenting this.  Quite surprising, given that cactus has arguments allowing the mesos port to be specified.
