### ISSUE TITLE
Python 3.6 doesn't work well in a Toil Appliance

### ISSUE THREAD

**Issue by glennhickey** [DataBiosphere/toil#2964]
When I use `TOIL_APPLIANCE_SELF=quay.io/ucsc_cgl/toil:3.24.1a1-3475cb8e60da9e064296dd96b6460562aebb0356 toil launch-cluster...`

I get something with python3 defaulting to `3.5.2`.  It is also where Toil seems to get installed.  Python3 support in Cactus requires Python 3.6.  This means I can' use (non singleMachine) batch systems with Cactus under Python3

@adamnovak mentions 

> Hm, maybe Toil is installing in 3.5 instead of 3.6. We should change https://github.com/DataBiosphere/toil/blob/3475cb8e60da9e064296dd96b6460562aebb0356/docker/Dockerfile.py#L25 to use something like https://github.com/DataBiosphere/toil/blob/3475cb8e60da9e064296dd96b6460562aebb0356/version_template.py#L67-L75 but to select the major and minor version of pip to use.

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-507)
┆Issue Number: TOIL-507

**Comment by DailyDreaming** [comment]
@glennhickey Can you try #2966 and see if that fixes your issue?

**Comment by glennhickey** [comment]
For reference, here is how I am testing on Cactus (please change all instances "glenn" appropriately if reproducing).  Derived from the [Cactus README](https://github.com/ComparativeGenomicsToolkit/cactus/blob/master/doc/running-in-aws.md) 
```
TOIL_APPLIANCE_SELF=quay.io/ucsc_cgl/toil:3.24.1a1-efeaa75465e9c6dd3df8e4535a810a47b17f0561-dirty-py3.6 toil launch-cluster glenn-test2 --leaderNodeType=t2.medium -z us-west-2a --keyPairName=glenn.hickey@gmail.com
ssh-cluster glenn-test2
screen
virtualenv -p python3.6 --system-site-packages venv
. venv/bin/activate
git clone https://github.com/ComparativeGenomicsToolkit/cactus.git --branch py3 --recursive
cd cactus
pip install -U .
cactus  --nodeTypes c4.8xlarge:0.6,r3.8xlarge --minNodes 0,0 --maxNodes 20,2 --provisioner aws --batchSystem mesos --logDebug --latest aws:us-west-2:glennhickey-jobstore ./examples/evolverMammals.txt output.hal  --logFile log
```
This gives the following error:
```
Overriding docker appliance of quay.io/ucsc_cgl/toil:3.24.1a1-efeaa75465e9c6dd3df8e4535a810a47b17f0561-dirty-py3.6 with quay.io/ucsc_cgl/toil:3.24.1a1-efeaa75465e9c6dd3df8e4535a810a47b17f0561-dirty-py3.6 from TOIL_APPLIANCE_SELF.
Launching 1 preemptable nodes
Exception encountered in scaler thread. Making a best-effort attempt to keep going, but things may go wrong from now on.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/toil/lib/retry.py", line 116, in repeated_attempt
    yield
  File "/usr/local/lib/python3.6/dist-packages/toil/lib/ec2.py", line 193, in create_spot_instances
    price, image_id, count=num_instances, **spec)
  File "/usr/local/lib/python3.6/dist-packages/boto/ec2/connection.py", line 1616, in request_spot_instances
    params['%s.UserData' % ls] = base64.b64encode(user_data)
  File "/venv/lib/python3.6/base64.py", line 58, in b64encode
    encoded = binascii.b2a_base64(s, newline=False)
TypeError: a bytes-like object is required, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/toil/provisioners/clusterScaler.py", line 881, in tryRun
    self.scaler.updateClusterSize(estimatedNodeCounts)
  File "/usr/local/lib/python3.6/dist-packages/toil/provisioners/clusterScaler.py", line 547, in updateClusterSize
    newNodeCount = self.setNodeCount(nodeType=nodeType, numNodes=estimatedNodeCount, preemptable=nodeShape.preemptable)
  File "/usr/local/lib/python3.6/dist-packages/toil/provisioners/clusterScaler.py", line 617, in setNodeCount
    preemptable=preemptable)
  File "/usr/local/lib/python3.6/dist-packages/toil/provisioners/clusterScaler.py", line 633, in _addNodes
    return self.provisioner.addNodes(nodeType=nodeType, numNodes=numNodes, preemptable=preemptable)
  File "/usr/local/lib/python3.6/dist-packages/toil/provisioners/aws/awsProvisioner.py", line 316, in addNodes
    tentative=True)
  File "/usr/local/lib/python3.6/dist-packages/toil/lib/ec2.py", line 193, in create_spot_instances
    price, image_id, count=num_instances, **spec)
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.6/dist-packages/toil/lib/retry.py", line 118, in repeated_attempt
    if time.time( ) + delay < expiration and predicate( e ):
  File "/usr/local/lib/python3.6/dist-packages/toil/lib/ec2.py", line 234, in inconsistencies_detected
    if e.code == 'InvalidGroup.NotFound':
AttributeError: 'TypeError' object has no attribute 'code'
```
I've never used different node-types in Toil before.  When trying with a single node type, as I use with toil-vg, I get a different error
```
Adding 1 preemptable nodes to get to desired cluster size of 1.
Exception encountered in scaler thread. Making a best-effort attempt to keep going, but things may go wrong from now on.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/toil/provisioners/clusterScaler.py", line 881, in tryRun
    self.scaler.updateClusterSize(estimatedNodeCounts)
  File "/usr/local/lib/python3.6/dist-packages/toil/provisioners/clusterScaler.py", line 547, in updateClusterSize
    newNodeCount = self.setNodeCount(nodeType=nodeType, numNodes=estimatedNodeCount, preemptable=nodeShape.preemptable)
  File "/usr/local/lib/python3.6/dist-packages/toil/provisioners/clusterScaler.py", line 617, in setNodeCount
    preemptable=preemptable)
  File "/usr/local/lib/python3.6/dist-packages/toil/provisioners/clusterScaler.py", line 633, in _addNodes
    return self.provisioner.addNodes(nodeType=nodeType, numNodes=numNodes, preemptable=preemptable)
  File "/usr/local/lib/python3.6/dist-packages/toil/provisioners/aws/awsProvisioner.py", line 281, in addNodes
    bdm = self._getBlockDeviceMapping(instanceType, rootVolSize=self._nodeStorage)
  File "/usr/local/lib/python3.6/dist-packages/toil/provisioners/aws/awsProvisioner.py", line 529, in _getBlockDeviceMapping
    for disk in range(1, instanceType.disks + 1):
TypeError: 'float' object cannot be interpreted as an integer
```

**Comment by DailyDreaming** [comment]
@glennhickey These look like bog standard python2/3 compatibility problems.  Might be able to get to this later today or tomorrow?  I'm working on the CWL end of toil and trying not to get completely bogged down with other work right now.

@diekhans Would you have bandwidth to tackle this?

**Comment by adamnovak** [comment]
Yeah, it looks like you got the Python versions matched up and now get
to be the first person to test the autoscaler in Python 3.
