### ISSUE TITLE
Toil CWL restart fails on du and not rev call.

### ISSUE THREAD

**Issue by DailyDreaming** [DataBiosphere/toil#2974]
Git lab is reporting that cwl passes but I'm seeing this in the log messages:

```
WARNING:toil.leader:kind-CWLWorkflow/instancea77betgc    Traceback (most recent call last):
WARNING:toil.leader:kind-CWLWorkflow/instancea77betgc      File "/builds/databiosphere/toil/src/toil/worker.py", line 369, in workerScript
WARNING:toil.leader:kind-CWLWorkflow/instancea77betgc        fileStore.startCommit(jobState=False)
WARNING:toil.leader:kind-CWLWorkflow/instancea77betgc      File "/usr/lib/python3.6/contextlib.py", line 88, in __exit__
WARNING:toil.leader:kind-CWLWorkflow/instancea77betgc        next(self.gen)
WARNING:toil.leader:kind-CWLWorkflow/instancea77betgc      File "/builds/databiosphere/toil/src/toil/fileStores/nonCachingFileStore.py", line 79, in open
WARNING:toil.leader:kind-CWLWorkflow/instancea77betgc        diskUsed = getDirSizeRecursively(self.localTempDir)
WARNING:toil.leader:kind-CWLWorkflow/instancea77betgc      File "/builds/databiosphere/toil/src/toil/common.py", line 1360, in getDirSizeRecursively
WARNING:toil.leader:kind-CWLWorkflow/instancea77betgc        env=dict(os.environ, BLOCKSIZE='512')).decode('utf-8').split()[0]) * 512
WARNING:toil.leader:kind-CWLWorkflow/instancea77betgc      File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
WARNING:toil.leader:kind-CWLWorkflow/instancea77betgc        **kwargs).stdout
WARNING:toil.leader:kind-CWLWorkflow/instancea77betgc      File "/usr/lib/python3.6/subprocess.py", line 423, in run
WARNING:toil.leader:kind-CWLWorkflow/instancea77betgc        with Popen(*popenargs, **kwargs) as process:
WARNING:toil.leader:kind-CWLWorkflow/instancea77betgc      File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
WARNING:toil.leader:kind-CWLWorkflow/instancea77betgc        restore_signals, start_new_session)
WARNING:toil.leader:kind-CWLWorkflow/instancea77betgc      File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
WARNING:toil.leader:kind-CWLWorkflow/instancea77betgc        raise child_exception_type(errno_num, err_msg, err_filename)
WARNING:toil.leader:kind-CWLWorkflow/instancea77betgc    FileNotFoundError: [Errno 2] No such file or directory: 'du': 'du'
WARNING:toil.leader:kind-CWLWorkflow/instancea77betgc    ERROR:toil.worker:Exiting the worker because of a failed job on host runner-buau-7ql-project-3-concurrent-3r82td
WARNING:toil.leader:kind-CWLWorkflow/instancea77betgc    WARNING:toil.jobGraph:Due to failure we are reducing the remaining retry count of job 'CWLWorkflow' kind-CWLWorkflow/instancea77betgc with ID kind-CWLWorkflow/instancea77betgc to 1
```

https://ucsc-ci.com/databiosphere/toil/-/jobs/40699

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-513)
┆Issue Number: TOIL-513

**Comment by mr-c** [comment]
@DailyDreaming your system is missing the `coreutils` package for some reason..

**Comment by DailyDreaming** [comment]
@mr-c Thank you!  I will add it and see if it fixes it.

Also, somewhat more concerning to me is the green light on what appears to be a failing test.  I'll have to make sure it blinks red should this happen again.

**Comment by diekhans** [comment]
IMHO, it shouldn't pass the tests unless the du check is
optional.  It should case, it would be good if it generated an
explicit warning rather than a scary stack trace.

**Comment by DailyDreaming** [comment]
Okay... so this is a weird one.  It's actually temporarily changing PATH to hide the `rev` built-in to force an error and test toil's restart, but it hits `du` first, then restarts with the same errors and exceptions so it actually is kind of testing the same thing it intended to.  I think I can just add `du` to the path and omit `rev` and it should "fix" this.

We also only recently enabled more verbose logging, so normally we wouldn't see a stack trace like this.

**Comment by diekhans** [comment]
rev and du both in /usr/bin

It is reasonable to a special way to trigger errors in the code or add a directory with
a bogus version of rev (e.g. symlink to false command) at the front of the path

**Comment by DailyDreaming** [comment]
@diekhans I've implemented your suggestion: https://github.com/DataBiosphere/toil/pull/2975
