### ISSUE TITLE
cwltoil fails when providing default and input value to nested workflows

### ISSUE THREAD

**Issue by liinus** [DataBiosphere/toil#2987]
`cwltoil` fails when an input is passed to an input in a nested workflow that also have a default value specified.

Environment:
```
$ uname -a
Linux docker-vm 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
$ pip3 freeze | grep toil
toil==3.24.0
```

Scripts:
```
$ head -n-0 wf.cwl sub.cwl tool.cwl
==> wf.cwl <==
cwlVersion: v1.0
class: Workflow
requirements:
  SubworkflowFeatureRequirement: {}
inputs:
  inp: string?
steps:
  tool:
    run: sub.cwl
    in:
      inp: inp
    out: []
outputs: []

==> sub.cwl <==
cwlVersion: v1.0
class: Workflow
requirements:
  SubworkflowFeatureRequirement: {}
inputs:
  inp: string?
steps:
  tool:
    run: tool.cwl
    in:
      inp: inp
    out: []
outputs: []

==> tool.cwl <==
cwlVersion: v1.0
class: CommandLineTool
baseCommand: echo
inputs:
  inp:
    type: string
    default: "Hello"
outputs: []
```

Running `cwltoil wf.cwl` works, but not `cwltoil wf.cwl --inp Hello`.

```
$ cwltoil --logWarning wf.cwl --inp Hello
docker-vm 2020-02-26 00:51:15,461 MainThread WARNING cwltool: Workflow checker warning:
sub.cwl:6:3:  Source 'inp' of type ["null", "string"] may be incompatible
sub.cwl:11:7:   with sink 'inp' of type "string"
docker-vm 2020-02-26 00:51:15,482 MainThread WARNING toil.batchSystems.singleMachine: Limiting maxCores to CPU count of system (4).
docker-vm 2020-02-26 00:51:15,484 MainThread WARNING toil.batchSystems.singleMachine: Limiting maxMemory to physically available memory (16819580928).
docker-vm 2020-02-26 00:51:15,485 MainThread WARNING toil.batchSystems.singleMachine: Limiting maxDisk to physically available disk (19015532544).
docker-vm 2020-02-26 00:51:16,917 MainThread WARNING toil.leader: The job seems to have left a log file, indicating failure: 'CWLWorkflow' kind-CWLWorkflow/instancedr0axrjw
docker-vm 2020-02-26 00:51:16,917 MainThread WARNING toil.leader: kind-CWLWorkflow/instancedr0axrjw    WARNING:toil.resource:Can't globalize module ModuleDescriptor(dirPath='/home/ubuntu/.local/lib/python3.6/site-packages', name='toil.cwl.cwltoil', fromVirtualEnv=False).
docker-vm 2020-02-26 00:51:16,918 MainThread WARNING toil.leader: kind-CWLWorkflow/instancedr0axrjw    WARNING:toil.resource:Can't globalize module ModuleDescriptor(dirPath='/home/ubuntu/.local/lib/python3.6/site-packages', name='toil.cwl.cwltoil', fromVirtualEnv=False).
docker-vm 2020-02-26 00:51:16,918 MainThread WARNING toil.leader: kind-CWLWorkflow/instancedr0axrjw    WARNING:toil.resource:Can't globalize module ModuleDescriptor(dirPath='/home/ubuntu/.local/lib/python3.6/site-packages', name='toil.cwl.cwltoil', fromVirtualEnv=False).
docker-vm 2020-02-26 00:51:16,918 MainThread WARNING toil.leader: kind-CWLWorkflow/instancedr0axrjw    WARNING:toil.resource:Can't globalize module ModuleDescriptor(dirPath='/home/ubuntu/.local/lib/python3.6/site-packages', name='toil.cwl.cwltoil', fromVirtualEnv=False).
docker-vm 2020-02-26 00:51:16,918 MainThread WARNING toil.leader: kind-CWLWorkflow/instancedr0axrjw    Traceback (most recent call last):
docker-vm 2020-02-26 00:51:16,918 MainThread WARNING toil.leader: kind-CWLWorkflow/instancedr0axrjw      File "/home/ubuntu/.local/lib/python3.6/site-packages/toil/worker.py", line 366, in workerScript
docker-vm 2020-02-26 00:51:16,919 MainThread WARNING toil.leader: kind-CWLWorkflow/instancedr0axrjw        job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore, defer=defer)
docker-vm 2020-02-26 00:51:16,919 MainThread WARNING toil.leader: kind-CWLWorkflow/instancedr0axrjw      File "/home/ubuntu/.local/lib/python3.6/site-packages/toil/job.py", line 1392, in _runner
docker-vm 2020-02-26 00:51:16,919 MainThread WARNING toil.leader: kind-CWLWorkflow/instancedr0axrjw        returnValues = self._run(jobGraph, fileStore)
docker-vm 2020-02-26 00:51:16,919 MainThread WARNING toil.leader: kind-CWLWorkflow/instancedr0axrjw      File "/home/ubuntu/.local/lib/python3.6/site-packages/toil/job.py", line 1329, in _run
docker-vm 2020-02-26 00:51:16,920 MainThread WARNING toil.leader: kind-CWLWorkflow/instancedr0axrjw        return self.run(fileStore)
docker-vm 2020-02-26 00:51:16,920 MainThread WARNING toil.leader: kind-CWLWorkflow/instancedr0axrjw      File "/home/ubuntu/.local/lib/python3.6/site-packages/toil/cwl/cwltoil.py", line 953, in run
docker-vm 2020-02-26 00:51:16,920 MainThread WARNING toil.leader: kind-CWLWorkflow/instancedr0axrjw        jobobj[key][0]] is None):
docker-vm 2020-02-26 00:51:16,920 MainThread WARNING toil.leader: kind-CWLWorkflow/instancedr0axrjw    TypeError: tuple indices must be integers or slices, not str
docker-vm 2020-02-26 00:51:16,920 MainThread WARNING toil.leader: kind-CWLWorkflow/instancedr0axrjw    ERROR:toil.worker:Exiting the worker because of a failed job on host docker-vm 
docker-vm 2020-02-26 00:51:16,921 MainThread WARNING toil.leader: kind-CWLWorkflow/instancedr0axrjw    WARNING:toil.jobGraph:Due to failure we are reducing the remaining retry count of job 'CWLWorkflow' kind-CWLWorkflow/instancedr0axrjw with ID kind-CWLWorkflow/instancedr0axrjw to 1
docker-vm 2020-02-26 00:51:18,215 MainThread WARNING toil.leader: The job seems to have left a log file, indicating failure: 'CWLWorkflow' kind-CWLWorkflow/instancedr0axrjw
docker-vm 2020-02-26 00:51:18,216 MainThread WARNING toil.leader: kind-CWLWorkflow/instancedr0axrjw    Traceback (most recent call last):
docker-vm 2020-02-26 00:51:18,216 MainThread WARNING toil.leader: kind-CWLWorkflow/instancedr0axrjw      File "/home/ubuntu/.local/lib/python3.6/site-packages/toil/worker.py", line 366, in workerScript
docker-vm 2020-02-26 00:51:18,216 MainThread WARNING toil.leader: kind-CWLWorkflow/instancedr0axrjw        job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore, defer=defer)
docker-vm 2020-02-26 00:51:18,216 MainThread WARNING toil.leader: kind-CWLWorkflow/instancedr0axrjw      File "/home/ubuntu/.local/lib/python3.6/site-packages/toil/job.py", line 1392, in _runner
docker-vm 2020-02-26 00:51:18,217 MainThread WARNING toil.leader: kind-CWLWorkflow/instancedr0axrjw        returnValues = self._run(jobGraph, fileStore)
docker-vm 2020-02-26 00:51:18,217 MainThread WARNING toil.leader: kind-CWLWorkflow/instancedr0axrjw      File "/home/ubuntu/.local/lib/python3.6/site-packages/toil/job.py", line 1329, in _run
docker-vm 2020-02-26 00:51:18,217 MainThread WARNING toil.leader: kind-CWLWorkflow/instancedr0axrjw        return self.run(fileStore)
docker-vm 2020-02-26 00:51:18,217 MainThread WARNING toil.leader: kind-CWLWorkflow/instancedr0axrjw      File "/home/ubuntu/.local/lib/python3.6/site-packages/toil/cwl/cwltoil.py", line 953, in run
docker-vm 2020-02-26 00:51:18,217 MainThread WARNING toil.leader: kind-CWLWorkflow/instancedr0axrjw        jobobj[key][0]] is None):
docker-vm 2020-02-26 00:51:18,217 MainThread WARNING toil.leader: kind-CWLWorkflow/instancedr0axrjw    TypeError: tuple indices must be integers or slices, not str
docker-vm 2020-02-26 00:51:18,217 MainThread WARNING toil.leader: kind-CWLWorkflow/instancedr0axrjw    ERROR:toil.worker:Exiting the worker because of a failed job on host docker-vm
docker-vm 2020-02-26 00:51:18,218 MainThread WARNING toil.leader: kind-CWLWorkflow/instancedr0axrjw    WARNING:toil.jobGraph:Due to failure we are reducing the remaining retry count of job 'CWLWorkflow' kind-CWLWorkflow/instancedr0axrjw with ID kind-CWLWorkflow/instancedr0axrjw to 0
docker-vm 2020-02-26 00:51:18,219 MainThread WARNING toil.leader: Job 'CWLWorkflow' kind-CWLWorkflow/instancedr0axrjw with ID kind-CWLWorkflow/instancedr0axrjw is completely failed
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/cwltoil", line 11, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/lib/python3.6/site-packages/toil/cwl/cwltoil.py", line 1357, in main
    result = toil.start(wf1)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/toil/common.py", line 800, in start
    return self._runMainLoop(rootJobGraph)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/toil/common.py", line 1070, in _runMainLoop
    jobCache=self._jobCache).run()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/toil/leader.py", line 246, in run
    raise FailedJobsException(self.config.jobStore, self.toilState.totalFailedJobs, self.jobStore)
toil.leader.FailedJobsException
```

If `default` is removed in `tool.cwl` it also works, so there seem to be a collision when both an input is provided and default value is specified. This only happens in a nested workflow. Running the workflow directly works fine:

```
$ cwltoil --logError sub.cwl --inp Hello
{}
```

Everything works as expected in `cwltool`:
```
$ pip3 freeze | grep cwltool
cwltool==2.0.20200224214940
$ cwltool --quiet wf.cwl --inp Hello
WARNING Workflow checker warning:
sub.cwl:6:3:  Source 'inp' of type ["null", "string"] may be incompatible
sub.cwl:11:7:   with sink 'inp' of type "string"

{}
```

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-517)
┆Issue Number: TOIL-517

**Comment by DailyDreaming** [comment]
@mr-c Is this not covered by the conformance tests?

**Comment by DailyDreaming** [comment]
@liinus This branch seems to fix the problem: https://github.com/DataBiosphere/toil/pull/2985

I'll create a separate PR, so that it can be added and toil updated to 3.24.1.

**Comment by liinus** [comment]
I tried the branch (commit 701937100887cfe989b5df0749e1467944c47aa1) and it fails even on tool.cwl (see above):

```
...
docker-vm 2020-03-02 23:53:48,065 MainThread WARNING toil.leader: kind-file_home_ubuntu_toil_nested_workflows_error_tool.cwl/instanceabwqtmmv    INFO:toil.worker:---TOIL WORKER OUTPUT LOG---
docker-vm 2020-03-02 23:53:48,065 MainThread WARNING toil.leader: kind-file_home_ubuntu_toil_nested_workflows_error_tool.cwl/instanceabwqtmmv    INFO:toil:Running Toil version 4.0.0a1-701937100887cfe989b5df0749e1467944c47aa1.
docker-vm 2020-03-02 23:53:48,065 MainThread WARNING toil.leader: kind-file_home_ubuntu_toil_nested_workflows_error_tool.cwl/instanceabwqtmmv    Traceback (most recent call last):
docker-vm 2020-03-02 23:53:48,065 MainThread WARNING toil.leader: kind-file_home_ubuntu_toil_nested_workflows_error_tool.cwl/instanceabwqtmmv      File "/home/ubuntu/toil/src/toil/worker.py", line 366, in workerScript
docker-vm 2020-03-02 23:53:48,066 MainThread WARNING toil.leader: kind-file_home_ubuntu_toil_nested_workflows_error_tool.cwl/instanceabwqtmmv        job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore, defer=defer)
docker-vm 2020-03-02 23:53:48,066 MainThread WARNING toil.leader: kind-file_home_ubuntu_toil_nested_workflows_error_tool.cwl/instanceabwqtmmv      File "/home/ubuntu/toil/src/toil/job.py", line 1392, in _runner
docker-vm 2020-03-02 23:53:48,066 MainThread WARNING toil.leader: kind-file_home_ubuntu_toil_nested_workflows_error_tool.cwl/instanceabwqtmmv        returnValues = self._run(jobGraph, fileStore)
docker-vm 2020-03-02 23:53:48,066 MainThread WARNING toil.leader: kind-file_home_ubuntu_toil_nested_workflows_error_tool.cwl/instanceabwqtmmv      File "/home/ubuntu/toil/src/toil/job.py", line 1329, in _run
docker-vm 2020-03-02 23:53:48,067 MainThread WARNING toil.leader: kind-file_home_ubuntu_toil_nested_workflows_error_tool.cwl/instanceabwqtmmv        return self.run(fileStore)
docker-vm 2020-03-02 23:53:48,067 MainThread WARNING toil.leader: kind-file_home_ubuntu_toil_nested_workflows_error_tool.cwl/instanceabwqtmmv      File "/home/ubuntu/toil/src/toil/cwl/cwltoil.py", line 809, in run
docker-vm 2020-03-02 23:53:48,067 MainThread WARNING toil.leader: kind-file_home_ubuntu_toil_nested_workflows_error_tool.cwl/instanceabwqtmmv        if self.conditional.is_false(cwljob):
docker-vm 2020-03-02 23:53:48,067 MainThread WARNING toil.leader: kind-file_home_ubuntu_toil_nested_workflows_error_tool.cwl/instanceabwqtmmv    AttributeError: 'CWLJob' object has no attribute 'conditional'
docker-vm 2020-03-02 23:53:48,068 MainThread WARNING toil.leader: kind-file_home_ubuntu_toil_nested_workflows_error_tool.cwl/instanceabwqtmmv    ERROR:toil.worker:Exiting the worker because of a failed job on host docker-vm
...
```

**Comment by DailyDreaming** [comment]
@liinus Try it with:
```toil-cwl-runner wf.cwl --inp Hello```

Instead of:
```cwltoil wf.cwl --inp Hello```

We've removed/deprecated `cwltoil` as a keyword so it looks like it's picking up on an old installation.  I didn't realize this would be a bug, so we'll probably have to add a shim to warn users if they try using the old `cwltoil` keyword instead of `toil-cwl-runner`.

If you still have problems, please let us know!

**Comment by liinus** [comment]
@DailyDreaming Yes, this seem to have been the problem. Toil did output the commit id in the log (4.0.0a1-701937100887cfe989b5df0749e1467944c47aa1) that matched the branch so I was confident I had the right version. I was running the branch from a virtual env but also had the latest version (3.24.0) installed on the OS. When running `cwltoil` it probably used 3.24.0, and picking up 4.0.0a1 when starting the worker.

```
$ source venv/bin/activate
(venv) ubuntu@docker-vm:~/toil$ cwltoil --version
3.24.0
(venv) ubuntu@docker-vm:~/toil$ toil-cwl-runner --version
4.0.0a1
```

This branch seem to fix the issue.
