### ISSUE TITLE
Toil process does not terminate when mesos batch system can't create new thread. 

### ISSUE THREAD

**Issue by glmxndr** [DataBiosphere/toil#2991]
When launching a lot of parallel processes, if the subprocess ulimit is reached, the toil process does not stop properly.

Sample of stack:

```
Traceback (most recent call last):
  File "/home/gandrieu/.local/bin/cwltoil", line 11, in <module>
    sys.exit(main())
  File "/home/gandrieu/.local/lib/python2.7/site-packages/toil/cwl/cwltoil.py", line 1508, in main
    outobj = toil.start(wf1)
  File "/home/gandrieu/.local/lib/python2.7/site-packages/toil/common.py", line 783, in start
    self._batchSystem = self.createBatchSystem(self.config)
  File "/home/gandrieu/.local/lib/python2.7/site-packages/toil/common.py", line 928, in createBatchSystem
    return batchSystemClass(**kwargs)
  File "/home/gandrieu/.local/lib/python2.7/site-packages/toil/batchSystems/mesos/batchSystem.py", line 87, in __init__
    super(MesosBatchSystem, self).__init__(config, maxCores, maxMemory, maxDisk)
  File "/home/gandrieu/.local/lib/python2.7/site-packages/toil/batchSystems/abstractBatchSystem.py", line 339, in __init__
    config, config.maxLocalJobs, maxMemory, maxDisk)
  File "/home/gandrieu/.local/lib/python2.7/site-packages/toil/batchSystems/singleMachine.py", line 144, in __init__
    worker.join()
  File "/usr/lib/python2.7/threading.py", line 929, in join
    raise RuntimeError("cannot join thread before it is started")
RuntimeError: cannot join thread before it is started
```

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-519)
┆Issue Number: TOIL-519

**Comment by adamnovak** [comment]
I think we might fix #1902 soon, which would solve the underlying problem (the fact that each `cwltoil` wants to run 10+ threads per core) that is causing the ulimit to be exhausted in the first place. But we should also handle hitting the thread ulimit better.
