### ISSUE TITLE
Launching many cwltoil processes in parallel leads to hanging processes

### ISSUE THREAD

**Issue by glmxndr** [DataBiosphere/toil#2996]
I have a bash script launching many cwltoil instances in parallel, like so:

```bash
for iter in {0..100}
do
  cwltoil ... &
done
```

When doing so, most of the processes are left hanging, with this stacktrace at the end of the logs.

```
Traceback (most recent call last):
  File "/home/gandrieu/.local/bin/cwltoil", line 11, in <module>
    result = main()
  File "/home/gandrieu/.local/lib/python2.7/site-packages/toil/cwl/cwltoil.py", line 1508, in main
    outobj = toil.start(wf1)
  File "/home/gandrieu/.local/lib/python2.7/site-packages/toil/common.py", line 782, in start
    self._batchSystem = self.createBatchSystem(self.config)
  File "/home/gandrieu/.local/lib/python2.7/site-packages/toil/common.py", line 927, in createBatchSystem
    return batchSystemClass(**kwargs)
  File "/home/gandrieu/.local/lib/python2.7/site-packages/toil/batchSystems/mesos/batchSystem.py", line 87, in __init__
    super(MesosBatchSystem, self).__init__(config, maxCores, maxMemory, maxDisk)
  File "/home/gandrieu/.local/lib/python2.7/site-packages/toil/batchSystems/abstractBatchSystem.py", line 339, in __init__
    config, config.maxLocalJobs, maxMemory, maxDisk)
  File "/home/gandrieu/.local/lib/python2.7/site-packages/toil/batchSystems/singleMachine.py", line 140, in __init__
    worker.start()
  File "/usr/lib/python2.7/threading.py", line 736, in start
    _start_new_thread(self.__bootstrap, ())
thread.error: can't start new thread
```

I noticed that if I happen to configure the line with an inexisting input file, the behaviour is the same (many hanging processes) with this stacktrace.

```
Traceback (most recent call last):
  File "/home/gandrieu/.local/bin/cwltoil", line 11, in <module>
    result = main()
  File "/home/gandrieu/.local/lib/python2.7/site-packages/toil/cwl/cwltoil.py", line 1426, in main
    loading_context.overrides_list, tool_file_uri)
  File "/home/gandrieu/.local/lib/python2.7/site-packages/cwltool/main.py", line 258, in load_job_order
    job_order_object, _ = loader.resolve_ref(job_order_file, checklinks=False)
  File "/home/gandrieu/.local/lib/python2.7/site-packages/schema_salad/ref_resolver.py", line 747, in resolve_ref
    doc = self.fetch(doc_url, inject_ids=(not mixin))
  File "/home/gandrieu/.local/lib/python2.7/site-packages/schema_salad/ref_resolver.py", line 1212, in fetch
    text = self.fetch_text(url)
  File "/home/gandrieu/.local/lib/python2.7/site-packages/schema_salad/ref_resolver.py", line 213, in fetch_text
    raise_from(ValidationException(Text(err)), err)
  File "/home/gandrieu/.local/lib/python2.7/site-packages/future/utils/__init__.py", line 483, in raise_from
    raise e
schema_salad.exceptions.ValidationException: [Errno 2] No such file or directory: '/home/gandrieu/Dev/inputs/args.json'
```

The hanging processes are still using around 90 megabytes of RAM each, no CPU activity whatsoever, and a `ps huH p $PID` lists 90 threads for each. I am able to kill these processes with a `killall cwltoil`.

Using pycharm's "Attach to process" functionality (allowing debugging of a running process) on one of these hanging processes reaches a connection timeout.

I could verify by modifying the cwltoil script that the main thread is not blocked, and that the `system.exit()` call is reached.

It looks like one or several threads are launched and are not joined properly.

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-522)
┆Issue Number: TOIL-522

**Comment by adamnovak** [comment]
I think what happens is that those worker threads are not "daemon
threads" as described in
https://docs.python.org/3.6/library/threading.html#thread-objects

When the main thread crashes (due to not being able to create another
worker, or due to the missing input file), nobody tells the worker
threads to stop, so they keep running, waiting for instructions that
never come.

We could fix this by making the worker threads daemons, but to fix
#1902 we are probably going to eliminate worker threads like this
entirely. We could still go through and make sure all the other
threads except the main one are daemons.

**Comment by glmxndr** [comment]
I could verify that the pull request allows the processes to terminate in both cases described in this ticket (with correct config and incorrect config).

**Comment by mr-c** [comment]
@glmxndr Thank you for reporting this issue.

1. `cwltoil` should be replaced by `toil-cwl-runner` as the "cwltoil" alias is deprecated and going away in the next release.

2. Can you share more about your use case and why you need to launch 101 `toil-cwl-runner` instances? If you are just varying the input, it might be better to wrap your workflow as a step in another workflow and scatter an array of your 101 sets of inputs over your original workflow. This will also speed up job execution as you only have the overhead of starting `toil` once.

**Comment by glmxndr** [comment]
@mr-c You're welcome.

1. Thanks! Will update the scripts.

2. We use toil to launch workflows corresponding to treatments on satellite images. These tend to arrive in groups and we were doing some benchmarking to make sure our system could take the load. in our setup, a process monitors a message queue for notification of new input data, and for each message, launches `toil-cwl-runner` on the new data. We don't know when the data arrives and there might be time constraints preventing to wait for a batch.
