### ISSUE TITLE
linkMerge of cwl has broken

### ISSUE THREAD

**Issue by altairwei** [DataBiosphere/toil#3003]
## Feature `linkMerge` of cwl has broken

Toil version 3.24.0-de586251cb579bcb80eef435825cb3cedc202f52

Error log:

```log
INFO:toil.worker:---TOIL WORKER OUTPUT LOG---
INFO:toil:Running Toil version 3.24.0-de586251cb579bcb80eef435825cb3cedc202f52.
Traceback (most recent call last):
  File "/home/testuser/usr/miniconda3/envs/wta/lib/python3.7/site-packages/toil/worker.py", line 366, in workerScript
    job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore, defer=defer)
  File "/home/testuser/usr/miniconda3/envs/wta/lib/python3.7/site-packages/toil/job.py", line 1392, in _runner
    returnValues = self._run(jobGraph, fileStore)
  File "/home/testuser/usr/miniconda3/envs/wta/lib/python3.7/site-packages/toil/job.py", line 1329, in _run
    return self.run(fileStore)
  File "/home/testuser/usr/miniconda3/envs/wta/lib/python3.7/site-packages/toil/cwl/cwltoil.py", line 566, in run
    resolved_cwljob = resolve_indirect(self.cwljob)
  File "/home/testuser/usr/miniconda3/envs/wta/lib/python3.7/site-packages/toil/cwl/cwltoil.py", line 210, in resolve_indirect
    res = _resolve_indirect_inner(inner)
  File "/home/testuser/usr/miniconda3/envs/wta/lib/python3.7/site-packages/toil/cwl/cwltoil.py", line 179, in _resolve_indirect_inner
    result[key] = value.resolve()
  File "/home/testuser/usr/miniconda3/envs/wta/lib/python3.7/site-packages/toil/cwl/cwltoil.py", line 126, in resolve
    source = promise[1][promise[0]]
TypeError: tuple indices must be integers or slices, not str
ERROR:toil.worker:Exiting the worker because of a failed job on host tanglab
WARNING:toil.jobGraph:Due to failure we are reducing the remaining retry count of job 'file:///home/testuser/src/test-folder/tests/test.cwl#test-link-merge/BundleLogs/c4e1067b-8800-4141-a2cb-d4de50f92a55' cat kind-file_home_testuser_src_test-folder_tests_test.cwl_test-link-merge_BundleLogs_c4e1067b-8800-4141-a2cb-d4de50f92a55/instance7q_s67gx with ID kind-file_home_testuser_src_test-folder_tests_test.cwl_test-link-merge_BundleLogs_c4e1067b-8800-4141-a2cb-d4de50f92a55/instance7q_s67gx to 0
```

## How to reproduce the problem

Here is the content of cwl document file `test.cwl`:

```yaml
class: Workflow
cwlVersion: v1.0
id: test-link-merge
inputs:
  - id: echo1_log
    type: string
  - id: echo2_log
    type: string
outputs:
  - id: log
    outputSource:
      - BundleLogs/logs
    type: File
requirements:
  - class: MultipleInputFeatureRequirement
steps:
  - id: echo1
    in:
      - id: echo1_op
        source: echo1_log
    out:
      - id: output
    run:
      class: CommandLineTool
      cwlVersion: v1.0
      baseCommand: echo
      inputs:
        - id: echo1_op
          type: string
          inputBinding:
            position: 1
      outputs:
        - id: output
          type: stdout
      stdout: echo1.log
  - id: echo2
    in:
      - id: echo2_op
        source: echo2_log
    out:
      - id: output
    run:
      class: CommandLineTool
      cwlVersion: v1.0
      baseCommand: echo
      inputs:
        - id: echo2_op
          type: string
          inputBinding:
            position: 1
      outputs:
        - id: output
          type: stdout
      stdout: echo2.log
  - id: BundleLogs
    in:
      - id: log_files
        linkMerge: merge_flattened
        source:
          - echo1/output
          - echo2/output
    out:
      - id: logs
    run:
      class: CommandLineTool
      cwlVersion: v1.0
      baseCommand: cat
      inputs:
        - id: log_files
          type: 'File[]'
          inputBinding:
            position: 1
      outputs:
        - id: logs
          type: stdout
      stdout: logs.txt
```

Here is the content of inputs object file `test.yml`:

```yaml
echo1_log: Hello World 1
echo2_log: Hello World 2
```

### Use toil-cwl-runner:

```shell
toil-cwl-runner --writeLogs . --logFile cwltoil.log test.cwl test.yml
```

Error log:

```log
INFO:toil.worker:---TOIL WORKER OUTPUT LOG---
INFO:toil:Running Toil version 3.24.0-de586251cb579bcb80eef435825cb3cedc202f52.
Traceback (most recent call last):
  File "/home/testuser/usr/miniconda3/envs/wta/lib/python3.7/site-packages/toil/worker.py", line 366, in workerScript
    job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore, defer=defer)
  File "/home/testuser/usr/miniconda3/envs/wta/lib/python3.7/site-packages/toil/job.py", line 1392, in _runner
    returnValues = self._run(jobGraph, fileStore)
  File "/home/testuser/usr/miniconda3/envs/wta/lib/python3.7/site-packages/toil/job.py", line 1329, in _run
    return self.run(fileStore)
  File "/home/testuser/usr/miniconda3/envs/wta/lib/python3.7/site-packages/toil/cwl/cwltoil.py", line 566, in run
    resolved_cwljob = resolve_indirect(self.cwljob)
  File "/home/testuser/usr/miniconda3/envs/wta/lib/python3.7/site-packages/toil/cwl/cwltoil.py", line 210, in resolve_indirect
    res = _resolve_indirect_inner(inner)
  File "/home/testuser/usr/miniconda3/envs/wta/lib/python3.7/site-packages/toil/cwl/cwltoil.py", line 179, in _resolve_indirect_inner
    result[key] = value.resolve()
  File "/home/testuser/usr/miniconda3/envs/wta/lib/python3.7/site-packages/toil/cwl/cwltoil.py", line 126, in resolve
    source = promise[1][promise[0]]
TypeError: tuple indices must be integers or slices, not str
ERROR:toil.worker:Exiting the worker because of a failed job on host tanglab
WARNING:toil.jobGraph:Due to failure we are reducing the remaining retry count of job 'file:///home/testuser/src/test-folder/tests/test.cwl#test-link-merge/BundleLogs/c4e1067b-8800-4141-a2cb-d4de50f92a55' cat kind-file_home_testuser_src_test-folder_tests_test.cwl_test-link-merge_BundleLogs_c4e1067b-8800-4141-a2cb-d4de50f92a55/instance7q_s67gx with ID kind-file_home_testuser_src_test-folder_tests_test.cwl_test-link-merge_BundleLogs_c4e1067b-8800-4141-a2cb-d4de50f92a55/instance7q_s67gx to 0
```

### Use cwltool:

```shell
cwltool test.cwl test.yml
```

The output:

```log
INFO /home/testuser/usr/miniconda3/envs/wta/bin/cwltool 1.0.20190906054215
INFO Resolved 'test.cwl' to 'file:///home/testuser/src/test-folder/tests/test.cwl'
INFO [workflow ] start
INFO [workflow ] starting step echo2
INFO [step echo2] start
INFO [job echo2] /tmp/se6vhf20$ echo \
    'Hello World 2' > /tmp/se6vhf20/echo2.log
INFO [job echo2] completed success
INFO [step echo2] completed success
INFO [workflow ] starting step echo1
INFO [step echo1] start
INFO [job echo1] /tmp/u2uimnbd$ echo \
    'Hello World 1' > /tmp/u2uimnbd/echo1.log
INFO [job echo1] completed success
INFO [step echo1] completed success
INFO [workflow ] starting step BundleLogs
INFO [step BundleLogs] start
INFO [job BundleLogs] /tmp/fl895pdf$ cat \
    /tmp/tmpv92lp2p3/stga2fda6e1-aa18-4efb-a1c4-e797a960859b/echo1.log \
    /tmp/tmpv92lp2p3/stgc5075679-9ee0-4e63-a78f-7ce48922afb4/echo2.log > /tmp/fl895pdf/logs.txt
INFO [job BundleLogs] completed success
INFO [step BundleLogs] completed success
INFO [workflow ] completed success
{
    "log": {
        "location": "file:///home/testuser/src/test-folder/tests/logs.txt",
        "basename": "logs.txt",
        "class": "File",
        "checksum": "sha1$8a32893e6f95776abbd184219bea56f23dac800e",
        "size": 28,
        "path": "/home/testuser/src/test-folder/tests/logs.txt"
    }
}
INFO Final process status is success
```

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-523)
┆Issue Number: TOIL-523

**Comment by altairwei** [comment]
Here is a successful try with Toil 3.20.0

```log
Resolved 'test.cwl' to 'file:///home/testuser/src/test-folder/tests/test.cwl'
Limiting maxCores to CPU count of system (8).
Limiting maxMemory to physically available memory (67334377472).
Limiting maxDisk to physically available disk (43784122368).
Running Toil version 3.20.0-cf34ca3416697f2abc816b2538f20ee29ba16932.
Issued job 'file:///home/testuser/src/test-folder/tests/test.cwl#echo2/d2f068df-b23b-4963-89b6-08ab7bac2c57' echo g/o/jobm1hax28f with job batch system ID: 1 and cores: 1, disk: 3.0 G, and memory: 2.0 G
Issued job 'file:///home/testuser/src/test-folder/tests/test.cwl#echo1/660c9862-86bc-4cd6-bd9b-ebd5544b679c' echo 8/Q/jobmbpvc44_ with job batch system ID: 2 and cores: 1, disk: 3.0 G, and memory: 2.0 G
Job ended successfully: 'file:///home/testuser/src/test-folder/tests/test.cwl#echo2/d2f068df-b23b-4963-89b6-08ab7bac2c57' echo g/o/jobm1hax28f
Job ended successfully: 'file:///home/testuser/src/test-folder/tests/test.cwl#echo1/660c9862-86bc-4cd6-bd9b-ebd5544b679c' echo 8/Q/jobmbpvc44_
Issued job 'file:///home/testuser/src/test-folder/tests/test.cwl#BundleLogs/dff69b3a-bb4f-4f4b-b5bf-d28128c3706d' cat z/N/jobsrvpssf_ with job batch system ID: 3 and cores: 1, disk: 3.0 G, and memory: 2.0 G
Job ended successfully: 'file:///home/testuser/src/test-folder/tests/test.cwl#BundleLogs/dff69b3a-bb4f-4f4b-b5bf-d28128c3706d' cat z/N/jobsrvpssf_
Issued job 'file:///home/testuser/src/test-folder/tests/test.cwl#echo2/d2f068df-b23b-4963-89b6-08ab7bac2c57' echo g/o/jobm1hax28f with job batch system ID: 4 and cores: 1, disk: 3.0 G, and memory: 2.0 G
Issued job 'file:///home/testuser/src/test-folder/tests/test.cwl#echo1/660c9862-86bc-4cd6-bd9b-ebd5544b679c' echo 8/Q/jobmbpvc44_ with job batch system ID: 5 and cores: 1, disk: 3.0 G, and memory: 2.0 G
Job ended successfully: 'file:///home/testuser/src/test-folder/tests/test.cwl#echo2/d2f068df-b23b-4963-89b6-08ab7bac2c57' echo g/o/jobm1hax28f
Job ended successfully: 'file:///home/testuser/src/test-folder/tests/test.cwl#echo1/660c9862-86bc-4cd6-bd9b-ebd5544b679c' echo 8/Q/jobmbpvc44_
Finished toil run successfully.
Successfully deleted the job store: FileJobStore(/tmp/tmpo1pfufgy)

```

**Comment by altairwei** [comment]
I think the problem was indroduced by `CWLJobWrapper.run` of `cwl/cwltoil.py` ：

```
    def run(self, file_store):
        cwljob = resolve_indirect(self.cwljob)
        fill_in_defaults(
            self.cwltool.tool['inputs'], cwljob,
            self.runtime_context.make_fs_access(
                self.runtime_context.basedir or ""))
        realjob = CWLJob(self.cwltool, cwljob, self.runtime_context)
        self.addChild(realjob)
        return realjob.rv()
```

After v3.20.0, `CWLJobWrapper.run` returns a tuple instead of a promise.

I have noticed that this problem have been fixed at #2845 , but these updates haven't been released yet.

**Comment by adamnovak** [comment]
If #2845 does fix this, we should have the fix in the next release, which would be due out at the beginning of April.

@altairwei Can you install Toil from source and use that until then? Or stick with 3.20.0?

**Comment by altairwei** [comment]
> If #2845 does fix this, we should have the fix in the next release, which would be due out at the beginning of April.
> 
> @altairwei Can you install Toil from source and use that until then? Or stick with 3.20.0?

OK, I will use 3.20.0 until the new version is released

**Comment by kaushik-work** [comment]
@altairwei and @adamnovak I can confirm that master (fcce48fe8b2bef8f05865d2db586b1c8763c6f47) executes this without errors:

```
KG-mac.fios-router.home 2020-03-11 16:43:46,255 MainThread INFO toil.leader: Finished toil run successfully.
{
    "log": {
        "location": "file:///Users/kghose/Downloads/logs.txt",
        "basename": "logs.txt",
        "nameroot": "logs",
        "nameext": ".txt",
        "class": "File",
        "checksum": "sha1$8a32893e6f95776abbd184219bea56f23dac800e",
        "size": 28
    }
```
