### ISSUE TITLE
toil_http_parser error when trying to run Cactus on mesos w/ toil 4.0.0

### ISSUE THREAD

**Issue by glennhickey** [DataBiosphere/toil#3032]
I get  `ModuleNotFoundError: No module named 'toil_http_parser'`  when trying to use Cactus with toil 4.0.0.  Here are the steps (very similar to #2968)
```
toil --version
4.0.0
toil launch-cluster glenn --leaderNodeType=t2.medium --keyPairName glenn....
INFO:toil:Using default docker appliance of quay.io/ucsc_cgl/toil:4.0.0-1c5f5fa1d8811660ee9b1b602b41607b63c6dd05-py3.6 as TOIL_APPLIANCE_SELF is not set.

toil ssh-cluster glenn
screen
virtualenv -p python3 --system-site-packages venv
. venv/bin/activate
git clone https://github.com/ComparativeGenomicsToolkit/cactus.git --recursive
cd cactus
pip install -U .
cactus  --nodeTypes c4.8xlarge:0.6,r3.8xlarge --minNodes 0,0 --maxNodes 20,2 --provisioner aws --batchSystem mesos --logDebug aws:us-west-2:glennhickey-jobstore ./examples/evolverMammals.txt output.hal  --logFile log
```
And here is the output:
```
Root logger is at level 'DEBUG', 'toil' logger at level 'DEBUG'.
Logging to file 'log'.
Root logger is at level 'DEBUG', 'toil' logger at level 'DEBUG'.
Logging to file 'log'.
Total machine size: 2 cores
CPU quota: -1
Traceback (most recent call last):
  File "//venv/bin/cactus", line 8, in <module>
    sys.exit(main())
  File "//venv/lib/python3.6/site-packages/cactus/progressive/cactus_progressive.py", line 403, in main
    runCactusProgressive(options)
  File "//venv/lib/python3.6/site-packages/cactus/progressive/cactus_progressive.py", line 409, in runCactusProgressive
    with Toil(options) as toil:
  File "/usr/local/lib/python3.6/dist-packages/toil/common.py", line 735, in __enter__
    config.setOptions(self.options)
  File "/usr/local/lib/python3.6/dist-packages/toil/common.py", line 217, in setOptions
    setBatchOptions(self, setOption)
  File "/usr/local/lib/python3.6/dist-packages/toil/batchSystems/options.py", line 112, in setOptions
    batchSystem = factory()
  File "/usr/local/lib/python3.6/dist-packages/toil/batchSystems/registry.py", line 32, in _mesosBatchSystemFactory
    from toil.batchSystems.mesos.batchSystem import MesosBatchSystem
  File "/usr/local/lib/python3.6/dist-packages/toil/batchSystems/mesos/batchSystem.py", line 43, in <module>
    from pymesos import MesosSchedulerDriver, Scheduler, encode_data, decode_data
  File "/usr/local/lib/python3.6/dist-packages/pymesos/__init__.py", line 2, in <module>
    from .scheduler import MesosSchedulerDriver
  File "/usr/local/lib/python3.6/dist-packages/pymesos/scheduler.py", line 7, in <module>
    from .process import Process
  File "/usr/local/lib/python3.6/dist-packages/pymesos/process.py", line 18, in <module>
    from toil_http_parser.http import HttpParser
ModuleNotFoundError: No module named 'toil_http_parser'
```

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-537)
┆Issue Number: TOIL-537

**Comment by DailyDreaming** [comment]
@glennhickey Looking at this now.

**Comment by adamnovak** [comment]
I think we just never actually renamed https://github.com/DailyDreaming/toil-http-parser. The PyPI package is called `toil-http-parser`, but you still import `http_parser` to use it (and you thus can't have it installed at the same time as `http-parser`).

**Comment by DailyDreaming** [comment]
@glennhickey This seems to have worked after Adam's fix and another minor bug fix removing a deprecated function in batchsystems:

```
virtualenv -p python3.7 v3nv && . v3nv/bin/activate && pip install toil[all]==4.0.0
toil launch-cluster im-also-glenn --leaderNodeType=t2.medium --keyPairName id_rsa --zone us-west-2a
toil ssh-cluster --zone us-west-2a im-also-glenn
```

```
screen
virtualenv -p python3.7 --system-site-packages v3nv && . v3nv/bin/activate
git clone https://github.com/ComparativeGenomicsToolkit/cactus.git --recursive && cd cactus && pip install -U .
cactus --nodeTypes t2.2xlarge --minNodes 0 --maxNodes 4 --provisioner aws --batchSystem mesos --logDebug aws:us-west-2:deleteme ./examples/evolverMammals.txt output.hal --logFile evolverMammalsLogfile
```

**Comment by glennhickey** [comment]
Thanks.  The command lines you posted give me the same error.  But if I use the latest Toil master instead of  `pip install toil[all]==4.0.0`  it seems to fix it. 

It does die shortly after with 
```
from cactus.shared.common import getOptionalAttrib
          File "/tmp/tmpg4385wbo/2bc6b9a586696b09ef20af951e39264d/cactus/shared/common.py", line 38, in <module>
            from sonLib.bioio import popenCatch
        ModuleNotFoundError: No module named 'sonLib'
        ERROR:toil.worker:Exiting the worker because of a failed job on host ip-172-31-31-44.us-west-2.compute.internal
```
but I suspect this is a problem on the cactus end.

**Comment by DailyDreaming** [comment]
@glennhickey I ran this last night and even though I assumed it was successful since it avoided the original error it actually never stopped running, so I'm making a separate issue.
