### ISSUE TITLE
invalid --batchSystem generates a key error instead of a usage message

### ISSUE THREAD

**Issue by diekhans** [DataBiosphere/toil#3038]
specifying` --batchSystem=sge`  generates  the error:

```
quanah 2020-04-13 21:02:47,010 MainThread DEBUG toil.lib.bioio: Root logger is at level 'DEBUG', 'toil' logger at level 'DEBUG'.
quanah 2020-04-13 21:02:47,012 MainThread DEBUG toil.lib.bioio: Logging to file 'log.txt'.
quanah 2020-04-13 21:02:47,013 MainThread DEBUG toil.lib.threading: Total machine size: 72 cores
quanah 2020-04-13 21:02:47,013 MainThread DEBUG toil.lib.threading: CPU quota: -1
Traceback (most recent call last):
  File "arf.py", line 11, in <module>
    with Toil(options) as toil:
  File "/lustre/scratch/mdiekhan/cactus/src/toil-debug/src/toil/common.py", line 736, in __enter__
    config.setOptions(self.options)
  File "/lustre/scratch/mdiekhan/cactus/src/toil-debug/src/toil/common.py", line 217, in setOptions
    setBatchOptions(self, setOption)
  File "/lustre/scratch/mdiekhan/cactus/src/toil-debug/src/toil/batchSystems/options.py", line 115, in setOptions
    factory = batchSystemFactoryFor(batchSystem)
  File "/lustre/scratch/mdiekhan/cactus/src/toil-debug/src/toil/batchSystems/registry.py", line 93, in batchSystemFactoryFor
    return _batchSystemRegistry[batchSystem ]
KeyError: 'sge'

```

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-540)
┆Issue Number: TOIL-540

**Comment by DailyDreaming** [comment]
@jeffrey856 Think you could add this error handling?  It should tell the user that they've specified an invalid batch system and then list the valid ones.

**Comment by diekhans** [comment]
doable with the choices argparse option

**Comment by DailyDreaming** [comment]
@diekhans You're right, I think adding `choices=unique_names()` should do it right here: https://github.com/DataBiosphere/toil/blob/727b7e1c30938c575717b46f0bc9f88758e3b6e9/src/toil/batchSystems/options.py#L124
