### ISSUE TITLE
Log file already exists

### ISSUE THREAD

**Issue by ionox0** [DataBiosphere/toil#3129]
We are experiencing an issue where a chained CWL job is trying to create a duplicate link to one of the log files. 

The offending portion of the CWL workflow has these two steps:
```
  find_covered_intervals:
    run: ../../cwl_tools/gatk/FindCoveredIntervals.cwl
    in:
      bams: bams
      reference_sequence: reference_fasta
      ignore_misencoded_base_qualities: fci__basq_fix
      out:
        valueFrom: ${return inputs.patient_id + '.fci.list'}
    out: [fci_list]

  list2bed:
    run: ../../cwl_tools/python/list2bed.cwl
    in:
      input_file: find_covered_intervals/fci_list
      output_filename:
        valueFrom: ${return inputs.input_file.basename.replace('.list', '.bed.srt')}
    out: [output_file]
```

The result is the following error:
```
Traceback (most recent call last):
  File "miniconda3/envs/ACCESS_1.3.40/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "miniconda3/envs/ACCESS_1.3.40/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "miniconda3/envs/ACCESS_1.3.40/lib/python2.7/site-packages/toil/statsAndLogging.py", line 153, in statsAndLoggingAggregator
    break
  File "miniconda3/envs/ACCESS_1.3.40/lib/python2.7/site-packages/toil/jobStores/fileJobStore.py", line 549, in readStatsAndLogging
    callback(fH)
  File "miniconda3/envs/ACCESS_1.3.40/lib/python2.7/site-packages/toil/statsAndLogging.py", line 146, in callback
    message='Received Toil worker log. Disable debug level logging to hide this output')
  File "miniconda3/envs/ACCESS_1.3.40/lib/python2.7/site-packages/toil/statsAndLogging.py", line 109, in writeLogFiles
    os.symlink(os.path.relpath(fullName, path), name)
OSError: [Errno 17] File exists
```

When I put some debugging in the code to see the file name it appears as so:
`file:--workflows-access_workflows-v1-pipeline_1.3.39-ACCESS--Pipeline-cwl_tools-python-list2bed.cwl_list2bed_kind--file_work_000.log`

And I can see that indeed that file is already present in the `--logDir`

If I should create a more reproducible example I can look into it. I feel this may have something to do with the `000` extension not being incremented, or perhaps a threading issue.

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-593)
┆Issue Number: TOIL-593

**Comment by DailyDreaming** [comment]
Closed by https://github.com/DataBiosphere/toil/pull/3130 .
