### ISSUE TITLE
TypeError during sock.sendall("CONNECT %s HTTP/1.0\r\n" % host)

### ISSUE THREAD

**Issue by fbemm** [DataBiosphere/toil#3140]
I am trying to launch a cluster with:

`toil launch-cluster --zone eu-central-1c --keyPairName aws --leaderNodeType t2.micro cactus --logDebug`

But keep getting the following error:

```
Traceback (most recent call last):
  File "/cactus/env/bin/toil", line 11, in <module>
    sys.exit(main())
  File "/cactus/env/lib/python3.7/site-packages/toil/utils/toilMain.py", line 25, in main
    module.main()
  File "/cactus/env/lib/python3.7/site-packages/toil/utils/toilLaunchCluster.py", line 154, in main
    awsEc2ExtraSecurityGroupIds=config.awsEc2ExtraSecurityGroupIds)
  File "/cactus/env/lib/python3.7/site-packages/toil/provisioners/aws/awsProvisioner.py", line 153, in launchCluster
    profileArn = kwargs.get('awsEc2ProfileArn') or self._getProfileArn()
  File "/cactus/env/lib/python3.7/site-packages/toil/provisioners/aws/awsProvisioner.py", line 95, in wrapper
    return f(*args, **kwargs)
  File "/cactus/env/lib/python3.7/site-packages/toil/provisioners/aws/awsProvisioner.py", line 652, in _getProfileArn
    iamRoleName = self._ctx.setup_iam_ec2_role(role_name=_INSTANCE_PROFILE_ROLE_NAME, policies=policy)
  File "/cactus/env/lib/python3.7/site-packages/toil/lib/context.py", line 535, in setup_iam_ec2_role
    "Action": ["sts:AssumeRole"]}
  File "/cactus/env/lib/python3.7/site-packages/boto/iam/connection.py", line 1155, in create_role
    return self.get_response('CreateRole', params)
  File "/cactus/env/lib/python3.7/site-packages/boto/iam/connection.py", line 85, in get_response
    response = self.make_request(action, params, path, verb)
  File "/cactus/env/lib/python3.7/site-packages/boto/connection.py", line 1117, in make_request
    return self._mexe(http_request)
  File "/cactus/env/lib/python3.7/site-packages/boto/connection.py", line 914, in _mexe
    self.is_secure)
  File "/cactus/env/lib/python3.7/site-packages/boto/connection.py", line 705, in get_http_connection
    return self.new_http_connection(host, port, is_secure)
  File "/cactus/env/lib/python3.7/site-packages/boto/connection.py", line 747, in new_http_connection
    connection = self.proxy_ssl(host, is_secure and 443 or 80)
  File "/cactus/env/lib/python3.7/site-packages/boto/connection.py", line 797, in proxy_ssl
    sock.sendall("CONNECT %s HTTP/1.0\r\n" % host)
TypeError: a bytes-like object is required, not 'str'
```

Any ideas where to start debugging?

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-598)
┆Issue Number: TOIL-598

**Comment by fbemm** [comment]
Proxy and proxy port are set correct. `sock.sendall` tries to send `CONNECT iam.amazonaws.com:443 HTTP/1.0`

**Comment by fbemm** [comment]
I manually encode the commands to send:

```
        cmd = "CONNECT %s HTTP/1.0\r\n" % host
        sock.sendall(cmd.encode())
```

Seems that fixes this issues but the next one follows right away:

```
Traceback (most recent call last):
  File "/cactus/env/bin/toil", line 11, in <module>
    sys.exit(main())
  File "/cactus/env/lib/python3.7/site-packages/toil/utils/toilMain.py", line 25, in main
    module.main()
  File "/cactus/env/lib/python3.7/site-packages/toil/utils/toilLaunchCluster.py", line 154, in main
    awsEc2ExtraSecurityGroupIds=config.awsEc2ExtraSecurityGroupIds)
  File "/cactus/env/lib/python3.7/site-packages/toil/provisioners/aws/awsProvisioner.py", line 153, in launchCluster
    profileArn = kwargs.get('awsEc2ProfileArn') or self._getProfileArn()
  File "/cactus/env/lib/python3.7/site-packages/toil/provisioners/aws/awsProvisioner.py", line 95, in wrapper
    return f(*args, **kwargs)
  File "/cactus/env/lib/python3.7/site-packages/toil/provisioners/aws/awsProvisioner.py", line 652, in _getProfileArn
    iamRoleName = self._ctx.setup_iam_ec2_role(role_name=_INSTANCE_PROFILE_ROLE_NAME, policies=policy)
  File "/cactus/env/lib/python3.7/site-packages/toil/lib/context.py", line 535, in setup_iam_ec2_role
    "Action": ["sts:AssumeRole"]}
  File "/cactus/env/lib/python3.7/site-packages/boto/iam/connection.py", line 1155, in create_role
    return self.get_response('CreateRole', params)
  File "/cactus/env/lib/python3.7/site-packages/boto/iam/connection.py", line 85, in get_response
    response = self.make_request(action, params, path, verb)
  File "/cactus/env/lib/python3.7/site-packages/boto/connection.py", line 1119, in make_request
    return self._mexe(http_request)
  File "/cactus/env/lib/python3.7/site-packages/boto/connection.py", line 916, in _mexe
    self.is_secure)
  File "/cactus/env/lib/python3.7/site-packages/boto/connection.py", line 705, in get_http_connection
    return self.new_http_connection(host, port, is_secure)
  File "/cactus/env/lib/python3.7/site-packages/boto/connection.py", line 747, in new_http_connection
    connection = self.proxy_ssl(host, is_secure and 443 or 80)
  File "/cactus/env/lib/python3.7/site-packages/boto/connection.py", line 810, in proxy_ssl
    resp = http_client.HTTPResponse(sock, strict=True, debuglevel=self.debug)
TypeError: __init__() got an unexpected keyword argument 'strict'  
```

**Comment by fbemm** [comment]
Same happens if I run everything from fresh t2.micro.

**Comment by DailyDreaming** [comment]
@fbemm Sorry for the trouble.  Looks like an old py2/py3 bug that was missed.  I'll look into it.
