### ISSUE TITLE
Error reading lsf.conf (utf-8)

### ISSUE THREAD

**Issue by caballero** [DataBiosphere/toil#3353]
I am running some CWL workfows using LSF submitter but I found the lsf.conf is in utf-8 format and toil failed to decode it:

```
[2020-11-30T20:49:57+0000] [MainThread] [I] [toil] Running Toil version 4.2.0-3aa1da130141039cb357efe36d7df9b9f6ae9b5b on host noah.
Cannot get parameter information from lsf.conf or ego.conf for LIM from host<noah>
[2020-11-30T20:49:58+0000] [Thread-2  ] [E] [toil.batchSystems.abstractGridEngineBatchSystem] GridEngine like batch system failure
Traceback (most recent call last):
  File "~/lib/python3.6/site-packages/toil/batchSystems/abstractGridEngineBatchSystem.py", line 226, in run
    while self._runStep():
  File "~/python3.6/site-packages/toil/batchSystems/abstractGridEngineBatchSystem.py", line 215, in _runStep
    activity |= self.createJobs(newJob)
  File "~/python3.6/site-packages/toil/batchSystems/abstractGridEngineBatchSystem.py", line 121, in createJobs
    subLine = self.prepareSubmission(cpu, memory, jobID, command, jobName)
  File "~/python3.6/site-packages/toil/batchSystems/lsf.py", line 88, in prepareSubmission
    return self.prepareBsub(cpu, memory, jobID) + [command]
  File "~/python3.6/site-packages/toil/batchSystems/lsf.py", line 253, in prepareBsub
    mem_resource = parse_memory_resource(mem)
  File "~/python3.6/site-packages/toil/batchSystems/lsfHelper.py", line 183, in parse_memory_resource
    return parse_memory(mem, True)
  File "~/python3.6/site-packages/toil/batchSystems/lsfHelper.py", line 195, in parse_memory
    lsf_unit = get_lsf_units(resource=resource)
  File "~/python3.6/site-packages/toil/batchSystems/lsfHelper.py", line 136, in get_lsf_units
    lsf_units = apply_conf_file(get_lsf_units_from_stream, LSF_CONF_FILENAME)
  File "~/python3.6/site-packages/toil/batchSystems/lsfHelper.py", line 71, in apply_conf_file
    value = fn(conf_handle)
  File "~/python3.6/site-packages/toil/batchSystems/lsfHelper.py", line 83, in get_lsf_units_from_stream
    for k, v in tokenize_conf_stream(stream):
  File "~/python3.6/site-packages/toil/batchSystems/lsfHelper.py", line 92, in tokenize_conf_stream
    for line in conf_handle:
  File "~/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 1765: ordinal not in range(128)
```

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-737)
┆Issue Number: TOIL-737

**Comment by mr-c** [comment]
@caballero Thanks for reporting this! Does https://github.com/DataBiosphere/toil/pull/3354 fix it for you? If it does, I'll merge it and the fix will be part of the next release.

**Comment by caballero** [comment]
Thanks, that should work, let me try, but could I recommend having an encoding autodetection part?

**Comment by caballero** [comment]
I confirm the change works in my particular case

**Comment by mr-c** [comment]
> Thanks, that should work, let me try, but could I recommend having an encoding autodetection part?

I don't know how to autodetect the encoding in Python. Absent that I'm happy to stick with utf-8 given the near ubiquity of that encoding in 2020
