### ISSUE TITLE
Toil fails with RecursionError when restarting big workflow

### ISSUE THREAD

**Issue by glennhickey** [DataBiosphere/toil#3393]
```
Traceback (most recent call last):
  File "//venv/bin/cactus-align", line 8, in <module>
    sys.exit(main())
  File "//venv/lib/python3.6/site-packages/cactus/setup/cactus_align.py", line 139, in main
    results_dict = toil.restart()
  File "/usr/local/lib/python3.6/dist-packages/toil/common.py", line 860, in restart
    rootJobGraph = self._jobStore.clean(jobCache=self._jobCache)
  File "/usr/local/lib/python3.6/dist-packages/toil/jobStores/abstractJobStore.py", line 526, in clean
    getConnectedJobs(self.loadRootJob())
  File "/usr/local/lib/python3.6/dist-packages/toil/jobStores/abstractJobStore.py", line 517, in getConnectedJobs
    getConnectedJobs(getJob(successorJobStoreID))
  File "/usr/local/lib/python3.6/dist-packages/toil/jobStores/abstractJobStore.py", line 517, in getConnectedJobs
    getConnectedJobs(getJob(successorJobStoreID))
  File "/usr/local/lib/python3.6/dist-packages/toil/jobStores/abstractJobStore.py", line 517, in getConnectedJobs
    getConnectedJobs(getJob(successorJobStoreID))
  [Previous line repeated 992 more times]
  File "/usr/local/lib/python3.6/dist-packages/toil/jobStores/abstractJobStore.py", line 514, in getConnectedJobs
    for successorJobStoreID in [x.jobStoreID for x in jobs]:
RecursionError: maximum recursion depth exceeded
```

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-765)
┆Issue Number: TOIL-765

**Comment by DailyDreaming** [comment]
@glennhickey Interesting.  I can refactor this to be non-recursive.  Toil's had a few more releases than the 4.2.0 that cactus has pinned, but it looks like this is still the same logic.

**Comment by DailyDreaming** [comment]
Should be a fix here (assuming tests pass and I didn't mess up something obvious): https://github.com/DataBiosphere/toil/pull/3394

**Comment by glennhickey** [comment]
Great, thanks!
