### ISSUE TITLE
--logDebug : ValueError: Unknown level: 'Debug'

### ISSUE THREAD

**Issue by jfouret** [DataBiosphere/toil#3407]
Hi, 

After upgrading version, I had some issues in my CI/CD pipelines:

When I use the parameter `--logDebug`, I got the following error.

```
$ for workflow in $(ls workflow*.cwl | sed -e 's/^workflow//g' | sed -e 's/cwl$//g') ; do echo "start cwl file $workflow"; for input in $(ls test/*input${workflow}yml) ; do echo "start input " ; OUTDIR=test/outdir_${workflow}_$(echo $input | sed -e 's/test\///g') ; JOBSTORE=${OUTDIR}.jobStore ; mkdir -p ${OUTDIR}.tmp ; mkdir -p ${OUTDIR}.tmpoutdir ; mkdir -p ${OUTDIR}.workdir ; echo "start job" ; toil-cwl-runner --logDebug --workDir ${OUTDIR}.workdir --tmpdir-prefix ${OUTDIR}.tmp --tmp-outdir-prefix ${OUTDIR}.tmpoutdir --outdir $OUTDIR --jobStore $JOBSTORE workflow${workflow}cwl $input ; done ; done
start cwl file .
start input 
start job
Traceback (most recent call last):
  File "/src/toil/venv/bin/toil-cwl-runner", line 33, in <module>
    sys.exit(load_entry_point('toil', 'console_scripts', 'toil-cwl-runner')())
  File "/src/toil/src/toil/cwl/cwltoil.py", line 2048, in main
    cwllogger.setLevel(options.logLevel)
  File "/usr/lib/python3.7/logging/__init__.py", line 1358, in setLevel
    self.level = _checkLevel(level)
  File "/usr/lib/python3.7/logging/__init__.py", line 192, in _checkLevel
    raise ValueError("Unknown level: %r" % level)
ValueError: Unknown level: 'Debug'
```

Here is the Dokerfile for the container used to run the job.

```
FROM debian:stable-slim

RUN apt-get update && \
    apt-get -y upgrade && \ 
    apt-get -y install wget curl python3 bc git openssh-client wget curl rsync sshpass python3-pip nodejs unzip make

RUN curl -fsSL https://get.docker.com -o get-docker.sh && \ 
    sh get-docker.sh

RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 1
RUN update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1

RUN pip install python-keystoneclient python-swiftclient virtualenv

RUN mkdir -p /src 

ENV TOIL_COMMIT d6c171e77edf3b6bde3daa7385b5ea8efd01f073

RUN wget https://codeload.github.com/DataBiosphere/toil/zip/$TOIL_COMMIT -O toil-$TOIL_COMMIT.zip && \
    unzip toil-$TOIL_COMMIT.zip && \
    rm -f toil-$TOIL_COMMIT.zip
RUN mv toil-$TOIL_COMMIT /src/toil

WORKDIR /src/toil

RUN virtualenv venv
RUN . venv/bin/activate && \
    make prepare && \
    make develop extras=[cwl]

ENV PATH="$PATH:/src/toil/venv/bin/"

WORKDIR /tmp
```

Of note using the parameter `--logLevel DEBUG` fixed the issue.

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-773)
┆Issue Number: TOIL-773

**Comment by DailyDreaming** [comment]
@jfouret That shouldn't be happening.  Will look into it.  Thanks for posting.

**Comment by DailyDreaming** [comment]
This looks like it might be fixed already: https://github.com/DataBiosphere/toil/blob/master/src/toil/cwl/cwltoil.py#L2064

The latest version of toil should resolve this.

**Comment by DailyDreaming** [comment]
Closing this.  If you encounter more problems, please reopen.
