### ISSUE TITLE
Failing to save user script resource because it isn't in a `site-packages` when Toil is installed in a venv.

### ISSUE THREAD

**Issue by imilos** [DataBiosphere/toil#3418]
I'm trying to follow the example at https://toil.readthedocs.io/en/latest/running/cloud/kubernetes.html, Option 2. However, I'm getting this:
```
(toil) [milos@mmilos toil_kube]$ python3 tutorial_helloworld.py aws:us-east-1:toil-kubernetes-example-milos-3 --batchSystem kubernetes --realTimeLogging --logInfo --disableCaching false
[2021-01-12T08:07:18+0100] [MainThread] [I] [botocore.credentials] Found credentials in shared credentials file: ~/.aws/credentials
[2021-01-12T08:07:18+0100] [MainThread] [I] [botocore.credentials] Found credentials in shared credentials file: ~/.aws/credentials
[2021-01-12T08:07:18+0100] [MainThread] [I] [botocore.credentials] Found credentials in shared credentials file: ~/.aws/credentials
[2021-01-12T08:07:26+0100] [MainThread] [I] [toil] Using default docker registry of quay.io/ucsc_cgl as TOIL_DOCKER_REGISTRY is not set.
[2021-01-12T08:07:26+0100] [MainThread] [I] [toil] Using default docker name of toil as TOIL_DOCKER_NAME is not set.
[2021-01-12T08:07:26+0100] [MainThread] [I] [toil] Using default docker appliance of quay.io/ucsc_cgl/toil:5.1.0-214041c3cc643baaec40da12083dd84ef4096e7c-py3.6 as TOIL_APPLIANCE_SELF is not set.
[2021-01-12T08:07:30+0100] [MainThread] [I] [toil.common] Successfully deleted the job store: <toil.jobStores.aws.jobStore.AWSJobStore object at 0x7f609d866190>
Traceback (most recent call last):
  File "tutorial_helloworld.py", line 13, in <module>
    output = toil.start(Job.wrapFn(helloWorld, "You did it!"))
  File "/home/milos/ttt/toil/lib/python3.8/site-packages/toil/common.py", line 827, in start
    self._setupAutoDeployment(rootJob.getUserScript())
  File "/home/milos/ttt/toil/lib/python3.8/site-packages/toil/common.py", line 1016, in _setupAutoDeployment
    userScriptResource = userScript.saveAsResourceTo(self._jobStore)
  File "/home/milos/ttt/toil/lib/python3.8/site-packages/toil/resource.py", line 466, in saveAsResourceTo
    return self._getResourceClass().create(jobStore, self._resourcePath)
  File "/home/milos/ttt/toil/lib/python3.8/site-packages/toil/resource.py", line 79, in create
    with cls._load(leaderPath) as src:
  File "/home/milos/ttt/toil/lib/python3.8/site-packages/toil/resource.py", line 325, in _load
    assert os.path.basename(path) == 'site-packages'
AssertionError
```
It does not even get to launching pods. What am I doing wrong? Thx in advance!

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-778)
┆Issue Number: TOIL-778

**Comment by adamnovak** [comment]
I'm not able to replicate this issue with something like:

```
pip3 uninstall toil
pip3 install --user toil[aws,kubernetes]==5.1.0
mkdir toiltest
cd toiltest
wget https://raw.githubusercontent.com/DataBiosphere/toil/98dbf33147ed029800dd43a73ee5c64e83feda7b/src/toil/test/docs/scripts/tutorial_helloworld.py
virtualenv --python python3 --system-site-packages venv
. venv/bin/activate

export TOIL_KUBERNETES_OWNER=adamnovak
export TOIL_AWS_SECRET_NAME=shared-s3-credentials
export TOIL_KUBERNETES_HOST_PATH=/data/scratch
python3 tutorial_helloworld.py aws:us-west-2:toil-kubernetes-example-adamnovak-3 --batchSystem kubernetes --realTimeLogging --logInfo --disableCaching false --clean always
```

This is my log:

```
[2021-01-12T10:52:02-0800] [MainThread] [I] [botocore.credentials] Found credentials in shared credentials file: ~/.aws/credentials
[2021-01-12T10:52:03-0800] [MainThread] [I] [botocore.credentials] Found credentials in shared credentials file: ~/.aws/credentials
Enter MFA code for arn:aws:iam::652235167018:mfa/anovak@soe.ucsc.edu: 
[2021-01-12T10:52:23-0800] [MainThread] [I] [toil] Using default docker registry of quay.io/ucsc_cgl as TOIL_DOCKER_REGISTRY is not set.
[2021-01-12T10:52:23-0800] [MainThread] [I] [toil] Using default docker name of toil as TOIL_DOCKER_NAME is not set.
[2021-01-12T10:52:23-0800] [MainThread] [I] [toil] Using default docker appliance of quay.io/ucsc_cgl/toil:5.1.0-214041c3cc643baaec40da12083dd84ef4096e7c-py3.6 as TOIL_APPLIANCE_SELF is not set.
[2021-01-12T10:52:27-0800] [MainThread] [I] [toil.batchSystems.kubernetes] Setting user script for deployment: DirectoryResource(name='toiltest', pathHash='3e462b8d11e0f9d853bbe25027c89d94', url='https://toil-kubernetes-example-adamnovak-3--files.s3-us-west-2.amazonaws.com:443/74a5fa53-3f60-5cbc-82fd-0ff2801ae4d9?versionId=cjHKsPtlIlKDkuU6FeEBw5a9xZE8XH_5', contentHash='90e3598ee34bfd1df4903e376bbce4c6')
[2021-01-12T10:52:28-0800] [MainThread] [I] [toil.job] Saving graph of 1 jobs, 1 new
[2021-01-12T10:52:28-0800] [MainThread] [I] [toil.job] Processing job 'FunctionWrappingJob' 56ada84c-854f-4257-87c5-58e41d226092
[2021-01-12T10:52:29-0800] [MainThread] [I] [toil] Running Toil version 5.1.0-214041c3cc643baaec40da12083dd84ef4096e7c on host courtyard.
[2021-01-12T10:52:29-0800] [MainThread] [I] [toil.realtimeLogger] Starting real-time logging.
[2021-01-12T10:52:29-0800] [MainThread] [I] [toil.leader] Issued job 'FunctionWrappingJob' 56ada84c-854f-4257-87c5-58e41d226092 with job batch system ID: 0 and cores: 1, disk: 1.0 G, and memory: 1.0 G
[2021-01-12T10:52:32-0800] [MainThread] [I] [toil.leader] 1 jobs are running, 0 jobs are issued and waiting to run
[2021-01-12T10:52:37-0800] [MainThread] [I] [toil.leader] Job ended: 'FunctionWrappingJob' 56ada84c-854f-4257-87c5-58e41d226092
[2021-01-12T10:52:39-0800] [MainThread] [I] [toil.leader] Finished toil run successfully.

Workflow Progress 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 (0 failures) [00:08<00:00, 0.13 jobs/s]
[2021-01-12T10:52:40-0800] [MainThread] [I] [toil.realtimeLogger] Stopping real-time logging server.
[2021-01-12T10:52:40-0800] [MainThread] [I] [toil.realtimeLogger] Joining real-time logging server thread.
[2021-01-12T10:52:43-0800] [MainThread] [I] [toil.common] Successfully deleted the job store: <toil.jobStores.aws.jobStore.AWSJobStore object at 0x7fea2f08ce10>
Hello, world!, here's a message: You did it!
```

I also have no trouble using Toil installed from a virtualenv, with or without `--system-site-packages`:

```
deactivate
pip3 uninstall toil
rm -Rf venv
virtualenv --python python3 ../toil-venv --system-site-packages
. ../toil-venv/bin/activate
pip3 install toil[aws,kubernetes]==5.1.0
python3 tutorial_helloworld.py aws:us-west-2:toil-kubernetes-example-adamnovak-3 --batchSystem kubernetes --realTimeLogging --logInfo --disableCaching false --clean always
```

And it even works if I install a different Toil at the system level and install over it in the virtualenv:

```
deactivate
rm -Rf ../toil-venv
pip3 install --user toil==5.0.0
virtualenv --python python3 --system-site-packages ../toil-venv
. ../toil-venv/bin/activate
pip3 install toil[aws,kubernetes]==5.1.0
python3 tutorial_helloworld.py aws:us-west-2:toil-kubernetes-example-adamnovak-3 --batchSystem kubernetes --realTimeLogging --logInfo --disableCaching false --clean always
```

Where is your `toil_kube` directory relative to your `toil` virtualenv?

**Comment by adamnovak** [comment]
Can you maybe try editing that line `assert os.path.basename(path) == 'site-packages'` in `/home/milos/ttt/toil/lib/python3.8/site-packages/toil/resource.py`? If you make it `assert os.path.basename(path) == 'site-packages', "Bad path: " + path`, we would be able to see what path it is actually expecting to end in `site-packages`.

**Comment by imilos** [comment]
Many thanks! The wrong path is actually a current working directory:
`Bad path: /home/milos/ttt/toil_kube`
I will try to reinstall venv and everything else following your steps and let you know what happens.

**Comment by imilos** [comment]
I can confirm that the error does not appear when installed as given in the documentation. My error was that I installed Toil using `pip` within the venv instead of installing it before setting up venv. Many thanks @adamnovak ! However, now I'm getting:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/toil/batchSystems/kubernetes.py", line 1110, in executor
    job = pickle.loads(base64.b64decode(sys.argv[1].encode('utf-8')))
ValueError: unsupported pickle protocol: 5

```
but perhaps I should open another issue or try to find this error in the already resolved issues.

**Comment by adamnovak** [comment]
Yes, Toil really wants the same Python to be used on the leader and in the workers. We publish `-py3.6`, `-py3.7`, and `-py3.8` versions of all the containers to make that happen. It's *supposed* to pick the right one based on the currently running version of Python. If you don't like the one it picked, you can set e.g. `TOIL_APPLIANCE_SELF=quay.io/ucsc_cgl/toil:5.1.0-214041c3cc643baaec40da12083dd84ef4096e7c-py3.8` in the environment to make it use the 3.8 container for that particular Toil version.

**Comment by imilos** [comment]
Dear @adamnovak , it works perfectly. Many thanks for your help and clarification. I'm closing the issue.
