### ISSUE TITLE
Singularity cache dir, like CWL_SINGULARITY_CACHE in CWL ref runner?

### ISSUE THREAD

**Issue by tamasgal** [DataBiosphere/toil#3427]
I am currently evaluating `toil` as a candidate to build our mass processing workflows upon; it really looks promising as we have to deal with different batch systems. We are however limited to Singularity and cannot build the images on our HPC systems.

I tried some small workflows with the `cwl-runner` from `cwltools` (reference runner) and it works nicely by setting the `CWL_SINGULARITY_CACHE` variable to point to a directory where we store the singularity images with the required naming scheme, meaning that in the tools we use the Docker registry path, which is then converted to the Singularity image name. E.g. `docker.km3net.de/km3pipe:v9.0.1` -> `docker.km3net.de_km3pipe:v9.0.1.sif`.

The `toil-cwl-runner` has also a `--singularity` option, but it ignores that environment variable and tries to build the Singularity image from the Docker image URL, I guess. I am getting the error below with toil version `5.1.0`.

Is there a way to tell toil to use a directory and prevent the build of Singularity images? I guess this is a common thing since we use many computing centres and none of them allow the building of images, let alone running Docker... (and no, `udocker` is not working at all 😉)

```
2021-01-21T22:50:03+0100] [MainThread] [I] [toil.leader] Finished toil run successfully.

Workflow Progress 100%|███████████████████████████████████████████████████████████████████████| 1/1 (0 failures) [00:35<00:00, 0.03 jobs/s]
Traceback (most recent call last):
  File "/sps/km3net/users/tgal/dev/pipelines/venv/bin/toil-cwl-runner", line 10, in <module>
    sys.exit(main())
  File "/sps/km3net/users/tgal/dev/pipelines/venv/lib/python3.7/site-packages/toil/cwl/cwltoil.py", line 2246, in main
    outobj = toil.start(wf1)
  File "/sps/km3net/users/tgal/dev/pipelines/venv/lib/python3.7/site-packages/toil/common.py", line 849, in start
    self._shutdownBatchSystem()
  File "/sps/km3net/users/tgal/dev/pipelines/venv/lib/python3.7/site-packages/toil/common.py", line 1150, in _shutdownBatchSystem
    self._batchSystem.shutdown()
  File "/sps/km3net/users/tgal/dev/pipelines/venv/lib/python3.7/site-packages/toil/batchSystems/singleMachine.py", line 565, in shutdown
    BatchSystemSupport.workerCleanup(self.workerCleanupInfo)
  File "/sps/km3net/users/tgal/dev/pipelines/venv/lib/python3.7/site-packages/toil/batchSystems/abstractBatchSystem.py", line 394, in workerCleanup
    AbstractFileStore.shutdownFileStore(workflowDir, info.workflowID)
  File "/sps/km3net/users/tgal/dev/pipelines/venv/lib/python3.7/site-packages/toil/fileStores/abstractFileStore.py", line 132, in shutdownFileStore
    CachingFileStore.shutdown(cacheDir)
  File "/sps/km3net/users/tgal/dev/pipelines/venv/lib/python3.7/site-packages/toil/fileStores/cachingFileStore.py", line 1849, in shutdown
    robust_rmtree(dir_)
  File "/sps/km3net/users/tgal/dev/pipelines/venv/lib/python3.7/site-packages/toil/lib/misc.py", line 55, in robust_rmtree
    shutil.rmtree(path)
  File "/pbs/throng/km3net/software/python/3.7.5/lib/python3.7/shutil.py", line 494, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/pbs/throng/km3net/software/python/3.7.5/lib/python3.7/shutil.py", line 452, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/pbs/throng/km3net/software/python/3.7.5/lib/python3.7/shutil.py", line 450, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
OSError: [Errno 16] Device or resource busy: '.nfs000000045fc424a500033439'
```

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-782)
┆Issue Number: TOIL-782

**Comment by mr-c** [comment]
Hello @tamasgal 

You should be able to use https://github.com/common-workflow-language/cwl-utils/#pull-the-all-referenced-software-container-images to pre-download the needed containers and pointing `CWL_SINGULARITY_CACHE` at the chosen directory.

If that doesn't work please let us know!
