### ISSUE TITLE
Error writing Stats

### ISSUE THREAD

**Issue by caballero** [DataBiosphere/toil#3453]
hello Toil developers (and thanks for your efforts).

I am running a workflow using Toil 5.2.0 + LSF, and got this error claiming permission issues in the stat dir (I'm running with --stats option), that dir is generated by toil and checking permissions it looks fine (drwxr-xr-x stats)

This is the log:

```
launching TOIL/CWL job with Singularity/Docker as PRJEB41764_ERR4921265
[2021-02-09T22:17:13+0000] [MainThread] [I] [cwltool] Resolved ~/jcaballero/mgnify-lr/cwl/workflows/long_read_assembly.cwl' to 'file://~/jcaballero/mgnify-lr/cwl/workflows/long_read_assembly.cwl'
[2021-02-09T22:17:50+0000] [MainThread] [I] [toil.job] Saving graph of 2 jobs, 2 new
[2021-02-09T22:17:50+0000] [MainThread] [I] [toil.job] Processing job 'ResolveIndirect' kind-ResolveIndirect/instance-qrkb8j17
[2021-02-09T22:17:50+0000] [MainThread] [I] [toil.job] Processing job 'CWLWorkflow' kind-CWLWorkflow/instance-jpjbo3wi
[2021-02-09T22:17:50+0000] [MainThread] [I] [toil] Running Toil version 5.2.0-047d0c4f2949c576c80e452a0807c5be6355c63d on host noah-login-01.ebi.ac.uk.
Cannot get parameter information from lsf.conf or ego.conf for LIM from host<noah-login-01>
Cannot get parameter information from lsf.conf or ego.conf for LIM from host<noah-login-01>
[2021-02-09T22:17:58+0000] [MainThread] [I] [toil.worker] Redirecting logging to /tmp/node-1b235e0a-3255-44ce-97a9-b484f1dc3798-26f9d8f8-6edf-4d09-8b88-fed35275a9b6/tmp7xk3mwlg/worker_log.txt
[2021-02-09T22:17:59+0000] [MainThread] [I] [toil.leader] 1 jobs are running, 0 jobs are issued and waiting to run
[2021-02-09T22:18:01+0000] [MainThread] [W] [toil.leader] A result seems to already have been processed for job 0
[2021-02-09T23:17:59+0000] [MainThread] [I] [toil.leader] 0 jobs are running, 1 jobs are issued and waiting to run
[2021-02-09T23:46:41+0000] [MainThread] [I] [toil.worker] Redirecting logging to /tmp/node-1b235e0a-3255-44ce-97a9-b484f1dc3798-26f9d8f8-6edf-4d09-8b88-fed35275a9b6/tmprhz88zsa/worker_log.txt
[2021-02-09T23:46:43+0000] [MainThread] [I] [toil.leader] Issued job 'CWLJob' fastp kind-CWLJob/instance-a03t2b2q with job batch system ID: 3 and cores: 8, disk: 2.0 G, and memory: 7.0 G
[2021-02-09T23:46:43+0000] [MainThread] [I] [toil.leader] Issued job 'CWLJob' calc_stats.pl kind-CWLJob/instance-hqfz37qi with job batch system ID: 4 and cores: 1, disk: 2.0 G, and memory: 1.0 G
Cannot get parameter information from lsf.conf or ego.conf for LIM from host<noah-login-01>
Cannot get parameter information from lsf.conf or ego.conf for LIM from host<noah-login-01>
Cannot get parameter information from lsf.conf or ego.conf for LIM from host<noah-login-01>
Cannot get parameter information from lsf.conf or ego.conf for LIM from host<noah-login-01>
[2021-02-09T23:50:21+0000] [MainThread] [I] [toil.leader] Job ended: 'CWLJob' calc_stats.pl kind-CWLJob/instance-hqfz37qi
Exception in thread Thread-6:
Traceback (most recent call last):
  File "~/jcaballero/miniconda3/envs/mgnify-lr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
  File "~/jcaballero/miniconda3/envs/mgnify-lr/lib/python3.8/threading.py", line 870, in run
  File "~/jcaballero/miniconda3/envs/mgnify-lr/lib/python3.8/site-packages/toil/statsAndLogging.py", line 170, in statsAndLoggingAggregator
  File "~/jcaballero/miniconda3/envs/mgnify-lr/lib/python3.8/site-packages/toil/jobStores/fileJobStore.py", line 599, in readStatsAndLogging
PermissionError: [Errno 13] Permission denied: '~/jcaballero/runs/work-dir/job-store-wf/PRJEB41764_ERR4921265/stats'
Traceback (most recent call last):
  File "~/jcaballero/miniconda3/envs/mgnify-lr/lib/python3.8/site-packages/toil/common.py", line 817, in start
  File "~/jcaballero/miniconda3/envs/mgnify-lr/lib/python3.8/site-packages/toil/common.py", line 1105, in _runMainLoop
  File "~/jcaballero/miniconda3/envs/mgnify-lr/lib/python3.8/site-packages/toil/leader.py", line 228, in run
  File "~/jcaballero/miniconda3/envs/mgnify-lr/lib/python3.8/site-packages/toil/leader.py", line 629, in innerLoop
  File "~/jcaballero/miniconda3/envs/mgnify-lr/lib/python3.8/site-packages/toil/statsAndLogging.py", line 184, in check
RuntimeError: Stats and logging thread has quit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/jcaballero/miniconda3/envs/mgnify-lr/bin/toil-cwl-runner", line 8, in <module>
  File "~/jcaballero/miniconda3/envs/mgnify-lr/lib/python3.8/site-packages/toil/cwl/cwltoil.py", line 2281, in main
  File "~/jcaballero/miniconda3/envs/mgnify-lr/lib/python3.8/site-packages/toil/common.py", line 819, in start
  File "~/jcaballero/miniconda3/envs/mgnify-lr/lib/python3.8/site-packages/toil/common.py", line 1120, in _shutdownBatchSystem
  File "~/jcaballero/miniconda3/envs/mgnify-lr/lib/python3.8/site-packages/toil/batchSystems/abstractGridEngineBatchSystem.py", line 398, in shutdown
  File "~/jcaballero/miniconda3/envs/mgnify-lr/lib/python3.8/site-packages/toil/batchSystems/abstractBatchSystem.py", line 456, in shutdownLocal
  File "~/jcaballero/miniconda3/envs/mgnify-lr/lib/python3.8/site-packages/toil/batchSystems/singleMachine.py", line 565, in shutdown
  File "~/jcaballero/miniconda3/envs/mgnify-lr/lib/python3.8/site-packages/toil/batchSystems/abstractBatchSystem.py", line 394, in workerCleanup
  File "~/jcaballero/miniconda3/envs/mgnify-lr/lib/python3.8/site-packages/toil/fileStores/abstractFileStore.py", line 124, in shutdownFileStore
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 915, in get_code
  File "<frozen importlib._bootstrap_external>", line 972, in get_data
PermissionError: [Errno 13] Permission denied: '~/jcaballero/miniconda3/envs/mgnify-lr/lib/python3.8/site-packages/toil/fileStores/cachingFileStore.py'
[2021-02-10T00:07:23+0000] [Thread-4  ] [E] [toil.batchSystems.lsf] bjobs detected job failed with:
exit code: 1
exit reason: TERM_MEMLIMIT: job killed after reaching LSF memory usage limit
for job: 3349031
```

**Comment by mr-c** [comment]
`PermissionError: [Errno 13] Permission denied: '~/jcaballero/miniconda3/envs/mgnify-lr/lib/python3.8/site-packages/toil/fileStores/cachingFileStore.py'` is weird

**Comment by caballero** [comment]
I ended installing a fresh Toil with conda, I didn't see again this error.
