### ISSUE TITLE
MaxCoresSingleMachineBatchSystemTest.test looks flaky.

### ISSUE THREAD

**Issue by DailyDreaming** [DataBiosphere/toil#3478]
```
__________________ MaxCoresSingleMachineBatchSystemTest.test ___________________
Traceback (most recent call last):
  File "/builds/databiosphere/toil/src/toil/test/batchSystems/batchSystemTest.py", line 556, in test
    self.assertEqual(maxConcurrentTasks, expectedMaxConcurrentTasks)
  File "/usr/lib/python3.7/unittest/case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python3.7/unittest/case.py", line 845, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 17 != 20
```

https://ucsc-ci.com/databiosphere/toil/-/jobs/77178

```
__________________ MaxCoresSingleMachineBatchSystemTest.test ___________________
Traceback (most recent call last):
  File "/builds/databiosphere/toil/src/toil/test/batchSystems/batchSystemTest.py", line 556, in test
    self.assertEqual(maxConcurrentTasks, expectedMaxConcurrentTasks)
  File "/usr/lib/python3.7/unittest/case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python3.7/unittest/case.py", line 845, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 19 != 20
```

https://ucsc-ci.com/databiosphere/toil/-/jobs/77134

Maybe since the kubernetes conformance tests (#3323)?

**Comment by adamnovak** [comment]
The logs don't have timestamps when we let pytest configure logging, so I can't tell if we're getting all 20 child processes launched in time for them to overlap in their 1 second sleeps. Or maybe all the file locking and IO is delaying them so they don't actually overlap in that 1 second?

We could maybe make the sleep longer at https://github.com/DataBiosphere/toil/blob/e9532a1f2bfd62c479262bcecaaf6256091adcf2/src/toil/test/batchSystems/batchSystemTest.py#L495 ? I can't think of why this would be related to the CWL Kubernetes stuff, other than that that might have increased the overall Kubernetes load, and also that it upgraded some base Ubuntu versions.
