### ISSUE TITLE
Random job graph test failed with "Attempted to schedule successors of the same job twice!"

### ISSUE THREAD

**Issue by adamnovak** [DataBiosphere/toil#3484]
In https://ucsc-ci.com/databiosphere/toil/-/jobs/77390/raw we failed a test in `master` because our random DAG managed to trick the scheduler.

Here's the error report:

```
_______________________ JobTest.testEvaluatingRandomDAG ________________________
Traceback (most recent call last):
  File "/builds/databiosphere/toil/src/toil/test/src/jobTest.py", line 412, in testEvaluatingRandomDAG
    toil.start(rootJob)
  File "/builds/databiosphere/toil/src/toil/common.py", line 823, in start
    return self._runMainLoop(rootJobDescription)
  File "/builds/databiosphere/toil/src/toil/common.py", line 1116, in _runMainLoop
    jobCache=self._jobCache).run()
  File "/builds/databiosphere/toil/src/toil/leader.py", line 228, in run
    self.innerLoop()
  File "/builds/databiosphere/toil/src/toil/leader.py", line 605, in innerLoop
    self._processReadyJobs()
  File "/builds/databiosphere/toil/src/toil/leader.py", line 514, in _processReadyJobs
    self._processReadyJob(updatedJob, resultStatus)
  File "/builds/databiosphere/toil/src/toil/leader.py", line 482, in _processReadyJob
    self._runJobSuccessors(readyJob)
  File "/builds/databiosphere/toil/src/toil/leader.py", line 383, in _runJobSuccessors
    assert predecessor.jobStoreID not in self.toilState.successorCounts, 'Attempted to schedule successors of the same job twice!'
AssertionError: Attempted to schedule successors of the same job twice!
```

And here's the log right before the exception happens:

```
DEBUG    toil.leader:leader.py:534 Job: kind-FunctionWrappingJob/instance-cjl2ee2q has established its services.
DEBUG    toil.leader:leader.py:534 Job: kind-FunctionWrappingJob/instance-mgxgr642 has established its services.
DEBUG    toil.batchSystems.singleMachine:singleMachine.py:484 Child 17077 for job 13 succeeded
DEBUG    toil.batchSystems.singleMachine:singleMachine.py:577 Ran jobID: 13 with exit value: 0
DEBUG    toil.leader:leader.py:568 Job ended: 'ServiceHostJob' kind-ServiceHostJob/instance-h25465ck
DEBUG    toil.leader:leader.py:1192 Job 'FunctionWrappingJob' kind-FunctionWrappingJob/instance-cjl2ee2q is no longer waiting on services
DEBUG    toil.leader:leader.py:508 Built the jobs list, currently have 2 jobs to update and 1 jobs issued
DEBUG    toil.leader:leader.py:434 Updating status of job 'FunctionWrappingJob' kind-FunctionWrappingJob/instance-cjl2ee2q with result status: 0
DEBUG    toil.leader:leader.py:380 Job: kind-FunctionWrappingJob/instance-cjl2ee2q has 1 successors to schedule
DEBUG    toil.leader:leader.py:362 Added job 'FunctionWrappingJob' kind-FunctionWrappingJob/instance-1j2fncd3 as coming after job 'FunctionWrappingJob' kind-FunctionWrappingJob/instance-cjl2ee2q
DEBUG    toil.leader:leader.py:322 Successor job: 'FunctionWrappingJob' kind-FunctionWrappingJob/instance-1j2fncd3 of job: 'FunctionWrappingJob' kind-FunctionWrappingJob/instance-cjl2ee2q has multiple predecessors
DEBUG    toil.leader:leader.py:434 Updating status of job 'FunctionWrappingJob' kind-FunctionWrappingJob/instance-mgxgr642 with result status: 0
DEBUG    toil.leader:leader.py:380 Job: kind-FunctionWrappingJob/instance-mgxgr642 has 1 successors to schedule
DEBUG    toil.leader:leader.py:362 Added job 'FunctionWrappingJob' kind-FunctionWrappingJob/instance-1j2fncd3 as coming after job 'FunctionWrappingJob' kind-FunctionWrappingJob/instance-mgxgr642
DEBUG    toil.leader:leader.py:322 Successor job: 'FunctionWrappingJob' kind-FunctionWrappingJob/instance-1j2fncd3 of job: 'FunctionWrappingJob' kind-FunctionWrappingJob/instance-mgxgr642 has multiple predecessors
DEBUG    toil.batchSystems.singleMachine:singleMachine.py:500 Issuing the command: _toil_worker FunctionWrappingJob file:/tmp/toil-test-toil.test.src.jobTest.JobTest-testEvaluatingRandomDAG-jobstore-xtdbveu4.4 kind-FunctionWrappingJob/instance-1j2fncd3 with memory: 2147483648, cores: 1.0, disk: 2147483648
INFO     toil.leader:leader.py:743 Issued job 'FunctionWrappingJob' kind-FunctionWrappingJob/instance-1j2fncd3 with job batch system ID: 15 and cores: 1, disk: 2.0 G, and memory: 2.0 G
DEBUG    toil.batchSystems.singleMachine:singleMachine.py:424 Launched job 15 as child 17089
DEBUG    toil.batchSystems.singleMachine:singleMachine.py:484 Child 17079 for job 14 succeeded
DEBUG    toil.batchSystems.singleMachine:singleMachine.py:577 Ran jobID: 14 with exit value: 0
DEBUG    toil.leader:leader.py:568 Job ended: 'ServiceHostJob' kind-ServiceHostJob/instance-_1z44vfe
DEBUG    toil.leader:leader.py:1192 Job 'FunctionWrappingJob' kind-FunctionWrappingJob/instance-mgxgr642 is no longer waiting on services
DEBUG    toil.leader:leader.py:508 Built the jobs list, currently have 1 jobs to update and 1 jobs issued
DEBUG    toil.leader:leader.py:434 Updating status of job 'FunctionWrappingJob' kind-FunctionWrappingJob/instance-mgxgr642 with result status: 0
DEBUG    toil.leader:leader.py:380 Job: kind-FunctionWrappingJob/instance-mgxgr642 has 1 successors to schedule
```

We need to figure out why the `mgxgr642` job manages to get its services established, update with a result of 0, schedule successors, become "no longer waiting on services", update with a result of 0 again, and schedule the same successors again. Unfortunately the random job graph tests don't seed or dump their job graphs so I don't think we can just rerun the broken graph.

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-818)
┆Issue Number: TOIL-818

**Comment by adamnovak** [comment]
It might be that [our test service job `check()` method returns `None`](https://github.com/DataBiosphere/toil/blob/e9532a1f2bfd62c479262bcecaaf6256091adcf2/src/toil/test/src/jobTest.py#L708-L709), which [isn't an acceptable check method implementation](https://github.com/DataBiosphere/toil/blob/e9532a1f2bfd62c479262bcecaaf6256091adcf2/src/toil/job.py#L1795-L1803). If it's being interpreted as `False`, then we'll take it as the service immediately cleanly stopping after startup.  So the service might be starting, clearing the job's successors, stopping immediately, and then because it stopped somehow clearing the job's successors again when it shouldn't be.

I think we are seeing the services stop and [thinking that that means that we can then proceed with follow-ons, because we think we were shutting down the services because the children using them finished](https://github.com/DataBiosphere/toil/blob/e9532a1f2bfd62c479262bcecaaf6256091adcf2/src/toil/leader.py#L1188-L1197), when actually we just issued the job whose children need the services and they are stopping cleanly before the children are done.

**Comment by adamnovak** [comment]
I observed this again in https://ucsc-ci.com/databiosphere/toil/-/jobs/1488/raw which ran on a merge to master, and I think this really is the problem. We kick the job with a `JobUpdatedMessage` when the services say they are established, and then again when we notice the services have stopped, because of the None from `check()`. If these land in different ticks and aren't deduplicated away, we will kick the job twice.

I'm not quite sure what the solution is; jobs might want to cleanly stop their services from in the user code (e.g. tell a DB service to close out when user code is done with it), and `check()` probably shouldn't say the service is running when it is actually stopped. But we're relying on the services not to come back as stopped before the child jobs are done for our scheduling state machine.
