### ISSUE TITLE
Toil Downloading Files Incorrectly

### ISSUE THREAD

**Issue by jpuerto-psc** [DataBiosphere/toil#3667]
Good Afternoon Toil Team,

Hope you all had a restful weekend. Running across a strange error as part of a pipeline I am testing out:

	Traceback (most recent call last):
	  File "/usr/local/lib/python3.6/dist-packages/toil/cwl/cwltoil.py", line 620, in visit
	    deref = downloadHttpFile(path)
	  File "/usr/local/lib/python3.6/dist-packages/cwltool/utils.py", line 441, in downloadHttpFile
	    r = cache_session.get(httpurl, stream=True)
	  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 555, in get
	    return self.request('GET', url, **kwargs)
	  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 542, in request
	    resp = self.send(prep, **send_kwargs)
	  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 649, in send
	    adapter = self.get_adapter(url=request.url)
	  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 742, in get_adapter
	    raise InvalidSchema("No connection adapters were found for {!r}".format(url))
	requests.exceptions.InvalidSchema: No connection adapters were found for 'file:///opt/input/<FILE>'

	During handling of the above exception, another exception occurred:

	Traceback (most recent call last):
	  File "/usr/local/lib/python3.6/dist-packages/toil/worker.py", line 394, in workerScript
	    job._runner(jobGraph=None, jobStore=jobStore, fileStore=fileStore, defer=defer)
	  File "/usr/local/lib/python3.6/dist-packages/toil/job.py", line 2362, in _runner
	    returnValues = self._run(jobGraph=None, fileStore=fileStore)
	  File "/usr/local/lib/python3.6/dist-packages/toil/job.py", line 2283, in _run
	    return self.run(fileStore)
	  File "/usr/local/lib/python3.6/dist-packages/toil/cwl/cwltoil.py", line 1223, in run
	    logger=cwllogger,
	  File "/usr/local/lib/python3.6/dist-packages/cwltool/executors.py", line 150, in execute
	    self.run_jobs(process, job_order_object, logger, runtime_context)
	  File "/usr/local/lib/python3.6/dist-packages/cwltool/executors.py", line 234, in run_jobs
	    for job in jobiter:
	  File "/usr/local/lib/python3.6/dist-packages/cwltool/command_line_tool.py", line 881, in job
	    reffiles, builder.stagedir, runtimeContext, True
	  File "/usr/local/lib/python3.6/dist-packages/toil/cwl/cwltoil.py", line 662, in make_path_mapper
	    runtimeContext.toil_get_file,  # type: ignore
	  File "/usr/local/lib/python3.6/dist-packages/toil/cwl/cwltoil.py", line 557, in __init__
	    referenced_files, basedir, stagedir, separateDirs=separateDirs
	  File "/usr/local/lib/python3.6/dist-packages/cwltool/pathmapper.py", line 70, in __init__
	    self.setup(dedup(referenced_files), basedir)
	  File "/usr/local/lib/python3.6/dist-packages/cwltool/pathmapper.py", line 180, in setup
	    staged=True,
	  File "/usr/local/lib/python3.6/dist-packages/toil/cwl/cwltoil.py", line 596, in visit
	    staged=staged,
	  File "/usr/local/lib/python3.6/dist-packages/cwltool/pathmapper.py", line 86, in visitlisting
	    staged=staged,
	  File "/usr/local/lib/python3.6/dist-packages/toil/cwl/cwltoil.py", line 634, in visit
	    deref, tgt, "WritableFile" if copy else "File", staged
	  File "schema_salad/sourceline.py", line 256, in __exit__
	schema_salad.exceptions.ValidationException: No connection adapters were found for 'file:///opt/input/<FILE>'
	[2021-06-22T20:25:31+0000] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host <AWS_IP>

Any ideas here? It seems to be attempting a download for some reason? Perhaps it could be the filename that is being detected incorrectly as a URL?

For clarity, the filename is structured as follows `file_name.fastq.gz`.

Please let me know if there is anything else I can provide for further analysis.

Best,

Juan

**Comment by adamnovak** [comment]
Hello @jpuerto-psc, sorry to hear that Toil isn't working right for you.

Are you by chance trying to run a CWL workflow across multiple nodes? Is this coming from a worker, and `/opt/input/<FILE>` is only available on the node where you launched the workflow?

We're aware that some CWL features around files and directories don't work quite right between nodes that don't share a filesystem; we currently aren't able to pass the conformance tests in that situation. #3628/#3652 will hopefully improve conformance a lot, by making sure to actually track directory structure; we're waiting on CI testing and code review for those.

If you want to test it out and you're using Toil-managed clusters, you should be able to set `TOIL_APPLIANCE_SELF=quay.io/ucsc_cgl/toil:5.4.0a1-0339197e80ba1083e1d772cd18629efc4f670c03-py3.7` in your environment and get a cluster using it with `toil launch-cluster`.

**Comment by jpuerto-psc** [comment]
Good Morning @adamnovak,

Sorry for not being more clear - I am running this workflow on AWS. Since that is the case, these files should be available through the S3 job store, correct?

Best,

Juan

**Comment by jpuerto-psc** [comment]
@adamnovak - thank you for that advice! Switching over to that version seemed to resolve my issue! Any idea on when that will be the latest and greatest release?

Best,

Juan

**Comment by adamnovak** [comment]
I believe @DailyDreaming is cutting a release before we merge it, because it is a slight breaking change (you need to pass a new option to use some optional CWL features, when previously they were there automatically).

After that, we need to merge the PR, and then we'd need to cut a new release. We don't have a set schedule for them, but I suppose we could do one right after if it would help you.

If nothing goes wrong we might have the PR in by Monday, but if it needs any more substantial revision I will probably not be able to get to it until mid-July.

**Comment by jpuerto-psc** [comment]
@adamnovak This is not urgent - purely using this for metrics gathering at this point, so I am fine with setting the environment variable when necessary.

Thanks again!

**Comment by melainalegaspi** [comment]
This should be fixed in the current Toil release.
