### ISSUE TITLE
referred from cactus issue#529 toil failure: Unable to run job: List access specifier of attribute "l_hard" in "M.default" does not allow modification

### ISSUE THREAD

**Issue by matt-shenton** [DataBiosphere/toil#3689]
Hi there, I'm trying to run the example cactus pangenome pipeline.

[test_pipeline3.sh.txt](https://github.com/DataBiosphere/toil/files/6737351/test_pipeline3.sh.txt)
[test_pipeline3.sh.e2734544.txt](https://github.com/DataBiosphere/toil/files/6737352/test_pipeline3.sh.e2734544.txt)

Attached are the file I submitted with qsub to run the commands, and the error output from the job.

The cactus-graphmap fails and jobs cannot be submitted:

command is:

`cactus-graphmap ./jobstore evolverPrimates.txt primates.gfa primates.paf --outputFasta primates.gfa.fa --realTimeLogging --binariesMode local --batchSystem grid_engine`

relevant looking parts of the error messages:
`[2021-06-30T10:11:11+0900] [MainThread] [I] [toil.leader] Issued job 'JobFunctionWrappingJob' kind-JobFunctionWrappingJob/instance-cw6sa928 with job batch system ID: 0 and cores: 1, disk: 2.0 G, and memory: 2.0 G
Unable to run job: List access specifier of attribute "l_hard" in "M.default" does not allow modification but value of element "h_vmem" was changed from "4G" to "2097152K".
Exiting.
[2021-06-30T10:11:12+0900] [Thread-2  ] [E] [toil.batchSystems.abstractGridEngineBatchSystem] Will retry errored operation submitJob, code 1: Unable to run job: List access specifier of attribute "l_hard" in "M.default" does not allow modification but value of element "h_vmem" was changed from "4G" to "2097152K".
Exiting.

[2021-06-30T10:11:14+0900] [Thread-2  ] [E] [toil.batchSystems.abstractGridEngineBatchSystem] GridEngine like batch system failure
Traceback (most recent call last):
  File "/prm/scratch/home/mshenton/pipelines/cactus2.0/venv/lib/python3.6/site-packages/toil/batchSystems/abstractGridEngineBatchSystem.py", line 221, in run
    while self._runStep():
  File "/prm/scratch/home/mshenton/pipelines/cactus2.0/venv/lib/python3.6/site-packages/toil/batchSystems/abstractGridEngineBatchSystem.py", line 210, in _runStep
    activity |= self.createJobs(newJob)
  File "/prm/scratch/home/mshenton/pipelines/cactus2.0/venv/lib/python3.6/site-packages/toil/batchSystems/abstractGridEngineBatchSystem.py", line 114, in createJobs
    batchJobID = self.boss.with_retries(self.submitJob, subLine)
  File "/prm/scratch/home/mshenton/pipelines/cactus2.0/venv/lib/python3.6/site-packages/toil/batchSystems/abstractGridEngineBatchSystem.py", line 447, in with_retries
    raise err
  File "/prm/scratch/home/mshenton/pipelines/cactus2.0/venv/lib/python3.6/site-packages/toil/batchSystems/abstractGridEngineBatchSystem.py", line 438, in with_retries
    return operation(*args, **kwargs)
  File "/prm/scratch/home/mshenton/pipelines/cactus2.0/venv/lib/python3.6/site-packages/toil/batchSystems/gridengine.py", line 55, in submitJob
    stdout = call_command(subLine)
  File "/prm/scratch/home/mshenton/pipelines/cactus2.0/venv/lib/python3.6/site-packages/toil/lib/misc.py", line 57, in call_command
    raise CalledProcessErrorStderr(proc.returncode, cmd, output=stdout, stderr=stderr)
toil.lib.misc.CalledProcessErrorStderr: Command '['qsub', '-V', '-b', 'y', '-terse', '-j', 'y', '-cwd', '-N', 'toil_job_0', '-v', 'TOIL_RT_LOGGING_ADDRESS=192.168.1.20:33832,TOIL_RT_LOGGING_LEVEL=INFO', '-hard', '-l', 'vf=2097152K,h_vmem=2097152K', '-o', '/tmp/2734544.1.M.q/toil_workflow_6ca16f16-565a-481c-a27a-5981b9ac97c2_job_0_batch_gridengine_$JOB_ID_std_output.log', '-e', '/tmp/2734544.1.M.q/toil_workflow_6ca16f16-565a-481c-a27a-5981b9ac97c2_job_0_batch_gridengine_$JOB_ID_std_error.log', '_toil_worker JobFunctionWrappingJob file:/prm/scratch/home/mshenton/pipelines/cactus2.0/cactus-bin-v2.0.1/jobstore kind-JobFunctionWrappingJob/instance-cw6sa928 --context gANjdG9pbC5iYXRjaFN5c3RlbXMuYWJzdHJhY3RCYXRjaFN5c3RlbQpXb3JrZXJDbGVhbnVwQ29udGV4dApxACmBcQF9cQIoWBEAAAB3b3JrZXJDbGVhbnVwSW5mb3EDY3RvaWwuYmF0Y2hTeXN0ZW1zLmFic3RyYWN0QmF0Y2hTeXN0ZW0KV29ya2VyQ2xlYW51cEluZm8KcQROWCQAAAA2Y2ExNmYxNi01NjVhLTQ4MWMtYTI3YS01OTgxYjlhYzk3YzJxBVgGAAAAYWx3YXlzcQaHcQeBcQhYBQAAAGFyZW5hcQlOdWIu']' exit status 1: Unable to run job: List access specifier of attribute "l_hard" in "M.default" does not allow modification but value of element "h_vmem" was changed from "4G" to "2097152K".
Exiting.
`

I suppose this may be something specific to the setup of our grid engine system. Many thanks in advance for looking into it.

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-945)
┆Issue Number: TOIL-945

**Comment by adamnovak** [comment]
So your grid engine setup doesn't allow us to submit jobs that need "2097152K" of memory, but only jobs that need "4G" of memory?

It looks like we might have run into a system like this before; we have a `--manualMemArgs` you can pass to make Toil not tell Grid Engine how much memory it thinks the jobs should have, and then you would set `TOIL_GRIDENGINE_ARGS` to the qsub arguments you actually need to pass to set the right memory limit that you system accepts.

https://github.com/DataBiosphere/toil/blob/796b0a02caadb19dc9cadd80d90472d9360cd8c2/src/toil/batchSystems/options.py#L139-L147

Obviously if you do this, jobs won't always get the amount of memory they need, if any are larger than your limit.

**Comment by matt-shenton** [comment]
Hi, thanks for checking this out. I'm getting a different "permissions are not sufficient" error now, but I'm going to close this issue as "--manualMemArgs" seems to get past the initial hurdle. Thanks
