### ISSUE TITLE
ValueError: could not convert string to float: 

### ISSUE THREAD

**Issue by lningyawen** [DataBiosphere/toil#3715]
Hello,

I got a bug in the last few days when running cactus-prepare-toil. I think it's about the toil, so I am here. the bug is following:

```
Traceback (most recent call last):
  File "/pwd/dragon_cactus/soft/cactus-bin-v2.0.2/venv/bin/cactus-prepare-toil", line 8, in <module>
    sys.exit(main_toil())
  File "/pwd/dragon_cactus/soft/cactus-bin-v2.0.2/venv/lib/python3.6/site-packages/cactus/progressive/cactus_prepare.py", line 46, in main_toil
    return main(toil_mode=True)
  File "/pwd/dragon_cactus/soft/cactus-bin-v2.0.2/venv/lib/python3.6/site-packages/cactus/progressive/cactus_prepare.py", line 230, in main
    cactusPrepare(options, project)
  File "/pwd/dragon_cactus/soft/cactus-bin-v2.0.2/venv/lib/python3.6/site-packages/cactus/progressive/cactus_prepare.py", line 393, in cactusPrepare
    toil.restart()
  File "/pwd/dragon_cactus/soft/cactus-bin-v2.0.2/venv/lib/python3.6/site-packages/toil/common.py", line 874, in restart
    return self._runMainLoop(rootJobDescription)
  File "/pwd/dragon_cactus/soft/cactus-bin-v2.0.2/venv/lib/python3.6/site-packages/toil/common.py", line 1132, in _runMainLoop
    jobCache=self._jobCache).run()
  File "/pwd/dragon_cactus/soft/cactus-bin-v2.0.2/venv/lib/python3.6/site-packages/toil/leader.py", line 229, in run
    self.innerLoop()
  File "/pwd/dragon_cactus/soft/cactus-bin-v2.0.2/venv/lib/python3.6/site-packages/toil/leader.py", line 622, in innerLoop
    self.checkForDeadlocks()
  File "/pwd/dragon_cactus/soft/cactus-bin-v2.0.2/venv/lib/python3.6/site-packages/toil/leader.py", line 654, in checkForDeadlocks
    totalRunningJobs = len(self.batchSystem.getRunningBatchJobIDs())
  File "/pwd/dragon_cactus/soft/cactus-bin-v2.0.2/venv/lib/python3.6/site-packages/toil/batchSystems/abstractGridEngineBatchSystem.py", line 371, in getRunningBatchJobIDs
    batchIds = self.with_retries(self.worker.getRunningJobIDs)
  File "/pwd/dragon_cactus/soft/cactus-bin-v2.0.2/venv/lib/python3.6/site-packages/toil/batchSystems/abstractGridEngineBatchSystem.py", line 426, in with_retries
    return operation(*args, **kwargs)
  File "/pwd/dragon_cactus/soft/cactus-bin-v2.0.2/venv/lib/python3.6/site-packages/toil/batchSystems/torque.py", line 92, in getRunningJobIDs
    walltime = hms_to_seconds(walltime)
  File "/pwd/dragon_cactus/soft/cactus-bin-v2.0.2/venv/lib/python3.6/site-packages/toil/lib/conversions.py", line 100, in hms_to_seconds
    if(float(val) < 0): 
ValueError: could not convert string to float:
```

I think the bug is due to `/pwd/dragon_cactus/soft/cactus-bin-v2.0.2/venv/lib/python3.6/site-packages/toil/lib/conversions.py`, line 100. I google this bug, maybe the variable vals_to_convert(in line 96 of `conversions.py`) containing the data had some space (so not visible). This is just my guess, what do you think is causing this bug?

Yawen

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-962)
┆Issue Number: TOIL-962

**Comment by adamnovak** [comment]
I think maybe we just need to accept an empty time from the backing scheduler and treat it as 0.
