### ISSUE TITLE
CWL Directory is missing

### ISSUE THREAD

**Issue by ionox0** [DataBiosphere/toil#3745]
toil version: `5.4.0a1`
cwltool version: `3.0.20201203173111`

Could anyone shed some light on the following error:

```
	[2021-08-10T15:54:28-0400] [MainThread] [D] [toil.deferred] Running orphaned deferred functions
	Traceback (most recent call last):
	  File "/juno/work/ci/prod_ridgeback/venv/lib/python3.7/site-packages/toil/worker.py", line 393, in workerScript
	    job._runner(jobGraph=None, jobStore=jobStore, fileStore=fileStore, defer=defer)
	  File "/juno/work/ci/prod_ridgeback/venv/lib/python3.7/site-packages/toil/job.py", line 2362, in _runner
	    returnValues = self._run(jobGraph=None, fileStore=fileStore)
	  File "/juno/work/ci/prod_ridgeback/venv/lib/python3.7/site-packages/toil/job.py", line 2281, in _run
	    return self.run(fileStore)
	  File "/juno/work/ci/prod_ridgeback/venv/lib/python3.7/site-packages/toil/cwl/cwltoil.py", line 1237, in run
	    adjustDirObjs(output, prepareDirectoryForUpload)
	  File "/juno/work/ci/prod_ridgeback/venv/lib/python3.7/site-packages/cwltool/utils.py", line 359, in adjustDirObjs
	    visit_class(rec, ("Directory",), op)
	  File "/juno/work/ci/prod_ridgeback/venv/lib/python3.7/site-packages/cwltool/utils.py", line 295, in visit_class
	    visit_class(rec[d], cls, op)
	  File "/juno/work/ci/prod_ridgeback/venv/lib/python3.7/site-packages/cwltool/utils.py", line 295, in visit_class
	    visit_class(rec[d], cls, op)
	  File "/juno/work/ci/prod_ridgeback/venv/lib/python3.7/site-packages/cwltool/utils.py", line 298, in visit_class
	    visit_class(d, cls, op)
	  File "/juno/work/ci/prod_ridgeback/venv/lib/python3.7/site-packages/cwltool/utils.py", line 295, in visit_class
	    visit_class(rec[d], cls, op)
	  File "/juno/work/ci/prod_ridgeback/venv/lib/python3.7/site-packages/cwltool/utils.py", line 298, in visit_class
	    visit_class(d, cls, op)
	  File "/juno/work/ci/prod_ridgeback/venv/lib/python3.7/site-packages/cwltool/utils.py", line 293, in visit_class
	    op(rec)
	  File "/juno/work/ci/prod_ridgeback/venv/lib/python3.7/site-packages/toil/cwl/cwltoil.py", line 827, in prepareDirectoryForUpload
	    "Directory is missing: %s" % directory_metadata["location"]
	cwltool.errors.WorkflowException: Directory is missing: file:///juno/work/access/testing/users/johnsoni/access_qc/5500_HF_2/work/91dbc7f2b0945a6a807bee88b20e393f/6274/be75/tmpvlb_etyq/out/uncollapsed_bam_stats_pool_a_dir/uncollapsed_bam_stats_pool_a/C-261TDL-N001-d
```

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-989)
┆Issue Number: TOIL-989

**Comment by ionox0** [comment]
It's a bit hard for me to decipher which step is causing this error, but a likely culprit is this ExpressionTool, which puts a File[] input into a nested subdirectory structure. Perhaps this JS is the wrong way to do this:
```
#!/usr/bin/env cwl-runner
# originally from https://github.com/mskcc/pluto-cwl

cwlVersion: v1.0
class: ExpressionTool
id: put-in-dir

inputs:
  output_directory_name:
    type: string
    doc: >-
      Put all `files` in a directory called `output_directory_name`.
  output_subdirectory_name:
    type: string?
    doc: >-
      If specified, nest all `files` within a directory called `output_subdirectory_name`, which itself is within `output_directory_name`.
  files:
    type:
      type: array
      items:
        - File
        - type: array
          items:
            - File
        - Directory
        - 'null'

outputs:
  directory:
    type: Directory

# This tool returns a Directory object,
# which holds all output files from the list
# of supplied input files
expression: |
  ${
    var output_files = [];
    var input_files = inputs.files.filter(function(single_file) {
      return String(single_file).toUpperCase() != 'NONE';
    });

    for (var i = 0; i < input_files.length; i++) {
      // Handle list of list of files
      if (input_files[i] && input_files[i].length) {
        for (var ii = 0; ii < input_files[i].length; ii++) {
          output_files.push(input_files[i][ii]);
        }
      // Handle list of files
      } else if (input_files[i]) {
        output_files.push(input_files[i]);
      }
    }

    if (inputs.output_subdirectory_name) {
      return {
        'directory': {
          'class': 'Directory',
          'basename': inputs.output_directory_name,
          'listing': [
          {
            'class': 'Directory',
            'basename': inputs.output_subdirectory_name,
            'listing': output_files
          }
          ]
        }
      };
    } else {
      return {
        'directory': {
          'class': 'Directory',
          'basename': inputs.output_directory_name,
          'listing': output_files
        }
      };
    }

  }

requirements:
  - class: ResourceRequirement
    ramMin: 2000
    coresMin: 1
  - class: InlineJavascriptRequirement
```

**Comment by ionox0** [comment]
Interestingly, there is a different subdirectory at the location where this folder is missing:

```
/juno/work/access/testing/users/johnsoni/access_qc/5500_HF_2/work/91dbc7f2b0945a6a807bee88b20e393f/6274/be75/tmpvlb_etyq/out/uncollapsed_bam_stats_pool_a_dir/uncollapsed_bam_stats_pool_a/C-R0CLHU-N001-d
```

It seems that somehow the `output_subdirectory_name` parameter is getting mixed up. 

Or possibly the `directory_metadata["location"]` field is incorrectly being set

**Comment by ionox0** [comment]
I've found that this error was indeed caused by the above JS ExpressionTool

It seems that returning a Directory schema within a Directory's listing is producing this error

```
return {
        'directory': {
          'class': 'Directory',
          'basename': inputs.output_directory_name,
          'listing': [
          {
            'class': 'Directory',
            'basename': inputs.output_subdirectory_name,
            'listing': output_files
          }
          ]
        }
      };
```

**Comment by mr-c** [comment]
Thanks for narrowing this down @ionox0 . Does the latest `cwltool` also produce this error?

**Comment by ionox0** [comment]
Sorry for leaving this unresolved, but this ended up being an issue on our end. 

I have moved away from the details of what was causing this, but I believe it was one of two things:
1. Two directories having the same dynamically-generated name in the same scatter. 
2. Providing the wrong directory name for the glob

Thanks for the help, I don't believe this is actually a Toil bug
