### ISSUE TITLE
Arguments are not read consistently while using SLURM

### ISSUE THREAD

**Issue by varikmp** [DataBiosphere/toil#3780]
Hello,

I am using SLURM arguments for the Toil CWL Runner (5.4.0) and Toil WDL Runner ([Toil Batch System API](https://toil.readthedocs.io/en/latest/developingWorkflows/toilAPIBatchsystem.html)). It works normally for the CWL version, but in the WDL version, I had an error as below:
```
Traceback (most recent call last):
  File "/usr/local/bin/toil-wdl-runner", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/toil/wdl/toilwdl.py", line 94, in main
    aWDL = get_analyzer(wdl_file=wdl_file)
  File "/usr/local/lib/python3.8/dist-packages/toil/wdl/utils.py", line 46, in get_analyzer
    with open(wdl_file, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/root/slurm'
```
And here is my command:
```
toil-wdl-runner --batchSystem slurm /data/varikmp.wdl /data/varikmp.json
```
Then I realized that the order of arguments matter according to #2721 

I am wondering if this logical issue will be fixed in the next release.

Best regards,

**Comment by mr-c** [comment]
The PR that needs finishing is https://github.com/DataBiosphere/toil/pull/2809
