### ISSUE TITLE
Toil virtualenv detection/propagation doesn't work on Slurm

### ISSUE THREAD

**Issue by gmloose** [DataBiosphere/toil#3832]
I stumbled upon this issue, because I tried to run the CWL test suite, which basically means that there's no installed version of Toil, other than the one in the virtual environment I'm using to run the tests.

**How to reproduce**
```
git clone https://github.com/DataBiosphere/toil.git
cd toil
python3 -m venv venv
unset PYTHONPATH
. venv/bin/activate
pip install -U pip wheel
pip install -e .[cwl] cwltest
git clone https://github.com/common-workflow-language/cwl-v1.2/
cd cwl-v1.2
mkdir -p tmp/{working,logs}
toil-cwl-runner --batchSystem=slurm --disableCaching --workDir=$PWD/tmp/working --writeLogs=$PWD/tmp/logs tests/bwa-mem-tool.cwl tests/bwa-mem-job.json
```
**Notes:** 

1. The last command is just the first test of the conformance tests suite, executed manually, with slightly different command-liine options.
2. `$PWD` must be on a shared disk that is also visible on the compute node.

This command fails with the following error:
```
[2021-10-08T14:46:38+0200] [MainThread] [I] [cwltool] Resolved 'tests/bwa-mem-tool.cwl' to 'file:///home/rapthor-mloose/code/toil/cwl-v1.2/tests/bwa-mem-tool.cwl'
[2021-10-08T14:46:40+0200] [MainThread] [I] [toil.job] Saving graph of 1 jobs, 1 new
[2021-10-08T14:46:40+0200] [MainThread] [I] [toil.job] Processing job 'CWLJob' python kind-CWLJob/instance-74x417w1 v0
[2021-10-08T14:46:40+0200] [MainThread] [I] [toil] Running Toil version 5.6.0a1-eb2ae8365ae2ebdd50132570b20f7d480eb40cac on host ui-02.spider.surfsara.nl.
[2021-10-08T14:46:40+0200] [MainThread] [I] [toil.leader] Issued job 'CWLJob' python kind-CWLJob/instance-74x417w1 v1 with job batch system ID: 0 and cores: 2, disk: 2.0 Gi, and memory: 256.0 Mi
[2021-10-08T14:46:42+0200] [MainThread] [I] [toil.leader] 1 jobs are running, 0 jobs are issued and waiting to run
[2021-10-08T14:46:50+0200] [MainThread] [W] [toil.leader] Job failed with exit value 127: 'CWLJob' python kind-CWLJob/instance-74x417w1 v1
Exit reason: None
[2021-10-08T14:46:50+0200] [MainThread] [W] [toil.leader] No log file is present, despite job failing: 'CWLJob' python kind-CWLJob/instance-74x417w1 v1
[2021-10-08T14:46:50+0200] [MainThread] [W] [toil.leader] The batch system left an empty file /home/rapthor-mloose/code/toil/cwl-v1.2/tmp/working/toil_f1bc8bc0-0c7c-4730-896a-1a999672a46a.0.784924.out.log
[2021-10-08T14:46:50+0200] [MainThread] [W] [toil.leader] The batch system left a non-empty file /home/rapthor-mloose/code/toil/cwl-v1.2/tmp/working/toil_f1bc8bc0-0c7c-4730-896a-1a999672a46a.0.784924.err.log:
[2021-10-08T14:46:50+0200] [MainThread] [W] [toil.leader] Log from job "kind-CWLJob/instance-74x417w1" follows:
=========>
	/var/spool/slurmd/job784924/slurm_script: line 4: _toil_worker: command not found
<=========

Workflow Progress 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 (0 failures) [00:10<00:00, 0.10 jobs/s]
Traceback (most recent call last):
  File "/home/rapthor-mloose/code/toil/src/toil/cwl/cwltoil.py", line 3400, in main
    outobj = toil.start(wf1)
  File "/home/rapthor-mloose/code/toil/src/toil/common.py", line 844, in start
    return self._runMainLoop(rootJobDescription)
  File "/home/rapthor-mloose/code/toil/src/toil/common.py", line 1160, in _runMainLoop
    jobCache=self._jobCache).run()
  File "/home/rapthor-mloose/code/toil/src/toil/leader.py", line 248, in run
    self.innerLoop()
  File "/home/rapthor-mloose/code/toil/src/toil/leader.py", line 703, in innerLoop
    self._gatherUpdatedJobs(updatedJobTuple)
  File "/home/rapthor-mloose/code/toil/src/toil/leader.py", line 662, in _gatherUpdatedJobs
    self.processFinishedJob(bsID, exitStatus, wallTime=wallTime, exitReason=exitReason)
  File "/home/rapthor-mloose/code/toil/src/toil/leader.py", line 1137, in processFinishedJob
    StatsAndLogging.writeLogFiles(jobNames, batchSystemFileStream, self.config, failed=True)
  File "/home/rapthor-mloose/code/toil/src/toil/statsAndLogging.py", line 108, in writeLogFiles
    mainFileName = jobNames[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rapthor-mloose/code/toil/venv/bin/toil-cwl-runner", line 11, in <module>
    load_entry_point('toil', 'console_scripts', 'toil-cwl-runner')()
  File "/home/rapthor-mloose/code/toil/src/toil/cwl/cwltoil.py", line 3404, in main
    if getattr(err, "exit_code") == CWL_UNSUPPORTED_REQUIREMENT_EXIT_CODE:
AttributeError: 'IndexError' object has no attribute 'exit_code'

```
Now, I'm not sure why the first error `_toil_worker: command not found` occurs, but that error is triggered on the compute node. The Toil runner on the head node then gets confused, because it doesn't receive from the compute node what it expects.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-1049)
┆Issue Number: TOIL-1049

**Comment by mr-c** [comment]
> ```
> 
> ```
> 
> 
>     
>   
> 
> Now, I'm not sure why the first error `_toil_worker: command not found` occurs, but that error is triggered on the compute node.

Is your virtualenv on a path that works from the compute nodes (same path both places)?

**Comment by mr-c** [comment]
is `TOIL_SLURM_ARGS` set, and what is its value?

Is there an `sbatch` wrapper script installed that adds an `--export=` option?
https://slurm.schedmd.com/sbatch.html#OPT_export

**Comment by gmloose** [comment]
> is `TOIL_SLURM_ARGS` set, and what is its value?
> 
> Is there an `sbatch` wrapper script installed that adds an `--export=` option? https://slurm.schedmd.com/sbatch.html#OPT_export

`TOIL_SLURM_ARGS` is not set, and `sbatch` is not wrapped.
```
$ file `which sbatch`
/usr/bin/sbatch: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=d9aebdcf7df3909dcbac458272298eb186a27f58, with debug_info, not stripped
```

**Comment by mr-c** [comment]
Virtualenv work by setting environment variables like `PATH` and `PYTHONPATH`. `sbatch` and other batch schedulers automatically forward all set environment variables set at job submission time.

So as long as the same paths are present on all nodes and the environment variables are set as part of the slurm job submission, then there should be no need for `.bashrc` hacking.

**Comment by adamnovak** [comment]
We don't see this on our Slurm cluster.

I think that on our cluster, the environment variables for the venv might be automatically picked up by Slurm and shipped out with the Toil jobs. Maybe this is a Slurm configuration option? Maybe trying `-e PATH` on the Toil command line might help?

We're *supposed* to have Toil notice if it is running in a virtual environment and use absolute paths to refer to itself, though. I think that that must not be working in this case, and we might be able to reproduce *that*. We should probably fix that feature.

**Comment by adamnovak** [comment]
The workaround for not getting `--writeLogs` output is to use `--batchLogsDir` which controls where the leader puts Slurm-level logs, which will help debug a failed Toil startup within Slurm jobs.

We need to check to make sure the virtualenv detection/propagation logic in Toil is actually working, and make sure it's under test, because it *should* run the `_toil_worker` for the virtualenv that supplies the `toil` module. That's what we should use this issue to track.

**Comment by kinow** [comment]
I have an issue running toil-cwl-runner in CSC LUMI, with a venv, but not sure if exactly this bug. I'll describe it here, but I can move it to a separate issue if it's not the same problem.

I activate my venv-toil venv, used in the CWL Conformance tests. I can run my workflow like this:

```bash
$ (venv-toil) toil-cwl-runner --singularity workflow-base-command.cwl
```

This runs fine, with the venv activated, on a login node of CSC LUMI.

When I run this with `--batchSystem=slurm`, jobs are submitted to Slurm, but they fail with a strange error:

```
$ (venv-toil) toil-cwl-runner --singularity --retryCount 0 --bypass-file-store  --batchSystem=slurm --allocate_mem --defaultMemory=2G --slurmArgs="--partition=standard -A project --export=ALL" --logFile=cwltoil.log workflow-base-command.cwl
```

```
# excerpt from cwltoil.log

After scontrol, got statuses: {18965003: ('FAILED', 130)}
Remaining jobs to find out about: []
UpdatedJobsQueue Item: UpdatedBatchJobInfo(jobID=2, exitStatus=130, exitReason=<BatchJobExitReason.FAILED: 2>, wallTime=None, backing_id='18965003')
Job failed with exit value 130: 'CWLJob' mpich-sr-workflow.mpicc.mpich-mpicc kind-CWLJob/instance-cjpyc4vf v1
Exit reason: FAILED
Failed job in backing scheduler: 18965003
Notifying toil.bus.JobCompletedMessage with message: JobCompletedMessage(job_type='mpich-sr-workflow.mpicc.mpich-mpicc', job_id='kind-CWLJob/instance-cjpyc4vf', exit_code=130)
Job 'CWLJob' mpich-sr-workflow.mpicc.mpich-mpicc kind-CWLJob/instance-cjpyc4vf v1 continues to exist (i.e. has more to do)
Expected newer version in job 'CWLJob' mpich-sr-workflow.mpicc.mpich-mpicc kind-CWLJob/instance-cjpyc4vf v1 from PID 22163 but it is no newer than job 'CWLJob' mpich-sr-workflow.mpicc.mpich-mpicc kind-CWLJob/instance-cjpyc4vf v1 from PID 22163
Job 'CWLJob' mpich-sr-workflow.mpicc.mpich-mpicc kind-CWLJob/instance-cjpyc4vf v1 has no new version available immediately. The batch system may have killed (or never started) the Toil worker.
No log file is present, despite job failing: 'CWLJob' mpich-sr-workflow.mpicc.mpich-mpicc kind-CWLJob/instance-cjpyc4vf v1
The batch system left an empty file /scratch/project/<USER>/tmp/toil_b6811f1f-7961-4e24-9e89-034c0fc339fd.2.18965003.out.log
The batch system left a non-empty file /scratch/project/<USER>/tmp/toil_b6811f1f-7961-4e24-9e89-034c0fc339fd.2.18965003.err.log:
Log from job "kind-CWLJob/instance-cjpyc4vf" follows:
=========>
        Traceback (most recent call last):
          File "/project/project/<USER>/cwl/cwl-mpi/cwl-conformance-tests/runs/venv-toil/bin/_toil_worker", line 3, in <module>
            from toil.worker import main
          File "/project/project/<USER>/cwl/cwl-mpi/cwl-conformance-tests/runs/venv-toil/lib/python3.13/site-packages/toil/__init__.py", line 21, in <module>
            from docker.errors import ImageNotFound
          File "/project/project/<USER>/cwl/cwl-mpi/cwl-conformance-tests/runs/venv-toil/lib/python3.13/site-packages/docker/__init__.py", line 1, in <module>
            from .api import APIClient
          File "/project/project/<USER>/cwl/cwl-mpi/cwl-conformance-tests/runs/venv-toil/lib/python3.13/site-packages/docker/api/__init__.py", line 1, in <module>
            from .client import APIClient
          File "/project/project/<USER>/cwl/cwl-mpi/cwl-conformance-tests/runs/venv-toil/lib/python3.13/site-packages/docker/api/client.py", line 6, in <module>
            import requests
          File "/project/project/<USER>/cwl/cwl-mpi/cwl-conformance-tests/runs/venv-toil/lib/python3.13/site-packages/requests/__init__.py", line 163, in <module>
            from .api import delete, get, head, options, patch, post, put, request
          File "/project/project/<USER>/cwl/cwl-mpi/cwl-conformance-tests/runs/venv-toil/lib/python3.13/site-packages/requests/api.py", line 11, in <module>
            from . import sessions
          File "/project/project/<USER>/cwl/cwl-mpi/cwl-conformance-tests/runs/venv-toil/lib/python3.13/site-packages/requests/sessions.py", line 16, in <module>
            from .adapters import HTTPAdapter
          File "/project/project/<USER>/cwl/cwl-mpi/cwl-conformance-tests/runs/venv-toil/lib/python3.13/site-packages/requests/adapters.py", line 48, in <module>
            from .models import Response
          File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
          File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
          File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
          File "<frozen importlib._bootstrap_external>", line 1019, in exec_module
          File "<frozen importlib._bootstrap_external>", line 1152, in get_code
          File "<frozen importlib._bootstrap_external>", line 781, in _compile_bytecode
        KeyboardInterrupt
<=========
Due to failure we are reducing the remaining try count of job 'CWLJob' mpich-sr-workflow.mpicc.mpich-mpicc kind-CWLJob/instance-cjpyc4vf v1 with ID kind-CWLJob/instance-cjpyc4vf to 0
```

The CWL files are in an HPC project folder, which is on LustreFS, accessible by all 

I have the impression that it's either something with the environment not being properly loaded in the compute node, or Toil on the compute node getting confused with the `--singularity` flag and that's why it's using the code from .

I added a bunch of extra flags, 

```
$ toil-cwl-runner --singularity --logLevel=DEBUG  --retryCount 0 --bypass-file-store --outdir=/scratch/project/<USER>/tmp/ --log-dir=/scratch/project/<USER>/tmp/ --tmpdir-prefix=/scratch/project/<USER>/tmp/ --tmp-outdir-prefix=/scratch/project/<USER>/tmp/ --workDir=/scratch/project/<USER>/tmp/ --coordinationDir=/scratch/project/<USER>/tmp/ --batchSystem=slurm --allocate_mem --defaultMemory=2G --slurmArgs="--partition=standard -A project --export=ALL" --disable-streaming --writeLogs=/scratch/project/<USER>/tmp/ --clean=never --logFile=cwltoil.log --leave-tmpdir --log-dir=/scratch/project/<USER>/tmp/  workflow-base-command.cwl
```

In that `<USER>/tmp` folder, I can see extra log files, like `failed_CWLJob_mpich--sr--workflow.mpicc.mpich--mpicc_toil_b6811f1f--7961--4e24--9e89--034c0fc339fd.2.18965003.err_000.log`, with the same error from `cwltoil.log`. I couldn't find anything else to help troubleshooting this error.

---

EDIT: wrapping the execution in a Slurm call works,

```bash
sbatch   --partition=standard   -A project  --time=00:07:00   --job-name=toil_bruno   --ntasks=1   --cpus-per-task=4   --wrap="/project/project/<USER>/cwl/cwl-mpi/cwl-conformance-tests/runs/venv-toil/bin/toil-cwl-runner --singularity ./workflow-base-command.cwl"
```

Launches a slurm job and runs the workflow with two CWL tools correctly, producing the expected output.
