### ISSUE TITLE
Google job store credentials on CI don't work

### ISSUE THREAD

**Issue by adamnovak** [DataBiosphere/toil#3892]
My PR #3891 where I break `--quiet` to get logs didn't actually have any CWL Kubernetes timeouts. But the Google job store tests in the next stage also fail:

```
______________________ GoogleJobStoreTest.testBatchCreate ______________________
Traceback (most recent call last):
  File "/builds/TnycNQM8/2/databiosphere/toil/src/toil/test/jobStores/jobStoreTest.py", line 125, in setUp
    self.jobstore_initialized.initialize(self.config)
  File "/builds/TnycNQM8/2/databiosphere/toil/src/toil/jobStores/googleJobStore.py", line 81, in wrapper
    return f(*args, **kwargs)
  File "/builds/TnycNQM8/2/databiosphere/toil/src/toil/jobStores/googleJobStore.py", line 134, in initialize
    self.bucket = self.storageClient.create_bucket(self.bucketName)
  File "/builds/TnycNQM8/2/databiosphere/toil/venv/lib/python3.8/site-packages/google/cloud/storage/client.py", line 229, in create_bucket
    bucket.create(client=self)
  File "/builds/TnycNQM8/2/databiosphere/toil/venv/lib/python3.8/site-packages/google/cloud/storage/bucket.py", line 276, in create
    api_response = client._connection.api_request(
  File "/builds/TnycNQM8/2/databiosphere/toil/venv/lib/python3.8/site-packages/google/cloud/_http.py", line 293, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.Forbidden: 403 POST https://www.googleapis.com/storage/v1/b?project=toil-dev: toil-498@toil-dev.iam.gserviceaccount.com does not have storage.buckets.create access to the Google Cloud project.
```

Looks like the new credentials we issued don't have the permissions they need.

_Originally posted by @adamnovak in https://github.com/DataBiosphere/toil/issues/3888#issuecomment-965364703_

@DailyDreaming, can you fix the permissions on the Google side?

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-1079)
┆friendlyId: TOIL-1079

**Comment by adamnovak** [comment]
We decided a while ago to not try to have the Google Cloud support under CI, I think mostly because we don't want to pay for it.
