### ISSUE TITLE
toil kill gives an error if running toil-cwl-runner

### ISSUE THREAD

**Issue by kannon92** [DataBiosphere/toil#3911]
If I try to run a long running command line tool, I can't use toil kill to terminate the job.  

sleep.yml:
```
#!/usr/bin/env cwl-runner

cwlVersion: v1.0
class: CommandLineTool
baseCommand: [sleep]
id: "echo"
inputs: 
  sleepParam: 
    type: int 
    inputBinding:
      position: 1
outputs: {}
```
param.yaml
```
sleepParam: 1000
```

```
toil-cwl-runner --jobStore /tmp/cwl/jobs sleep.cwl param.yaml
```

In a different terminal, I try to run:

```
toil kill /tmp/cwl/jobs
```

I get the following error on both slurm batchsstem and singleMachine

```
(toil-dev) (base) C02G14FQMD6T:~ kevinhannon$ toil kill /tmp/cwl/jobs/
Traceback (most recent call last):
  File "/Users/kevinhannon/toil-dev/bin/toil", line 33, in <module>
    sys.exit(load_entry_point('toil', 'console_scripts', 'toil')())
  File "/Users/kevinhannon/Work/GIT/toil/src/toil/utils/toilMain.py", line 31, in main
    get_or_die(module, 'main')()
  File "/Users/kevinhannon/Work/GIT/toil/src/toil/utils/toilKill.py", line 45, in main
    with open(pid_log) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/cwl/jobs/pid.log'
```

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-1083)
┆Issue Number: TOIL-1083

**Comment by kannon92** [comment]
Another issue was posted about this.  

https://github.com/DataBiosphere/toil/issues/3917
