### ISSUE TITLE
"Argument list too long" error on Toil jobs

### ISSUE THREAD

**Issue by stevekm** [DataBiosphere/toil#3955]
We are seeing CWL pipeline failures from Toil child jobs running on our LSF HPC system. This is happening regularly, but randomly, such that we are not able to reproduce on-demand, and if the same workflow is restarted it usually eventually runs to successful completion. 

So far it looks like the errors come in two main flavors;

- `OSError: [Errno 7] Argument list too long` on the `du` command used by Toil

```
[2021-12-01T20:45:39-0500] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---
[2021-12-01T20:45:39-0500] [MainThread] [I] [toil] Running Toil version 5.4.0a1-e8a0daf09545a0711d00e5a60abf086b09421245 on host ju24.
[2021-12-01T20:45:39-0500] [MainThread] [I] [toil.worker] Working on job 'ResolveIndirect' kind-ResolveIndirect/instance-epr7m5lc
[2021-12-01T20:45:39-0500] [MainThread] [I] [toil.worker] Loaded body Job('ResolveIndirect' kind-ResolveIndirect/instance-epr7m5lc) from description 'ResolveIndirect' kind-ResolveIndirect/instance-epr7m5lc
[2021-12-01T20:45:39-0500] [MainThread] [I] [toil.job] Saving graph of 1 jobs, 0 new
[2021-12-01T20:45:39-0500] [MainThread] [I] [toil.job] Processing job 'ResolveIndirect' kind-ResolveIndirect/instance-epr7m5lc
Traceback (most recent call last):
  File "/juno/work/ci/prod_ridgeback/venv/lib/python3.7/site-packages/toil/worker.py", line 393, in workerScript
    job._runner(jobGraph=None, jobStore=jobStore, fileStore=fileStore, defer=defer)
  File "/opt/common/CentOS_7/python/python-3.7.1/lib/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/juno/work/ci/prod_ridgeback/venv/lib/python3.7/site-packages/toil/fileStores/nonCachingFileStore.py", line 59, in open
    disk = getDirSizeRecursively(self.localTempDir)
  File "/juno/work/ci/prod_ridgeback/venv/lib/python3.7/site-packages/toil/common.py", line 1432, in getDirSizeRecursively
    env=dict(os.environ, BLOCKSIZE='512')).decode('utf-8').split()[0]) * 512
  File "/opt/common/CentOS_7/python/python-3.7.1/lib/python3.7/subprocess.py", line 389, in check_output
    **kwargs).stdout
  File "/opt/common/CentOS_7/python/python-3.7.1/lib/python3.7/subprocess.py", line 466, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/common/CentOS_7/python/python-3.7.1/lib/python3.7/subprocess.py", line 769, in __init__
    restore_signals, start_new_session)
  File "/opt/common/CentOS_7/python/python-3.7.1/lib/python3.7/subprocess.py", line 1516, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 7] Argument list too long: 'du'
[2021-12-01T20:45:40-0500] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host ju24
```

- the same error as above but this time on both the `du` command and also the `bjobs` command:

```
[2021-09-30T18:51:12-0400] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---
[2021-09-30T18:51:12-0400] [MainThread] [I] [toil] Running Toil version 5.4.0a1-e30349c6facbada3c5dd839c7352af4116a65214 on host ju18.
[2021-09-30T18:51:12-0400] [MainThread] [I] [toil.worker] Working on job 'CWLGather' kind-CWLGather/instance-f7vhi465
[2021-09-30T18:51:12-0400] [MainThread] [I] [toil.worker] Loaded body Job('CWLGather' kind-CWLGather/instance-f7vhi465) from description 'CWLGa
ther' kind-CWLGather/instance-f7vhi465
[2021-09-30T18:51:12-0400] [MainThread] [I] [toil.job] Saving graph of 1 jobs, 0 new
[2021-09-30T18:51:12-0400] [MainThread] [I] [toil.job] Processing job 'CWLGather' kind-CWLGather/instance-f7vhi465
Traceback (most recent call last):
  File "/juno/work/ci/prod_ridgeback/venv/lib/python3.7/site-packages/toil/worker.py", line 393, in workerScript
    job._runner(jobGraph=None, jobStore=jobStore, fileStore=fileStore, defer=defer)
  File "/opt/common/CentOS_7/python/python-3.7.1/lib/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/juno/work/ci/prod_ridgeback/venv/lib/python3.7/site-packages/toil/fileStores/nonCachingFileStore.py", line 59, in open
    disk = getDirSizeRecursively(self.localTempDir)
  File "/juno/work/ci/prod_ridgeback/venv/lib/python3.7/site-packages/toil/common.py", line 1432, in getDirSizeRecursively
    env=dict(os.environ, BLOCKSIZE='512')).decode('utf-8').split()[0]) * 512
  File "/opt/common/CentOS_7/python/python-3.7.1/lib/python3.7/subprocess.py", line 389, in check_output
    **kwargs).stdout
  File "/opt/common/CentOS_7/python/python-3.7.1/lib/python3.7/subprocess.py", line 466, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/common/CentOS_7/python/python-3.7.1/lib/python3.7/subprocess.py", line 769, in __init__
    restore_signals, start_new_session)
  File "/opt/common/CentOS_7/python/python-3.7.1/lib/python3.7/subprocess.py", line 1516, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 7] Argument list too long: 'du'
[2021-09-30T18:51:13-0400] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host ju18
[2021-09-30T18:51:16-0400] [MainThread] [I] [toil.realtimeLogger] Stopping real-time logging server.
[2021-09-30T18:51:16-0400] [MainThread] [I] [toil.realtimeLogger] Joining real-time logging server thread.
Traceback (most recent call last):
  File "/juno/work/ci/prod_ridgeback/venv/bin/toil-cwl-runner", line 11, in <module>
    load_entry_point('toil==5.4.0a1', 'console_scripts', 'toil-cwl-runner')()
  File "/juno/work/ci/prod_ridgeback/venv/lib/python3.7/site-packages/toil/cwl/cwltoil.py", line 2399, in main
    outobj = toil.start(wf1)
  File "/juno/work/ci/prod_ridgeback/venv/lib/python3.7/site-packages/toil/common.py", line 843, in start
    return self._runMainLoop(rootJobDescription)
  File "/juno/work/ci/prod_ridgeback/venv/lib/python3.7/site-packages/toil/common.py", line 1134, in _runMainLoop
    jobCache=self._jobCache).run()
  File "/juno/work/ci/prod_ridgeback/venv/lib/python3.7/site-packages/toil/leader.py", line 229, in run
    self.innerLoop()
  File "/juno/work/ci/prod_ridgeback/venv/lib/python3.7/site-packages/toil/leader.py", line 633, in innerLoop
    self._reportWorkflowStatus()
  File "/juno/work/ci/prod_ridgeback/venv/lib/python3.7/site-packages/toil/leader.py", line 818, in _reportWorkflowStatus
    logger.info(self._getStatusHint())
  File "/juno/work/ci/prod_ridgeback/venv/lib/python3.7/site-packages/toil/leader.py", line 806, in _getStatusHint
    runningJobCount = len(self.batchSystem.getRunningBatchJobIDs())
  File "/juno/work/ci/prod_ridgeback/venv/lib/python3.7/site-packages/toil/batchSystems/abstractGridEngineBatchSystem.py", line 399, in getRunningBatchJobIDs
    batchIds = self.with_retries(self.worker.getRunningJobIDs)
  File "/juno/work/ci/prod_ridgeback/venv/lib/python3.7/site-packages/toil/batchSystems/abstractGridEngineBatchSystem.py", line 454, in with_retries
    return operation(*args, **kwargs)
  File "/juno/work/ci/prod_ridgeback/venv/lib/python3.7/site-packages/toil/batchSystems/lsf.py", line 58, in getRunningJobIDs
    stdout = call_command(["bjobs","-json","-o", "jobid stat start_time"])
  File "/juno/work/ci/prod_ridgeback/venv/lib/python3.7/site-packages/toil/lib/misc.py", line 62, in call_command
    encoding='utf-8', errors="replace", env=env)
  File "/opt/common/CentOS_7/python/python-3.7.1/lib/python3.7/subprocess.py", line 769, in __init__
    restore_signals, start_new_session)
  File "/opt/common/CentOS_7/python/python-3.7.1/lib/python3.7/subprocess.py", line 1516, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 7] Argument list too long: 'bjobs'

```

Any ideas on how to handle this? Is this a Toil bug?

Thanks!

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-1106)
┆friendlyId: TOIL-1106

**Comment by stevekm** [comment]
oh also I forgot to mention, this error can be replicated outside of Toil by trying to run a `subprocess` with an `env` dict that is too large;

(Python 3.7.1)

```
>>> import subprocess
>>> path = "/tmp"
>>> bigdict = {"FOO": 'i' * 10000000}
>>> print(subprocess.check_output(['du', '-s', path], env=bigdict).decode('utf-8').split()[0])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/common/CentOS_7/python/python-3.7.1/lib/python3.7/subprocess.py", line 389, in check_output
    **kwargs).stdout
  File "/opt/common/CentOS_7/python/python-3.7.1/lib/python3.7/subprocess.py", line 466, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/common/CentOS_7/python/python-3.7.1/lib/python3.7/subprocess.py", line 769, in __init__
    restore_signals, start_new_session)
  File "/opt/common/CentOS_7/python/python-3.7.1/lib/python3.7/subprocess.py", line 1516, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 7] Argument list too long: 'du'
```

so it looks like the issue stems from Toil trying to pass in an env that is too large, though its not clear where it got that env from in the first place since the [source code](https://github.com/DataBiosphere/toil/blob/b084951c38b00e7457a0a80073229748c6114233/src/toil/common.py#L1562-L1563) for this appears to be;

```
        return int(subprocess.check_output(['du', '-s', dirPath],
                                           env=dict(os.environ, BLOCKSIZE='512')).decode('utf-8').split()[0]) * 512
```

which suggests that the value for `env` is coming from `dict(os.environ, BLOCKSIZE='512')`, which should (???) be just the job's parent env plus the extra `BLOCKSIZE` variable, right?

**Comment by adamnovak** [comment]
I suppose the extra `BLOCKSIZE` variable could push the environment size over the limit?

We could leave the Toil process environment off of `du`'s environment, but then we might have problems with `PATH`.

Maybe we need to catch this failure and log the environment for debugging.

**Comment by stevekm** [comment]
why does an environment need to be passed? Shouldn't subprocesses inherit the environment of the parent by default?

**Comment by adamnovak** [comment]
Processes inherit the parent's environment by default, but we want to pass a `BLOCKSIZE` environment variable to `du` here that isn't in Toil's environment, without adjusting the environment that other child processes of Toil are going to see. I think that passing an environment to `subprocess` replaces the parent process's environment as the template used for the child process (so that you can e.g. run a child process with an empty environment).

I think we're doing all of this to avoid having to deal with argument parsing differences between Mac and Linux GNU `du`. Maybe we can just check the platform we're on and send command line arguments and stop fiddling with environment variables altogether? Or, @DailyDreaming had some ideas about adjusting the max argument size ourselves.

**Comment by diekhans** [comment]
Maximum argument list size requires a kernel configuration changes,
at least on may OSes:

  https://www.in-ulm.de/~mascheck/various/argmax/


BLOCKSIZE seems to be just the straw breaking the slugs back,
the environment must be huge.

**Comment by DailyDreaming** [comment]
@diekhans That's also the conclusion I came to as well, though other limits (like max arg length) can be set with `ulimit`.

@adamnovak I think that the right solution here is to attempt this with `du`, and if it fails, use `sys` to get the `dir` size.  Using `du` was an optimization in the past because it both greatly sped up looking at file sizes (I suspect due to caching somewhere) and we had a size discrepancy reported in the past that this fixed, but the size was, but the discrepancy was slight if I remember correctly.

**Comment by mhardcastle** [comment]
I see this is still not fixed -- can it be? An option to use the python-native file size methods instead would surely be straightforward.

**Comment by mr-c** [comment]
@mhardcastle @stevekm can you test https://github.com/DataBiosphere/toil/pull/4753 ?
