### ISSUE TITLE
Toil Cactus integration test failing due to NetworkX bug

### ISSUE THREAD

**Issue by adamnovak** [DataBiosphere/toil#4106]
https://ucsc-ci.com/databiosphere/toil/-/jobs/15482#L2236

	Traceback (most recent call last):
	  File "/usr/local/lib/python3.9/dist-packages/toil/worker.py", line 381, in workerScript
	    job = Job.loadJob(jobStore, jobDesc)
	  File "/usr/local/lib/python3.9/dist-packages/toil/job.py", line 2292, in loadJob
	    job = cls._unpickle(userModule, fileHandle, requireInstanceOf=Job)
	  File "/usr/local/lib/python3.9/dist-packages/toil/job.py", line 1918, in _unpickle
	    runnable = unpickler.load()
	  File "/usr/local/lib/python3.9/dist-packages/networkx/classes/reportviews.py", line 1290, in __setstate__
	    self._adjdict = G._pred if hasattr(G, "pred") else G._adj
	AttributeError: 'DiGraph' object has no attribute '_adj'

I think maybe the Cactus we use is hitting https://github.com/networkx/networkx/issues/5655 which was maybe introduced in a new NetworkX release.

We will probably have to ignore the Cactus integration test until Cactus or NetworkX fixes this, and then update to a fixed Cactus.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-1172)
┆friendlyId: TOIL-1172

**Comment by adamnovak** [comment]
NetworkX 2.8.1 released yesterday: https://pypi.org/project/networkx/#history

**Comment by adamnovak** [comment]
This should actually be fixed now.
