### ISSUE TITLE
Single CWL tools run without a workflow cannot read from S3 when using `loadContents`

### ISSUE THREAD

**Issue by adamnovak** [DataBiosphere/toil#4125]
As described by @boyangzhao [here](https://github.com/DataBiosphere/toil/issues/4094#issuecomment-1146783257) and in more detail [here](https://github.com/DataBiosphere/toil/issues/4091#issuecomment-1144714219), running a single CWL tool with an S3 `File` input does not work.

If I do:
```
cat >helloworld.cwl <<'EOF'
class: CommandLineTool
cwlVersion: v1.0
id: helloworld
baseCommand:
  - echo
inputs:
  - id: txt_file
    type: File?
    inputBinding:
      position: 0
      loadContents: true
      valueFrom: $(self.contents)
outputs:
  - id: output
    type: File?
    outputBinding:
      glob: helloworld.txt
label: helloworld
requirements:
  - class: ShellCommandRequirement
  - class: DockerRequirement
    dockerPull: 'alpine:3.7'
  - class: InlineJavascriptRequirement
stdout: helloworld.txt
EOF

cat >helloworld.job.yaml <<'EOF'
txt_file:
  class: File
  location: s3://toil-datasets/hello.txt
EOF

toil-cwl-runner --jobStore ./tree --clean=always helloworld.cwl helloworld.job.yaml
```

Then I get:
```
[2022-06-06T07:15:15-0700] [MainThread] [I] [cwltool] Resolved 'helloworld.cwl' to 'file:///public/home/anovak/build/toil/helloworld.cwl'
[2022-06-06T07:15:22-0700] [MainThread] [I] [toil.common] Successfully deleted the job store: FileJobStore(/public/home/anovak/build/toil/tree)
Traceback (most recent call last):
  File "/public/home/anovak/build/toil/venv/lib/python3.9/site-packages/cwltool/builder.py", line 434, in bind_input
    with self.fs_access.open(
  File "/public/home/anovak/build/toil/venv/lib/python3.9/site-packages/cwltool/stdfsaccess.py", line 40, in open
    return open(self._abs(fn), mode)
FileNotFoundError: [Errno 2] No such file or directory: '/public/home/anovak/build/toil/s3://toil-datasets/hello.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/public/home/anovak/build/toil/venv/lib/python3.9/site-packages/cwltool/builder.py", line 439, in bind_input
    raise Exception(
Exception: Reading s3://toil-datasets/hello.txt
[Errno 2] No such file or directory: '/public/home/anovak/build/toil/s3://toil-datasets/hello.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/public/home/anovak/build/toil/venv/bin/toil-cwl-runner", line 33, in <module>
    sys.exit(load_entry_point('toil', 'console_scripts', 'toil-cwl-runner')())
  File "/public/home/anovak/build/toil/src/toil/cwl/cwltoil.py", line 3575, in main
    builder = tool._init_job(initialized_job_order, runtime_context)
  File "/public/home/anovak/build/toil/venv/lib/python3.9/site-packages/cwltool/process.py", line 917, in _init_job
    builder.bind_input(
  File "/public/home/anovak/build/toil/venv/lib/python3.9/site-packages/cwltool/builder.py", line 375, in bind_input
    self.bind_input(
  File "/public/home/anovak/build/toil/venv/lib/python3.9/site-packages/cwltool/builder.py", line 306, in bind_input
    self.bind_input(
  File "/public/home/anovak/build/toil/venv/lib/python3.9/site-packages/cwltool/builder.py", line 439, in bind_input
    raise Exception(
  File "schema_salad/sourceline.py", line 256, in __exit__
cwltool.errors.WorkflowException:  Reading s3://toil-datasets/hello.txt
 [Errno 2] No such file or directory: '/public/home/anovak/build/toil/s3://toil-datasets/hello.txt'
```

But if I add workflow wrapper:
```
cat >helloworld.wf.cwl <<'EOF'
cwlVersion: v1.2
class: Workflow
requirements:
  SubworkflowFeatureRequirement: {}
inputs:
  - id: txt_file
    type: File
steps:
  helloworld:
    run: helloworld.cwl
    in:
      txt_file: txt_file
    out: [output]
outputs:
  - id: output
    type: File?
    outputSource: helloworld/output
EOF

toil-cwl-runner --jobStore ./tree --clean=always helloworld.wf.cwl helloworld.job.yaml
```

Then it works:
```
[2022-06-06T07:10:49-0700] [MainThread] [I] [cwltool] Resolved 'helloworld.wf.cwl' to 'file:///public/home/anovak/build/toil/helloworld.wf.cwl'
[2022-06-06T07:11:13-0700] [MainThread] [I] [toil.job] Saving graph of 2 jobs, 2 new
[2022-06-06T07:11:13-0700] [MainThread] [I] [toil.job] Processing job 'ResolveIndirect' kind-ResolveIndirect/instance-euw42xmb v0
[2022-06-06T07:11:13-0700] [MainThread] [I] [toil.job] Processing job 'CWLWorkflow' kind-CWLWorkflow/instance-mlw0xnyq v0
[2022-06-06T07:11:13-0700] [MainThread] [I] [toil] Running Toil version 5.6.0a1-312b6e1f221ee7f7f187dd6dbfce1aecffd00e09 on host courtyard.
[2022-06-06T07:11:15-0700] [MainThread] [I] [toil.leader] 1 jobs are running, 0 jobs are issued and waiting to run
[2022-06-06T07:11:19-0700] [MainThread] [I] [toil.worker] Redirecting logging to /data/tmp/375756c44eb55db3805af3ac81115d77/9456/worker_log.txt
[2022-06-06T07:11:21-0700] [MainThread] [I] [toil.leader] Issued job 'CWLJob' helloworld.wf.cwl.helloworld.helloworld kind-CWLJob/instance-t45hig6d v1 with job batch system ID: 1 and cores: 1, disk: 3.0 
Gi, and memory: 2.0 Gi
[2022-06-06T07:11:26-0700] [MainThread] [I] [toil.worker] Redirecting logging to /data/tmp/375756c44eb55db3805af3ac81115d77/4617/worker_log.txt
[2022-06-06T07:11:53-0700] [MainThread] [I] [toil.worker] Redirecting logging to /data/tmp/375756c44eb55db3805af3ac81115d77/8b77/worker_log.txt
[2022-06-06T07:12:01-0700] [MainThread] [I] [toil.worker] Redirecting logging to /data/tmp/375756c44eb55db3805af3ac81115d77/5c23/worker_log.txt
[2022-06-06T07:12:05-0700] [MainThread] [I] [toil.leader] Finished toil run successfully.

Workflow Progress 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 (0 failures) [00:49<00:00, 0.08 jobs/s]
{
    "output": {
        "location": "file:///public/home/anovak/build/toil/helloworld.txt",
        "basename": "helloworld.txt",
        "nameroot": "helloworld",
        "nameext": ".txt",
        "class": "File",
        "checksum": "sha1$e3efd3aaf726bbf6320bc03fd4b495963f1d9b69",
        "size": 147
    }
}[2022-06-06T07:12:05-0700] [MainThread] [I] [toil.common] Successfully deleted the job store: FileJobStore(/public/home/anovak/build/toil/tree)
```

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-1178)
┆friendlyId: TOIL-1178

**Comment by adamnovak** [comment]
This seems to only fail if `loadContents` is `true` on the input. If I get rid of it, the run manages to start (but fails later because `contents` isn't filled in). If I change this from an `echo` to a `cat` and from passign the contents on the command line to passing the name, it works even without a wrapping workflow.

The problem is that we do the contents loading very early in workflow setup, before we've configured `cwltool` to use Toil's filesystem machinery, so it doesn't know how to read anything but local paths yet.
