### ISSUE TITLE
Biocintainers CWL test no longer works on CI

### ISSUE THREAD

**Issue by adamnovak** [DataBiosphere/toil#4197]
A [bunch](https://ucsc-ci.com/databiosphere/toil/-/jobs/20674) of [recent](https://ucsc-ci.com/databiosphere/toil/-/jobs/20699) CI runs have been producing this lately:

```
______________________ CWLWorkflowTest.test_biocontainers ______________________
Traceback (most recent call last):
  File "/builds/databiosphere/toil/src/toil/test/cwl/cwlTest.py", line 410, in test_biocontainers
    self._tester(
  File "/builds/databiosphere/toil/src/toil/test/cwl/cwlTest.py", line 228, in _tester
    cwltoil.main(main_args, stdout=st)
  File "/builds/databiosphere/toil/src/toil/cwl/cwltoil.py", line 3694, in main
    outobj = toil.start(wf1)
  File "/builds/databiosphere/toil/src/toil/common.py", line 989, in start
    return self._runMainLoop(rootJobDescription)
  File "/builds/databiosphere/toil/src/toil/common.py", line 1409, in _runMainLoop
    return Leader(config=self.config,
  File "/builds/databiosphere/toil/src/toil/leader.py", line 330, in run
    raise FailedJobsException(self.jobStore, failed_jobs, exit_code=self.recommended_fail_exit_code)
toil.leader.FailedJobsException: The job store '/tmp/tmp_26raip1' contains 1 failed jobs: 'CWLJob' seqtk_seq kind-CWLJob/instance-b2c1pgy4 v6
Log from job "'CWLJob' seqtk_seq kind-CWLJob/instance-b2c1pgy4 v6" follows:
=========>
	[2022-08-23T20:45:09+0000] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---
	[2022-08-23T20:45:09+0000] [MainThread] [I] [toil] Running Toil version 5.8.0a1-f317b7c5d3c28fd17389cc82cfb2fd4d54d6fae6 on host runner-l96kpzps-project-3-concurrent-02v45w.
	[2022-08-23T20:45:09+0000] [MainThread] [I] [toil.worker] Working on job 'CWLJob' seqtk_seq kind-CWLJob/instance-b2c1pgy4 v4
	[2022-08-23T20:45:09+0000] [MainThread] [I] [toil.worker] Loaded body Job('CWLJob' seqtk_seq kind-CWLJob/instance-b2c1pgy4 v4) from description 'CWLJob' seqtk_seq kind-CWLJob/instance-b2c1pgy4 v4
	[2022-08-23T20:45:09+0000] [MainThread] [I] [galaxy.tool_util.deps.containers] Checking with container resolver [ExplicitContainerResolver[]] found description [None]
	[2022-08-23T20:45:10+0000] [MainThread] [I] [galaxy.tool_util.deps.containers] Checking with container resolver [CachedMulledDockerContainerResolver[namespace=biocontainers]] found description [None]
	[2022-08-23T20:45:10+0000] [MainThread] [I] [galaxy.tool_util.deps.containers] Checking with container resolver [CachedMulledDockerContainerResolver[namespace=local]] found description [None]
	[2022-08-23T20:45:10+0000] [MainThread] [E] [galaxy.tool_util.deps.containers] Could not get container description for tool 'None'
	Traceback (most recent call last):
	  File "/builds/databiosphere/toil/venv/lib/python3.9/site-packages/galaxy/tool_util/deps/containers.py", line 281, in find_best_container_description
	    resolved_container_description = self.resolve(enabled_container_types, tool_info, **kwds)
	  File "/builds/databiosphere/toil/venv/lib/python3.9/site-packages/galaxy/tool_util/deps/containers.py", line 303, in resolve
	    container_description = container_resolver.resolve(enabled_container_types, tool_info, install=install, resolution_cache=resolution_cache, session=session)
	  File "/builds/databiosphere/toil/venv/lib/python3.9/site-packages/galaxy/tool_util/deps/container_resolvers/mulled.py", line 534, in resolve
	    name = targets_to_mulled_name(targets=targets, hash_func=self.hash_func, namespace=self.namespace, resolution_cache=resolution_cache, session=session)
	  File "/builds/databiosphere/toil/venv/lib/python3.9/site-packages/galaxy/tool_util/deps/container_resolvers/mulled.py", line 353, in targets_to_mulled_name
	    tags = mulled_tags_for(namespace, target.package_name, resolution_cache=resolution_cache, session=session)
	  File "/builds/databiosphere/toil/venv/lib/python3.9/site-packages/galaxy/tool_util/deps/mulled/util.py", line 103, in mulled_tags_for
	    if not _namespace_has_repo_name(namespace, image, resolution_cache):
	  File "/builds/databiosphere/toil/venv/lib/python3.9/site-packages/galaxy/tool_util/deps/mulled/util.py", line 71, in _namespace_has_repo_name
	    return repo_name in resolution_cache.get(cache_key)
	TypeError: argument of type 'NoneType' is not iterable
	[2022-08-23T20:45:10+0000] [MainThread] [I] [cwltool] [job seqtk_seq] /tmp/9848d07a78185a96bd579a6bf463dc5d/a81b/908b/tmpkb68z3t1/tmp-outl4e3ax4a$ seqtk \
	    seq \
	    -a \
	    /tmp/9848d07a78185a96bd579a6bf463dc5d/a81b/908b/tmp7d1bjg0be9gbvu47/stg31a12e19-64bf-4864-80b3-553b3f22615f/2.fastq > /tmp/9848d07a78185a96bd579a6bf463dc5d/a81b/908b/tmpkb68z3t1/tmp-outl4e3ax4a/out
	[2022-08-23T20:45:10+0000] [MainThread] [E] [cwltool] 'seqtk' not found: [Errno 2] No such file or directory: 'seqtk'
	[2022-08-23T20:45:10+0000] [MainThread] [W] [cwltool] [job seqtk_seq] completed permanentFail
	[2022-08-23T20:45:10+0000] [MainThread] [W] [toil.fileStores.abstractFileStore] Failed job accessed files:
	[2022-08-23T20:45:10+0000] [MainThread] [W] [toil.fileStores.abstractFileStore] Downloaded file 'files/no-job/file-2b40ab3094084b019ca49c8c88c70f16/2.fastq' to path '/tmp/9848d07a78185a96bd579a6bf463dc5d/a81b/908b/tmp4yatkddt.tmp'
	Traceback (most recent call last):
	  File "/builds/databiosphere/toil/src/toil/worker.py", line 407, in workerScript
	    job._runner(jobGraph=None, jobStore=jobStore, fileStore=fileStore, defer=defer)
	  File "/builds/databiosphere/toil/src/toil/job.py", line 2406, in _runner
	    returnValues = self._run(jobGraph=None, fileStore=fileStore)
	  File "/builds/databiosphere/toil/src/toil/job.py", line 2324, in _run
	    return self.run(fileStore)
	  File "/builds/databiosphere/toil/src/toil/cwl/cwltoil.py", line 2256, in run
	    raise cwltool.errors.WorkflowException(status)
	cwltool.errors.WorkflowException: permanentFail
	[2022-08-23T20:45:10+0000] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host runner-l96kpzps-project-3-concurrent-02v45w
<=========
```

I can't tell how this could even begin to be our fault, but I also couldn't reproduce it locally when I tried. This is either a bug in the `galaxy` module for not being able to find the container, or in the test for asking for a container which somehow no longer exists.

I am going to mark the test xfail to unblock development, because I have no idea why biocontainers would only not work in Toil, but at some point we should actually fix it.

@mr-c Do you know what "biocontainers" even ism and whether we should expect it to work here?

**Comment by mr-c** [comment]
There was a bug in Galaxy. They just released a fix: https://pypi.org/project/galaxy-tool-util/22.1.2/
