### ISSUE TITLE
Flaky Test: PreemptableDeficitCompensationTest can fail because the cluster leader can be terminated before it launches

### ISSUE THREAD

**Issue by adamnovak** [DataBiosphere/toil#4234]
I had the [provisioner integration tests fail](https://ucsc-ci.com/databiosphere/toil/-/jobs/24229) in #4199 because a cluster leader got terminated by something before it could launch.

Maybe we need to let launch-cluster handle retrying when it tries to make an instance and it immediately goes away?

```
=================================== FAILURES ===================================
___________________ PreemptableDeficitCompensationTest.test ____________________
Traceback (most recent call last):
  File "/builds/databiosphere/toil/src/toil/test/provisioners/aws/awsProvisionerTest.py", line 476, in test
    self._test(preemptableJobs=True)
  File "/builds/databiosphere/toil/src/toil/test/provisioners/aws/awsProvisionerTest.py", line 162, in _test
    self.launchCluster()
  File "/builds/databiosphere/toil/src/toil/test/provisioners/clusterTest.py", line 158, in launchCluster
    self.createClusterUtil()
  File "/builds/databiosphere/toil/src/toil/test/provisioners/clusterTest.py", line 154, in createClusterUtil
    subprocess.check_call(command)
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['toil', 'launch-cluster', '-p=aws', '-z', 'us-west-2a', '--keyPairName=id_rsa', '--leaderNodeType=t2.medium', '--clusterType=mesos', '--logDebug', 'deficit-test-341582d9-e10c-48c9-a1a4-1693c8e9eb21']' returned non-zero exit status 1.
---------------------------- Captured stdout setup -----------------------------


[TEST] toil.test.provisioners.aws.awsProvisionerTest.PreemptableDeficitCompensationTest:test (Oct 04 2022 00:20:04:468407 PDT)


------------------------------ Captured log setup ------------------------------
DEBUG    botocore.hooks:hooks.py:483 Changing event name from creating-client-class.iot-data to creating-client-class.iot-data-plane
DEBUG    botocore.hooks:hooks.py:483 Changing event name from before-call.apigateway to before-call.api-gateway
DEBUG    botocore.hooks:hooks.py:483 Changing event name from request-created.machinelearning.Predict to request-created.machine-learning.Predict
DEBUG    botocore.hooks:hooks.py:483 Changing event name from before-parameter-build.autoscaling.CreateLaunchConfiguration to before-parameter-build.auto-scaling.CreateLaunchConfiguration
DEBUG    botocore.hooks:hooks.py:483 Changing event name from before-parameter-build.route53 to before-parameter-build.route-53
DEBUG    botocore.hooks:hooks.py:483 Changing event name from request-created.cloudsearchdomain.Search to request-created.cloudsearch-domain.Search
DEBUG    botocore.hooks:hooks.py:483 Changing event name from docs.*.autoscaling.CreateLaunchConfiguration.complete-section to docs.*.auto-scaling.CreateLaunchConfiguration.complete-section
DEBUG    botocore.hooks:hooks.py:483 Changing event name from before-parameter-build.logs.CreateExportTask to before-parameter-build.cloudwatch-logs.CreateExportTask
DEBUG    botocore.hooks:hooks.py:483 Changing event name from docs.*.logs.CreateExportTask.complete-section to docs.*.cloudwatch-logs.CreateExportTask.complete-section
DEBUG    botocore.hooks:hooks.py:483 Changing event name from before-parameter-build.cloudsearchdomain.Search to before-parameter-build.cloudsearch-domain.Search
DEBUG    botocore.hooks:hooks.py:483 Changing event name from docs.*.cloudsearchdomain.Search.complete-section to docs.*.cloudsearch-domain.Search.complete-section
DEBUG    botocore.utils:utils.py:431 IMDS ENDPOINT: http://169.254.169.254/
DEBUG    toil:__init__.py:616 Attempting to read cached credentials from /root/.cache/aws/cached_temporary_credentials.
DEBUG    toil:__init__.py:628 /root/.cache/aws/cached_temporary_credentials is empty. Credentials are not temporary.
DEBUG    botocore.credentials:credentials.py:2094 Looking for credentials via: env
DEBUG    botocore.credentials:credentials.py:2094 Looking for credentials via: assume-role
DEBUG    botocore.credentials:credentials.py:2094 Looking for credentials via: assume-role-with-web-identity
DEBUG    botocore.credentials:credentials.py:2094 Looking for credentials via: sso
DEBUG    botocore.credentials:credentials.py:2094 Looking for credentials via: shared-credentials-file
INFO     botocore.credentials:credentials.py:1311 Found credentials in shared credentials file: ~/.aws/credentials
----------------------------- Captured stderr call -----------------------------
[2022-10-04T00:20:06+0000] [MainThread] [I] [toil.utils.toilDestroyCluster] Destroying cluster deficit-test-341582d9-e10c-48c9-a1a4-1693c8e9eb21
[2022-10-04T00:20:06+0000] [MainThread] [I] [toil.provisioners.aws.awsProvisioner] Terminating any remaining workers ...
[2022-10-04T00:20:07+0000] [MainThread] [I] [toil.provisioners.aws.awsProvisioner] Deleting launch templates ...
[2022-10-04T00:20:07+0000] [MainThread] [I] [toil.provisioners.aws.awsProvisioner] Deleting IAM roles ...
[2022-10-04T00:20:08+0000] [MainThread] [I] [toil.provisioners.aws.awsProvisioner] Deleting security group ...
[2022-10-04T00:20:08+0000] [MainThread] [I] [toil.provisioners.aws.awsProvisioner] Deleting S3 buckets ...
[2022-10-04T00:20:08+0000] [MainThread] [I] [toil.utils.toilDestroyCluster] Cluster deficit-test-341582d9-e10c-48c9-a1a4-1693c8e9eb21 is now gone.
[2022-10-04T00:20:10+0000] [MainThread] [D] [toil.statsAndLogging] Suppressing the following loggers: {'rsa', 'oauthlib', 'pyasn1', 'kubernetes', 'boto3', 'websocket', 'setuptools', 'requests', 'urllib3', 'botocore', 'dill', 'bcdocs', 'pkg_resources', 'boto', 'charset_normalizer', 'google', 'docker', 'requests_oauthlib'}
[2022-10-04T00:20:10+0000] [MainThread] [D] [toil.statsAndLogging] Root logger is at level 'DEBUG', 'toil' logger at level 'DEBUG'.
[2022-10-04T00:20:10+0000] [MainThread] [I] [toil] Overriding docker registry of quay.io/ucsc_cgl with quay.io/ucsc_cgl from TOIL_DOCKER_REGISTRY.
[2022-10-04T00:20:10+0000] [MainThread] [I] [toil] Overriding docker name of toil with toil from TOIL_DOCKER_NAME.
[2022-10-04T00:20:10+0000] [MainThread] [I] [toil] Overriding docker appliance of quay.io/ucsc_cgl/toil:5.8.0a1-a5938346214d417721737fbacc0e4496a7b28672-py3.9 with quay.io/ucsc_cgl/toil:5.8.0a1-a5938346214d417721737fbacc0e4496a7b28672-py3.9 from TOIL_APPLIANCE_SELF.
[2022-10-04T00:20:10+0000] [MainThread] [I] [toil.utils.toilLaunchCluster] Creating cluster deficit-test-341582d9-e10c-48c9-a1a4-1693c8e9eb21...
[2022-10-04T00:20:11+0000] [MainThread] [D] [toil.lib.aws.iam] Allowed actions: defaultdict(<function init_action_collection.<locals>.<lambda> at 0x7f7f8c797940>, {})
[2022-10-04T00:20:11+0000] [MainThread] [W] [toil.lib.aws.iam] You appear to lack the folowing AWS permissions: iam:CreateRole, iam:CreateInstanceProfile, iam:TagInstanceProfile, iam:DeleteRole, iam:DeleteRoleProfile, iam:ListAttatchedRolePolicies, iam:ListPolicies, iam:ListRoleTags, iam:PassRole, iam:PutRolePolicy, iam:RemoveRoleFromInstanceProfile, iam:TagRole, ec2:AuthorizeSecurityGroupIngress, ec2:CancelSpotInstanceRequests, ec2:CreateSecurityGroup, ec2:CreateTags, ec2:DeleteSecurityGroup, ec2:DescribeAvailabilityZones, ec2:DescribeImages, ec2:DescribeInstances, ec2:DescribeInstanceStatus, ec2:DescribeKeyPairs, ec2:DescribeSecurityGroups, ec2:DescribeSpotInstanceRequests, ec2:DescribeSpotPriceHistory, ec2:DescribeVolumes, ec2:ModifyInstanceAttribute, ec2:RequestSpotInstances, ec2:RunInstances, ec2:StartInstances, ec2:StopInstances, ec2:TerminateInstances
[2022-10-04T00:20:11+0000] [MainThread] [W] [toil.provisioners.aws.awsProvisioner] Toil may not be able to properly launch (or destroy!) your cluster.
[2022-10-04T00:20:11+0000] [MainThread] [D] [toil] Attempting to read cached credentials from /root/.cache/aws/cached_temporary_credentials.
[2022-10-04T00:20:11+0000] [MainThread] [D] [toil] /root/.cache/aws/cached_temporary_credentials is empty. Credentials are not temporary.
[2022-10-04T00:20:11+0000] [MainThread] [D] [toil.provisioners.aws.awsProvisioner] Creating IAM role deficit_test_341582d9_e10c_48c9_a1a4_1693c8e9eb21_toil...
[2022-10-04T00:20:11+0000] [MainThread] [D] [toil.provisioners.aws.awsProvisioner] Created new IAM role
[2022-10-04T00:20:13+0000] [MainThread] [D] [toil.provisioners.aws.awsProvisioner] Created new instance profile: {'path': '/', 'instance_profile_name': 'deficit_test_341582d9_e10c_48c9_a1a4_1693c8e9eb21_toil', 'roles': {}, 'arn': 'arn:aws:iam::318423852362:instance-profile/deficit_test_341582d9_e10c_48c9_a1a4_1693c8e9eb21_toil', 'instance_profile_id': 'AIPAUUI4KMVFCMZ6VMONL', 'create_date': '2022-10-04T00:20:13Z'}
[2022-10-04T00:20:13+0000] [MainThread] [D] [toil.lib.ec2] Checking for instance profile deficit_test_341582d9_e10c_48c9_a1a4_1693c8e9eb21_toil...
[2022-10-04T00:20:14+0000] [MainThread] [D] [toil.lib.ec2] Instance profile found
[2022-10-04T00:20:14+0000] [MainThread] [D] [toil.provisioners.aws.awsProvisioner] Associated role deficit_test_341582d9_e10c_48c9_a1a4_1693c8e9eb21_toil with profile
[2022-10-04T00:20:14+0000] [MainThread] [D] [toil] Attempting to read cached credentials from /root/.cache/aws/cached_temporary_credentials.
[2022-10-04T00:20:14+0000] [MainThread] [D] [toil] /root/.cache/aws/cached_temporary_credentials is empty. Credentials are not temporary.
[2022-10-04T00:20:15+0000] [MainThread] [D] [toil.provisioners.aws.awsProvisioner] Device mapping: [{'DeviceName': '/dev/xvda', 'Ebs': {'DeleteOnTermination': True, 'VolumeSize': 50, 'VolumeType': 'gp2'}}]
[2022-10-04T00:20:15+0000] [MainThread] [I] [toil] Using default user-defined custom docker init command of  as TOIL_CUSTOM_DOCKER_INIT_COMMAND is not set.
[2022-10-04T00:20:15+0000] [MainThread] [I] [toil] Using default user-defined custom init command of  as TOIL_CUSTOM_INIT_COMMAND is not set.
[2022-10-04T00:20:15+0000] [MainThread] [I] [toil] Overriding docker registry of quay.io/ucsc_cgl with quay.io/ucsc_cgl from TOIL_DOCKER_REGISTRY.
[2022-10-04T00:20:15+0000] [MainThread] [I] [toil] Overriding docker name of toil with toil from TOIL_DOCKER_NAME.
[2022-10-04T00:20:15+0000] [MainThread] [I] [toil] Overriding docker appliance of quay.io/ucsc_cgl/toil:5.8.0a1-a5938346214d417721737fbacc0e4496a7b28672-py3.9 with quay.io/ucsc_cgl/toil:5.8.0a1-a5938346214d417721737fbacc0e4496a7b28672-py3.9 from TOIL_APPLIANCE_SELF.
[2022-10-04T00:20:15+0000] [MainThread] [D] [toil.provisioners.aws.awsProvisioner] Launching leader with tags: {'Name': 'deficit-test-341582d9-e10c-48c9-a1a4-1693c8e9eb21', 'Owner': 'shared', 'clusterName': 'deficit-test-341582d9-e10c-48c9-a1a4-1693c8e9eb21', 'ToilNodeType': 'leader'}
[2022-10-04T00:20:16+0000] [MainThread] [D] [toil.lib.aws.ami] No AMI found in TOIL_AWS_AMI; checking Flatcar release feed (try 1)
[2022-10-04T00:20:16+0000] [MainThread] [I] [toil.lib.aws.ami] Selected Flatcar AMI: ami-0a74156d2cf5281c6
[2022-10-04T00:20:16+0000] [MainThread] [I] [toil.lib.ec2] Creating t2.medium instance(s) ... 
[2022-10-04T00:20:16+0000] [MainThread] [D] [toil.lib.ec2] Checking for instance profile deficit_test_341582d9_e10c_48c9_a1a4_1693c8e9eb21_toil...
[2022-10-04T00:20:16+0000] [MainThread] [D] [toil.lib.ec2] Instance profile found
[2022-10-04T00:20:17+0000] [MainThread] [W] [toil.lib.retry] Error in <function create_instances at 0x7f7f8cef9c10>: An error occurred (InvalidParameterValue) when calling the RunInstances operation: Value (arn:aws:iam::318423852362:instance-profile/deficit_test_341582d9_e10c_48c9_a1a4_1693c8e9eb21_toil) for parameter iamInstanceProfile.arn is invalid. Invalid IAM Instance Profile ARN. Retrying after 5 s...
[2022-10-04T00:20:22+0000] [MainThread] [I] [toil.lib.ec2] Creating t2.medium instance(s) ... 
[2022-10-04T00:20:22+0000] [MainThread] [D] [toil.lib.ec2] Checking for instance profile deficit_test_341582d9_e10c_48c9_a1a4_1693c8e9eb21_toil...
[2022-10-04T00:20:22+0000] [MainThread] [D] [toil.lib.ec2] Instance profile found
[2022-10-04T00:20:24+0000] [MainThread] [I] [toil.provisioners.aws.awsProvisioner] Waiting for leader instance ec2.Instance(id='i-09e60d49ac5f9828e') to be running
Traceback (most recent call last):
  File "/builds/databiosphere/toil/venv/bin/toil", line 33, in <module>
    sys.exit(load_entry_point('toil', 'console_scripts', 'toil')())
  File "/builds/databiosphere/toil/src/toil/utils/toilMain.py", line 33, in main
    get_or_die(module, 'main')()
  File "/builds/databiosphere/toil/src/toil/utils/toilLaunchCluster.py", line 163, in main
    cluster.launchCluster(leaderNodeType=options.leaderNodeType,
  File "/builds/databiosphere/toil/src/toil/provisioners/aws/awsProvisioner.py", line 377, in launchCluster
    leader.wait_until_running()
  File "/builds/databiosphere/toil/venv/lib/python3.9/site-packages/boto3/resources/factory.py", line 413, in do_waiter
    waiter(self, *args, **kwargs)
  File "/builds/databiosphere/toil/venv/lib/python3.9/site-packages/boto3/resources/action.py", line 215, in __call__
    response = waiter.wait(**params)
  File "/builds/databiosphere/toil/venv/lib/python3.9/site-packages/botocore/waiter.py", line 55, in wait
    Waiter.wait(self, **kwargs)
  File "/builds/databiosphere/toil/venv/lib/python3.9/site-packages/botocore/waiter.py", line 375, in wait
    raise WaiterError(
botocore.exceptions.WaiterError: Waiter InstanceRunning failed: Waiter encountered a terminal failure state: For expression "Reservations[].Instances[].State.Name" we matched expected path: "terminated" at least once
[2022-10-04T00:20:41+0000] [MainThread] [I] [toil.utils.toilDestroyCluster] Destroying cluster deficit-test-341582d9-e10c-48c9-a1a4-1693c8e9eb21
[2022-10-04T00:20:41+0000] [MainThread] [I] [toil.provisioners.aws.awsProvisioner] Terminating any remaining workers ...
[2022-10-04T00:20:42+0000] [MainThread] [I] [toil.provisioners.aws.awsProvisioner] Deleting launch templates ...
[2022-10-04T00:20:42+0000] [MainThread] [I] [toil.provisioners.aws.awsProvisioner] Deleting IAM roles ...
[2022-10-04T00:20:44+0000] [MainThread] [I] [toil.provisioners.aws.awsProvisioner] Deleting security group ...
[2022-10-04T00:20:44+0000] [MainThread] [I] [toil.provisioners.aws.awsProvisioner] Deleting S3 buckets ...
[2022-10-04T00:20:44+0000] [MainThread] [I] [toil.utils.toilDestroyCluster] Cluster deficit-test-341582d9-e10c-48c9-a1a4-1693c8e9eb21 is now gone.
[2022-10-04T00:20:47+0000] [MainThread] [I] [toil.utils.toilClean] Failed to delete the job store: aws:us-west-2:deficit-24f51388-a4be-4ae0-9ec7-5f1dab6c1152 is non-existent.
------------------------------ Captured log call -------------------------------
INFO     toil.test:__init__.py:114 Setting up toil.test.provisioners.aws.awsProvisionerTest.PreemptableDeficitCompensationTest.test ...
DEBUG    toil.test.provisioners.clusterTest:clusterTest.py:151 Launching cluster: ['toil', 'launch-cluster', '-p=aws', '-z', 'us-west-2a', '--keyPairName=id_rsa', '--leaderNodeType=t2.medium', '--clusterType=mesos', '--logDebug', 'deficit-test-341582d9-e10c-48c9-a1a4-1693c8e9eb21']
INFO     toil.test:__init__.py:119 Tore down toil.test.provisioners.aws.awsProvisionerTest.PreemptableDeficitCompensationTest.test
```

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-1228)
┆friendlyId: TOIL-1228

**Comment by adamnovak** [comment]
This also affects `AWSAutoscaleTestMultipleNodeTypes.testAutoScale`, and probably any test that launches a cluster. It caused a CI failure on job https://ucsc-ci.com/databiosphere/toil/-/jobs/25042 for #4247 which I need to merge to... fix other intermittent CI failures.

**Comment by w-gao** [comment]
@adamnovak I ran into this in #4284 as well, where `UtilsTest.testAWSProvisionerUtils` failed because of this. Do you happen to know why the instance may immediately go away? Is it just something that happens occasionally, and we just need to retry?

Since this is not assigned to anyone yet, I can take this.

**Comment by adamnovak** [comment]
I don't know why the instance would jump right to terminated. I think the Genomics Institute untagged instance killer is supposed to wait an hour before killing anything, so it *shouldn't* be that. Maybe we have our own cleanup code that is killing it?
