### ISSUE TITLE
Flaky Test: AWSManagedAutoscaleTest.testAutoScale can fail because the cluster can't be destroyed

### ISSUE THREAD

**Issue by adamnovak** [DataBiosphere/toil#4280]
┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-1245)
┆Issue Number: TOIL-1245

**Comment by adamnovak** [comment]
In https://ucsc-ci.com/databiosphere/toil/-/jobs/26996 I got this failure:

```
____________________ AWSManagedAutoscaleTest.testAutoScale _____________________
Traceback (most recent call last):
  File "/builds/databiosphere/toil/src/toil/test/provisioners/clusterTest.py", line 79, in tearDown
    self.destroyCluster()
  File "/builds/databiosphere/toil/src/toil/test/provisioners/clusterTest.py", line 64, in destroyCluster
    subprocess.check_call(['toil', 'destroy-cluster', '-p=aws', '-z', self.zone, self.clusterName])
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['toil', 'destroy-cluster', '-p=aws', '-z', 'us-west-2a', 'provisioner-test-66b40bd0-30b9-4dd4-9838-b9c9e08f5185']' returned non-zero exit status 1.
```

It looks like the actual error is:

```
[2022-11-16T03:01:58+0000] [MainThread] [I] [toil.utils.toilDestroyCluster] Destroying cluster provisioner-test-66b40bd0-30b9-4dd4-9838-b9c9e08f5185
[2022-11-16T03:01:59+0000] [MainThread] [E] [toil.lib.retry] Got a <class 'botocore.exceptions.ClientError'>: An error occurred (ValidationError) when calling the DeleteAutoScalingGroup operation: AutoScalingGroup name not found - AutoScalingGroup 'toil-a087ca19-84fa-4e1a-bfee-66548c8ed73a' not found which is not retriable according to <function expectedShutdownErrors at 0x7fae086b98b0>
Traceback (most recent call last):
  File "/builds/databiosphere/toil/venv/bin/toil", line 33, in <module>
    sys.exit(load_entry_point('toil', 'console_scripts', 'toil')())
  File "/builds/databiosphere/toil/src/toil/utils/toilMain.py", line 32, in main
    get_or_die(module, 'main')()
  File "/builds/databiosphere/toil/src/toil/utils/toilDestroyCluster.py", line 33, in main
    cluster.destroyCluster()
  File "/builds/databiosphere/toil/src/toil/provisioners/aws/awsProvisioner.py", line 614, in destroyCluster
    self.aws.client(self._region, 'autoscaling').delete_auto_scaling_group(AutoScalingGroupName=asgName, ForceDelete=True)
  File "/builds/databiosphere/toil/venv/lib/python3.9/site-packages/botocore/client.py", line 515, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/builds/databiosphere/toil/venv/lib/python3.9/site-packages/botocore/client.py", line 934, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ValidationError) when calling the DeleteAutoScalingGroup operation: AutoScalingGroup name not found - AutoScalingGroup 'toil-a087ca19-84fa-4e1a-bfee-66548c8ed73a' not found
```

So we probably need to add this to the expected errors to get at shutdown, because an ASG we want to destroy might not exist or might be being destroyed.
