### ISSUE TITLE
GPU acceleration on a single machine through Singularity

### ISSUE THREAD

**Issue by muffato** [DataBiosphere/toil#4311]
Hello

I found this problem whilst running Cactus (https://github.com/ComparativeGenomicsToolkit/cactus/issues/900) through Singularity.
The container has its own `/usr/bin`, which means that the host's `/usr/bin/nvida-smi` is not available. Therefore, toil https://github.com/DataBiosphere/toil/blob/083ad3b6d40f145e3ba2073fe66c7c0cf3c60ea7/src/toil/lib/accelerators.py#L64 is not able to run `nvidia-smi` to find out the number of GPUs available. This results in the following error when using `--gpu 1`
```
Traceback (most recent call last):
  File "/home/cactus/cactus_env/bin/cactus", line 8, in <module>
    sys.exit(main())
  File "/home/cactus/cactus_env/lib/python3.8/site-packages/cactus/progressive/cactus_progressive.py", line 400, in main
    hal_id = toil.start(Job.wrapJobFn(progressive_workflow, options, config_node, mc_tree, og_map, input_seq_id_map))
  File "/home/cactus/cactus_env/lib/python3.8/site-packages/toil/common.py", line 1017, in start
    return self._runMainLoop(rootJobDescription)
  File "/home/cactus/cactus_env/lib/python3.8/site-packages/toil/common.py", line 1456, in _runMainLoop
    return Leader(config=self.config,
  File "/home/cactus/cactus_env/lib/python3.8/site-packages/toil/leader.py", line 292, in run
    self.innerLoop()
  File "/home/cactus/cactus_env/lib/python3.8/site-packages/toil/leader.py", line 778, in innerLoop
    self._processReadyJobs()
  File "/home/cactus/cactus_env/lib/python3.8/site-packages/toil/leader.py", line 675, in _processReadyJobs
    self._processReadyJob(message.job_id, message.result_status)
  File "/home/cactus/cactus_env/lib/python3.8/site-packages/toil/leader.py", line 591, in _processReadyJob
    self._runJobSuccessors(job_id)
  File "/home/cactus/cactus_env/lib/python3.8/site-packages/toil/leader.py", line 485, in _runJobSuccessors
    self.issueJobs(successors)
  File "/home/cactus/cactus_env/lib/python3.8/site-packages/toil/leader.py", line 962, in issueJobs
    self.issueJob(job)
  File "/home/cactus/cactus_env/lib/python3.8/site-packages/toil/leader.py", line 939, in issueJob
    jobBatchSystemID = self.batchSystem.issueBatchJob(jobNode, job_environment=job_environment)
  File "/home/cactus/cactus_env/lib/python3.8/site-packages/toil/batchSystems/singleMachine.py", line 731, in issueBatchJob
    self.check_resource_request(scaled_desc)
  File "/home/cactus/cactus_env/lib/python3.8/site-packages/toil/batchSystems/singleMachine.py", line 490, in check_resource_request
    raise e
  File "/home/cactus/cactus_env/lib/python3.8/site-packages/toil/batchSystems/singleMachine.py", line 486, in check_resource_request
    super().check_resource_request(requirer)
  File "/home/cactus/cactus_env/lib/python3.8/site-packages/toil/batchSystems/abstractBatchSystem.py", line 335, in check_resource_request
    raise e
  File "/home/cactus/cactus_env/lib/python3.8/site-packages/toil/batchSystems/abstractBatchSystem.py", line 330, in check_resource_request
    self._check_accelerator_request(requirer)
  File "/home/cactus/cactus_env/lib/python3.8/site-packages/toil/batchSystems/singleMachine.py", line 496, in _check_accelerator_request
    raise InsufficientSystemResources(requirer, 'accelerators', self.accelerator_identities, details=[
toil.batchSystems.abstractBatchSystem.InsufficientSystemResources: The job LastzRepeatMaskJob is requesting [{'count': 1, 'kind': 'gpu', 'api': 'cuda', 'brand': 'nvidia'}] accelerators, more than the maximum of [] accelerators that SingleMachineBatchSystem was configured with. The accelerator {'count': 1, 'kind': 'gpu', 'api': 'cuda', 'brand': 'nvidia'} could not be provided. Scale is set to 1.0.
```

and when just using `--gpu`:
```
Traceback (most recent call last):
  File "/home/cactus/cactus_env/bin/cactus", line 8, in <module>
    sys.exit(main())
  File "/home/cactus/cactus_env/lib/python3.8/site-packages/cactus/progressive/cactus_progressive.py", line 372, in main
    config_wrapper.initGPU(options)
  File "/home/cactus/cactus_env/lib/python3.8/site-packages/cactus/shared/configWrapper.py", line 274, in initGPU
    lastz_gpu = get_gpu_count()
  File "/home/cactus/cactus_env/lib/python3.8/site-packages/cactus/shared/configWrapper.py", line 261, in get_gpu_count
    raise RuntimeError('Unable to automatically determine number of GPUs: Please set with --gpu N')
RuntimeError: Unable to automatically determine number of GPUs: Please set with --gpu N
```

Is there a workaround ?

Best,
Matthieu

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-1259)
┆Issue Number: TOIL-1259

**Comment by muffato** [comment]
Not an issue, I had forgotten to add the `--nv` flag to my singularity command
