### ISSUE TITLE
ToilMetrics object has no attirbute 'nodeExporterProc'

### ISSUE THREAD

**Issue by larryns** [DataBiosphere/toil#4326]
I ran cactus on a toil leader node with the following command:
```
cactus --nodeTypes m6a.4xlarge,m6a.2xlarge,m5.4xlarge --minNodes 0,0,0 --maxNodes 4,8,4 --consCores 4 --provisioner aws --batchSystem mesos --metrics aws:us-east-1:cactus-examples-1  evolverMammals.txt output.hal
```

At the end (I think it was the end), I got this error:

```
2023-01-24T02:17:39+0000] [MainThread] [I] [toil.realtimeLogger] Stopping real-time logging server.
[2023-01-24T02:17:39+0000] [MainThread] [I] [toil.realtimeLogger] Joining real-time logging server thread.
Traceback (most recent call last):
  File "/venv/bin/cactus", line 8, in <module>
    sys.exit(main())
  File "/venv/lib/python3.9/site-packages/cactus/progressive/cactus_progressive.py", line 400, in main
    hal_id = toil.start(Job.wrapJobFn(progressive_workflow, options, config_node, mc_tree, og_map, input_seq_id_map))
  File "/usr/local/lib/python3.9/dist-packages/toil/common.py", line 1017, in start
    return self._runMainLoop(rootJobDescription)
  File "/usr/local/lib/python3.9/dist-packages/toil/common.py", line 1456, in _runMainLoop
    return Leader(config=self.config,
  File "/usr/local/lib/python3.9/dist-packages/toil/leader.py", line 308, in run
    self.toilMetrics.shutdown()
  File "/usr/local/lib/python3.9/dist-packages/toil/common.py", line 1666, in shutdown
    if self.nodeExporterProc:
AttributeError: 'ToilMetrics' object has no attribute 'nodeExporterProc'
```

Any idea how I can fix this?  Btw, if I remove the --metrics option I don't get the error.

Thanks very much.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-1267)
┆Issue Number: TOIL-1267

**Comment by adamnovak** [comment]
It looks like at metrics startup we only set `nodeExporterProc` to anything at all, even None, if `--provisioner` isn't passed. Then at shutdown we check if it is None or not to tear it down, but if it is completely unset we will crash like this.

So we need to set it to None if the provisioner is in use (and the provisioning logic is responsible for managing that container). Otherwise we will always crash when you use `--metrics` and `--provisioner` together.
