### ISSUE TITLE
`toil` command can't run when installed with just the `htcondor` extra

### ISSUE THREAD

**Issue by adamnovak** [DataBiosphere/toil#4327]
@amizeranschi ran these commands:

```
docker run -v $(pwd):/data --rm -it quay.io/comparative-genomics-toolkit/cactus:v2.3.1

git clone https://github.com/DataBiosphere/toil.git
cd toil
pip install virtualenv
virtualenv venv
. venv/bin/activate
apt update && apt install build-essential -y
make prepare
make develop extras=[htcondor]
```

This produces:

```
(venv) root@4f5b13a918d5:/data/toil# which toil
/data/toil/venv/bin/toil
(venv) root@4f5b13a918d5:/data/toil# 
(venv) root@4f5b13a918d5:/data/toil# 
(venv) root@4f5b13a918d5:/data/toil# toil
Traceback (most recent call last):
  File "/data/toil/venv/bin/toil", line 33, in <module>
    sys.exit(load_entry_point('toil', 'console_scripts', 'toil')())
  File "/data/toil/src/toil/utils/toilMain.py", line 14, in main
    modules = loadModules()
  File "/data/toil/src/toil/utils/toilMain.py", line 54, in loadModules
    from toil.utils import toilLaunchCluster  # noqa
  File "/data/toil/src/toil/utils/toilLaunchCluster.py", line 22, in <module>
    from toil.lib.aws.utils import build_tag_dict_from_env
  File "/data/toil/src/toil/lib/aws/utils.py", line 34, in <module>
    from toil.lib.aws import session
  File "/data/toil/src/toil/lib/aws/session.py", line 35, in <module>
    import boto3
ModuleNotFoundError: No module named 'boto3'
```

_Originally posted by @amizeranschi in https://github.com/DataBiosphere/toil/issues/4315#issuecomment-1402204021_

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-1268)
┆Issue Number: TOIL-1268

**Comment by adamnovak** [comment]
@Hexotical fixed this in 92570421d671a94a5dfcb8c751aacefc63ff5b56 by moving the `build_tag_dict_from_env` function somewhere that doesn't need boto3 to import cleanly.

I think this ends up being a duplicate of #4314.
