### ISSUE TITLE
toil launch-cluster doesn't work, presumably due to missing AMI

### ISSUE THREAD

**Issue by glennhickey** [DataBiosphere/toil#4390]
I think any `toil launch-cluster` command can be used to reproduce
```
[2023-02-22T16:32:30-0500] [MainThread] [D] [toil.lib.aws.ami] No AMI found in TOIL_AWS_AMI; checking Flatcar release feed (try 1)
[2023-02-22T16:32:31-0500] [MainThread] [W] [toil.lib.retry] Error in <function official_flatcar_ami_release at 0x7f059b61c160>: HTTP Error 404: Not Found. Retrying after 1 s...
[2023-02-22T16:32:32-0500] [MainThread] [W] [toil.lib.retry] Error in <function official_flatcar_ami_release at 0x7f059b61c160>: HTTP Error 404: Not Found. Retrying after 1 s...
[2023-02-22T16:32:34-0500] [MainThread] [W] [toil.lib.retry] Error in <function official_flatcar_ami_release at 0x7f059b61c160>: HTTP Error 404: Not Found. Retrying after 2 s...
[2023-02-22T16:32:37-0500] [MainThread] [W] [toil.lib.retry] Error in <function official_flatcar_ami_release at 0x7f059b61c160>: HTTP Error 404: Not Found. Retrying after 4 s...
[2023-02-22T16:32:41-0500] [MainThread] [W] [toil.lib.retry] Error in <function official_flatcar_ami_release at 0x7f059b61c160>: HTTP Error 404: Not Found. Retrying after 8 s...
[2023-02-22T16:32:50-0500] [MainThread] [W] [toil.lib.retry] Error in <function official_flatcar_ami_release at 0x7f059b61c160>: HTTP Error 404: Not Found. Retrying after 16 s...
Traceback (most recent call last):
  File "/home/hickey/dev/cactus/venv-592/bin/toil", line 8, in <module>
    sys.exit(main())
  File "/home/hickey/dev/cactus/venv-592/lib/python3.10/site-packages/toil/utils/toilMain.py", line 32, in main
    get_or_die(module, 'main')()
  File "/home/hickey/dev/cactus/venv-592/lib/python3.10/site-packages/toil/utils/toilLaunchCluster.py", line 172, in main
    cluster.launchCluster(leaderNodeType=options.leaderNodeType,
  File "/home/hickey/dev/cactus/venv-592/lib/python3.10/site-packages/toil/provisioners/aws/awsProvisioner.py", line 381, in launchCluster
    image_id=self._discoverAMI(),
  File "/home/hickey/dev/cactus/venv-592/lib/python3.10/site-packages/toil/provisioners/aws/awsProvisioner.py", line 917, in _discoverAMI
    return get_flatcar_ami(self.aws.client(self._region, 'ec2'), self._architecture)
  File "/home/hickey/dev/cactus/venv-592/lib/python3.10/site-packages/toil/lib/aws/ami.py", line 42, in get_flatcar_ami
    ami = official_flatcar_ami_release(ec2_client=ec2_client, architecture=architecture)
  File "/home/hickey/dev/cactus/venv-592/lib/python3.10/site-packages/toil/lib/retry.py", line 292, in call
    return func(*args, **kwargs)
  File "/home/hickey/dev/cactus/venv-592/lib/python3.10/site-packages/toil/lib/aws/ami.py", line 69, in official_flatcar_ami_release
    feed = json.loads(urllib.request.urlopen(JSON_FEED_URL).read())
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-1295)
┆Issue Number: TOIL-1295

**Comment by adamnovak** [comment]
I tacked a workaround for this onto #4350; the upstream issue is that Flatcar's release feed JSON files, which tell us the AMIs to use on AWS, are mysteriously gone (https://github.com/flatcar/Flatcar/issues/962).

The workaround is to set TOIL_AWS_AMI to something, but without the feeds it is hard to know what to use unless you upload Flatcar yourself, and it is region-dependent.

The Flatcar Beta channel still has its feed: https://beta.release.flatcar-linux.net/amd64-usr/current/flatcar_production_ami_all.json

That only exists in `us-west-2` for `amd64`, but if you are working there you can use `ami-038346de5c451d0c2` as of today.

**Comment by adamnovak** [comment]
@DailyDreaming Should we leave this open until we can do something about this for release Toil? Or until we can get Flatcar to restart the feed?

**Comment by adamnovak** [comment]
It looks like the Flatcar folks restored the feed files for `stable` (and might recommend `lts` as our channel instead?) so thai *should* work again with released Toil versions.

I am going to close this as done.
