### ISSUE TITLE
AWSJobStoreTest.testSharedFiles can't pass anymore because Amazon turned off public access and ACL support on new buckets

### ISSUE THREAD

**Issue by adamnovak** [DataBiosphere/toil#4442]
It has been [observed](https://ucsc-ci.com/databiosphere/toil/-/jobs/39488) to fail thusly:

```
_______________________ AWSJobStoreTest.testSharedFiles ________________________
[gw2] linux -- Python 3.9.15 /builds/databiosphere/toil/venv/bin/python
Traceback (most recent call last):
  File "/builds/databiosphere/toil/src/toil/test/jobStores/jobStoreTest.py", line 374, in testSharedFiles
    self.assertUrl(jobstore1.get_shared_public_url('nonEncrypted'))
  File "/builds/databiosphere/toil/src/toil/jobStores/aws/jobStore.py", line 660, in get_shared_public_url
    return self.get_public_url(self._shared_file_id(shared_file_name))
  File "/builds/databiosphere/toil/src/toil/lib/retry.py", line 292, in call
    return func(*args, **kwargs)
  File "/builds/databiosphere/toil/src/toil/jobStores/aws/jobStore.py", line 634, in get_public_url
    self.filesBucket.Object(compat_bytes(jobStoreFileID)).Acl().put(ACL='public-read')
  File "/builds/databiosphere/toil/venv/lib/python3.9/site-packages/boto3/resources/factory.py", line 580, in do_action
    response = action(self, *args, **kwargs)
  File "/builds/databiosphere/toil/venv/lib/python3.9/site-packages/boto3/resources/action.py", line 88, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/builds/databiosphere/toil/venv/lib/python3.9/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/builds/databiosphere/toil/venv/lib/python3.9/site-packages/botocore/client.py", line 960, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the PutObjectAcl operation: Access Denied
```

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-1323)
┆Issue Number: TOIL-1323

**Comment by adamnovak** [comment]
This is #4235 back again to haunt us I think?

**Comment by adamnovak** [comment]
No, it looks like this is a new problem, caused by https://aws.amazon.com/about-aws/whats-new/2022/12/amazon-s3-automatically-enable-block-public-access-disable-access-control-lists-buckets-april-2023/

Amazon now turns on the disable-public-access feature for new buckets, and also sets them to not use ACLs anymore (like the ACLs we use to mark files public so we can get public links to them) and instead wants you to use IAM policies.

We're almost certainly not going to revise the AWS job store logic to write custom policies that open access to particular objects. I think we need to add code to make the AWS API calls to restore the old behavior here. That is probably:

https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3/client/delete_public_access_block.html#S3.Client.delete_public_access_block

https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3/client/put_bucket_ownership_controls.html
