### ISSUE TITLE
CachingFileStoreTestWithFileJobStore.testExtremeCacheSetup test is flaky

### ISSUE THREAD

**Issue by adamnovak** [DataBiosphere/toil#4443]
The "extreme" cache setup [can sometimes be too extreme and time out](https://ucsc-ci.com/databiosphere/toil/-/jobs/39498).

```
__________ CachingFileStoreTestWithFileJobStore.testExtremeCacheSetup __________
[gw5] linux -- Python 3.10.8 /builds/databiosphere/toil/venv/bin/python
Traceback (most recent call last):
  File "/builds/databiosphere/toil/src/toil/test/src/fileStoreTest.py", line 419, in testExtremeCacheSetup
    Job.Runner.startToil(E, self.options)
  File "/builds/databiosphere/toil/src/toil/job.py", line 2119, in startToil
    return toil.start(job)
  File "/builds/databiosphere/toil/src/toil/common.py", line 1044, in start
    return self._runMainLoop(rootJobDescription)
  File "/builds/databiosphere/toil/src/toil/common.py", line 1480, in _runMainLoop
    with RealtimeLogger(self._batchSystem,
  File "/builds/databiosphere/toil/src/toil/realtimeLogger.py", line 240, in __exit__
    RealtimeLogger._stopLeader()
  File "/builds/databiosphere/toil/src/toil/realtimeLogger.py", line 176, in _stopLeader
    cls.loggingServer.shutdown()
  File "/usr/lib/python3.10/socketserver.py", line 252, in shutdown
    self.__is_shut_down.wait()
  File "/usr/lib/python3.10/threading.py", line 607, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.10/threading.py", line 320, in wait
    waiter.acquire()
  File "/builds/databiosphere/toil/venv/lib/python3.10/site-packages/pytest_timeout.py", line 241, in handler
    timeout_sigalrm(item, settings.timeout)
  File "/builds/databiosphere/toil/venv/lib/python3.10/site-packages/pytest_timeout.py", line 409, in timeout_sigalrm
    pytest.fail("Timeout >%ss" % timeout)
  File "/builds/databiosphere/toil/venv/lib/python3.10/site-packages/_pytest/outcomes.py", line 198, in fail
    raise Failed(msg=reason, pytrace=pytrace)
Failed: Timeout >1000.0s
```

**Comment by adamnovak** [comment]
This is #3886 again but it is back, I guess?
