### ISSUE TITLE
Toil 5.9.2, CWLTool, TypeError inheriting from compiled class (conda install)

### ISSUE THREAD

**Issue by douglowe** [DataBiosphere/toil#4470]
I get the following error when I try to run Toil 5.9.2:
```
Traceback (most recent call last):
  File "/work/n02/n02/lowe/miniconda3/envs/toil5.9.2/bin/toil-cwl-runner", line 10, in <module>
    sys.exit(main())
  File "/work/n02/n02/lowe/miniconda3/envs/toil5.9.2/lib/python3.10/site-packages/toil/cwl/cwltoil.py", line 3651, in main
    tool = cwltool.load_tool.make_tool(uri, loading_context)
  File "cwltool/load_tool.py", line 620, in make_tool
  File "/work/n02/n02/lowe/miniconda3/envs/toil5.9.2/lib/python3.10/site-packages/toil/cwl/cwltoil.py", line 989, in toil_make_tool
    return ToilCommandLineTool(toolpath_object, loadingContext)
TypeError: interpreted classes cannot inherit from compiled
```

Unfortunately it's not clear to me if this is a CWL issue, or a Toil issue.

My conda environment is:
```
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
addict                    2.4.0              pyhd8ed1ab_2    conda-forge
aiohttp                   3.7.4.post0     py310h6acc77f_1    conda-forge
apache-libcloud           2.8.1                      py_0    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
argcomplete               3.0.8              pyhd8ed1ab_0    conda-forge
asn1crypto                1.5.1              pyhd8ed1ab_0    conda-forge
async-timeout             3.0.1                   py_1000    conda-forge
atk-1.0                   2.38.0               hd4edc92_1    conda-forge
attrs                     22.2.0             pyh71513ae_0    conda-forge
backports                 1.0                pyhd8ed1ab_3    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
bagit                     1.8.1              pyhd8ed1ab_0    conda-forge
black                     22.12.0         py310hff52083_0    conda-forge
bleach                    6.0.0              pyhd8ed1ab_0    conda-forge
blessed                   1.19.1          py310hff52083_1    conda-forge
blinker                   1.6.2              pyhd8ed1ab_0    conda-forge
boltons                   23.0.0             pyhd8ed1ab_0    conda-forge
boost                     1.78.0          py310hc4a4660_4    conda-forge
boost-cpp                 1.78.0               h5adbc97_2    conda-forge
brotlipy                  0.7.0           py310h5764c6d_1005    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2022.12.7            ha878542_0    conda-forge
cachecontrol              0.12.11            pyhd8ed1ab_1    conda-forge
cachetools                5.3.0              pyhd8ed1ab_0    conda-forge
cairo                     1.16.0            ha61ee94_1014    conda-forge
certifi                   2022.12.7          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1          py310h255011f_3    conda-forge
chardet                   4.0.0           py310hff52083_3    conda-forge
charset-normalizer        3.1.0              pyhd8ed1ab_0    conda-forge
cheetah3                  3.2.6.post2     py310h5764c6d_3    conda-forge
click                     8.1.3           py310hff52083_1    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
coloredlogs               15.0.1          py310hff52083_2    conda-forge
conda                     23.1.0          py310hff52083_0    conda-forge
conda-package-handling    2.0.2              pyh38be061_0    conda-forge
conda-package-streaming   0.7.0              pyhd8ed1ab_1    conda-forge
cryptography              40.0.2          py310h34c0648_0    conda-forge
cwl-upgrader              1.2.6              pyhd8ed1ab_0    conda-forge
cwl-utils                 0.25               pyhc268e32_0    conda-forge
cwlformat                 2022.02.18         pyhd8ed1ab_0    conda-forge
cwltool                   3.1.20221201130942 py310hb099472_1    conda-forge
dill                      0.3.6              pyhd8ed1ab_1    conda-forge
docker-py                 5.0.3           py310hff52083_2    conda-forge
docker-pycreds            0.4.0                      py_0    conda-forge
docutils                  0.19            py310hff52083_1    conda-forge
enlighten                 1.11.2             pyhd8ed1ab_0    conda-forge
expat                     2.5.0                hcb278e6_1    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.2               h14ed4e7_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
freetype                  2.12.1               hca18f0e_1    conda-forge
fribidi                   1.0.10               h36c2ea0_0    conda-forge
future                    0.18.3             pyhd8ed1ab_0    conda-forge
galaxy-containers         22.1.1             pyhd8ed1ab_0    conda-forge
galaxy-tool-util          22.1.5             pyhd8ed1ab_0    conda-forge
galaxy-util               22.1.2             pyhd8ed1ab_0    conda-forge
gdk-pixbuf                2.42.10              h05c8ddd_0    conda-forge
gettext                   0.21.1               h27087fc_0    conda-forge
giflib                    5.2.1                h0b41bf4_3    conda-forge
google-api-core           2.11.0             pyhd8ed1ab_0    conda-forge
google-auth               2.17.3             pyh1a96a4e_0    conda-forge
google-cloud-core         2.3.2              pyhd8ed1ab_0    conda-forge
google-cloud-storage      1.43.0             pyh6c4a22f_0    conda-forge
google-crc32c             1.1.2           py310he8fe98e_4    conda-forge
google-resumable-media    2.5.0              pyhd8ed1ab_0    conda-forge
googleapis-common-protos  1.57.1             pyhd8ed1ab_0    conda-forge
graphite2                 1.3.13            h58526e2_1001    conda-forge
graphviz                  2.50.0               h5abf519_3    conda-forge
grpcio                    1.54.1          py310heca2aa9_0    conda-forge
gsoap                     2.8.123              h8dc497d_0    conda-forge
gtk2                      2.24.33              h90689f9_2    conda-forge
gts                       0.7.6                h64030ff_2    conda-forge
harfbuzz                  6.0.0                h8e241bc_0    conda-forge
htcondor-classads         10.3.1               hcefb720_0    conda-forge
html5lib                  1.1                pyh9f0ad1d_0    conda-forge
humanfriendly             10.0            py310hff52083_4    conda-forge
icu                       70.1                 h27087fc_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
importlib-metadata        6.6.0              pyha770c72_0    conda-forge
importlib_resources       5.12.0             pyhd8ed1ab_0    conda-forge
isodate                   0.6.1              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   h0b41bf4_3    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.20.1               h81ceb04_0    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libabseil                 20230125.0      cxx17_hcb278e6_1    conda-forge
libblas                   3.9.0           16_linux64_openblas    conda-forge
libcblas                  3.9.0           16_linux64_openblas    conda-forge
libcondor_utils           10.3.1               hb879ae7_0    conda-forge
libcrc32c                 1.1.2                h9c3ff4c_0    conda-forge
libcurl                   8.0.1                h588be90_0    conda-forge
libdeflate                1.17                 h0b41bf4_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libexpat                  2.5.0                hcb278e6_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.2.0              h65d4601_19    conda-forge
libgd                     2.3.3                h5aea950_4    conda-forge
libgfortran-ng            12.2.0              h69a702a_19    conda-forge
libgfortran5              12.2.0              h337968e_19    conda-forge
libglib                   2.76.2               hebfc3b9_0    conda-forge
libgomp                   12.2.0              h65d4601_19    conda-forge
libgrpc                   1.54.1               hcf146ea_0    conda-forge
libiconv                  1.17                 h166bdaf_0    conda-forge
liblapack                 3.9.0           16_linux64_openblas    conda-forge
libnghttp2                1.52.0               h61bc06f_0    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libopenblas               0.3.21          pthreads_h78a6416_3    conda-forge
libpng                    1.6.39               h753d276_0    conda-forge
libprotobuf               3.21.12              h3eb15da_0    conda-forge
librsvg                   2.54.4               h7abd40a_0    conda-forge
libsodium                 1.0.18               h36c2ea0_1    conda-forge
libsqlite                 3.40.0               h753d276_1    conda-forge
libssh2                   1.10.0               hf14f497_3    conda-forge
libstdcxx-ng              12.2.0              h46fd767_19    conda-forge
libtiff                   4.5.0                h6adf6a1_2    conda-forge
libtool                   2.4.7                h27087fc_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libuv                     1.44.2               h166bdaf_0    conda-forge
libwebp                   1.2.4                h1daa5a0_1    conda-forge
libwebp-base              1.2.4                h166bdaf_0    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libxml2                   2.10.3               hca2bb57_4    conda-forge
libxslt                   1.1.37               h873f0b0_0    conda-forge
libzlib                   1.2.13               h166bdaf_4    conda-forge
lockfile                  0.12.2                     py_1    conda-forge
lxml                      4.9.2           py310hbdc0903_0    conda-forge
mistune                   2.0.5              pyhd8ed1ab_0    conda-forge
msgpack-python            1.0.5           py310hdf3cbec_0    conda-forge
multidict                 6.0.4           py310h1fa729e_0    conda-forge
munge                     0.5.13               h1c5bbd1_1    conda-forge
mypy_extensions           1.0.0              pyha770c72_0    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
networkx                  2.8.4              pyhd8ed1ab_0    conda-forge
nodejs                    18.15.0              h8d033a5_0    conda-forge
numpy                     1.24.3          py310ha4c1d20_0    conda-forge
oauthlib                  3.2.2              pyhd8ed1ab_0    conda-forge
openssl                   3.1.0                hd590300_3    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pango                     1.50.14              hd33c08f_0    conda-forge
pathspec                  0.11.1             pyhd8ed1ab_0    conda-forge
pcre2                     10.40                hc3806b6_0    conda-forge
pip                       23.1.2             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h36c2ea0_0    conda-forge
platformdirs              3.5.0              pyhd8ed1ab_0    conda-forge
pluggy                    1.0.0           py310hff52083_4    conda-forge
prefixed                  0.7.0              pyhd8ed1ab_0    conda-forge
protobuf                  4.21.12         py310heca2aa9_0    conda-forge
prov                      1.5.1                      py_1    conda-forge
psutil                    5.9.5           py310h1fa729e_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pyasn1                    0.4.8                      py_0    conda-forge
pyasn1-modules            0.2.7                      py_0    conda-forge
pycosat                   0.6.4           py310h5764c6d_1    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pydantic                  1.10.7          py310h1fa729e_0    conda-forge
pydot                     1.4.2           py310hff52083_3    conda-forge
pydotplus                 2.0.2              pyhaef67bd_5    conda-forge
pyjwt                     2.6.0              pyhd8ed1ab_0    conda-forge
pynacl                    1.5.0           py310h5764c6d_2    conda-forge
pyopenssl                 23.1.1             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pypubsub                  4.0.3                      py_0    conda-forge
pysocks                   1.7.1           py310hff52083_5    conda-forge
python                    3.10.10         he550d4f_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-htcondor           10.3.1          py310h44c86e6_0    conda-forge
python-kubernetes         21.7.0             pyhd8ed1ab_0    conda-forge
python_abi                3.10                    3_cp310    conda-forge
pytz                      2023.3             pyhd8ed1ab_0    conda-forge
pyu2f                     0.1.5              pyhd8ed1ab_0    conda-forge
pyyaml                    6.0             py310h5764c6d_5    conda-forge
rdflib                    6.2.0              pyhd8ed1ab_0    conda-forge
re2                       2023.02.02           hcb278e6_0    conda-forge
readline                  8.2                  h8228510_1    conda-forge
repoze.lru                0.7                        py_0    conda-forge
requests                  2.29.0             pyhd8ed1ab_0    conda-forge
requests-oauthlib         1.3.1              pyhd8ed1ab_0    conda-forge
routes                    2.5.1              pyhd8ed1ab_0    conda-forge
rsa                       4.9                pyhd8ed1ab_0    conda-forge
ruamel.yaml               0.17.21         py310h1fa729e_3    conda-forge
ruamel.yaml.clib          0.2.7           py310h1fa729e_1    conda-forge
schema-salad              8.4.20230426093816 py310h2372a71_0    conda-forge
scitokens-cpp             0.7.1                hf3971a6_0    conda-forge
setuptools                67.7.2             pyhd8ed1ab_0    conda-forge
shellescape               3.4.1                      py_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
sqlite                    3.40.0               h4ff8645_1    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
toil                      5.9.2              pyhdfd78af_0    bioconda
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
tqdm                      4.65.0             pyhd8ed1ab_1    conda-forge
typing-extensions         4.5.0                hd8ed1ab_0    conda-forge
typing_extensions         4.5.0              pyha770c72_0    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
urllib3                   1.26.15            pyhd8ed1ab_0    conda-forge
voms                      2.1.0rc3             h25bd2b9_0    conda-forge
wcwidth                   0.2.6              pyhd8ed1ab_0    conda-forge
webencodings              0.5.1                      py_1    conda-forge
websocket-client          1.5.1              pyhd8ed1ab_0    conda-forge
wheel                     0.40.0             pyhd8ed1ab_0    conda-forge
whoosh                    2.7.4           py310hff52083_7    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.0.10               h7f98852_0    conda-forge
xorg-libsm                1.2.3             hd9c2040_1000    conda-forge
xorg-libx11               1.8.4                h0b41bf4_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h0b41bf4_2    conda-forge
xorg-libxrender           0.9.10            h7f98852_1003    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h0b41bf4_1003    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
yarl                      1.9.1           py310h2372a71_0    conda-forge
zipp                      3.15.0             pyhd8ed1ab_0    conda-forge
zipstream-new             1.1.8              pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               h166bdaf_4    conda-forge
zstandard                 0.19.0          py310hdeb6495_1    conda-forge
zstd                      1.5.2                h3eb15da_6    conda-forge
```

**Comment by douglowe** [comment]
I should add, I don't get this error when I run the same workflow using Toil 5.7.1 (also installed using conda).

**Comment by douglowe** [comment]
I should add, I don't get this error when I run the same workflow using Toil 5.7.1 (also installed using conda).

**Comment by mr-c** [comment]
This was fixed in cwltool 3.1.20230302145532 https://github.com/common-workflow-language/cwltool/releases/tag/3.1.20230302145532
Alas Toil 5.9.2 requires cwltool 3.1.20221201130942

Perhaps @DailyDreaming or @adamnovak will make a new Toil release soon?

**Comment by DailyDreaming** [comment]
@mr-c Capital idea.
