### ISSUE TITLE
Passing File arguments in an expression placeholder results in toil-wdl-runner failing to import those files

### ISSUE THREAD

**Issue by stxue1** [DataBiosphere/toil#4514]
I previously thought this was something with how Toil converts strings into paths, but it looks like that functionality is good and that the cause of this error is something else.

When calling a WDL function that takes a File as an argument, putting the function call in an expression placeholder will result in an AssertionError that the file is not a local file. It looks like it happens on any function that takes a File as an argument, and passing a String normally works.

This occurs both when the file is defined inside the workflow and when the file is defined in the JSON input.

```wdl
workflow wf {
  input {}
  call t {
  }
}

task t {
  input {}
  File f = "/home/heaucques/Documents/toil-examples/test.wdl" # any file, error also happens if f is defined from the json
  command {
    echo ${size(f)} > output.txt
  }
}
```
```
[2023-06-28T15:25:08-0700] [MainThread] [E] [toil.wdl.wdltoil] Expression evaluation failed for command: 
	    echo ~{size(f)} > output.txt
	  
	Traceback (most recent call last):
	  File "/home/heaucques/Documents/toil/venv/lib/python3.10/site-packages/WDL/Expr.py", line 123, in eval
	    ans = self._eval(env, stdlib)
	  File "/home/heaucques/Documents/toil/venv/lib/python3.10/site-packages/WDL/Expr.py", line 1140, in _eval
	    return f(self, env, stdlib)
	  File "/home/heaucques/Documents/toil/venv/lib/python3.10/site-packages/WDL/StdLib.py", line 232, in __call__
	    return self._call_eager(expr, [arg.eval(env, stdlib=stdlib) for arg in expr.arguments])
	  File "/home/heaucques/Documents/toil/src/toil/wdl/wdltoil.py", line 366, in _call_eager
	    total_size += os.path.getsize(self.stdlib._devirtualize_filename(uri))
	  File "/home/heaucques/Documents/toil/src/toil/wdl/wdltoil.py", line 452, in _devirtualize_filename
	    assert os.path.exists(result), f"Virtualized file {filename} looks like a local file but isn't!"
	AssertionError: Virtualized file /mnt/miniwdl_task_container/work/_miniwdl_inputs/0/test.wdl looks like a local file but isn't!
```

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-1359)
┆Issue Number: TOIL-1359

**Comment by stxue1** [comment]
It looks like this is the result of `_devirtualize_filename` returning the wrong filepath. With tasks, the function thinks it is a local file and returns the absolute filepaths:
https://github.com/DataBiosphere/toil/blob/d686daca091849e681d2f3f3a349001ca83d2e3e/src/toil/wdl/wdltoil.py#L449
But this filepath is from within the container, so the runner cannot access it from the outside.

I think this is because the devirtualization function cannot deal with devirtualizing the container's imported files.

\
When toil-wdl-runner calls on MiniWDL to create the task container,
https://github.com/DataBiosphere/toil/blob/d686daca091849e681d2f3f3a349001ca83d2e3e/src/toil/wdl/wdltoil.py#L1212
MiniWDL maps the file inputs to the absolute filepaths as inside the container:
https://github.com/chanzuckerberg/miniwdl/blob/1bc3776e65d3069c2e890fa73aee0c5e44861e69/WDL/runtime/task_container.py#L153-L156
MiniWDL deals with this by overriding `_devirtualize_filename` for tasks specifically:
https://github.com/chanzuckerberg/miniwdl/blob/1bc3776e65d3069c2e890fa73aee0c5e44861e69/WDL/runtime/task.py#L1022-L1024
But this is overridden by toil's overarching definition of the function:
https://github.com/DataBiosphere/toil/blob/d686daca091849e681d2f3f3a349001ca83d2e3e/src/toil/wdl/wdltoil.py#L419

Imported task files also don't use Toil's URI, which could be changed to match how files are imported in workflows.
