### ISSUE TITLE
Issue with toil-mutex-toil_miniwdl_sif_cache_mutex

### ISSUE THREAD

**Issue by juklucas** [DataBiosphere/toil#4654]
When running the DeepPolisher WDL I get an error that does not seem to stem from the workflow itself.

I'm running this with Toil  5.11.0 and miniwdl 1.9.1. 

Here is the command I used:
```
mkdir toil_logs 
mkdir analysis

SINGULARITY_CACHEDIR=`pwd`/outputs/cache/.singularity/cache 
MINIWDL__SINGULARITY__IMAGE_CACHE=`pwd`/outputs/cache/.cache/miniwdl 

toil-wdl-runner \
    --jobStore ./big_store \
    --batchSystem slurm \
    --batchLogsDir ./toil_logs \
    /private/groups/hprc/scaff_test/HG01099/github/hpp_production_workflows/QC/wdl/workflows/hprc_DeepPolisher.wdl \
    HG01099_polishing_inputs.json \
    --outputDirectory analysis/polishing \
    --outputFile HG01099_polishing_outputs.json \
    --runLocalJobsOnWorkers \
    --retryCount 0 \
    --disableProgress \
    2>&1 | tee log.txt
```
And here is the log output...
```
toil.exceptions.FailedJobsException: The job store '/private/groups/hprc/scaff_test/HG01099/toil/big_store' contains 13 failed jobs: 'WDLScatterJob' scatter-L40C5-readFile kind-WDLWorkflowNodeJob/instance-f8xp6wca v4, 'WDLWorkflowNodeJob' call-extractReads kind-WDLWorkflowNodeJob/instance-h1wc8g2q v2, 'WDLWorkflowNodeJob' call-alignONTToMat kind-WDLWorkflowNodeJob/instance-16t1jrg_ v2, 'WDLWorkflowNodeJob' call-alignHifiToDiploid kind-WDLWorkflowNodeJob/instance-pgsrk_co v2, 'WDLWorkflowNodeJob' call-extractReads kind-WDLWorkflowNodeJob/instance-ptr0_hk9 v2, 'WDLCombineBindingsJob' kind-WDLCombineBindingsJob/instance-svuk5r6q v3, 'WDLWorkflowJob' kind-WDLRootJob/instance-xqrk3eai v4, 'WDLTaskJob' hprc_DeepPolisher.alignHifiToDiploid.extractReads kind-WDLTaskJob/instance-cczh3854 v3, 'WDLWorkflowNodeJob' call-extractReads kind-WDLWorkflowNodeJob/instance-fb6geiri v2, 'WDLWorkflowJob' kind-WDLWorkflowJob/instance-quq08neh v2, 'WDLTaskJob' hprc_DeepPolisher.alignHifiToDiploid.extractReads kind-WDLTaskJob/instance-gwsl6nwk v2, 'WDLCombineBindingsJob' kind-WDLCombineBindingsJob/instance-0tseqm3x v3, 'WDLWorkflowNodeJob' call-alignONTToPat kind-WDLWorkflowNodeJob/instance-7gvvjkof v2
Log from job "'WDLTaskJob' hprc_DeepPolisher.alignHifiToDiploid.extractReads kind-WDLTaskJob/instance-cczh3854 v3" follows:
=========>
        [2023-10-24T21:09:10-0700] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---
        [2023-10-24T21:09:10-0700] [MainThread] [I] [toil] Running Toil version 5.11.0-9a04dabb36d6ab13ed1ac7c711dbdc8c71724dc9 on host phoenix-08.prism.
        [2023-10-24T21:09:10-0700] [MainThread] [I] [toil.worker] Working on job 'WDLTaskJob' hprc_DeepPolisher.alignHifiToDiploid.extractReads kind-WDLTaskJob/instance-cczh3854 v1
        [2023-10-24T21:09:10-0700] [MainThread] [I] [toil.worker] Loaded body Job('WDLTaskJob' hprc_DeepPolisher.alignHifiToDiploid.extractReads kind-WDLTaskJob/instance-cczh3854 v1) from description 'WDLTaskJob' hprc_DeepPolisher.alignHifiToDiploid.extractReads kind-WDLTaskJob/instance-cczh3854 v1
        [2023-10-24T21:09:10-0700] [MainThread] [I] [toil.wdl.wdltoil] Running task extractReads (['extractReads_t', 'extractReads']) called as hprc_DeepPolisher.alignHifiToDiploid.extractReads
        [2023-10-24T21:09:10-0700] [MainThread] [I] [toil.wdl.wdltoil] Defaulting referenceFasta to None
        [2023-10-24T21:09:10-0700] [MainThread] [I] [MiniWDLContainers] no configuration file found
        [2023-10-24T21:09:10-0700] [MainThread] [N] [MiniWDLContainers] Singularity runtime initialized (BETA) :: singularity_version: "singularity-ce version 3.10.3"
        [2023-10-24T21:09:10-0700] [MainThread] [I] [MiniWDLContainers] detected host resources :: cpu: 128, mem_bytes: 2151678160896
        [2023-10-24T21:17:53-0700] [MainThread] [I] [MiniWDLContainers] Singularity SIF found in image cache directory :: sif: "/private/groups/hprc/scaff_test/HG01099/toil/outputs/cache/.cache/miniwdl/docker___mobinasri_bio_base_v0.2.sif"
        [2023-10-24T21:17:54-0700] [MainThread] [W] [toil.fileStores.abstractFileStore] Failed job accessed files:
        [2023-10-24T21:17:54-0700] [MainThread] [W] [toil.fileStores.abstractFileStore] Downloaded file 'files/no-job/file-b0b082d222be423399129ff7dc462883/HG01099.m64043_210707_032602.dc.q20.fastq.gz' to path '/data/tmp/0af5f7544b42535fb8aa818e3571d5a0/35fc/b5ff/tmplqsr4ujg/HG01099.m64043_210707_032602.dc.q20.fastq.gz'
        Traceback (most recent call last):
          File "/private/home/juklucas/.local/lib/python3.8/site-packages/toil/worker.py", line 403, in workerScript
            job._runner(jobGraph=None, jobStore=jobStore, fileStore=fileStore, defer=defer)
          File "/private/home/juklucas/.local/lib/python3.8/site-packages/toil/job.py", line 2774, in _runner
            returnValues = self._run(jobGraph=None, fileStore=fileStore)
          File "/private/home/juklucas/.local/lib/python3.8/site-packages/toil/job.py", line 2691, in _run
            return self.run(fileStore)
          File "/private/home/juklucas/.local/lib/python3.8/site-packages/toil/wdl/wdltoil.py", line 1239, in run
            task_container._pull(miniwdl_logger, cleanup)
          File "/private/home/juklucas/miniconda3/lib/python3.8/contextlib.py", line 120, in __exit__
            next(self.gen)
          File "/private/home/juklucas/.local/lib/python3.8/site-packages/toil/lib/threading.py", line 410, in global_mutex
            os.unlink(lock_filename)
        FileNotFoundError: [Errno 2] No such file or directory: '/private/groups/hprc/scaff_test/HG01099/toil/outputs/cache/.cache/miniwdl/toil-mutex-toil_miniwdl_sif_cache_mutex'
        [2023-10-24T21:17:54-0700] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host phoenix-08.prism
<=========
```

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-1435)
┆Issue Number: TOIL-1435

**Comment by adamnovak** [comment]
This might be the same issue as https://github.com/DataBiosphere/toil/issues/3867#issuecomment-956154369 where vanishing supposedly-locked files were also observed on an NFS filesystem.

**Comment by adamnovak** [comment]
@juklucas The workaround here is to move `SINGULARITY_CACHEDIR` and `MINIWDL__SINGULARITY__IMAGE_CACHE` off of NFS and to node-local storage (`/data/tmp` or similar). Then each node is going to pull its own copy of the container images, but the locking would be more likely to work properly because it would be on a local filesystem. I think if you just leave them unset Toil will also find a per-workflow (or maybe per-batch-of-simultaneous-jobs) temp location for them?
