### ISSUE TITLE
Illegal Deletion Cache Error - toil on AWS

### ISSUE THREAD

**Issue by tinaveit** [DataBiosphere/toil#4671]
Hi, 
We are performing genome alignments using Progressive Cactus software and toil on Amazon Web Services. We don't have much computational background, and are getting the following error (several times for different files):
```
[2023-11-01T18:32:07+0000] [MainThread] [W] [toil.fileStores.abstractFileStore] Downloaded file 'bf4f430c-df49-4049-96aa-0ba8aa0a4ef4' to path '/var/lib/toil/763e2024bed95368b51575f16bfd24d8/8abf/d73a/tmprvt3_8zm.tmp' (gone!)
	Traceback (most recent call last):
	  File "/usr/local/lib/python3.9/dist-packages/toil/worker.py", line 403, in workerScript
	    job._runner(jobGraph=None, jobStore=jobStore, fileStore=fileStore, defer=defer)
	  File "/usr/local/lib/python3.9/dist-packages/toil/job.py", line 2774, in _runner
	    returnValues = self._run(jobGraph=None, fileStore=fileStore)
	  File "/usr/local/lib/python3.9/dist-packages/toil/job.py", line 2691, in _run
	    return self.run(fileStore)
	  File "/usr/local/lib/python3.9/dist-packages/toil/job.py", line 2919, in run
	    rValue = userFunction(*((self,) + tuple(self.args)), **self.kwargs)
	  File "/tmp/tmphwz2n1dh/44097f2889ffca8eaa1f024272157472/cactus/paf/local_alignment.py", line 142, in merge_combined_chunks
	    job.fileStore.deleteGlobalFile(chunk)
	  File "/usr/local/lib/python3.9/dist-packages/toil/fileStores/cachingFileStore.py", line 1729, in deleteGlobalFile
	    self.deleteLocalFile(fileStoreID)
	  File "/usr/local/lib/python3.9/dist-packages/toil/fileStores/cachingFileStore.py", line 1724, in deleteLocalFile
	    raise IllegalDeletionCacheError(missingFile)
	toil.fileStores.cachingFileStore.IllegalDeletionCacheError: Cache tracked file (/var/lib/toil/763e2024bed95368b51575f16bfd24d8/8abf/d73a/tmprvt3_8zm.tmp) has been deleted or moved by user without updating cache database. Use deleteLocalFile to delete such files.
[2023-11-01T18:32:07+0000] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host (...) 
```
It doesn't crash the Cactus run, but once workflow is 100% we can't get an outputfile. We haven't deleted any files from the jobstore on AWS and have no idea what this error could be related to. Any help/ideas would be greatly appreciated! Thank you.

**Comment by adamnovak** [comment]
@glennhickey Does Cactus ever delete files it reads or writes through Toil, without using `deleteLocalFile`?

Or maybe it deletes something multiple times?

**Comment by glennhickey** [comment]
@adamnovak There does seem to be a sort of double deletion (note this line appears in the stack trace above)

https://github.com/ComparativeGenomicsToolkit/cactus/blob/master/src/cactus/paf/local_alignment.py#L141-L142

I guess I need to remove that `os.remove(chunk_path)` ? 

I just ran the latest Cactus release on AWS/MESOS (as it's been quite a while) and could not reproduce the error.

**Comment by adamnovak** [comment]
@glennhickey I think removing the `os.remove()` will fix the error. The cache expects that files it hands out aren't going to get deleted by the user on their own, because it means the user is not thinking about the cache's reference tracking.

We might still have a Toil bug here though; you asked for a mutable file, so maybe we *should* let you delete it on your own.

**Comment by tinaveit** [comment]
Thank you @glennhickey and @adamnovak ! Should I give this another go or do you still think there might be another bug here?

**Comment by tinaveit** [comment]
On a side note, we tried running with 3 species (the previous one was 8), and got this other error message: 
`No log file is present, despite job failing: 'run_lastz' 41ff109d-df4c-45eb-897b-a7c2c9eae970 v1
Due to failure we are reducing the remaining try count of job 'run_lastz' 41ff109d-df4c-45eb-897b-a7c2c9eae970 v1 with ID 41ff109d-df4c-45eb-897b-a7c2c9eae970 to 5
We have increased the default memory of the failed job 'run_lastz' 41ff109d-df4c-45eb-897b-a7c2c9eae970 v1 to 2147483648 bytes
We have increased the disk of the failed job 'run_lastz' 41ff109d-df4c-45eb-897b-a7c2c9eae970 v1 to the default of 2147483648 bytes
Issued job 'run_lastz' 41ff109d-df4c-45eb-897b-a7c2c9eae970 v2 with job batch system ID: 17361 and disk: 2.0 Gi, memory: 2.0 Gi, cores: 1, accelerators: [], preemptible: False
Job failed with exit value 255: 'run_lastz' 257e6b07-2875-4f0f-b233-166bc7d02364 v1
Exit reason: 3`

Could this be related at all?
