### ISSUE TITLE
Allow referencing body of a WDL workflow in the input

### ISSUE THREAD

**Issue by stxue1** [DataBiosphere/toil#5003]
The WDL spec mentions the input section can reference the body of the workflow:
> As with tasks, declarations can appear in the body of a workflow in any order. Expressions in workflows can reference the outputs of calls, including in input declarations.

This currently doesn't work as we compute bindings sequentially:
```
	[2024-07-01T13:06:00-0700] [MainThread] [C] [toil.worker] Worker crashed with traceback:
	Traceback (most recent call last):
	  File "/home/heaucques/Documents/toil/venv3.12/lib/python3.12/site-packages/WDL/Expr.py", line 124, in eval
	    ans = self._eval(env, stdlib)
	          ^^^^^^^^^^^^^^^^^^^^^^^
	  File "/home/heaucques/Documents/toil/venv3.12/lib/python3.12/site-packages/WDL/Expr.py", line 864, in _eval
	    return env[self.name]
	           ~~~^^^^^^^^^^^
	  File "/home/heaucques/Documents/toil/venv3.12/lib/python3.12/site-packages/WDL/Env.py", line 127, in __getitem__
	    return self.resolve(name)
	           ^^^^^^^^^^^^^^^^^^
	  File "/home/heaucques/Documents/toil/venv3.12/lib/python3.12/site-packages/WDL/Env.py", line 114, in resolve
	    return self.resolve_binding(name).value
	           ^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "/home/heaucques/Documents/toil/venv3.12/lib/python3.12/site-packages/WDL/Env.py", line 106, in resolve_binding
	    raise KeyError()
	KeyError
	
	The above exception was the direct cause of the following exception:
	
	Traceback (most recent call last):
	  File "/home/heaucques/Documents/toil/src/toil/worker.py", line 440, in workerScript
	    job._runner(jobGraph=None, jobStore=job_store, fileStore=fileStore, defer=defer)
	  File "/home/heaucques/Documents/toil/src/toil/job.py", line 2984, in _runner
	    returnValues = self._run(jobGraph=None, fileStore=fileStore)
	                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "/home/heaucques/Documents/toil/src/toil/job.py", line 2895, in _run
	    return self.run(fileStore)
	           ^^^^^^^^^^^^^^^^^^^
	  File "/home/heaucques/Documents/toil/src/toil/wdl/wdltoil.py", line 145, in decorated
	    return decoratee(*args, **kwargs)
	           ^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "/home/heaucques/Documents/toil/src/toil/wdl/wdltoil.py", line 3259, in run
	    bindings = bindings.bind(input_decl.name, evaluate_defaultable_decl(input_decl, bindings, standard_library))
	                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "/home/heaucques/Documents/toil/src/toil/wdl/wdltoil.py", line 1275, in evaluate_defaultable_decl
	    return evaluate_decl(node, environment, stdlib)
	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "/home/heaucques/Documents/toil/src/toil/wdl/wdltoil.py", line 1235, in evaluate_decl
	    return evaluate_named_expression(node, node.name, node.type, node.expr, environment, stdlib)
	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "/home/heaucques/Documents/toil/src/toil/wdl/wdltoil.py", line 1216, in evaluate_named_expression
	    value = expression.eval(environment, stdlib)
	            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "/home/heaucques/Documents/toil/venv3.12/lib/python3.12/site-packages/WDL/Expr.py", line 124, in eval
	    ans = self._eval(env, stdlib)
	          ^^^^^^^^^^^^^^^^^^^^^^^
	  File "/home/heaucques/Documents/toil/venv3.12/lib/python3.12/site-packages/WDL/Expr.py", line 1019, in _eval
	    innard_value = self.expr.eval(env, stdlib)
	                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "/home/heaucques/Documents/toil/venv3.12/lib/python3.12/site-packages/WDL/Expr.py", line 130, in eval
	    raise Error.EvalError(self, str(exn)) from exn
	WDL.Error.EvalError
	
	[2024-07-01T13:06:00-0700] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host pop-os
```

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-1608)
┆Issue Number: TOIL-1608

**Comment by adamnovak** [comment]
I think I already reported this as #4993.

**Comment by stxue1** [comment]
Closing as this is duplicated.
