### ISSUE TITLE
Caching 

### ISSUE THREAD

**Issue by adamnovak** [DataBiosphere/toil#5084]
It looks like, on the GI Slurm cluster, files are able to vanish from the cache.

I ran:
```
sbatch -c2 --mem 8G --partition long --time 7-00:00:00 --wrap "toil-wdl-runner https://raw.githubusercontent.com/vgteam/vg_wdl/9b3e4016b16d657a0a7c73e01e1b4c4410f5593e/workflows/giraffe.wdl ./inputs-training-HG002.m84005_220827_014912_s1.json --wdlOutputDirectory ./output/training/HG002.m84005_220827_014912_s1 --wdlOutputFile ./output/training/HG002.m84005_220827_014912_s1.json --logFile ./output/training/HG002.m84005_220827_014912_s1.log --writeLogs ./output/training/log-HG002.m84005_220827_014912_s1 --jobStore ./output/training/tree-HG002.m84005_220827_014912_s1 --batchSystem slurm --slurmTime 11:59:59 --disableProgress --caching=True"
```

Using the inputs file:
```
{
    "Giraffe.INPUT_READ_FILE_1": "https://storage.googleapis.com/brain-genomics/awcarroll/share/ucsc/pacbio_fastq/HG002.m84005_220827_014912_s1.fastq.gz",
    "Giraffe.SAMPLE_NAME": "HG002.m84005_220827_014912_s1",
    "Giraffe.PAIRED_READS": false,
    "Giraffe.HAPLOTYPE_SAMPLING": false,
    "Giraffe.GBZ_FILE": "/private/groups/patenlab/anovak/projects/hprc/lr-giraffe/graphs/hprc-v1.1-mc-grch38.d9.gbz",
    "Giraffe.MIN_FILE": "/private/groups/patenlab/anovak/projects/hprc/lr-giraffe/graphs/hprc-v1.1-mc-grch38.d9.k31.w50.W.withzip.min",
    "Giraffe.ZIPCODES_FILE": "/private/groups/patenlab/anovak/projects/hprc/lr-giraffe/graphs/hprc-v1.1-mc-grch38.d9.k31.w50.W.zipcodes",
    "Giraffe.DIST_FILE": "/private/groups/patenlab/anovak/projects/hprc/lr-giraffe/graphs/hprc-v1.1-mc-grch38.d9.dist",
    "Giraffe.VG_DOCKER": "quay.io/adamnovak/vg:beec239",
    "Giraffe.READS_PER_CHUNK": 150000,
    "Giraffe.GIRAFFE_PRESET": "hifi",
    "Giraffe.PRUNE_LOW_COMPLEXITY": true,
    "Giraffe.LEFTALIGN_BAM": true,
    "Giraffe.REALIGN_INDELS": false,
    "Giraffe.OUTPUT_SINGLE_BAM": true,
    "Giraffe.REFERENCE_PREFIX": "GRCh38#0#",
    "Giraffe.REFERENCE_FILE": "/private/groups/patenlab/anovak/projects/hprc/lr-giraffe/references/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna",
    "Giraffe.CONTIGS": ["GRCh38#0#chr1", "GRCh38#0#chr2", "GRCh38#0#chr3",  "GRCh38#0#chr4", "GRCh38#0#chr5", "GRCh38#0#chr6", "GRCh38#0#chr7", "GRCh38#0#chr8", "GRCh38#0#chr9", "GRCh38#0#chr10", "GRCh38#0#chr11", "GRCh38#0#chr12", "GRCh38#0#chr13", "GRCh38#0#chr14", "GRCh38#0#chr15", "GRCh38#0#chr16", "GRCh38#0#chr17", "GRCh38#0#chr18", "GRCh38#0#chr19", "GRCh38#0#chr20", "GRCh38#0#chr21", "GRCh38#0#chr22", "GRCh38#0#chrX", "GRCh38#0#chrY"]
}
```
On Toil `c8ba20fa7e95714966cbbfd002e46c26fcafcc05`.

I got errors like this in the log from some jobs:
```
Log from job "'WDLTaskJob' Giraffe.14.runVGGIRAFFEse.command kind-WDLTaskJob/instance-yeovm589 v6" follows:
=========>
	[2024-09-10T11:46:36-0700] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---
	[2024-09-10T11:46:36-0700] [MainThread] [I] [toil] Running Toil version 6.2.0a1-8281a413cc028d4d448bbba9c344d42dcf55c2b8 on host phoenix-12.prism.
	[2024-09-10T11:46:36-0700] [MainThread] [I] [toil.worker] Working on job 'WDLTaskJob' Giraffe.14.runVGGIRAFFEse.command kind-WDLTaskJob/instance-yeovm589 v4
	[2024-09-10T11:46:36-0700] [MainThread] [I] [toil.worker] Loaded body Job('WDLTaskJob' Giraffe.14.runVGGIRAFFEse.command kind-WDLTaskJob/instance-yeovm589 v4) from description 'WDLTaskJob' Giraffe.14.runVGGIRAFFEse.command kind-WDLTaskJob/instance-yeovm589 v4
	[2024-09-10T11:46:36-0700] [MainThread] [I] [toil.wdl.wdltoil] Running task command for runVGGIRAFFE (['map', 'runVGGIRAFFE']) called as Giraffe.runVGGIRAFFEse
	[2024-09-10T11:46:36-0700] [MainThread] [I] [MiniWDLContainers] no configuration file found
	[2024-09-10T11:46:36-0700] [MainThread] [N] [MiniWDLContainers] Singularity runtime initialized (BETA) :: singularity_version: "singularity-ce version 3.10.3"
	[2024-09-10T11:46:36-0700] [MainThread] [I] [MiniWDLContainers] detected host resources :: cpu: 256, mem_bytes: 2151637909504
	[2024-09-10T11:46:36-0700] [MainThread] [W] [toil.fileStores.abstractFileStore] Failed job accessed files:
	[2024-09-10T11:46:36-0700] [MainThread] [W] [toil.fileStores.abstractFileStore] Downloaded file 'files/no-job/file-f72e592d1205456e987d787ad09cfc6a/hprc-v1.1-mc-grch38.d9.k31.w50.W.zipcodes' to path '/data/tmp/toilwf-f683e8bc4898542ab64ebee26f3926d8/c935/job/Giraffe/hprc-v1.1-mc-grch38.d9.k31.w50.W.zipcodes'
	[2024-09-10T11:46:36-0700] [MainThread] [W] [toil.fileStores.abstractFileStore] Downloaded file 'files/no-job/file-71817319594f4aa99cbcd408d65a2690/hprc-v1.1-mc-grch38.d9.k31.w50.W.withzip.min' to path '/data/tmp/toilwf-f683e8bc4898542ab64ebee26f3926d8/c935/job/Giraffe/hprc-v1.1-mc-grch38.d9.k31.w50.W.withzip.min'
	[2024-09-10T11:46:36-0700] [MainThread] [W] [toil.fileStores.abstractFileStore] Downloaded file 'files/no-job/file-fe9289b731b4460f8fcaa8423e41fdf4/hprc-v1.1-mc-grch38.d9.dist' to path '/data/tmp/toilwf-f683e8bc4898542ab64ebee26f3926d8/c935/job/Giraffe/hprc-v1.1-mc-grch38.d9.dist'
	[2024-09-10T11:46:36-0700] [MainThread] [W] [toil.fileStores.abstractFileStore] Downloaded file 'files/no-job/file-099bfda4486c46da94e4ec9202d82fb3/hprc-v1.1-mc-grch38.d9.gbz' to path '/data/tmp/toilwf-f683e8bc4898542ab64ebee26f3926d8/c935/job/Giraffe/hprc-v1.1-mc-grch38.d9.gbz'
	[2024-09-10T11:46:36-0700] [MainThread] [C] [toil.worker] Worker crashed with traceback:
	Traceback (most recent call last):
	  File "/private/home/anovak/workspace/toil/src/toil/worker.py", line 439, in workerScript
	    job._runner(jobGraph=None, jobStore=job_store, fileStore=fileStore, defer=defer)
	  File "/private/home/anovak/workspace/toil/src/toil/job.py", line 3008, in _runner
	    returnValues = self._run(jobGraph=None, fileStore=fileStore)
	  File "/private/home/anovak/workspace/toil/src/toil/job.py", line 2919, in _run
	    return self.run(fileStore)
	  File "/private/home/anovak/workspace/toil/src/toil/wdl/wdltoil.py", line 150, in decorated
	    return decoratee(*args, **kwargs)
	  File "/private/home/anovak/workspace/toil/src/toil/wdl/wdltoil.py", line 2314, in run
	    bindings = devirtualize_files(bindings, standard_library)
	  File "/private/home/anovak/workspace/toil/src/toil/wdl/wdltoil.py", line 1419, in devirtualize_files
	    return map_over_files_in_bindings(environment, stdlib._devirtualize_filename)
	  File "/private/home/anovak/workspace/toil/src/toil/wdl/wdltoil.py", line 1645, in map_over_files_in_bindings
	    return map_over_typed_files_in_bindings(bindings, lambda _, x: transform(x))
	  File "/private/home/anovak/workspace/toil/src/toil/wdl/wdltoil.py", line 1635, in map_over_typed_files_in_bindings
	    return environment.map(lambda b: map_over_typed_files_in_binding(b, transform))
	  File "/private/home/anovak/workspace/toil/venv/lib/python3.10/site-packages/WDL/Env.py", line 151, in map
	    fb = f(b)
	  File "/private/home/anovak/workspace/toil/src/toil/wdl/wdltoil.py", line 1635, in <lambda>
	    return environment.map(lambda b: map_over_typed_files_in_binding(b, transform))
	  File "/private/home/anovak/workspace/toil/src/toil/wdl/wdltoil.py", line 1654, in map_over_typed_files_in_binding
	    return WDL.Env.Binding(binding.name, map_over_typed_files_in_value(binding.value, transform), binding.info)
	  File "/private/home/anovak/workspace/toil/src/toil/wdl/wdltoil.py", line 1679, in map_over_typed_files_in_value
	    new_path = transform(value.type, value.value)
	  File "/private/home/anovak/workspace/toil/src/toil/wdl/wdltoil.py", line 1645, in <lambda>
	    return map_over_typed_files_in_bindings(bindings, lambda _, x: transform(x))
	  File "/private/home/anovak/workspace/toil/src/toil/wdl/wdltoil.py", line 880, in _devirtualize_filename
	    result = self.devirtualize_to(
	  File "/private/home/anovak/workspace/toil/src/toil/wdl/wdltoil.py", line 972, in devirtualize_to
	    result = file_source.readGlobalFile(file_id, dest_path, mutable=False, symlink=True)
	  File "/private/home/anovak/workspace/toil/src/toil/fileStores/cachingFileStore.py", line 1163, in readGlobalFile
	    finalPath = self._readGlobalFileWithCache(fileStoreID, localFilePath, symlink, readerID)
	  File "/private/home/anovak/workspace/toil/src/toil/fileStores/cachingFileStore.py", line 1611, in _readGlobalFileWithCache
	    if self._createLinkFromCache(cachedPath, localFilePath, symlink):
	  File "/private/home/anovak/workspace/toil/src/toil/fileStores/cachingFileStore.py", line 1507, in _createLinkFromCache
	    assert os.path.exists(cachedPath), "Cannot create link to missing cache file %s" % cachedPath
	AssertionError: Cannot create link to missing cache file /data/tmp/toilwf-f683e8bc4898542ab64ebee26f3926d8/cache-2a428c6e-0fce-48b3-ac46-5ce532ae055a/tmp8i75v67v3c77a1488820623ed088bca6ae103da3bde63510

	[2024-09-10T11:46:36-0700] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host phoenix-12.prism
<=========
```

Something is wrong with the caching logic and files are apparently going missing from the cache while other jobs are trying to link to them.

**Comment by adamnovak** [comment]
The files for the original example case are mostly gone now, so I am testing this with:
```
cat >inputs-training-HG002.real.json <<'EOF'
{
    "Giraffe.INPUT_READ_FILE_1": "/private/groups/patenlab/anovak/projects/hprc/lr-giraffe/reads/real/hifi/HG002/HG002Revio_hg002v1.0.1_hifi_revio_pbmay24.pri.unshuffled.full.fq.gz",
    "Giraffe.SAMPLE_NAME": "HG002",
    "Giraffe.PAIRED_READS": false,
    "Giraffe.HAPLOTYPE_SAMPLING": false,
    "Giraffe.GBZ_FILE": "https://s3-us-west-2.amazonaws.com/human-pangenomics/pangenomes/freeze/release2/minigraph-cactus/v2.1/hprc-v2.1-mc-grch38/hprc-v2.1-mc-grch38.d46.gbz",
    "Giraffe.DIST_FILE": "https://s3-us-west-2.amazonaws.com/human-pangenomics/pangenomes/freeze/release2/minigraph-cactus/v2.1/hprc-v2.1-mc-grch38/hprc-v2.1-mc-grch38.d46.dist",
    "Giraffe.VG_DOCKER": "quay.io/vgteam/vg:v1.77.0",
    "Giraffe.READS_PER_CHUNK": 150000,
    "Giraffe.GIRAFFE_PRESET": "hifi",
    "Giraffe.PRUNE_LOW_COMPLEXITY": true,
    "Giraffe.LEFTALIGN_BAM": true,
    "Giraffe.REALIGN_INDELS": false,
    "Giraffe.OUTPUT_SINGLE_BAM": true,
    "Giraffe.REFERENCE_PREFIX": "GRCh38#0#",
    "Giraffe.REFERENCE_FILE": "/private/groups/patenlab/anovak/projects/hprc/lr-giraffe/references/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna",
    "Giraffe.CONTIGS": ["GRCh38#0#chr1", "GRCh38#0#chr2", "GRCh38#0#chr3",  "GRCh38#0#chr4", "GRCh38#0#chr5", "GRCh38#0#chr6", "GRCh38#0#chr7", "GRCh38#0#chr8", "GRCh38#0#chr9", "GRCh38#0#chr10", "GRCh38#0#chr11", "GRCh38#0#chr12", "GRCh38#0#chr13", "GRCh38#0#chr14", "GRCh38#0#chr15", "GRCh38#0#chr16", "GRCh38#0#chr17", "GRCh38#0#chr18", "GRCh38#0#chr19", "GRCh38#0#chr20", "GRCh38#0#chr21", "GRCh38#0#chr22", "GRCh38#0#chrX", "GRCh38#0#chrY"]
}
EOF

rm -Rf ./output/training/tree-HG002.real

toil-wdl-runner https://raw.githubusercontent.com/vgteam/vg_wdl/ab754ff79faf6dafeb93c4467c66a55664f9edde/workflows/giraffe.wdl ./inputs-training-HG002.real.json --wdlOutputDirectory ./output/training/HG002.real --wdlOutputFile ./output/training/HG002.real.json --logFile ./output/training/HG002.real.log --writeLogs ./output/training/log-HG002.real --jobStore ./output/training/tree-HG002.real --batchSystem slurm --slurmTime 11:59:59 --disableProgress --caching=True
```

**Comment by adamnovak** [comment]
I noticed I didn't have the right indexes for that run, so I tried to generate them, and in doing that I managed to replicate the vanishing cache files!

```
cat >inputs-indexing.json <<'EOF'
{
    "IndexForGiraffe.GBZ_FILE": "https://s3-us-west-2.amazonaws.com/human-pangenomics/pangenomes/freeze/release2/minigraph-cactus/v2.1/hprc-v2.1-mc-grch38/hprc-v2.1-mc-grch38.d46.gbz",
    "IndexForGiraffe.DIST_FILE": "https://s3-us-west-2.amazonaws.com/human-pangenomics/pangenomes/freeze/release2/minigraph-cactus/v2.1/hprc-v2.1-mc-grch38/hprc-v2.1-mc-grch38.d46.dist",
    "IndexForGiraffe.HAPLOTYPE_SAMPLING": false,
    "IndexForGiraffe.GIRAFFE_PRESET": "hifi",
    "IndexForGiraffe.VG_DOCKER": "quay.io/vgteam/vg:v1.77.0"
}
EOF

rm -Rf ./output/indexing-tree

toil-wdl-runner https://raw.githubusercontent.com/vgteam/vg_wdl/ab754ff79faf6dafeb93c4467c66a55664f9edde/workflows/internal/index_for_giraffe.wdl ./inputs-indexing.json --wdlOutputDirectory ./output/indexing/out --wdlOutputFile ./output/indexing.json --logFile ./output/indexing.log --writeLogs ./output/indexing/logs --jobStore ./output/indexing-tree --batchSystem slurm --slurmTime 11:59:59 --disableProgress --caching=True
```

```
[2026-09-22T12:56:58-0700] [MainThread] [E] [toil.wdl.wdltoil] WDL job failed: The job store '/private/groups/patenlab/anovak/trash/toil/output/indexing-tree' contains 6 failed jobs: 'WDLWorkflowNodeListJob' decl-minimizer_k+ kind-WDLWorkflowNodeListJob/instance-2vvk8n75 v2, 'WDLTaskJob' IndexForGiraffe.createMinimizerIndex.command kind-WDLTaskJob/instance-54ctaof4 v6, 'WDLWorkflowJob' kind-WDLStartJob/instance-rq5dzhs_ v4, 'WDLTaskWrapperJob' IndexForGiraffe.createMinimizerIndex.inputs kind-WDLWorkflowNodeJob/instance-gtjjofh4 v21, 'WDLConditionalJob' if-L62C5 kind-WDLWorkflowNodeJob/instance-ud8a5tts v5, 'WDLConditionalJob' if-L125C5 kind-WDLWorkflowNodeJob/instance-ge0gtw0t v4
Log from job "'WDLTaskJob' IndexForGiraffe.createMinimizerIndex.command kind-WDLTaskJob/instance-54ctaof4 v6" follows:
=========>
        [2026-09-22T12:56:42-0700] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---
        [2026-09-22T12:56:42-0700] [MainThread] [I] [toil] Running Toil version 9.6.0a1-c6c2b1e1c2bcbd6301ec4790967518041659a207 on host phoenix-20.prism.
        [2026-09-22T12:56:42-0700] [MainThread] [I] [toil.worker] Working on job 'WDLTaskJob' IndexForGiraffe.createMinimizerIndex.command kind-WDLTaskJob/instance-54ctaof4 v4
        [2026-09-22T12:56:42-0700] [MainThread] [I] [toil.worker] Loaded body Job('WDLTaskJob' IndexForGiraffe.createMinimizerIndex.command kind-WDLTaskJob/instance-54ctaof4 v4) from description 'WDLTaskJob' IndexForGiraffe.createMinimizerIndex.command kind-WDLTaskJob/instance-54ctaof4 v4
        [2026-09-22T12:56:42-0700] [MainThread] [I] [toil.wdl.wdltoil] Running task command for createMinimizerIndex (['index', 'createMinimizerIndex']) called as IndexForGiraffe.createMinimizerIndex
        [2026-09-22T12:56:42-0700] [MainThread] [I] [MiniWDL] no configuration file found
        [2026-09-22T12:56:42-0700] [MainThread] [N] [MiniWDL] Singularity runtime initialized (BETA) :: singularity_version: "singularity-ce version 3.10.3"
        [2026-09-22T12:56:42-0700] [MainThread] [I] [MiniWDL] detected host resources :: cpu: 256, mem_bytes: 2151638466560
        [2026-09-22T12:56:42-0700] [MainThread] [C] [toil.fileStores.cachingFileStore] Cannot create link to missing cache file /data/tmp/toilwf-903d6543f2695175ba2793e43828cc50/cache-14008451-eab7-4019-8226-4510ae582590/tmpqpo4n51k41985016e994397aa70be7b24c4e644ab03c35f2
        [2026-09-22T12:56:42-0700] [MainThread] [C] [toil.fileStores.cachingFileStore] File row: ('files-flat/file-65dcb0be59974f21aaf123ec448bfd1e/stream', '/data/tmp/toilwf-903d6543f2695175ba2793e43828cc50/cache-14008451-eab7-4019-8226-4510ae582590/tmpqpo4n51k41985016e994397aa70be7b24c4e644ab03c35f2', 3122730128, 'cached', None)
        [2026-09-22T12:56:42-0700] [MainThread] [C] [toil.fileStores.cachingFileStore] Our ref row: ('/data/tmp/toilwf-903d6543f2695175ba2793e43828cc50/3351/job/@url/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fhuman-pangenomics%2Fpangenomes%2Ffreeze%2Frelease2%2Fminigraph-cactus%2Fv2.1%2Fhprc-v2.1-mc-grch38%2F/hprc-v2.1-mc-grch38.d46.dist', 'files-flat/file-65dcb0be59974f21aaf123ec448bfd1e/stream', 'kind-WDLTaskJob/instance-54ctaof4', 'immutable')
        [2026-09-22T12:56:42-0700] [MainThread] [C] [toil.fileStores.cachingFileStore] Cache ref row: ('/data/tmp/toilwf-903d6543f2695175ba2793e43828cc50/3351/job/@url/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fhuman-pangenomics%2Fpangenomes%2Ffreeze%2Frelease2%2Fminigraph-cactus%2Fv2.1%2Fhprc-v2.1-mc-grch38%2F/hprc-v2.1-mc-grch38.d46.dist', 'files-flat/file-65dcb0be59974f21aaf123ec448bfd1e/stream', 'kind-WDLTaskJob/instance-54ctaof4', 'immutable')
        [2026-09-22T12:56:42-0700] [MainThread] [C] [toil.worker] Worker crashed with traceback:
        Traceback (most recent call last):
          File "/private/home/anovak1/workspace/toil/src/toil/worker.py", line 619, in workerScript
            job._runner(
          File "/private/home/anovak1/workspace/toil/src/toil/job.py", line 3450, in _runner
            returnValues = self._run(jobGraph=None, fileStore=fileStore)
          File "/private/home/anovak1/workspace/toil/src/toil/job.py", line 3300, in _run
            return self.run(fileStore)
          File "/private/home/anovak1/workspace/toil/src/toil/wdl/wdltoil.py", line 341, in decorated
            return decoratee(*args, **kwargs)
          File "/private/home/anovak1/workspace/toil/src/toil/wdl/wdltoil.py", line 4147, in run
            bindings = devirtualize_inodes(bindings, standard_library)
          File "/private/home/anovak1/workspace/toil/src/toil/wdl/wdltoil.py", line 2915, in devirtualize_inodes
            return map_over_inodes_in_bindings(environment, stdlib._devirtualize_file)
          File "/private/home/anovak1/workspace/toil/src/toil/wdl/wdltoil.py", line 3212, in map_over_inodes_in_bindings
            return environment.map(lambda b: map_over_inodes_in_binding(b, transform))
          File "/private/home/anovak1/workspace/toil/venv/lib/python3.10/site-packages/WDL/Env.py", line 151, in map
            fb = f(b)
          File "/private/home/anovak1/workspace/toil/src/toil/wdl/wdltoil.py", line 3212, in <lambda>
            return environment.map(lambda b: map_over_inodes_in_binding(b, transform))
          File "/private/home/anovak1/workspace/toil/src/toil/wdl/wdltoil.py", line 3228, in map_over_inodes_in_binding
            map_over_typed_inodes_in_value(binding.value, transform),
          File "/private/home/anovak1/workspace/toil/src/toil/wdl/wdltoil.py", line 3354, in map_over_typed_inodes_in_value
            return map_over_typed_value(value, predicate)
          File "/private/home/anovak1/workspace/toil/src/toil/wdl/wdltoil.py", line 3314, in map_over_typed_value
            return transform(value)
          File "/private/home/anovak1/workspace/toil/src/toil/wdl/wdltoil.py", line 3340, in predicate
            transformed = transform(value)
          File "/private/home/anovak1/workspace/toil/src/toil/wdl/wdltoil.py", line 1581, in _devirtualize_file
            devirtualized_path = self._devirtualize_filename(virtualized_filename)
          File "/private/home/anovak1/workspace/toil/src/toil/wdl/wdltoil.py", line 1631, in _devirtualize_filename
            result = self.devirtualize_to(
          File "/private/home/anovak1/workspace/toil/src/toil/wdl/wdltoil.py", line 2032, in devirtualize_to
            cls._write_uri_to(filename, dest_path, file_source, export)
          File "/private/home/anovak1/workspace/toil/src/toil/wdl/wdltoil.py", line 1678, in _write_uri_to
            result = file_source.readGlobalFile(
          File "/private/home/anovak1/workspace/toil/src/toil/fileStores/cachingFileStore.py", line 1338, in readGlobalFile
            finalPath = self._readGlobalFileWithCache(
          File "/private/home/anovak1/workspace/toil/src/toil/fileStores/cachingFileStore.py", line 2010, in _readGlobalFileWithCache
            if self._createLinkFromCache(
          File "/private/home/anovak1/workspace/toil/src/toil/fileStores/cachingFileStore.py", line 1840, in _createLinkFromCache
            raise RuntimeError(f"Missing cache file: {cachedPath}")
        RuntimeError: Missing cache file: /data/tmp/toilwf-903d6543f2695175ba2793e43828cc50/cache-14008451-eab7-4019-8226-4510ae582590/tmpqpo4n51k41985016e994397aa70be7b24c4e644ab03c35f2

        [2026-09-22T12:56:42-0700] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host phoenix-20.prism
<=========
```

**Comment by adamnovak** [comment]
The situation here is vg is crashing (since the distance index is the wrong version) and then we're immediately retrying the job on the same node (after a 2-second retry delay). It looks like the new run of the job thinks its worker received an immutable reference to the distance index file, but also the distance index file is not actually in the cache.

**Comment by adamnovak** [comment]
OK, I think I have managed to replicate this on demand:
```
          File "/private/home/anovak1/workspace/toil/src/toil/fileStores/cachingFileStore.py", line 1840, in _createLinkFromCache
            raise RuntimeError(f"Missing cache file: {cachedPath}")
        RuntimeError: Missing cache file: /data/tmp/toilwf-9871cbeacb515d4ab207e5524d4f4e63/cache-c183c343-f03f-49ab-a86e-c6f9afb2cbd5/tmpjsks2p1v8e426c64dd28799711f49dfbc4c971b841e963e8

        [2026-09-22T14:47:43-0700] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host phoenix-20.prism
```

This is by running:

```
cat >inputs-indexing.json <<'EOF'                                                                                                                                                                           {                                                                                                                                                                                                                                               "IndexForGiraffe.GBZ_FILE": "https://s3-us-west-2.amazonaws.com/human-pangenomics/pangenomes/freeze/release2/minigraph-cactus/v2.1/hprc-v2.1-mc-grch38/hprc-v2.1-mc-grch38.d46.gbz",
    "IndexForGiraffe.DIST_FILE": "https://s3-us-west-2.amazonaws.com/human-pangenomics/pangenomes/freeze/release2/minigraph-cactus/v2.1/hprc-v2.1-mc-grch38/hprc-v2.1-mc-grch38.d46.dist",
    "IndexForGiraffe.HAPLOTYPE_SAMPLING": false,
    "IndexForGiraffe.GIRAFFE_PRESET": "hifi",
    "IndexForGiraffe.VG_DOCKER": "quay.io/vgteam/vg:v1.77.0"
}
EOF

rm -Rf ./output/indexing-tree

TOIL_SLURM_ARGS="--nodelist=phoenix-20" toil-wdl-runner https://raw.githubusercontent.com/vgteam/vg_wdl/ab754ff79faf6dafeb93c4467c66a55664f9edde/workflows/internal/index_for_giraffe.wdl ./inputs-indexing.json --wdlOutputDirectory ./output/indexing/out --wdlOutputFile ./output/indexing.json --logFile ./output/indexing.log --writeLogs ./output/indexing/logs --jobStore ./output/indexing-tree --batchSystem slurm --slurmTime 11:59:59 --disableProgress --caching=True --logDebug
```

Slurm is set up with TOIL_SLURM_ARGS so that after the vg job fails because vg rejects the index file version, the retry job goes to the same node. I think that might be important.
