### ISSUE TITLE
Permission denied: 'amd-smi' - Error while detecting accelerators

### ISSUE THREAD

**Issue by ndonyapour** [DataBiosphere/toil#5111]
Hello, I'm encountering an issue while running a CWL workflow using Toil, and I'm getting the following error:
```
Traceback (most recent call last):
  File "/home/donyapourn2/mambaforge-pypy3/envs/wic/bin/toil-cwl-runner", line 33, in <module>
    sys.exit(load_entry_point('toil', 'console_scripts', 'toil-cwl-runner')())
  File "/home/donyapourn2/projects/wic/toil/src/toil/cwl/cwltoil.py", line 4051, in main
    outobj = toil.start(wf1)
  File "/home/donyapourn2/projects/wic/toil/src/toil/common.py", line 924, in start
    self._batchSystem = self.createBatchSystem(self.config)
  File "/home/donyapourn2/projects/wic/toil/src/toil/common.py", line 1073, in createBatchSystem
    return batch_system(**kwargs)
  File "/home/donyapourn2/projects/wic/toil/src/toil/batchSystems/slurm.py", line 625, in __init__
    super().__init__(config, maxCores, maxMemory, maxDisk)
  File "/home/donyapourn2/projects/wic/toil/src/toil/batchSystems/abstractGridEngineBatchSystem.py", line 382, in __init__
    super().__init__(
  File "/home/donyapourn2/projects/wic/toil/src/toil/batchSystems/cleanup_support.py", line 48, in __init__
    super().__init__(config, maxCores, maxMemory, maxDisk)
  File "/home/donyapourn2/projects/wic/toil/src/toil/batchSystems/local_support.py", line 33, in __init__
    self.localBatch: SingleMachineBatchSystem = SingleMachineBatchSystem(
  File "/home/donyapourn2/projects/wic/toil/src/toil/batchSystems/singleMachine.py", line 166, in __init__
    self.accelerator_identities = get_individual_local_accelerators()
  File "/home/donyapourn2/projects/wic/toil/src/toil/lib/accelerators.py", line 150, in get_individual_local_accelerators
    gpus.extend([{'kind': 'gpu', 'brand': 'amd', 'api': 'rocm', 'count': 1} for _ in range(count_amd_gpus())])
  File "/home/donyapourn2/projects/wic/toil/src/toil/lib/accelerators.py", line 121, in count_amd_gpus
    out = subprocess.check_output((["amd-smi", "static"]))
  File "/home/donyapourn2/mambaforge-pypy3/envs/wic/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/home/donyapourn2/mambaforge-pypy3/envs/wic/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/donyapourn2/mambaforge-pypy3/envs/wic/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/donyapourn2/mambaforge-pypy3/envs/wic/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'amd-smi'
```
It looks like the issue is caused by the line ``` subprocess.check_output((["amd-smi", "static"]))```. This command is being executed without checking if AMD GPUs are available on the system, resulting in a PermissionError.

I’m not entirely sure what the best way to check for AMD GPUs is, but adding a preliminary check before running the command fixed the issue for me. Here's a possible solution:

``` python
def is_amd_gpu_installed() -> bool:
    """ 
    Check if the system has any AMD GPUs by scanning PCI devices (lspci).
    Returns True if AMD GPUs are found, False otherwise.
    """
    try:
        # Execute lspci to list PCI devices
        out = subprocess.check_output("lspci", shell=True).decode("utf-8")
        
        # Check for AMD-related entries in the PCI device list
        for line in out.split("\n"):
            if "VGA compatible controller" in line and ("AMD" in line or "Radeon" in line):
                return True  # Found AMD GPU
    except subprocess.SubprocessError:
        # In case lspci fails, assume no AMD GPUs
        return False

    # If no AMD GPU is found
    return False
  
    
@memoize
def count_amd_gpus() -> int:
    """
    Return the number of amd GPUs seen by rocm-smi, or 0 if it is not working.
    :return:
    """
    if not is_amd_gpu_installed():
        # If no AMD GPU is detected, return 0 early
        print("No AMD GPUs detected.")
        return 0
    try:
        # see if the amd-smi CLI tool is installed
        # we believe this is the expected output for amd-smi, but we don't actually have and amd gpu to test against
        # so we assume the output from the amd-smi documentation:
        # https://rocm.docs.amd.com/projects/amdsmi/en/latest/how-to/using-AMD-SMI-CLI-tool.html
        out = subprocess.check_output((["amd-smi", "static"]))
        gpu_count = len([line for line in out.decode("utf-8").split("\n") if line.startswith("gpu")])
        return gpu_count
    except (FileNotFoundError, subprocess.SubprocessError):
        # if the amd-smi command fails, try rocm-smi
        # if a different exception is raised, something other than the subprocess call is wrong
        pass
    try:
        # similarly, since we don't have an AMD gpu to test against, assume the output from the rocm-smi documentation:
        # https://rocm.blogs.amd.com/software-tools-optimization/affinity/part-2/README.html#gpu-numa-configuration-rocm-smi-showtoponuma
        out = subprocess.check_output(["rocm-smi"])
        gpu_count = len([line for line in out.decode("utf-8").split("\n") if len(line)> 0 and line[0] in string.digits])
        return gpu_count
    except (FileNotFoundError, subprocess.SubprocessError):
        pass
    return 0
```

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-1653)
┆Issue Number: TOIL-1653

**Comment by ndonyapour** [comment]
The HPC servers I’m using only have CPUs, so neither `amd-smi` nor `nvidia-smi` is installed. Here are the outputs of the commands you requested:

```
which amd-smi:
/usr/bin/which: no amd-smi 

ls -lah $(which amd-smi):
no amd-smi 

amd-smi:
bash: amd-smi: command not found
```
It seems that amd-smi isn’t installed on the system, which makes sense given the current hardware setup. Thanks for the solution you suggested—it’s a great idea!

**Comment by ndonyapour** [comment]
I just checked, and it looks like there are two more exceptions that can be raised when using `subprocess.check_output(["amd-smi", "static"])`, along with some other common ones. Are you planning to add support for all of these?
```
FileNotFoundError: Command not found.
PermissionError: Insufficient permissions to execute the command.
subprocess.CalledProcessError: Command returned a non-zero exit code.
OSError: System-related issue (e.g., lack of resources).
UnicodeDecodeError: Issue decoding the output from the command.
```

**Comment by stxue1** [comment]
> I just checked, and it looks like there are two more exceptions that can be raised when using `subprocess.check_output(["amd-smi", "static"])`, along with some other common ones. Are you planning to add support for all of these?
> 
> ```
> FileNotFoundError: Command not found.
> PermissionError: Insufficient permissions to execute the command.
> subprocess.CalledProcessError: Command returned a non-zero exit code.
> OSError: System-related issue (e.g., lack of resources).
> UnicodeDecodeError: Issue decoding the output from the command.
> ```

It seems odd that those type of exceptions can occur, but if they are exceptions related to not having `amd-smi` available, then yes, we should add them.
