### ISSUE TITLE
Toil complains that a filename with spaces "contains illegal characters" while cwltool works fine

### ISSUE THREAD

**Issue by ndonyapour** [DataBiosphere/toil#5158]
Hello, we have workflows running with Toil that run issues when datasets contain files and folders with whitespaces in their names. We’d like to preserve the original data without running a preprocessing step to rename these files and folders. Is it possible to add support for file and folder names with whitespaces? 

Thank you!

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-1669)
┆Issue Number: TOIL-1669

**Comment by adamnovak** [comment]
As far as I know, Toil *should* already support whitespace in path names for input and output files. There's nothing I know of about its import/export machinery that shouldn't be able to handle it.

Are you using Toil with the CWL or WDL front-end? Are you using a particular CWL or WDL workflow? It's easy to write a WDL workflow that doesn't quote filename placeholders and won't work properly when filenames contain spaces.

Can you provide a reproducible example of Toil not supporting whitespace in a filename?

**Comment by ndonyapour** [comment]
Actually, the error is coming from CWL, not Toil. I’m using Toil with CWL, and here’s the error I'm running into

```
visit_class(d, cls, op)
     File "/home/donyapourn2/mambaforge-pypy3/envs/wic/lib/python3.10/site-packages/cwltool/utils.py", line 218, in visit_class
      visit_class(d, cls, op)
     File "/home/donyapourn2/mambaforge-pypy3/envs/wic/lib/python3.10/site-packages/cwltool/utils.py", line 213, in visit_class
      op(rec)
     File "/home/donyapourn2/mambaforge-pypy3/envs/wic/lib/python3.10/site-packages/cwltool/command_line_tool.py", line 379, in check_adjust
      raise WorkflowException(
    cwl_utils.errors.WorkflowException: Invalid filename: 'CD_SOD1_2_E1023884 __1' contains illegal characters
```
I don’t get this error when I run the workflow with CWLtool directly.
[toil_whitespace_example.zip](https://github.com/user-attachments/files/17756387/toil_whitespace_example.zip)

**Comment by mr-c** [comment]
> Actually, the error is coming from CWL, not Toil. I’m using Toil with CWL, and here’s the error I'm running into
> 
> ```
> visit_class(d, cls, op)
>      File "/home/donyapourn2/mambaforge-pypy3/envs/wic/lib/python3.10/site-packages/cwltool/utils.py", line 218, in visit_class
>       visit_class(d, cls, op)
>      File "/home/donyapourn2/mambaforge-pypy3/envs/wic/lib/python3.10/site-packages/cwltool/utils.py", line 213, in visit_class
>       op(rec)
>      File "/home/donyapourn2/mambaforge-pypy3/envs/wic/lib/python3.10/site-packages/cwltool/command_line_tool.py", line 379, in check_adjust
>       raise WorkflowException(
>     cwl_utils.errors.WorkflowException: Invalid filename: 'CD_SOD1_2_E1023884 __1' contains illegal characters
> ```
> 
> I don’t get this error when I run the workflow with CWLtool directly. [toil_whitespace_example.zip](https://github.com/user-attachments/files/17756387/toil_whitespace_example.zip)

Can you try again with `--relax-path-checks`?

@adamnovak I remember that we had made this the default for `toil-cwl-runner`

**Comment by stxue1** [comment]
> > Actually, the error is coming from CWL, not Toil. I’m using Toil with CWL, and here’s the error I'm running into
> > ```
> > visit_class(d, cls, op)
> >      File "/home/donyapourn2/mambaforge-pypy3/envs/wic/lib/python3.10/site-packages/cwltool/utils.py", line 218, in visit_class
> >       visit_class(d, cls, op)
> >      File "/home/donyapourn2/mambaforge-pypy3/envs/wic/lib/python3.10/site-packages/cwltool/utils.py", line 213, in visit_class
> >       op(rec)
> >      File "/home/donyapourn2/mambaforge-pypy3/envs/wic/lib/python3.10/site-packages/cwltool/command_line_tool.py", line 379, in check_adjust
> >       raise WorkflowException(
> >     cwl_utils.errors.WorkflowException: Invalid filename: 'CD_SOD1_2_E1023884 __1' contains illegal characters
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I don’t get this error when I run the workflow with CWLtool directly. [toil_whitespace_example.zip](https://github.com/user-attachments/files/17756387/toil_whitespace_example.zip)
> 
> Can you try again with `--relax-path-checks`?
> 
> @adamnovak I remember that we had made this the default for `toil-cwl-runner`

This is currently set to `False` by default:
https://github.com/DataBiosphere/toil/blob/47ac7bfbc4c5b6a3db812a59542e6c91d5dd58ed/src/toil/options/cwl.py#L235

Maybe this should be set to True by default. We would then also need to either change the argument name or not have it as `store_true`.

**Comment by ndonyapour** [comment]
Thank you for your help! Using `--relax-path-checks` fixed the issue.

**Comment by adamnovak** [comment]
@stxue1 volunteered to see if there's actually a discrepancy in the default value of the option for Toil vs. cwltool, or if there's something else causing cwltool to succeed and Toil to fail on the example workflow.

**Comment by stxue1** [comment]
Hey @ndonyapour, it seems like the example files you provided have some missing CWL steps. I'm getting a validation error with cwltool:
```
cwltool img_segmentation.cwl inputs.yml 
INFO /home/heaucques/Documents/toil/venv3.13/bin/cwltool 3.1.20250110105449
INFO Resolved 'img_segmentation.cwl' to 'file:///home/heaucques/Documents/toil-examples/toil_whitespace_example/img_segmentation.cwl'
WARNING img_segmentation.cwl:36:3: object id 'img_segmentation.cwl#cwl_nuclear_segmentation_SOD1__step__1__FileRenaming___outDir' previously defined
ERROR Tool definition failed validation:
img_segmentation.cwl:4:1:  checking field 'steps'
img_segmentation.cwl:5:3:    checking object
                             'img_segmentation.cwl#cwl_nuclear_segmentation_SOD1__step__1__FileRenaming'
img_segmentation.cwl:22:3:     Field 'run' contains undefined reference to
                               'file:///home/heaucques/Documents/toil-examples/toil_whitespace_example/cwl_nuclear_segmentation_SOD1__step__1__FileRenaming/FileRenaming.cwl'
```

Is it possible you could provide the rest of the CWL files?

**Comment by stxue1** [comment]
I've tried to create a new example with the existing example code:
test_workflow.cwl
```cwl
steps:
- id: test
  scatter:
  - inpDir
  in:
    inpDir:
      source: inpDir
  run: test_whitespace.cwl
  out: []
cwlVersion: v1.2
class: Workflow
inputs:
  inpDir:
    type:
      type: array
      items: Directory
outputs:
  {}
requirements:
  ScatterFeatureRequirement: {}
```

test_whitespace.cwl:
```cwl
class: CommandLineTool
cwlVersion: v1.2
requirements:
  - class: ShellCommandRequirement
inputs:
  inpDir:
    type: Directory
outputs:
  outlist:
    type: File
    outputBinding:
      glob: output.txt
arguments: ["find", "-L", ".", "!", "-path", "*.txt",
  {shellQuote: false, valueFrom: "|"},
  "sort"]
stdout: output.txt
```
test_inputs.yml
```yml
inpDir:
- class: Directory
  location: ./dataset/CD_SOD1_2_E1023884 __1
- class: Directory
  location: ./dataset/CD_SOD1_2_E1023980 __1
```

With cwltool, the above gives me an error:
```
$ cwltool test_workflow.cwl test_inputs.yml 
INFO /home/heaucques/Documents/toil/venv3.13/bin/cwltool 3.1.20250110105449
INFO Resolved 'test_workflow.cwl' to 'file:///home/heaucques/Documents/toil-examples/toil_whitespace_example/test_workflow.cwl'
INFO [workflow ] start
INFO [workflow ] starting step test
INFO [step test] start
ERROR Exception on step 'test'
ERROR Cannot make scatter job: Invalid filename: 'CD_SOD1_2_E1023884 __1' contains illegal characters
ERROR Workflow cannot make any more progress.
WARNING Final process status is permanentFail
```

With toil, it gives me an error that looks similar to the traceback provided:
```
	Traceback (most recent call last):
	  File "/home/heaucques/Documents/toil/src/toil/worker.py", line 502, in workerScript
	    job._runner(
	    ~~~~~~~~~~~^
	        jobGraph=None,
	        ^^^^^^^^^^^^^^
	    ...<2 lines>...
	        defer=defer,
	        ^^^^^^^^^^^^
	    )
	    ^
	  File "/home/heaucques/Documents/toil/src/toil/job.py", line 3219, in _runner
	    returnValues = self._run(jobGraph=None, fileStore=fileStore)
	  File "/home/heaucques/Documents/toil/src/toil/job.py", line 3128, in _run
	    return self.run(fileStore)
	           ~~~~~~~~^^^^^^^^^^^
	  File "/home/heaucques/Documents/toil/src/toil/cwl/cwltoil.py", line 2863, in run
	    output, status = ToilSingleJobExecutor().execute(
	                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
	        process=self.cwltool,
	        ^^^^^^^^^^^^^^^^^^^^^
	    ...<2 lines>...
	        logger=cwllogger,
	        ^^^^^^^^^^^^^^^^^
	    )
	    ^
	  File "/home/heaucques/Documents/toil/venv3.13/lib/python3.13/site-packages/cwltool/executors.py", line 136, in execute
	    self.run_jobs(process, job_order_object, logger, runtime_context)
	    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "/home/heaucques/Documents/toil/src/toil/cwl/cwltoil.py", line 1097, in run_jobs
	    return super().run_jobs(process, job_order_object, logger, runtime_context)
	           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "/home/heaucques/Documents/toil/venv3.13/lib/python3.13/site-packages/cwltool/executors.py", line 213, in run_jobs
	    for job in jobiter:
	               ^^^^^^^
	  File "/home/heaucques/Documents/toil/venv3.13/lib/python3.13/site-packages/cwltool/command_line_tool.py", line 985, in job
	    visit_class([builder.files, builder.bindings], ("File", "Directory"), _check_adjust)
	    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "/home/heaucques/Documents/toil/venv3.13/lib/python3.13/site-packages/cwltool/utils.py", line 207, in visit_class
	    visit_class(d, cls, op)
	    ~~~~~~~~~~~^^^^^^^^^^^^
	  File "/home/heaucques/Documents/toil/venv3.13/lib/python3.13/site-packages/cwltool/utils.py", line 207, in visit_class
	    visit_class(d, cls, op)
	    ~~~~~~~~~~~^^^^^^^^^^^^
	  File "/home/heaucques/Documents/toil/venv3.13/lib/python3.13/site-packages/cwltool/utils.py", line 202, in visit_class
	    op(rec)
	    ~~^^^^^
	  File "/home/heaucques/Documents/toil/venv3.13/lib/python3.13/site-packages/cwltool/command_line_tool.py", line 366, in check_adjust
	    raise WorkflowException(
	        f"Invalid filename: {file_o['basename']!r} contains illegal characters"
	    )
	cwl_utils.errors.WorkflowException: Invalid filename: 'CD_SOD1_2_E1023980 __1' contains illegal characters
```

Passing `--relax-path-checks` fixes it for both runners.

Since `--relax-path-checks` provides a workaround and because I can't create a working example, I'll close this issue for now. If you have a working workflow that triggers this error or something related, feel free to reopen this issue.
