### ISSUE TITLE
Add support for job functions that are static methods

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/toil#667]
```
class JobCacheTest(ToilTest):
    '''
    Tests the various cache functions
    '''
    # sanity
    def testToilIsNotBroken(self):
        '''
        Make a job, make a child, make merry.
        '''
        F = Job.wrapJobFn(self._uselessFunc)
        G = Job.wrapJobFn(self._uselessFunc)
        H = Job.wrapJobFn(self._uselessFunc)
        I = Job.wrapJobFn(self._uselessFunc)
        F.addChild(G)
        F.addChild(H)
        G.addChild(I)
        H.addChild(I)
        Job.Runner.startToil(F, self.options)

    @staticmethod
    def _uselessFunc(job):
        '''
        I do nothing. Don't judge me.
        '''
        return None
```

gives 

```
2016-02-04 14:37:02,710 WARNING:toil.leader: 8/b/jobkUlJy5:    ---TOIL WORKER OUTPUT LOG---
2016-02-04 14:37:02,710 WARNING:toil.leader: 8/b/jobkUlJy5:    Traceback (most recent call last):
2016-02-04 14:37:02,710 WARNING:toil.leader: 8/b/jobkUlJy5:      File "/Users/arjun/cached_toil/toil/src/toil/worker.py", line 293, in main
2016-02-04 14:37:02,710 WARNING:toil.leader: 8/b/jobkUlJy5:        fileStore=fileStore)
2016-02-04 14:37:02,710 WARNING:toil.leader: 8/b/jobkUlJy5:      File "/Users/arjun/cached_toil/toil/src/toil/job.py", line 2229, in _execute
2016-02-04 14:37:02,710 WARNING:toil.leader: 8/b/jobkUlJy5:        returnValues = self.run(fileStore)
2016-02-04 14:37:02,710 WARNING:toil.leader: 8/b/jobkUlJy5:      File "/Users/arjun/cached_toil/toil/src/toil/job.py", line 2352, in run
2016-02-04 14:37:02,710 WARNING:toil.leader: 8/b/jobkUlJy5:        userFunction = self._getUserFunction()
2016-02-04 14:37:02,710 WARNING:toil.leader: 8/b/jobkUlJy5:      File "/Users/arjun/cached_toil/toil/src/toil/job.py", line 2328, in _getUserFunction
2016-02-04 14:37:02,711 WARNING:toil.leader: 8/b/jobkUlJy5:        return getattr(userFunctionModule, self.userFunctionName)
2016-02-04 14:37:02,711 WARNING:toil.leader: 8/b/jobkUlJy5:    AttributeError: 'module' object has no attribute '_uselessFunc'
2016-02-04 14:37:02,711 WARNING:toil.leader: 8/b/jobkUlJy5:    Exiting the worker because of a failed jobWrapper on host eduroam-169-233-245-29.ucsc.edu
```

but

```
class JobCacheTest(ToilTest):
    '''
    Tests the various cache functions
    '''
    # sanity
    def testToilIsNotBroken(self):
        '''
        Make a job, make a child, make merry.
        '''
        F = Job.wrapJobFn(self._uselessFunc)
        G = Job.wrapJobFn(self._uselessFunc)
        H = Job.wrapJobFn(self._uselessFunc)
        I = Job.wrapJobFn(self._uselessFunc)
        F.addChild(G)
        F.addChild(H)
        G.addChild(I)
        H.addChild(I)
        Job.Runner.startToil(F, self.options)

    @staticmethod
    def _uselessFunc(job):
        '''
        I do nothing. Don't judge me.
        '''
        return None

def _uselessFunc(job):
    '''
    I do nothing. Don't judge me.
    '''
    return None
```

works

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-325)
┆Issue Number: TOIL-325

**Comment by arkal** [comment]
This also works
```
class JobCacheTest(ToilTest):
    '''
    Tests the various cache functions
    '''
    # sanity
    def testToilIsNotBroken(self):
        '''
        Make a job, make a child, make merry.
        '''
        F = Job.wrapJobFn(self._uselessFunc)
        G = Job.wrapJobFn(self._uselessFunc)
        H = Job.wrapJobFn(self._uselessFunc)
        I = Job.wrapJobFn(self._uselessFunc)
        F.addChild(G)
        F.addChild(H)
        G.addChild(I)
        H.addChild(I)
        Job.Runner.startToil(F, self.options)

    @staticmethod
    def _uselessFunc(job):
        '''
        I do nothing. Don't judge me.
        '''
        return None

_uselessFunc = JobCacheTest._uselessFunc
```

**Comment by DailyDreaming** [comment]
Stale, closing.  Reopen if still relevant.
