### ISSUE TITLE
Stats/logging: EntityAlreadyExists in Azure job store

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/toil#909]
http://jenkins.cgcloud.info/job/toil-branches/branch/master/160/testReport/junit/src.toil.test.src.jobCacheTest/AzureJobStoreCacheTest/testWriteLocalFileToJobStore/

```
Process Process-117:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/ephemeral/workspace/toil-branches/master/src/toil/leader.py", line 89, in statsAndLoggingAggregatorProcess
    if jobStore.readStatsAndLogging(callback) == 0:
  File "/mnt/ephemeral/workspace/toil-branches/master/src/toil/jobStores/azureJobStore.py", line 342, in readStatsAndLogging
    self.statsFileIDs.insert_entity(entity={'RowKey': jobStoreFileID + suffix})
  File "/mnt/ephemeral/workspace/toil-branches/master/src/toil/jobStores/azureJobStore.py", line 583, in f
    return function(**kwargs)
  File "/mnt/ephemeral/workspace/toil-branches/master/venv/local/lib/python2.7/site-packages/azure/storage/table/tableservice.py", line 451, in insert_entity
    response = self._perform_request(request)
  File "/mnt/ephemeral/workspace/toil-branches/master/venv/local/lib/python2.7/site-packages/azure/storage/storageclient.py", line 178, in _perform_request
    _storage_error_handler(ex)
  File "/mnt/ephemeral/workspace/toil-branches/master/venv/local/lib/python2.7/site-packages/azure/storage/_serialization.py", line 25, in _storage_error_handler
    return _general_error_handler(http_error)
  File "/mnt/ephemeral/workspace/toil-branches/master/venv/local/lib/python2.7/site-packages/azure/storage/_common_error.py", line 82, in _general_error_handler
    raise AzureHttpError(message, http_error.status)
AzureConflictHttpError: Conflict
<?xml version="1.0" encoding="utf-8"?><error xmlns="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata"><code>EntityAlreadyExists</code><message xml:lang="en-US">The specified entity already exists.
RequestId:3df3a25f-0002-00cc-4263-b875a8000000
Time:2016-05-27T22:04:20.0351913Z</message></error>
```

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-348)
┆Issue Number: TOIL-348

**Comment by hannes-ucsc** [comment]
Also here:

http://jenkins.cgcloud.info/job/toil-branches/branch/master/161/testReport/junit/src.toil.test.src.jobCacheTest/AzureJobStoreCacheTest/testDeleteLocalFile/

**Comment by hannes-ucsc** [comment]
See my attempt here for fixing this.

**Comment by cricketsloan** [comment]
➤ Adam Novak commented:

We redid a bunch of Azure stuff since this was reported. I think it is fixed.
